//! Localization Key 代码生成器
//!
//! 扫描 `assets/localization/en-US/*.ftl` 并生成 `src/infra/localization/generated/keys.rs`。
//! 包含编译期常量模块 `loc` 和 `ALL_KEYS` 数组。
//!
//! 详见 docs/03-technical/localization-design.md §5

use std::{collections::BTreeMap, env, fs, path::Path};

fn main() {
    let ftl_dir = Path::new("assets/localization/en-US");

    // 确保目录存在；不存在时生成空的 keys.rs
    if !ftl_dir.exists() {
        let out_path = generated_keys_path();
        fs::write(&out_path, EMPTY_KEYS_RS).expect("Failed to write empty keys.rs");
        return;
    }

    let mut keys: Vec<String> = Vec::new();

    // 扫描所有 .ftl 文件
    let entries = match fs::read_dir(ftl_dir) {
        Ok(e) => e,
        Err(_) => {
            let out_path = generated_keys_path();
            fs::write(&out_path, EMPTY_KEYS_RS).expect("Failed to write empty keys.rs");
            return;
        }
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "ftl") {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {:?}: {}", path, e));
            extract_keys(&content, &mut keys);
        }
    }

    keys.sort();
    keys.dedup();

    generate_keys_file(&keys);

    // 增量编译控制
    println!("cargo:rerun-if-changed=assets/localization/en-US/");
    println!("cargo:rerun-if-changed=build.rs");
}

/// 生成的 keys.rs 输出路径
fn generated_keys_path() -> std::path::PathBuf {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    Path::new(&manifest_dir).join("src/infra/localization/generated/keys.rs")
}

/// 从 .ftl 内容中提取所有 message ID 并转换为点分 key
fn extract_keys(content: &str, keys: &mut Vec<String>) {
    let mut current_message_id: Option<String> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        // 跳过注释和空行
        if trimmed.starts_with("###") || trimmed.is_empty() {
            continue;
        }

        // Message ID: -xxx-yyy = value
        if let Some(id_end) = trimmed.find('=') {
            let id_part = trimmed[..id_end].trim();

            if id_part.starts_with('-') {
                // 主 message ID
                let raw_id = id_part.strip_prefix('-').unwrap().trim();
                if !raw_id.is_empty() {
                    let key = raw_id.replace('-', ".");
                    keys.push(key.clone());
                    current_message_id = Some(key);
                }
            } else if id_part.starts_with('.') {
                // 属性行: .desc = value
                if let Some(ref base_key) = current_message_id {
                    let attr_name = id_part.trim_start_matches('.').trim();
                    if !attr_name.is_empty() {
                        keys.push(format!("{}.{}", base_key, attr_name));
                    }
                }
            }
        }
    }
}

/// 生成 keys.rs 文件
fn generate_keys_file(keys: &[String]) {
    let out_path = generated_keys_path();

    let mut output = String::from(
        "// Auto-generated by build.rs — DO NOT EDIT\n\
         // Source: assets/localization/en-US/*.ftl\n\n\
         #![allow(non_snake_case, non_upper_case_globals)]\n\n\
         pub mod loc {\n",
    );

    // 按 namespace 分组
    let mut namespaces: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for key in keys {
        let parts: Vec<&str> = key.splitn(3, '.').collect();
        if parts.len() < 3 {
            // 短 key: "core.yes"
            let ns = parts[0].to_string();
            let const_name = parts[1].to_uppercase();
            let entry = format!("    pub const {}: &str = \"{}\";", const_name, key);
            namespaces.entry(ns).or_default().push(entry);
        } else {
            // 长 key: "ability.abl_000042.name"
            // → pub mod ability { pub mod abl_000042 { pub const NAME: &str = "..."; } }
            let ns = parts[0].to_string();
            let sub = parts[1].to_string();
            let const_name = parts[2].to_uppercase();
            let entry = format!(
                "    pub mod {} {{\n        pub const {}: &str = \"{}\";\n    }}",
                sub, const_name, key
            );
            namespaces.entry(ns).or_default().push(entry);
        }
    }

    for (ns, entries) in &namespaces {
        output.push_str(&format!("    pub mod {} {{\n", ns));
        for entry in entries {
            output.push_str(&format!("{}\n", entry));
        }
        output.push_str("    }\n\n");
    }

    output.push_str("}\n");

    // ALL_KEYS 数组
    output.push_str("\n/// 所有已注册的 Key 列表（用于启动校验）\n");
    output.push_str("pub const ALL_KEYS: &[&str] = &[\n");
    for key in keys {
        output.push_str(&format!("    \"{}\",\n", key));
    }
    output.push_str("];\n");

    // 确保输出目录存在
    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).expect("Failed to create generated/ directory");
    }

    fs::write(&out_path, &output)
        .unwrap_or_else(|e| panic!("Failed to write {:?}: {}", out_path, e));

    println!("cargo:info=Generated {} keys in keys.rs", keys.len());
}

/// 空 keys.rs（当 assets/localization/en-US/ 不存在或不包含 .ftl 时使用）
const EMPTY_KEYS_RS: &str = r#"// Auto-generated by build.rs — DO NOT EDIT
// Source: assets/localization/en-US/*.ftl

#![allow(non_snake_case, non_upper_case_globals)]

pub mod loc {
    // No localization keys found — add .ftl files to assets/localization/en-US/
}

/// 所有已注册的 Key 列表（用于启动校验）
pub const ALL_KEYS: &[&str] = &[];
"#;
