#!/usr/bin/env python3
"""Replace catalog entries for UI examples with detailed content.
Matches entries by filename pattern instead of hardcoded line numbers."""

CATALOG_PATH = "/Users/lf380/Code/Bevy/a1/bevy_examples_catalog.md"

ENTRIES = {
    "empty_defaults.rs": {
        "seq": 229,
        "cat": "UI",
        "filename": "`empty_defaults.rs`（同108）",
        "intent": [
            "**意图**：带 DefaultPlugins 的空 UI 应用——UI 开发必备的最小骨架，展示窗口/渲染/输入基础设施；⭐",
            "- **应用结构**:",
            "  - App::new().add_plugins(DefaultPlugins) 获得完整 UI 渲染能力；",
            "  - ⚠️ 无 DefaultPlugins 时无窗口/渲染——纯控制台应用才可省略；",
            "  - 🔧 UI 开发必须有 Camera2d 才能显示 UI 元素；",
            "- **UI 根节点**:",
            "  - commands.spawn(Node { width: percent(100), height: percent(100), ..default() }) 创建全屏根节点；",
            "  - Node 组件定义布局属性(flex_direction/align_items/justify_content 等)；",
            "  - ⚠️ UI 节点必须是 Camera2d/UiCamera 的后代才能被渲染；",
            "- **典型用途**:",
            "  - 🔧 快速创建 UI 原型——添加 Node + 子元素即可开始；",
            "  - 🧩 后续所有 UI 示例都基于此骨架；",
        ],
        "knowledge": [
            "知：<br>- DefaultPlugins 默认插件组；<br>- Node 布局组件基础；<br>- Camera2d 渲染 UI 必需。",
            "例：<br>- app/empty_defaults.rs(108)；<br>- hello_world(1)。",
        ],
    },
    "button.rs": {
        "seq": 230,
        "cat": "UI",
        "filename": "`button.rs`",
        "intent": [
            "**意图**：按钮交互核心——根据 Interaction 状态动态改变颜色和文本，演示 Bevy UI 事件处理范式；⭐⭐",
            "- **Interaction 枚举**:",
            "  - Interaction::None 默认状态（无交互）；",
            "  - Interaction::Hovered 鼠标悬停——触发高亮；",
            "  - Interaction::Pressed 鼠标按下——触发点击反馈；",
            "  - ⚠️ Changed<Interaction> 过滤器仅在状态变化时运行系统，避免每帧轮询；",
            "- **按钮节点构建**:",
            "  - Button 组件标记按钮实体——Interaction 系统自动为 Button 实体生成事件；",
            "  - Node { width/height/border/border_radius/justify_content/align_items } 定义按钮尺寸和内部布局；",
            "  - BorderColor + BackgroundColor 组件控制边框和背景色；",
            "- **文本更新**:",
            '  - Text::new("Button") + TextFont + TextColor 创建按钮文本；',
            '  - 通过 Children 查询获取子文本实体，修改 **text = "Press".to_string()；',
            "  - 🔧 children![...] 宏简化子实体创建；",
            "- **无障碍支持**:",
            "  - InputFocus 资源必须 init 才能让无障碍系统识别按钮；",
            "  - button.set_changed() 手动标记变更通知无障碍系统；",
            "- **事件处理模式**:",
            "  - Query<(&Interaction, &mut BackgroundColor, &Children), Changed<Interaction>> 事件驱动查询；",
            "  - ⚠️ 不要在系统内轮询所有按钮状态，用 Changed 过滤器提高效率；",
            "  - 🧩 该模式适用于所有需要响应交互的 UI 组件；",
        ],
        "knowledge": [
            "知：<br>- Interaction 三态枚举；<br>- Button 组件标记；<br>- Changed 过滤器；<br>- InputFocus 无障碍。",
            "例：<br>- app/empty_defaults.rs(108)。",
        ],
    },
    "text.rs": {
        "seq": 231,
        "cat": "UI",
        "filename": "`text.rs`",
        "intent": [
            "**意图**：UI 文本完整用法——单行/多行/富文本(TextSpan)、FPS 实时更新、颜色动画、OpenType 特性；⭐⭐⭐",
            "- **Text 基础**:",
            '  - Text::new("hello\\nbevy!") 创建带换行的文本；',
            "  - TextFont { font, font_size } 指定字体和字号；",
            "  - TextLayout::new_with_justify(Justify::Center) 控制对齐；",
            "  - TextShadow::default() 添加文本投影；",
            "- **TextSpan 富文本**:",
            "  - 父 Text + 子 TextSpan 实现多色/多字号文本段落；",
            "  - 每个 TextSpan 独立设置 TextFont/TextColor；",
            "  - 🔧 FPS 显示用 TextSpan 动态更新数值，避免重建整个 Text；",
            "- **FPS 实时更新**:",
            "  - FrameTimeDiagnosticsPlugin + DiagnosticsStore 获取帧率数据；",
            "  - Query<&mut TextSpan, With<FpsText>> 定位目标 span；",
            '  - **span = format!("{value:.2}") 解引用修改文本内容；',
            "- **颜色动画**:",
            "  - ops::sin/cos 驱动 RGB 三通道周期变化；",
            "  - TextColor(Color::srgb(r, g, b)) 动态修改文本颜色；",
            "- **OpenType 特性**:",
            "  - FontFeatureTag::SMALL_CAPS/STANDARD_LIGATURES/FRACTIONS 等特性标签；",
            "  - FontFeatures::builder().enable(feature).build() 启用 OpenType 特性；",
            "  - 🔧 高级排版功能如小型大写、连字、分数等；",
            "- **注意事项**:",
            "  - ⚠️ 文本必须在 Camera2d 可见范围内才能渲染；",
            "  - 🔧 Underline 组件直接添加下划线装饰；",
        ],
        "knowledge": [
            "知：<br>- Text/TextFont/TextColor 组件；<br>- TextSpan 富文本；<br>- DiagnosticsStore 诊断数据。",
            "例：<br>- ui/button.rs(230)；<br>- 2D/text2d.rs(11)。",
        ],
    },
    "flex_layout.rs": {
        "seq": 232,
        "cat": "UI",
        "filename": "`flex_layout.rs`",
        "intent": [
            "**意图**：Flexbox 布局完整演示——AlignItems × JustifyContent 30 种组合的可视化矩阵；⭐⭐",
            "- **Flexbox 核心属性**:",
            "  - AlignItems 控制交叉轴对齐（FlexStart/Center/FlexEnd/Baseline/Stretch）；",
            "  - JustifyContent 控制主轴分布（FlexStart/Center/FlexEnd/SpaceEvenly/SpaceAround/SpaceBetween）；",
            "  - FlexDirection::Row/Column 控制主轴方向；",
            "- **布局矩阵**:",
            "  - 5 种 AlignItems × 6 种 JustifyContent = 30 个单元格；",
            "  - 每个单元格独立显示对齐标签和实际布局效果；",
            "  - 🔧 视觉对比是理解 Flexbox 最直观的方式；",
            "- **嵌套布局**:",
            "  - 外层 FlexDirection::Column + 内层 FlexDirection::Row 构成网格；",
            "  - row_gap/column_gap 控制间距；",
            "  - padding/margin 控制内边距和外边距；",
            "- **文本标签**:",
            "  - 文本嵌套在独立 Node 中——⚠️ margin/padding 不能直接应用到 Text；",
            "  - 🔧 用 Node 包裹 Text 实现精确的间距控制；",
        ],
        "knowledge": [
            "知：<br>- AlignItems/JustifyContent 枚举；<br>- FlexDirection 方向控制；<br>- gap/padding/margin。",
            "例：<br>- ui/text.rs(231)；<br>- ui/button.rs(230)。",
        ],
    },
    "grid.rs": {
        "seq": 233,
        "cat": "UI",
        "filename": "`grid.rs`",
        "intent": [
            "**意图**：CSS Grid 二维布局——grid_template_columns/rows 定义网格轨道，aspect_ratio 自适应宽高比；⭐⭐⭐",
            "- **Grid 布局基础**:",
            "  - display: Display::Grid 启用网格布局（非 Flexbox）；",
            "  - grid_template_columns: vec![GridTrack::min_content(), GridTrack::flex(1.0)] 定义列；",
            "  - grid_template_rows: vec![GridTrack::auto(), GridTrack::flex(1.0), GridTrack::px(20.)] 定义行；",
            "- **GridTrack 类型**:",
            "  - GridTrack::px(N) 固定像素尺寸；",
            "  - GridTrack::flex(1.0) 占比分配（fr 单位）；",
            "  - GridTrack::auto() 自适应内容；",
            "  - GridTrack::min_content() 最小内容宽度；",
            "  - RepeatedGridTrack::flex(4, 1.0) 重复定义 4 等分列；",
            "- **GridPlacement**:",
            "  - grid_column: GridPlacement::span(2) 跨 2 列；",
            "  - 🔧 无显式位置的 Grid Item 自动填充到下一个可用单元格；",
            "- **场景结构**:",
            "  - 顶部 Header 跨 2 列 + 中间 4×4 网格 + 右侧 Sidebar + 底部 Footer；",
            "  - aspect_ratio: Some(1.0) 强制 1:1 宽高比——⚠️ 需要明确设置高度；",
            "- **注意事项**:",
            "  - ⚠️ Grid 布局和 Flexbox 布局不能混用——一个节点只能选一种；",
            "  - 🔧 Grid 适合二维布局（如仪表盘），Flexbox 适合一维布局（如列表）；",
        ],
        "knowledge": [
            "知：<br>- Display::Grid 网格模式；<br>- GridTrack 网格轨道；<br>- GridPlacement 跨列/行。",
            "例：<br>- ui/flex_layout.rs(232)。",
        ],
    },
    "anchor_layout.rs": {
        "seq": 234,
        "cat": "UI",
        "filename": "`anchor_layout.rs`",
        "intent": [
            "**意图**：绝对定位锚点布局——通过 left/right/top/bottom + margin:auto 实现 9 种经典锚点位置；⭐⭐",
            "- **绝对定位基础**:",
            "  - PositionType::Absolute 将节点从文档流中移出；",
            "  - left/right/top/bottom 控制节点边缘相对于父节点的位置；",
            "  - 🔧 绝对定位节点不占据布局空间，兄弟节点会重叠；",
            "- **9 种锚点组合**:",
            "  - left+top / center(margin auto)+top / right+top（顶部三位置）；",
            "  - left+center(margin vertical auto) / center(all auto) / right+center（中部三位置）；",
            "  - left+bottom / center(margin horizontal auto)+bottom / right+bottom（底部三位置）；",
            "- **margin:auto 居中**:",
            "  - margin: UiRect::all(Val::Auto) 水平+垂直居中；",
            "  - margin: auto().horizontal() 仅水平居中；",
            "  - 🔧 margin auto 是实现居中的经典 CSS 技巧；",
            "- **Grid 容器**:",
            "  - 外层使用 Display::Grid + 3×3 网格布局容器；",
            "  - 每个锚点组合放在独立的网格单元格中展示；",
            "  - Children::spawn(SpawnIter(...)) 批量生成子实体；",
        ],
        "knowledge": [
            "知：<br>- PositionType::Absolute 绝对定位；<br>- left/right/top/bottom 锚点；<br>- margin:auto 居中。",
            "例：<br>- ui/flex_layout.rs(232)；<br>- ui/grid.rs(233)。",
        ],
    },
    "borders.rs": {
        "seq": 235,
        "cat": "UI",
        "filename": "`borders.rs`",
        "intent": [
            "**意图**：UI 边框完整演示——16 种 UiRect 边框组合 + Outline 轮廓 + BorderRadius 圆角；⭐⭐",
            "- **边框定义**:",
            "  - Node { border: UiRect::all(px(10)) } 四边等宽边框；",
            "  - UiRect::left/right/top/bottom(px(N)) 单边边框；",
            "  - UiRect::horizontal/vertical(px(N)) 双边边框；",
            "  - UiRect { left, right, top, bottom } 自定义组合；",
            "- **BorderColor 组件**:",
            "  - BorderColor { top: RED, bottom: YELLOW, left: GREEN, right: BLUE } 四边独立颜色；",
            "  - ⚠️ 边框颜色与 BackgroundColor 独立——背景填充内容区域，边框在外部；",
            "- **Outline 轮廓**:",
            "  - Outline { width: px(6), offset: px(6), color: Color::WHITE } 在边框外绘制轮廓；",
            "  - ⚠️ Outline 不占据布局空间——与 border 不同，不影响节点尺寸；",
            "- **BorderRadius 圆角**:",
            "  - BorderRadius::all(px(41)) 四角等半径圆角；",
            "  - BorderRadius::MAX 完全圆形（适用于正方形节点）；",
            "  - BorderRadius::px(tl, tr, br, bl) 四角独立控制；",
            "  - 🔧 border_size 辅助函数：有边框的角用 f32::MAX，无边框的角用 0；",
        ],
        "knowledge": [
            "知：<br>- UiRect 边框定义；<br>- BorderColor 四边颜色；<br>- Outline 轮廓；<br>- BorderRadius 圆角。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "box_shadow.rs": {
        "seq": 236,
        "cat": "UI",
        "filename": "`box_shadow.rs`",
        "intent": [
            "**意图**：UI 阴影效果——BoxShadow 组件的 offset/blur/spread/count/samples 参数交互式调节；⭐⭐⭐",
            "- **BoxShadow 组件**:",
            "  - BoxShadow(vec![ShadowStyle { color, x_offset, y_offset, spread_radius, blur_radius }]) 一个节点可有多个阴影；",
            "  - ShadowStyle.color 阴影颜色（支持 alpha 透明度）；",
            "  - ShadowStyle.x_offset/y_offset 阴影偏移量；",
            "  - ShadowStyle.spread_radius 扩散半径——阴影向外扩展；",
            "  - ShadowStyle.blur_radius 模糊半径——阴影边缘柔化程度；",
            "- **渲染配置**:",
            "  - BoxShadowSamples(samples) 控制阴影渲染采样数——越多越平滑但越慢；",
            "  - Camera2d 上设置 BoxShadowSamples 启用阴影渲染；",
            "- **交互式调节面板**:",
            "  - SettingsButton 枚举标记 +/- 按钮，SettingType 枚举标记当前参数类型；",
            "  - Resource 存储 ShadowSettings/ShapeSettings——全局状态驱动渲染；",
            "  - run_if(resource_changed::<ShadowSettings>) 条件系统——仅在参数变化时更新；",
            "- **5 种形状**:",
            "  - 正方形/圆角正方形/圆形/宽矩形/高矩形——通过 BorderRadius 控制；",
            "  - SHAPES 数组存储形状配置函数，index 切换；",
            "- **按钮长按重复**:",
            "  - HeldButton Resource 追踪按住状态和重复间隔；",
            "  - 🔧 长按 +/- 持续调参，无需反复点击；",
        ],
        "knowledge": [
            "知：<br>- BoxShadow/ShadowStyle 阴影组件；<br>- BoxShadowSamples 采样数；<br>- Resource 全局状态。",
            "例：<br>- ui/borders.rs(235)；<br>- ui/button.rs(230)。",
        ],
    },
    "size_constraints.rs": {
        "seq": 237,
        "cat": "UI",
        "filename": "`size_constraints.rs`",
        "intent": [
            "**意图**：UI 节点尺寸约束——flex_basis/width/min_width/max_width 四种约束的交互式调节；⭐⭐",
            "- **四种尺寸约束**:",
            "  - flex_basis: flex 布局的初始主轴尺寸——被 width 覆盖；",
            "  - width/min_width/max_width: 固定/最小/最大宽度约束；",
            "  - ⚠️ 约束优先级：max_width ≥ width ≥ min_width；",
            "- **交互式单选按钮**:",
            "  - Constraint 枚举标记按钮所属约束组；",
            "  - ButtonValue(Val) 存储按钮代表的值（Auto/0%~125%）；",
            "  - Message<ButtonActivated> 消息系统通知状态变化；",
            "- **Radio Button 模式**:",
            "  - 同一组约束的按钮互斥——激活一个自动取消其他；",
            "  - ACTIVE/INACTIVE 颜色常量控制视觉状态；",
            "  - 🔧 MessageWriter/MessageReader 比 EventWriter 更轻量，适合 UI 内部通信；",
            "- **可视化条**:",
            "  - Bar 组件标记目标节点——动态修改其 flex_basis/width/min_width/max_width；",
            "  - 白色条在黑色容器中实时反映约束变化；",
            "- **按钮交互**:",
            "  - 三层嵌套：按钮 → 内部背景 → 文本标签；",
            "  - 遍历 Children/GrandChildren 更新颜色——⚠️ 层级深时查询效率降低；",
        ],
        "knowledge": [
            "知：<br>- flex_basis/width/min_width/max_width 约束；<br>- Message 消息系统；<br>- 互斥按钮模式。",
            "例：<br>- ui/button.rs(230)；<br>- ui/flex_layout.rs(232)。",
        ],
    },
    "display_and_visibility.rs": {
        "seq": 238,
        "cat": "UI",
        "filename": "`display_and_visibility.rs`",
        "intent": [
            "**意图**：Display::None 与 Visibility::Hidden 的本质区别——前者移除布局空间，后者保留空间但不可见；⭐⭐",
            "- **Display 属性**:",
            "  - Display::Flex 默认显示——节点参与布局；",
            "  - Display::None 完全隐藏——⚠️ 节点及其后代不占据任何布局空间；",
            "  - 切换 Display::None → Flex 时，布局会重新计算；",
            "- **Visibility 属性**:",
            "  - Visibility::Visible 正常显示；",
            "  - Visibility::Hidden 隐藏但保留布局空间——⚠️ 仍占据位置，其他节点不会移动；",
            "  - Visibility::Inherited 继承父节点的可见性；",
            "  - 🔧 Hidden 适合占位隐藏（如加载动画占位），None 适合完全移除；",
            "- **嵌套层级控制**:",
            "  - 4 层嵌套节点（520→400→300→200px）每层独立可控；",
            "  - Target<T> 泛型组件标记控制目标实体；",
            "  - buttons_handler<T> 泛型系统复用 Display/Visibility 控制逻辑；",
            "- **交互面板**:",
            "  - 右侧面板按钮切换左侧嵌套节点的 Display/Visibility 状态；",
            "  - bypass_change_detection() 仅修改颜色时跳过变更检测——🔧 性能优化；",
        ],
        "knowledge": [
            "知：<br>- Display::None 移除布局空间；<br>- Visibility::Hidden 保留布局空间；<br>- Visibility::Inherited 继承。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "overflow.rs": {
        "seq": 239,
        "cat": "UI",
        "filename": "`overflow.rs`",
        "intent": [
            "**意图**：UI 溢出裁剪——Overflow 四种模式(visible/clip_x/clip_y/clip)对子元素的裁剪行为；⭐⭐",
            "- **Overflow 四种模式**:",
            "  - Overflow::visible() 默认——子元素可超出父边界显示；",
            "  - Overflow::clip_x() 仅裁剪水平溢出；",
            "  - Overflow::clip_y() 仅裁剪垂直溢出；",
            "  - Overflow::clip() 水平+垂直全部裁剪；",
            "  - ⚠️ clip 与 hidden 的区别：clip 是 GPU 硬件裁剪，性能更好；",
            "- **裁剪演示**:",
            "  - 100×100px 容器 + 100×100px 子图片 + 25px padding = 子元素溢出 25px；",
            "  - 4 种 Overflow 模式并排对比裁剪效果；",
            "- **交互高亮**:",
            "  - Outline 组件在 hover/press 时显示颜色——验证裁剪区域是否正确；",
            "  - Outline::color 根据 Interaction 状态变化（None=透明/Hovered=白/Pressed=红）；",
            "- **注意事项**:",
            "  - ⚠️ Overflow::visible() 在某些情况下可能导致渲染伪影；",
            "  - 🔧 滚动容器需要 Overflow::clip() + Scroll 组件；",
        ],
        "knowledge": [
            "知：<br>- Overflow 四种裁剪模式；<br>- clip vs visible 行为差异。",
            "例：<br>- ui/size_constraints.rs(237)。",
        ],
    },
    "overflow_clip_margin.rs": {
        "seq": 240,
        "cat": "UI",
        "filename": "`overflow_clip_margin.rs`",
        "intent": [
            "**意图**：OverflowClipMargin 精细控制裁剪边距——border_box/padding_box/content_box 三种裁剪盒模型；⭐",
            "- **OverflowClipMargin 类型**:",
            "  - OverflowClipMargin::border_box() 裁剪到边框外边缘——允许子元素延伸到 padding 区域；",
            "  - OverflowClipMargin::padding_box() 裁剪到内边距外边缘——子元素不能超出 padding；",
            "  - OverflowClipMargin::content_box() 裁剪到内容区域——最严格裁剪；",
            "  - with_margin(N) 附加额外裁剪边距——允许子元素超出裁剪盒 N 像素；",
            "- **裁剪层级**:",
            "  - content_box ⊂ padding_box ⊂ border_box（裁剪范围递增）；",
            "  - 🔧 margin 值越大，子元素可见区域越大；",
            "- **演示布局**:",
            "  - 4 种 OverflowClipMargin 配置并排展示；",
            "  - 100×100 容器 + 20px padding + 5px border + 100×100 子内容；",
            "  - 右侧标签显示当前裁剪模式名称；",
            "- **注意事项**:",
            "  - ⚠️ 需要配合 Overflow::clip() 使用——仅设置 clip_margin 无效果；",
            "  - 🔧 border_box + margin 是最常用的组合——允许子元素延伸到边框区域；",
        ],
        "knowledge": [
            "知：<br>- OverflowClipMargin 裁剪盒模型；<br>- border_box/padding_box/content_box 区别。",
            "例：<br>- ui/overflow.rs(239)。",
        ],
    },
    "overflow_debug.rs": {
        "seq": 241,
        "cat": "UI",
        "filename": "`overflow_debug.rs`",
        "intent": [
            "**意图**：UiTransform 在 Overflow::Hidden 下的裁剪行为——平移/缩放/旋转三种变换的裁剪效果对比；⭐⭐",
            "- **UiTransform 三种变换**:",
            "  - translation: percent(sin/cos) 圆周运动——裁剪边界处子元素被截断；",
            "  - scale: cos 驱动缩放——放大时溢出被裁剪，缩小时正常显示；",
            "  - rotation: Rot2::radians(cos) 旋转——旋转后矩形超出边界被裁剪；",
            "- **裁剪行为对比**:",
            "  - 6 个容器（3 种变换 × 图片/文本）展示不同裁剪效果；",
            "  - Overflow::clip() 统一裁剪——容器尺寸变化时裁剪区域动态调整；",
            "  - 🔧 图片和文本在相同变换下的裁剪表现可能不同；",
            "- **动画控制**:",
            "  - AnimationState Resource 追踪播放/暂停状态；",
            "  - Space 暂停/恢复，O 切换 Overflow 模式，S 切换容器尺寸；",
            "  - LOOP_LENGTH = 4.0 秒一个完整动画周期；",
            "- **容器尺寸切换**:",
            "  - 3 种尺寸：100%×100% / 100%×30% / 30%×100%——验证不同宽高比下的裁剪；",
            "  - ⚠️ 小容器中旋转/缩放更容易触发裁剪；",
            "- **注意事项**:",
            "  - ⚠️ Overflow 只影响直接子元素——孙元素不受影响（除非孙元素也有 Overflow）；",
            "  - 🔧 UiTransform 在 UI 中不同于 Transform——前者用于 UI 节点，后者用于 2D/3D 实体；",
        ],
        "knowledge": [
            "知：<br>- UiTransform 平移/缩放/旋转；<br>- Overflow::clip() 裁剪行为；<br>- 动画暂停/恢复。",
            "例：<br>- ui/overflow.rs(239)；<br>- ui/ui_transform.rs(256)。",
        ],
    },
    "z_index.rs": {
        "seq": 242,
        "cat": "UI",
        "filename": "`z_index.rs`",
        "intent": [
            "**意图**：ZIndex/GlobalZIndex 控制 UI 节点深度——同级兄弟排序 vs 全局跨层级排序；⭐⭐",
            "- **ZIndex 组件**:",
            "  - ZIndex(0) 默认值——同级节点按 spawn 顺序排列；",
            "  - ZIndex(2) 正值——在同级节点之上显示；",
            "  - ZIndex(-1) 负值——在同级节点之下显示；",
            "  - ⚠️ ZIndex 仅影响同级节点（兄弟之间）的渲染顺序；",
            "- **GlobalZIndex 组件**:",
            "  - GlobalZIndex(1) 全局正值——在所有 UI 节点之上显示；",
            "  - GlobalZIndex(-1) 全局负值——在所有 UI 节点之下显示（包括父节点）；",
            "  - 🔧 GlobalZIndex 打破层级限制，适合弹窗/覆盖层；",
            "- **演示场景**:",
            "  - 灰色容器内 5 个重叠的彩色矩形（RED/BLUE/LIME/PURPLE/YELLOW）；",
            "  - RED: 默认 ZIndex(0)；BLUE: ZIndex(2) 在灰容器内最高；",
            "  - LIME: ZIndex(-1) 在灰容器内最低；",
            "  - PURPLE: GlobalZIndex(1) 在所有节点之上；",
            "  - YELLOW: GlobalZIndex(-1) 在所有节点之下（甚至在父节点下方）；",
            "- **注意事项**:",
            "  - ⚠️ ZIndex 相同的节点按 spawn 顺序决定先后；",
            "  - 🔧 PositionType::Absolute 的节点也需要正确的 ZIndex 才能正确重叠；",
        ],
        "knowledge": [
            "知：<br>- ZIndex 同级排序；<br>- GlobalZIndex 全局排序；<br>- 绝对定位与 ZIndex 配合。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "gradients.rs": {
        "seq": 243,
        "cat": "UI",
        "filename": "`gradients.rs`",
        "intent": [
            "**意图**：UI 渐变完整体系——LinearGradient/RadialGradient/ConicGradient 三种渐变类型 + 颜色空间切换；⭐⭐⭐",
            "- **三种渐变类型**:",
            "  - LinearGradient { angle, stops } 线性渐变——角度控制方向；",
            "  - RadialGradient { stops, shape, position } 径向渐变——从中心向外扩散；",
            "  - ConicGradient { start, stops, position } 锥形渐变——绕中心旋转；",
            "- **ColorStop 颜色停靠点**:",
            "  - ColorStop::new(color, position) 指定颜色和位置（0%~100%）；",
            "  - ColorStop::auto(color) 自动均匀分布；",
            "  - 🔧 硬边界：两个相同颜色的停靠点在同一位置产生锐利分界；",
            "- **BackgroundGradient/BorderGradient**:",
            "  - BackgroundGradient(vec![gradient.into()]) 背景渐变——可叠加多个；",
            "  - BorderGradient::from(gradient) 边框渐变——独立于背景；",
            "  - 🔧 背景渐变和边框渐变可使用不同渐变类型和角度；",
            "- **InterpolationColorSpace 颜色空间**:",
            "  - Oklaba/Oklcha/Srgba/LinearRgba/Hsla/Hsva 等 9 种颜色空间；",
            "  - 按钮点击切换颜色空间——影响渐变插值效果；",
            "  - 🔧 Oklaba 视觉感知最均匀，Hsla 最直观；",
            "- **动画效果**:",
            "  - AnimateMarker 组件标记需要动画的渐变节点；",
            "  - 每帧更新 LinearGradient.angle 实现渐变旋转动画；",
        ],
        "knowledge": [
            "知：<br>- LinearGradient/RadialGradient/ConicGradient；<br>- ColorStop 颜色停靠；<br>- InterpolationColorSpace。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "stacked_gradients.rs": {
        "seq": 244,
        "cat": "UI",
        "filename": "`stacked_gradients.rs`",
        "intent": [
            "**意图**：多层渐变叠加——单个节点上同时应用 Linear/Radial/Conic 多种渐变形成复杂视觉效果；⭐⭐",
            "- **渐变叠加机制**:",
            "  - BackgroundGradient(vec![g1.into(), g2.into(), ...]) 多个渐变按数组顺序叠加；",
            "  - 🔧 后绘制的渐变覆盖在先绘制的渐变之上（画家算法）；",
            "- **6 层渐变示例**:",
            "  - LinearGradient::to_top_right 红色→透明（右上对角线）；",
            "  - LinearGradient::to_top_left 蓝色→透明（左上对角线）；",
            "  - ConicGradient 黄色锥形渐变（中心旋转）；",
            "  - RadialGradient 黄色径向渐变（顶部偏左）；",
            "  - 两条黑色→透明的 LinearGradient（不同角度）作为遮罩；",
            "- **颜色停靠点技巧**:",
            "  - ColorStop::auto(color.with_alpha(0.)) 透明停靠点实现渐隐；",
            "  - AngularColorStop::auto(color) 锥形渐变专用停靠点；",
            "  - 🔧 透明停靠点是实现渐变融合的关键——让多层渐变自然过渡；",
            "- **注意事项**:",
            "  - ⚠️ 大量渐变叠加有性能开销——每个渐变都需要额外的着色器计算；",
            "  - 🔧 简单场景 2~3 层渐变足够，复杂效果考虑预渲染到纹理；",
        ],
        "knowledge": [
            "知：<br>- BackgroundGradient 多层渐变；<br>- 渐变叠加顺序；<br>- 透明停靠点融合。",
            "例：<br>- ui/gradients.rs(243)。",
        ],
    },
    "font_weights.rs": {
        "seq": 245,
        "cat": "UI",
        "filename": "`font_weights.rs`",
        "intent": [
            "**意图**：FontWeight 字重系统——9 级标准字重(Thin~Black)在可变字体上的渲染效果；⭐",
            "- **FontWeight 9 级字重**:",
            "  - FontWeight::THIN (100) / EXTRA_LIGHT (200) / LIGHT (300)；",
            "  - FontWeight::NORMAL (400) / MEDIUM (500) / SEMIBOLD (600)；",
            "  - FontWeight::BOLD (700) / EXTRA_BOLD (800) / BLACK (900)；",
            "- **可变字体支持**:",
            "  - MonaSans-VariableFont.ttf 可变字体——单个文件包含所有字重；",
            "  - ⚠️ 静态字体（每个字重一个文件）需要加载不同字体文件；",
            "  - 🔧 可变字体文件更小但渲染引擎需要支持；",
            "- **TextFont.weight 字段**:",
            "  - weight: FontWeight::BOLD 设置字重；",
            "  - ⚠️ 字重不影响 font_size——粗细和大小是独立属性；",
            "- **注意事项**:",
            "  - 🔧 字重选择影响文本可读性——正文用 Normal/Medium，标题用 Bold/Black；",
            "  - 🔧 Underline 组件可与其他文本属性组合使用；",
        ],
        "knowledge": [
            "知：<br>- FontWeight 9 级字重；<br>- 可变字体 vs 静态字体；<br>- TextFont.weight 字段。",
            "例：<br>- ui/text.rs(231)。",
        ],
    },
    "font_atlas_debug.rs": {
        "seq": 246,
        "cat": "UI",
        "filename": "`font_atlas_debug.rs`",
        "intent": [
            "**意图**：FontAtlas 内部机制可视化——展示 Bevy 如何将字符光栅化到纹理图集(font atlas)中；⭐⭐",
            "- **FontAtlas 工作原理**:",
            "  - Bevy 将文本字符按需光栅化到大型纹理图集中；",
            "  - FontAtlasSet 管理所有字体的图集数据；",
            "  - ⚠️ 每个字体有独立的 FontAtlasSet——不同字体不共享图集；",
            "- **图集填充过程**:",
            "  - 随机字符每隔 0.05 秒添加一个到文本；",
            "  - 新字符首次出现时触发光栅化——添加到当前 FontAtlas；",
            "  - 当前图集满时创建新图集——atlas_count 追踪数量；",
            "- **可视化**:",
            "  - ImageNode 显示每个 FontAtlas 的纹理内容——字符按网格排列；",
            "  - x_offset = atlas_count × 图像宽度——图集水平排列展示；",
            "  - 🔧 观察图集填充过程可理解文本渲染的内存开销；",
            "- **确定性测试**:",
            "  - ChaCha8Rng::seed_from_u64(19878367467713) 确定性随机数——每次运行结果相同；",
            "  - 🔧 确定性对于回归测试和性能对比非常重要；",
            "- **注意事项**:",
            "  - ⚠️ FontAtlas 是按需创建的——不使用的字符不会占用图集空间；",
            "  - 🔧 大量不同字符（如中文）会创建更多图集——性能关注点；",
        ],
        "knowledge": [
            "知：<br>- FontAtlas/FontAtlasSet 图集机制；<br>- 字符按需光栅化；<br>- 确定性随机数。",
            "例：<br>- ui/text.rs(231)。",
        ],
    },
    "text_wrap_debug.rs": {
        "seq": 247,
        "cat": "UI",
        "filename": "`text_wrap_debug.rs`",
        "intent": [
            "**意图**：文本换行策略——LineBreak 四种模式 × JustifyContent 六种对齐的组合矩阵；⭐⭐",
            "- **LineBreak 四种模式**:",
            "  - LineBreak::AnyCharacter 任意字符处换行——最灵活但可能断词；",
            "  - LineBreak::WordBoundary 按单词边界换行——英文推荐；",
            "  - LineBreak::WordOrCharacter 优先单词，必要时字符——平衡方案；",
            "  - LineBreak::NoWrap 不换行——文本溢出容器；",
            "- **组合矩阵**:",
            "  - 4 种 LineBreak × 6 种 JustifyContent = 24 种组合；",
            "  - 每种组合独立展示换行效果；",
            "  - 🔧 矩阵式对比是理解文本排版最直观的方式；",
            "- **文本测试用例**:",
            '  - 短文本 "Line 1\\nLine 2" 验证显式换行；',
            "  - 长段落 Lorem ipsum 验证自动换行；",
            "  - 超长单词 pneumonoultramicroscopicsilicovolcanoconiosis 验证单词边界换行；",
            "- **命令行参数**:",
            "  - --scale-factor 窗口缩放因子——影响像素密度；",
            "  - --ui-scale UI 缩放因子——影响文本大小；",
            "  - 🔧 不同缩放因子下换行行为可能不同；",
            "- **注意事项**:",
            "  - ⚠️ overflow: Overflow::clip_x() 防止文本溢出容器宽度；",
            "  - 🔧 TextLayout::new(Justify::Left, linebreak) 同时设置对齐和换行；",
        ],
        "knowledge": [
            "知：<br>- LineBreak 四种换行模式；<br>- TextLayout 换行配置；<br>- 文本溢出处理。",
            "例：<br>- ui/text.rs(231)。",
        ],
    },
    "text_debug.rs": {
        "seq": 248,
        "cat": "UI",
        "filename": "`text_debug.rs`",
        "intent": [
            "**意图**：文本布局综合调试——多种对齐/换行/背景色/TextSpan 组合 + 实时 FPS 显示；⭐⭐⭐",
            "- **文本对齐**:",
            "  - Justify::Left/Right/Center/Justified 四种水平对齐；",
            "  - TextLayout::new_with_justify(justify) 设置对齐方式；",
            "- **TextSpan 富文本**:",
            "  - 父 Text::default() + 多个子 TextSpan 实现混合样式；",
            "  - 每个 span 独立 TextFont/TextColor——实现彩色/多字号文本；",
            "  - 🔧 TextUiWriter 精确修改特定 span 的文本内容（按索引）；",
            "- **实时 FPS 显示**:",
            "  - FrameTimeDiagnosticsPlugin 获取帧率和帧时间；",
            "  - Local<VecDeque> 存储历史数据计算平均值和方差；",
            "  - writer.text(entity, index) 按 span 索引更新文本；",
            "- **布局控制**:",
            "  - max_width: px(300/400) 限制文本宽度——触发换行；",
            "  - BackgroundColor(MAROON) 文本背景色——可视化文本边界；",
            "  - PositionType::Absolute 绝对定位——固定在窗口角落；",
            "- **注意事项**:",
            "  - ⚠️ font_size: 0.0 或负值——Bevy 会忽略但不报错；",
            "  - 🔧 PresentMode::AutoNoVsync 关闭垂直同步以观察真实帧率；",
        ],
        "knowledge": [
            "知：<br>- Justify 四种对齐；<br>- TextUiWriter 按索引更新；<br>- Local 历史数据。",
            "例：<br>- ui/text.rs(231)。",
        ],
    },
    "text_background_colors.rs": {
        "seq": 249,
        "cat": "UI",
        "filename": "`text_background_colors.rs`",
        "intent": [
            "**意图**：TextBackgroundColor 文本背景色——每个字符独立背景色 + 鼠标交互 + 颜色循环动画；⭐⭐",
            "- **TextBackgroundColor 组件**:",
            "  - TextBackgroundColor(Color) 为文本字符添加背景色块；",
            "  - ⚠️ 每个 TextSpan 独立背景色——可实现逐字符着色；",
            "  - 背景色块大小由字符尺寸决定——不包含额外 padding；",
            "- **逐字符着色**:",
            '  - 21 个 TextSpan 组成 "Text Background Colors!" 文本；',
            "  - PALETTE 颜色数组循环分配：RED/GREEN/BLUE/YELLOW/PURPLE；",
            "  - 🔧 字符级背景色适合高亮/语法着色/密码掩码等场景；",
            "- **鼠标交互**:",
            "  - observe(On<Pointer<Over>>) 鼠标悬停时文字变白；",
            "  - observe(On<Pointer<Out>>) 鼠标离开时文字恢复黑色；",
            "  - 🔧 Observer 模式比 Query + Changed 更简洁——直接在实体上注册回调；",
            "- **颜色循环动画**:",
            "  - cycle_text_background_colors 系统每帧偏移颜色索引；",
            "  - (i + n) % PALETTE.len() 实现滚动效果；",
            "  - ⚠️ single().unwrap() 假设只有一个 Text 实体——多文本时需修改；",
        ],
        "knowledge": [
            "知：<br>- TextBackgroundColor 文本背景色；<br>- Pointer<Over/Out> 鼠标事件；<br>- Observer 模式。",
            "例：<br>- ui/text.rs(231)；<br>- ui/button.rs(230)。",
        ],
    },
    "strikethrough_and_underline.rs": {
        "seq": 250,
        "cat": "UI",
        "filename": "`strikethrough_and_underline.rs`",
        "intent": [
            "**意图**：文本装饰组件——Strikethrough 删除线 + Underline 下划线 + 自定义颜色；⭐",
            "- **Strikethrough 组件**:",
            "  - Strikethrough 标记组件——添加到 Text/Text2d/TextSpan 即可生效；",
            "  - StrikethroughColor(Color) 自定义删除线颜色——默认跟随文本颜色；",
            "  - 🔧 删除线贯穿文本中部，不受字号影响；",
            "- **Underline 组件**:",
            "  - Underline 标记组件——添加下划线装饰；",
            "  - UnderlineColor(Color) 自定义下划线颜色；",
            "  - 🔧 下划线位于文本底部，间距由字体 metrics 决定；",
            "- **组合使用**:",
            "  - Strikethrough + Underline 可同时添加——文本同时有删除线和下划线；",
            "  - TextBackgroundColor 与装饰组件独立——背景色不影响装饰线；",
            "  - 🔧 适合编辑器 UI（已删除文本 + 语法标记）；",
            "- **TextSpan 装饰**:",
            "  - 每个 TextSpan 独立控制装饰——同一文本的不同部分可有不同装饰；",
            "  - 不同字号(15/30/50/70)的装饰线粗细相同——⚠️ 装饰线不随字号缩放；",
            "- **注意事项**:",
            "  - ⚠️ 装饰线颜色独立于文本颜色——需分别设置；",
            "  - 🔧 TextBackgroundColor 在装饰线之下——视觉层级：背景 → 装饰线 → 文本；",
        ],
        "knowledge": [
            "知：<br>- Strikethrough 删除线；<br>- Underline 下划线；<br>- StrikethroughColor/UnderlineColor。",
            "例：<br>- ui/text.rs(231)。",
        ],
    },
    "transparency_ui.rs": {
        "seq": 251,
        "cat": "UI",
        "filename": "`transparency_ui.rs`",
        "intent": [
            "**意图**：UI 透明度控制——TextColor alpha 通道实现半透明文本 + 不同背景色对比效果；⭐",
            "- **透明度原理**:",
            "  - TextColor(Color::srgba(1.0, 1.0, 1.0, 0.2)) alpha=0.2 高度透明；",
            "  - ⚠️ alpha 值范围 0.0(完全透明)~1.0(完全不透明)；",
            "  - 透明文本在不同背景色上呈现不同视觉效果；",
            "- **演示场景**:",
            "  - 绿色背景按钮 + 半透明白色文本；",
            "  - 紫色背景按钮 + 半透明白色文本；",
            "  - ⚠️ 同样的 alpha 值在不同背景上对比度不同——影响可读性；",
            "- **BackgroundColor 透明度**:",
            "  - BackgroundColor(Color::srgb(0.1, 0.5, 0.1)) 不透明背景；",
            "  - 🔧 背景不透明时文本透明效果更明显；",
            "  - ClearColor(Color::BLACK) 窗口清除色——全局背景；",
            "- **注意事项**:",
            "  - ⚠️ 极低 alpha 值(如 0.1)在深色背景上几乎不可见——影响无障碍性；",
            "  - 🔧 UI 透明度常用于：禁用状态文本、占位符文本、叠加层文本；",
        ],
        "knowledge": [
            "知：<br>- TextColor alpha 透明度；<br>- srgba 颜色模型；<br>- 透明度对可读性的影响。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "ghost_nodes.rs": {
        "seq": 252,
        "cat": "UI",
        "filename": "`ghost_nodes.rs`",
        "intent": [
            "**意图**：GhostNode 幽灵节点——布局中跳过自身，子元素视为直接后代（实验性功能）；⭐⭐",
            "- **GhostNode 概念**:",
            "  - GhostNode 标记的节点在布局计算时被忽略——子元素仿佛直接挂在父节点下；",
            "  - ⚠️ 实验性功能——需要启用 ghost_nodes feature flag；",
            "  - 🔧 适合分组逻辑但不影响布局的场景（如组件封装）；",
            "- **布局行为**:",
            "  - Ghost 节点的子元素参与非 Ghost 祖先的布局；",
            "  - Ghost 节点本身不占据任何空间——不产生边距/内边距；",
            "  - ⚠️ 第三方插件/系统可能不感知 Ghost 节点——需谨慎使用；",
            "- **演示场景**:",
            "  - Ghost 根节点 + 两个按钮——按钮视为普通根节点的直接子元素；",
            "  - 普通父节点 + Ghost 子节点 + Ghost 的子按钮——按钮视为普通父节点的子元素；",
            "  - Counter 组件追踪点击次数——Ghost 子元素与普通子元素共享父节点状态；",
            "- **交互**:",
            "  - 点击按钮更新父节点的 Counter——验证 Ghost 子元素的 ChildOf 关系；",
            "  - ChildOf 组件获取父实体——Ghost 节点跳过不计入布局层级；",
            "- **注意事项**:",
            "  - ⚠️ 该功能不稳定——API 可能在未来版本变更；",
            "  - 🔧 仅在确实需要分组逻辑但不影响布局时使用；",
        ],
        "knowledge": [
            "知：<br>- GhostNode 幽灵节点；<br>- 实验性 feature flag；<br>- ChildOf 父子关系。",
            "例：<br>- ui/flex_layout.rs(232)；<br>- ui/button.rs(230)。",
        ],
    },
    "relative_cursor_position.rs": {
        "seq": 253,
        "cat": "UI",
        "filename": "`relative_cursor_position.rs`",
        "intent": [
            "**意图**：RelativeCursorPosition 光标相对位置——检测鼠标在 UI 节点内的归一化坐标；⭐⭐",
            "- **RelativeCursorPosition 组件**:",
            "  - RelativeCursorPosition::default() 添加到节点即可启用；",
            "  - normalized: Option<Vec2> 归一化坐标(0.0~1.0)——(0,0)左上角，(1,1)右下角；",
            "  - cursor_over() -> bool 鼠标是否在节点区域内；",
            "  - ⚠️ 光标离开节点时 normalized 为 None；",
            "- **坐标系统**:",
            "  - 归一化坐标不受节点实际尺寸影响——始终 0~1 范围；",
            "  - 🔧 适合实现渐变色选择器/颜色拾取器等需要精确位置的 UI；",
            "- **Viewport 偏移**:",
            "  - Camera viewport: Viewport { physical_position: [200, 100] } 视口偏移；",
            "  - ⚠️ RelativeCursorPosition 自动考虑 viewport 偏移——坐标仍然正确；",
            "- **交互反馈**:",
            "  - Single<&RelativeCursorPosition> 单一实例查询——高效；",
            "  - 鼠标在区域内文字变绿，离开变红——实时视觉反馈；",
            '  - Text::new(format!("({:.1}, {:.1})", x, y)) 显示坐标值；',
            "- **注意事项**:",
            "  - ⚠️ 仅在节点有明确尺寸时有效——无尺寸节点返回 None；",
            "  - 🔧 配合 Pointer Events 可实现更复杂的交互逻辑；",
        ],
        "knowledge": [
            "知：<br>- RelativeCursorPosition 归一化坐标；<br>- cursor_over() 区域检测；<br>- Viewport 偏移。",
            "例：<br>- input/mouse_input.rs(182)；<br>- ui/button.rs(230)。",
        ],
    },
    "ui_scaling.rs": {
        "seq": 254,
        "cat": "UI",
        "filename": "`ui_scaling.rs`",
        "intent": [
            "**意图**：UiScale 资源全局缩放——键盘控制 1/8x~8x 缩放 + 指数缓动动画；⭐⭐",
            "- **UiScale 资源**:",
            "  - UiScale(1.0) 默认缩放倍数——1.0 = 100%；",
            "  - 修改 UiScale.0 全局缩放所有 UI 元素；",
            "  - ⚠️ 缩放影响所有 UI——包括文本/按钮/布局间距；",
            "- **缩放范围**:",
            "  - ArrowUp: scale * 2.0，最大 8.0；ArrowDown: scale / 2.0，最小 1/8；",
            "  - 🔧 指数级缩放（×2/÷2）比线性更直观——适合 DPI 调节；",
            "- **缓动动画**:",
            "  - TargetScale Resource 存储起始值/目标值/计时器；",
            "  - ease_in_expo(x) 指数缓动函数——快速启动，缓慢结束；",
            "  - Timer::new(400ms, Once) 400ms 缓动时长；",
            "  - 🔧 lerp(start, target, t) 插值——t=0 时为 start，t=1 时为 target；",
            "- **演示内容**:",
            "  - 红色方块 + 蓝色百分比方块 + Bevy 图标——不同尺寸的 UI 元素；",
            "  - 缩放时所有元素同步缩放——验证全局一致性；",
            "- **注意事项**:",
            "  - ⚠️ UiScale 与窗口 scale_factor 独立——两者叠加影响最终渲染尺寸；",
            "  - 🔧 UiScale 适合实现游戏内 DPI 调节/无障碍缩放功能；",
        ],
        "knowledge": [
            "知：<br>- UiScale 全局缩放资源；<br>- 缓动动画 easing；<br>- Timer 驱动过渡。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "ui_target_camera.rs": {
        "seq": 255,
        "cat": "UI",
        "filename": "`ui_target_camera.rs`",
        "intent": [
            "**意图**：UiTargetCamera 指定 UI 渲染目标 + Camera order 控制多层 UI 叠加；⭐⭐⭐",
            "- **UiTargetCamera 组件**:",
            "  - UiTargetCamera(camera_entity) 将 UI 节点绑定到指定相机；",
            "  - ⚠️ 不设置 UiTargetCamera 的 UI 使用最高 order 的主窗口相机；",
            "  - 🔧 一个 UI 节点只能有一个渲染目标——不支持 RenderLayers；",
            "- **Camera Order**:",
            "  - Camera { order: 0/1/2 } 控制相机渲染顺序——数字越大越后渲染（在上层）；",
            "  - order 0 的相机 ClearColorConfig 决定窗口清除色；",
            "  - 🔧 3 个相机分别渲染红/绿/蓝方块——通过 UiTargetCamera 绑定；",
            "- **多层 UI 叠加**:",
            "  - 不同相机渲染不同 UI 层——模拟 HUD + 游戏 UI 分层；",
            "  - 左键/右键调整相机 order——实时观察层级变化；",
            "  - ⚠️ order 相同时渲染顺序不确定——需要显式设置不同的 order；",
            "- **ClearColorConfig**:",
            "  - ClearColorConfig::Custom(color) 指定清除颜色；",
            "  - ClearColorConfig::NONE 不清除——保持前一个相机的渲染结果；",
            "  - 🔧 仅最低 order 的相机执行清除——高层相机叠加在低层之上；",
            "- **注意事项**:",
            "  - ⚠️ Bevy UI 不支持 RenderLayers——每个 UI 树只能有一个渲染目标；",
            "  - 🔧 多相机 UI 适合：主菜单 + 游戏 HUD + 调试面板 分层渲染；",
        ],
        "knowledge": [
            "知：<br>- UiTargetCamera 绑定渲染目标；<br>- Camera order 层级；<br>- ClearColorConfig 清除色。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "ui_transform.rs": {
        "seq": 256,
        "cat": "UI",
        "filename": "`ui_transform.rs`",
        "intent": [
            "**意图**：UiTransform UI 变换——平移/旋转/缩放 UI 元素 + 按钮交互控制；⭐⭐",
            "- **UiTransform 组件**:",
            "  - translation: Val2 平移——Val::Px/Val::Percent 精确控制位置；",
            "  - rotation: Rot2 旋转——基于弧度的 2D 旋转；",
            "  - scale: Vec2 缩放——独立控制水平/垂直缩放；",
            "  - 🔧 UiTransform 与 Node 的 position 不同——前者是变换矩阵，后者是布局定位；",
            "- **按钮交互控制**:",
            "  - RotateButton(Rot2) 组件存储旋转步长——点击旋转 ±22.5°(FRAC_PI_8)；",
            "  - ScaleButton(f32) 组件存储缩放步长——点击缩放 ±0.25；",
            "  - ⚠️ scale clamp(0.25, 3.0) 防止过度缩放；",
            "- **键盘平移**:",
            "  - ArrowLeft/Right/Up/Down 键盘控制平移方向；",
            "  - 50.0 * time.delta_secs() 帧率无关平移速度；",
            "  - ⚠️ clamp(-150, 150) 限制平移范围——防止移出视野；",
            "- **旋转子元素**:",
            '  - UiTransform::from_rotation(Rot2::radians(PI/2)) 旋转 90°——"Left"/"Right" 按钮；',
            "  - 🔧 旋转后的按钮文本也会旋转——⚠️ 可能影响可读性；",
            "- **注意事项**:",
            "  - ⚠️ UiTransform 不影响布局计算——节点仍占据原始空间；",
            "  - 🔧 GlobalZIndex(1) 确保控制按钮在目标节点之上；",
        ],
        "knowledge": [
            "知：<br>- UiTransform 平移/旋转/缩放；<br>- Rot2 二维旋转；<br>- clamp 限制范围。",
            "例：<br>- ui/flex_layout.rs(232)；<br>- ui/overflow_debug.rs(241)。",
        ],
    },
    "ui_material.rs": {
        "seq": 257,
        "cat": "UI",
        "filename": "`ui_material.rs`",
        "intent": [
            "**意图**：UiMaterial 自定义着色器材质——AsBindGroup 桥接 Rust 数据到 GPU + WGSL 片段着色器；⭐⭐⭐",
            "- **UiMaterial trait**:",
            "  - impl UiMaterial for CustomUiMaterial { fn fragment_shader() -> ShaderRef } 定义自定义材质；",
            "  - UiMaterialPlugin::<CustomUiMaterial>::default() 注册材质插件；",
            "  - 🔧 UiMaterial 类似 Material3d 但专用于 UI 节点；",
            "- **AsBindGroup 数据绑定**:",
            "  - #[uniform(0)] color: Vec4 均匀缓冲区——每帧可更新；",
            "  - #[texture(2)] + #[sampler(3)] 纹理+采样器绑定；",
            "  - ⚠️ uniform 必须 16 字节对齐——Vec4 而非 Vec3/f32；",
            "- **MaterialNode 组件**:",
            "  - MaterialNode(handle) 绑定材质到 UI 节点——替换默认 BackgroundColor；",
            "  - 材质节点仍支持 Outline/BoxShadow 等 UI 组件；",
            "- **动画效果**:",
            "  - animate 系统每帧更新材质参数；",
            "  - rainbow color: Color::hsl(time * 60 % 360, 1, 0.5) 彩虹色循环；",
            "  - slider: Vec4::splat(progress) 进度条从 0→1→0 循环；",
            "- **WGSL 着色器**:",
            '  - SHADER_ASSET_PATH = "shaders/custom_ui_material.wgsl" 外部着色器文件；',
            "  - 🔧 着色器中通过 @group(1) @binding(N) 访问绑定数据；",
        ],
        "knowledge": [
            "知：<br>- UiMaterial trait 自定义材质；<br>- AsBindGroup 数据绑定；<br>- WGSL 着色器。",
            "例：<br>- shader/shader_material.rs(294)；<br>- ui/button.rs(230)。",
        ],
    },
    "ui_texture_atlas.rs": {
        "seq": 258,
        "cat": "UI",
        "filename": "`ui_texture_atlas.rs`",
        "intent": [
            "**意图**：UI 中使用 TextureAtlas 纹理图集——SpriteSheet 动画帧切换 + 键盘交互控制；⭐⭐",
            "- **TextureAtlas 在 UI 中的使用**:",
            "  - ImageNode::from_atlas_image(texture_handle, TextureAtlas::from(layout_handle)) 创建图集图像节点；",
            "  - TextureAtlasLayout::from_grid(UVec2::splat(24), 7, 1, None, None) 定义 7 帧 24×24 网格；",
            "  - ⚠️ UI 的 ImageNode 使用 texture_atlas 字段，而非 Sprite 组件；",
            "- **帧切换控制**:",
            "  - ImageNode.texture_atlas.as_mut().unwrap().index = (index + 1) % 6 手动推进帧；",
            "  - Space 键触发帧切换——just_pressed 保证每次只进一帧；",
            "  - 🔧 % 6 防止越界——7 帧但只用前 6 帧（第 7 帧留空）；",
            "- **像素风格渲染**:",
            "  - ImagePlugin::default_nearest() 防止纹理缩放模糊；",
            "  - ⚠️ 默认线性过滤会让像素风纹理变模糊——必须显式设置 nearest；",
            "- **演示场景**:",
            "  - 256×256 像素的 Gabe 角色精灵动画；",
            "  - Outline::new(px(8), Val::ZERO, CRIMSON) 红色轮廓线标记；",
            '  - TextSpan 提示 "press space to advance frames"；',
            "- **注意事项**:",
            "  - ⚠️ TextureAtlas 帧索引从 0 开始——⚠️ 越界会导致渲染异常；",
            "  - 🔧 适合 UI 动画图标/角色肖像动画/技能图标动画；",
        ],
        "knowledge": [
            "知：<br>- ImageNode + TextureAtlas；<br>- TextureAtlasLayout 帧定义；<br>- ImagePlugin::default_nearest。",
            "例：<br>- ui/button.rs(230)；<br>- 2D/sprite_sheet.rs(10)。",
        ],
    },
}


def build_line(entry, orig_seq=None):
    """Build a catalog table line from entry dict, optionally using original seq number."""
    seq = orig_seq if orig_seq is not None else entry["seq"]
    intent_str = "<br>".join(entry["intent"])
    knowledge_str = "<br>".join(entry["knowledge"])
    return f"| {seq} | {entry['cat']} | {entry['filename']} | {intent_str} | {knowledge_str} |"


def extract_seq(line):
    """Extract the sequence number from a catalog line like '| 232 | UI | ...'"""
    import re

    m = re.match(r"\|\s*(\d+)\s*\|", line)
    return m.group(1) if m else None


# Read the catalog
with open(CATALOG_PATH, "r", encoding="utf-8") as f:
    content = f.read()

lines = content.split("\n")

# Find and replace entries by matching filename pattern in placeholder rows
new_lines = []
replaced = 0
for line in lines:
    matched = False
    for fname, entry in ENTRIES.items():
        pattern = f"| UI | `{fname}`"
        if pattern in line and "**Sprite组件**" in line:  # placeholder content marker
            orig_seq = extract_seq(line)
            new_lines.append(build_line(entry, orig_seq))
            replaced += 1
            matched = True
            break
    if not matched:
        new_lines.append(line)

# Write back
with open(CATALOG_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(new_lines))

print(f"Replaced {replaced} entries (expected 30)")
assert replaced == 30, f"Expected 30 replacements, got {replaced}"
