#!/usr/bin/env python3
"""Replace catalog entries 210-230 and 261-281 with detailed content from source files.
Matches entries by filename pattern instead of hardcoded line numbers."""

import re

CATALOG_PATH = "/Users/lf380/Code/Bevy/a1/bevy_examples_catalog.md"

ENTRIES = {
    # ── diagnostics ──────────────────────────────────────────────
    "log_diagnostics.rs": {
        "seq": 210,
        "cat": "诊断",
        "filename": "`log_diagnostics.rs`",
        "intent": [
            "**意图**：将 FPS/帧数/帧时间/实体数/系统 CPU/内存 等诊断指标输出到控制台，并支持过滤切换；⭐⭐",
            "- **诊断插件组合**:",
            "  - LogDiagnosticsPlugin::default() 将诊断数据打印到控制台——⚠️ 必须在 DefaultPlugins 之后添加；",
            "  - FrameTimeDiagnosticsPlugin::default() 提供 FPS/帧数/帧时间三项指标；",
            "  - EntityCountDiagnosticsPlugin::default() 追踪运行时实体总数；",
            "  - SystemInformationDiagnosticsPlugin 提供进程级 CPU/内存使用率；",
            "  - 🔧 RenderDiagnosticsPlugin 转发渲染线程诊断——数据量大但可精确定位 GPU 瓶颈；",
            "- **DiagnosticPath 常量**:",
            "  - FRAME_TIME_DIAGNOSTICS / ENTITY_COUNT_DIAGNOSTICS / SYSTEM_INFO_DIAGNOSTICS 数组分组；",
            "  - 每个 DiagnosticPath 是唯一标识符——用于过滤/启用/禁用单个诊断；",
            "- **LogDiagnosticsState 过滤**:",
            "  - enable_filtering() 启用过滤模式——仅输出指定诊断；",
            "  - extend_filter(iter) 批量添加诊断到过滤器；",
            "  - remove_filter(path) 移除单个诊断；",
            "  - ⚠️ 过滤器为空时输出所有诊断——等价于禁用过滤；",
            "- **交互控制**:",
            "  - Q 键切换过滤模式（启用/禁用）；",
            "  - 1/2/3 键分别切换 FrameTimes/EntityCount/SystemInfo；",
            "  - LogDiagnosticsStatus Resource 追踪当前状态——驱动 UI 颜色更新；",
            "- **注意事项**:",
            "  - ⚠️ 诊断插件需要时间系统——必须在 DefaultPlugins 之后添加；",
            "  - 🔬 每帧输出大量诊断数据会占用控制台——生产环境建议关闭或降低频率；",
        ],
        "knowledge": [
            "知：<br>- LogDiagnosticsPlugin 诊断输出；<br>- DiagnosticPath 唯一标识；<br>- LogDiagnosticsState 过滤。",
            "例：<br>- app/empty_defaults.rs(108)。",
        ],
    },
    "custom_diagnostic.rs": {
        "seq": 211,
        "cat": "诊断",
        "filename": "`custom_diagnostic.rs`",
        "intent": [
            "**意图**：创建自定义诊断指标——注册 Diagnostic 并在系统中添加测量值；⭐",
            "- **Diagnostic 注册**:",
            "  - Diagnostic::new(SYSTEM_ITERATION_COUNT) 创建新诊断——需要全局唯一 DiagnosticPath；",
            '  - .with_suffix(" iterations") 添加单位后缀——输出时显示在数值后面；',
            "  - 🔧 register_diagnostic() 必须在 Startup 之前调用——⚠️ 运行时注册会导致 panic；",
            "- **DiagnosticPath 定义**:",
            '  - DiagnosticPath::const_new("system_iteration_count") 编译时常量——推荐方式；',
            "  - ⚠️ 路径名称必须全局唯一——重复注册会 panic；",
            "- **添加测量值**:",
            "  - diagnostics.add_measurement(&path, || 10.0) 闭包返回当前值——每帧调用一次；",
            "  - ⚠️ 闭包仅在诊断启用时执行——禁用时无性能开销；",
            "- **与 LogDiagnosticsPlugin 配合**:",
            "  - LogDiagnosticsPlugin 自动收集所有注册的诊断并输出；",
            "  - 🔧 自定义诊断可用于：系统调用计数、缓存命中率、队列长度等；",
        ],
        "knowledge": [
            "知：<br>- Diagnostic 自定义诊断；<br>- DiagnosticPath 唯一路径；<br>- add_measurement 添加测量值。",
            "例：<br>- diagnostics/log_diagnostics.rs(210)。",
        ],
    },
    "enabling_disabling_diagnostic.rs": {
        "seq": 212,
        "cat": "诊断",
        "filename": "`enabling_disabling_diagnostic.rs`",
        "intent": [
            "**意图**：运行时动态启用/禁用诊断——遍历 DiagnosticsStore 切换 is_enabled 标志；⭐",
            "- **DiagnosticsStore 遍历**:",
            "  - store.iter_mut() 获取所有已注册诊断的可变引用；",
            "  - diag.is_enabled = !diag.is_enabled 切换启用状态——布尔标志；",
            "  - ⚠️ 禁用后诊断不再收集数据——但 Diagnostic 对象仍保留在 Store 中；",
            "- **on_timer 条件系统**:",
            "  - run_if(on_timer(Duration::from_secs_f32(10.0))) 每 10 秒触发一次；",
            "  - 🔧 比在系统内 if 判断更高效——条件不满足时整个系统不调度；",
            "- **诊断路径输出**:",
            "  - diag.path() 获取诊断的 DiagnosticPath——用于日志标识；",
            "  - info! 宏输出切换信息——方便调试；",
            "- **注意事项**:",
            "  - ⚠️ 禁用 FrameTimeDiagnosticsPlugin 会影响依赖 FPS 的 UI 显示；",
            "  - 🔧 适合性能敏感场景：战斗时禁用非关键诊断，探索时恢复；",
        ],
        "knowledge": [
            "知：<br>- DiagnosticsStore 诊断存储；<br>- is_enabled 启用标志；<br>- on_timer 定时条件。",
            "例：<br>- diagnostics/log_diagnostics.rs(210)。",
        ],
    },
    # ── dev_tools ────────────────────────────────────────────────
    "fps_overlay.rs": {
        "seq": 213,
        "cat": "开发者工具",
        "filename": "`fps_overlay.rs`",
        "intent": [
            "**意图**：FPS 覆盖层——运行时显示帧率/帧时间图表，支持颜色/字号/刷新率交互调节；⭐⭐",
            "- **FpsOverlayPlugin 配置**:",
            "  - FpsOverlayConfig { text_config, text_color, refresh_interval, enabled, frame_time_graph_config } 完整配置；",
            "  - text_config: TextFont { font_size: 42.0, font, font_smoothing } 控制文本样式；",
            "  - text_color: Color 控制覆盖层颜色——运行时可通过 ResMut 修改；",
            "  - refresh_interval: Duration 刷新间隔——100ms 平衡精度与性能；",
            "- **FrameTimeGraphConfig**:",
            "  - enabled: bool 启用帧时间图表——实时显示帧时间波动；",
            "  - min_fps: 30.0 最低可接受帧率——低于此值图表变红；",
            "  - target_fps: 144.0 目标帧率——图表参考线；",
            "  - 🔧 图表直观显示帧率稳定性——比数字更易发现问题；",
            "- **运行时配置修改**:",
            "  - ResMut<FpsOverlayConfig> 直接修改资源——立即生效；",
            "  - 1 键切换颜色（红/绿）；2/3 键调节字号；",
            "  - 4 键切换覆盖层可见性；5 键切换帧时间图表；",
            "- **注意事项**:",
            "  - ⚠️ 覆盖层需要 Camera2d 才能显示——无相机时不可见；",
            "  - 🔧 字号过大可能遮挡游戏内容——建议用 PositionType::Absolute 定位；",
        ],
        "knowledge": [
            "知：<br>- FpsOverlayPlugin FPS 覆盖层；<br>- FpsOverlayConfig 配置；<br>- FrameTimeGraphConfig 图表。",
            "例：<br>- app/empty_defaults.rs(108)。",
        ],
    },
    # ── window ───────────────────────────────────────────────────
    "window_settings.rs": {
        "seq": 214,
        "cat": "窗口管理",
        "filename": "`window_settings.rs`",
        "intent": [
            "**意图**：综合演示窗口设置——光标/PresentMode/全屏/窗口层级/按钮控制/光标图标循环；⭐⭐⭐",
            "- **Window 初始配置**:",
            "  - Window { title, name, resolution, present_mode, fit_canvas_to_parent, window_theme, enabled_buttons, visible } 全面配置；",
            "  - visible: false 延迟显示——避免 GPU 未就绪时的白屏闪烁；",
            "  - 🔧 make_visible() 系统在第 3 帧后显示窗口——确保渲染管线就绪；",
            "- **PresentMode 切换**:",
            "  - V 键切换 AutoVsync ↔ AutoNoVsync——影响帧率上限和撕裂；",
            "  - ⚠️ AutoNoVsync 关闭垂直同步——帧率更高但可能撕裂；",
            "- **WindowLevel 层级**:",
            "  - T 键循环 AlwaysOnBottom → Normal → AlwaysOnTop；",
            "  - ⚠️ 仅部分平台支持——macOS/Linux/Windows 行为不同；",
            "- **窗口按钮控制**:",
            "  - 1/2/3 键分别切换 minimize/maximize/close 按钮可用性；",
            "  - enabled_buttons { minimize, maximize, close } 独立控制；",
            "  - 🔧 隐藏关闭按钮可防止用户误关——适合长时间运行的应用；",
            "- **光标图标循环**:",
            "  - CursorIcon::from(SystemCursorIcon) 系统光标图标枚举；",
            "  - cycle_cursor_icon 系统遍历所有 SystemCursorIcon——展示可用图标；",
            "- **光标锁定**:",
            "  - CursorOptions { visible, grab_mode } 控制光标可见性和锁定模式；",
            "  - ⚠️ grab_mode 仅在窗口聚焦时有效——失焦自动解锁；",
        ],
        "knowledge": [
            "知：<br>- Window 组件配置；<br>- PresentMode 垂直同步；<br>- WindowLevel 窗口层级；<br>- CursorIcon 光标图标。",
            "例：<br>- app/empty_defaults.rs(108)。",
        ],
    },
    "clear_color.rs": {
        "seq": 215,
        "cat": "窗口管理",
        "filename": "`clear_color.rs`",
        "intent": [
            "**意图**：设置窗口清除颜色（背景色）——InsertResource 注入 + 运行时 ResMut 修改；⭐",
            "- **ClearColor 资源**:",
            "  - ClearColor(Color::srgb(0.5, 0.5, 0.9)) 通过 insert_resource 设置初始清除色；",
            "  - ResMut<ClearColor> 运行时修改——立即生效于下一帧；",
            "  - ⚠️ ClearColor 是全局资源——影响所有使用默认清除的相机；",
            "- **颜色模型**:",
            "  - Color::srgb(r, g, b) 标准 RGB——0.0~1.0 范围；",
            "  - PURPLE 常量来自 palettes::css——预定义 CSS 颜色；",
            "- **交互控制**:",
            "  - Space 键切换清除色为紫色——演示运行时修改；",
            "  - 🔧 ClearColor::NONE 可禁用清除——保留上一帧内容（适合后处理）；",
            "- **注意事项**:",
            "  - ⚠️ 清除色仅在相机 ClearColorConfig::Default 时生效；",
            "  - 🔧 透明窗口需要 ClearColor(Color::NONE) + transparent: true；",
        ],
        "knowledge": [
            "知：<br>- ClearColor 背景色资源；<br>- insert_resource / ResMut 修改。",
            "例：<br>- app/empty_defaults.rs(108)。",
        ],
    },
    "window_resizing.rs": {
        "seq": 216,
        "cat": "窗口管理",
        "filename": "`window_resizing.rs`",
        "intent": [
            "**意图**：窗口大小调整——ResolutionSettings 资源存储预设分辨率 + WindowResized 事件响应；⭐⭐",
            "- **ResolutionSettings Resource**:",
            "  - large/medium/small: Vec2 三档预设分辨率——存储为 Resource 全局访问；",
            "  - window.resolution.set(x, y) 设置新分辨率——触发窗口调整；",
            "  - 🔧 Resource 存储配置数据比硬编码更灵活——可扩展为动态分辨率；",
            "- **WindowResized 事件**:",
            "  - MessageReader<WindowResized> 监听窗口大小变化事件；",
            "  - e.width / e.height 新的窗口尺寸——逻辑像素单位；",
            "  - ⚠️ 事件在窗口调整期间持续触发——频繁更新文本可能有性能开销；",
            "- **交互控制**:",
            "  - 1/2/3 键分别切换 small/medium/large 分辨率；",
            "  - ResolutionText 组件标记文本实体——精确定位更新目标；",
            "- **注意事项**:",
            "  - ⚠️ 分辨率变化会触发重新布局——所有 UI 节点重新计算；",
            "  - 🔧 监听 WindowResized 可实现自适应 UI——根据窗口大小调整布局；",
        ],
        "knowledge": [
            "知：<br>- Window.resolution.set 分辨率设置；<br>- WindowResized 事件监听；<br>- ResolutionSettings Resource。",
            "例：<br>- window/window_settings.rs(214)。",
        ],
    },
    "transparent_window.rs": {
        "seq": 217,
        "cat": "窗口管理",
        "filename": "`transparent_window.rs`",
        "intent": [
            "**意图**：透明窗口——transparent + decorations:false + ClearColor::NONE 实现无边框透明；⭐",
            "- **透明窗口配置**:",
            "  - Window { transparent: true, decorations: false } 启用透明并禁用装饰；",
            "  - ClearColor(Color::NONE) 清除色为透明——⚠️ alpha=0 是必须的；",
            "  - 🔧 CompositeAlphaMode 控制透明混合模式——macOS 用 PostMultiplied，Linux 用 PreMultiplied；",
            "- **平台差异**:",
            "  - ⚠️ transparent 在不同平台表现不同——需检查文档确认兼容性；",
            "  - macOS: 需要 PostMultiplied alpha 模式；",
            "  - Linux: 需要 PreMultiplied alpha 模式；",
            "  - Windows: 原生支持，无需特殊配置；",
            "- **使用场景**:",
            "  - 🧩 透明窗口适合：桌面小组件/覆盖层/浮动工具栏/OSD 信息显示；",
            "  - 🔧 配合 window_fallthrough.rs 可实现鼠标事件穿透；",
            "- **注意事项**:",
            "  - ⚠️ 透明窗口性能开销略高——GPU 需要混合透明像素；",
            "  - 🔧 decorations:false 移除标题栏——窗口变为纯内容区域；",
        ],
        "knowledge": [
            "知：<br>- Window::transparent 透明模式；<br>- ClearColor::NONE 透明清除；<br>- CompositeAlphaMode 透明混合。",
            "例：<br>- window/window_settings.rs(214)。",
        ],
    },
    "window_drag_move.rs": {
        "seq": 218,
        "cat": "窗口管理",
        "filename": "`window_drag_move.rs`",
        "intent": [
            "**意图**：无装饰窗口的拖拽移动和调整大小——start_drag_move/start_drag_resize API；⭐⭐",
            "- **start_drag_move()**:",
            "  - window.start_drag_move() 启动窗口拖拽——⚠️ 必须在 MouseButton::Left 按下时调用；",
            "  - winit 0.30.5 在非左键按下时调用会 panic；",
            "  - 🔧 适合自定义标题栏/全屏应用的窗口移动；",
            "- **start_drag_resize(direction)**:",
            "  - window.start_drag_resize(CompassOctant) 启动窗口调整——指定方向；",
            "  - CompassOctant::North/East/South/West/NE/SE/SW/NW 八个方向；",
            "  - 🔧 可实现自定义窗口边缘拖拽调整——无需系统标题栏；",
            "- **LeftClickAction Resource**:",
            "  - Move/Resize/Nothing 三种左键行为——A 键循环切换；",
            "  - S/D 键切换调整方向——8 方向循环；",
            "- **注意事项**:",
            "  - ⚠️ start_drag_move/start_drag_resize 必须在鼠标按下事件中调用；",
            "  - 🔧 decorations:false 是前提——有装饰的窗口已内置拖拽功能；",
        ],
        "knowledge": [
            "知：<br>- start_drag_move 拖拽移动；<br>- start_drag_resize 拖拽调整；<br>- CompassOctant 方向枚举。",
            "例：<br>- window/window_settings.rs(214)。",
        ],
    },
    "low_power.rs": {
        "seq": 219,
        "cat": "窗口管理",
        "filename": "`low_power.rs`",
        "intent": [
            "**意图**：反应式低功耗模式——WinitSettings 控制事件循环频率，游戏/桌面应用/自定义模式切换；⭐⭐⭐",
            "- **WinitSettings 三种模式**:",
            "  - WinitSettings::game() 游戏模式——聚焦时连续渲染，失焦时 60Hz 限频；",
            "  - WinitSettings::desktop_app() 桌面应用模式——聚焦时仅在输入事件后渲染，失焦时 1 分钟限频；",
            "  - 自定义 WinitSettings { focused_mode, unfocused_mode } 精细控制；",
            "  - ⚠️ desktop_app() 可大幅降低 CPU/GPU 占用——适合工具类应用；",
            "- **focused_mode / unfocused_mode**:",
            "  - UpdateMode::Continuous 连续渲染——每帧都更新；",
            "  - UpdateMode::reactive_low_power(Duration) 反应式低功耗——仅在输入/事件后更新；",
            "  - 🔧 reactive_low_power(10ms) 设置最大延迟——确保 UI 响应及时；",
            "- **RequestRedraw 事件**:",
            "  - MessageWriter<RequestRedraw> 手动请求重绘——覆盖 reactive 模式限制；",
            "  - 适合动画播放时强制重绘——动画结束后停止发送；",
            "  - 🔧 配合 desktop_app() 可实现「按需渲染」——大幅节省电量；",
            "- **WakeUp 事件**:",
            "  - EventLoopProxyWrapper 发送 WakeUp——从外部线程唤醒事件循环；",
            "  - 🔧 适合后台任务完成后通知 UI 刷新——如文件下载完成；",
            "- **四种模式切换**:",
            "  - Space 键循环 Game → Application → ApplicationWithRequestRedraw → ApplicationWithWakeUp；",
            "  - ModeText 组件追踪当前模式——实时显示在屏幕上；",
        ],
        "knowledge": [
            "知：<br>- WinitSettings 事件循环配置；<br>- reactive_low_power 低功耗模式；<br>- RequestRedraw 手动重绘。",
            "例：<br>- window/window_settings.rs(214)。",
        ],
    },
    "scale_factor_override.rs": {
        "seq": 220,
        "cat": "窗口管理",
        "filename": "`scale_factor_override.rs`",
        "intent": [
            "**意图**：覆盖操作系统窗口缩放因子——WindowResolution::with_scale_factor_override 强制 DPI 缩放；⭐⭐",
            "- **scale_factor_override**:",
            "  - WindowResolution::new(500, 300).with_scale_factor_override(1.0) 强制 1x 缩放；",
            "  - window.resolution.scale_factor_override() 获取当前覆盖值——Option<f32>；",
            "  - window.resolution.set_scale_factor_override(Some/None) 设置/清除覆盖；",
            "  - ⚠️ 覆盖后窗口内容按指定缩放因子渲染——忽略系统 DPI 设置；",
            "- **交互控制**:",
            "  - Enter 键切换覆盖/清除——Some(1.0) ↔ None；",
            "  - ArrowUp/Down 增减覆盖值——步长 1.0，最小 1.0；",
            "- **display_override 系统**:",
            "  - window.scale_factor() 获取实际缩放因子——包含系统和覆盖；",
            '  - format!("Scale factor: {:.1} (overridden/default)") 显示当前状态；',
            "  - window.title 同步更新标题栏——直观显示缩放信息；",
            "- **注意事项**:",
            "  - ⚠️ 覆盖值为 None 时使用系统 DPI——Retina 屏幕默认 2x；",
            "  - 🔧 强制 1.0 缩放可避免 HiDPI 模糊——适合像素风游戏；",
        ],
        "knowledge": [
            "知：<br>- WindowResolution::scale_factor_override 缩放覆盖；<br>- scale_factor 实际缩放因子。",
            "例：<br>- window/window_settings.rs(214)。",
        ],
    },
    "screenshot.rs": {
        "seq": 221,
        "cat": "窗口管理",
        "filename": "`screenshot.rs`",
        "intent": [
            "**意图**：保存屏幕截图到磁盘——Screenshot::primary_window() + save_to_disk Observer；⭐⭐",
            "- **Screenshot 组件**:",
            "  - Screenshot::primary_window() 创建主窗口截图实体；",
            "  - .observe(save_to_disk(path)) 注册保存回调——Observer 模式；",
            "  - 🔧 save_to_disk 接受路径字符串——支持 .png/.bmp/.tga 格式；",
            "- **Capturing 组件**:",
            "  - Query<Entity, With<Capturing>> 查询正在捕获的截图实体；",
            "  - 0 个：无截图进行中——移除光标图标；",
            "  - >0 个：有截图进行中——设置 Progress 光标图标；",
            "  - 🔧 CursorIcon::from(SystemCursorIcon::Progress) 显示加载状态光标；",
            "- **Local 计数器**:",
            "  - Local<u32> 存储截图序号——每次截图递增；",
            '  - format!("./screenshot-{}.png", *counter) 文件名包含序号——避免覆盖；',
            "- **注意事项**:",
            "  - ⚠️ 截图保存到当前工作目录——路径是相对路径；",
            "  - 🔧 截图期间光标变为进度图标——防止用户误操作；",
            "  - 🔬 截图会暂停渲染管线一帧——频繁截图可能影响帧率；",
        ],
        "knowledge": [
            "知：<br>- Screenshot 截图组件；<br>- save_to_disk 保存回调；<br>- Capturing 捕获状态。",
            "例：<br>- 3D/render_to_texture.rs(56)。",
        ],
    },
    "multiple_windows.rs": {
        "seq": 222,
        "cat": "窗口管理",
        "filename": "`multiple_windows.rs`",
        "intent": [
            "**意图**：两个窗口从不同角度可视化 3D 模型——WindowRef + RenderTarget::Window 多窗口渲染；⭐⭐",
            "- **第二窗口创建**:",
            '  - commands.spawn(Window { title: "Second window", ..default() }) 创建新窗口实体；',
            "  - .id() 获取窗口 Entity——用于绑定相机和 UI；",
            "  - 🔧 PrimaryWindow 由 DefaultPlugins 自动创建——无需手动管理；",
            "- **RenderTarget::Window(WindowRef::Entity)**:",
            "  - Camera { render_target: RenderTarget::Window(WindowRef::Entity(window)) } 绑定到指定窗口；",
            "  - ⚠️ 不设置 render_target 的相机默认渲染到 PrimaryWindow；",
            "- **UiTargetCamera 绑定**:",
            "  - UiTargetCamera(camera_entity) 将 UI 节点绑定到特定相机；",
            "  - ⚠️ 多相机时必须显式绑定——否则 UI 可能渲染到错误的窗口；",
            "- **场景构建**:",
            "  - SceneRoot(glTF) 加载 3D 模型——torus 环面；",
            "  - DirectionalLight 方向光照明——两个窗口共享同一场景；",
            "  - 🔧 两个相机从不同角度（正面/侧面）观察同一模型；",
        ],
        "knowledge": [
            "知：<br>- WindowRef 窗口引用；<br>- RenderTarget::Window 多窗口渲染；<br>- UiTargetCamera UI 绑定。",
            "例：<br>- window/window_settings.rs(214)。",
        ],
    },
    "multi_window_text.rs": {
        "seq": 223,
        "cat": "窗口管理",
        "filename": "`multi_window_text.rs`",
        "intent": [
            "**意图**：多窗口文本渲染——不同缩放因子的窗口中渲染 Text 和 Text2d，演示 RenderLayers 分离；⭐⭐⭐",
            "- **多缩放因子窗口**:",
            "  - PrimaryWindow: scale_factor_override(1.0) —— 标准分辨率；",
            "  - SecondaryWindow: scale_factor_override(2.0) —— 双倍分辨率（Retina 级别）；",
            "  - ⚠️ 缩放因子影响字体渲染质量——高缩放因子文字更清晰但消耗更多 GPU；",
            "- **RenderLayers 分离**:",
            "  - PrimaryWindow camera: 默认 layer(0)；",
            "  - SecondaryWindow camera: RenderLayers::layer(1) + RenderTarget::Window；",
            "  - 🧩 RenderLayers 类似图层蒙版——决定相机看到哪些实体；",
            "- **Text2d 跨层渲染**:",
            "  - RenderLayers::from_layers(&[0, 1]) 同时属于两个图层——被两个相机渲染；",
            "  - ⚠️ 单个 Text2d 实体只有一个布局——使用较高缩放因子的布局，再降采样到低缩放窗口；",
            "- **UiTargetCamera 绑定**:",
            "  - PrimaryWindow UI 无 UiTargetCamera——自动使用最高 order 的主窗口相机；",
            "  - SecondaryWindow UI 需要显式 UiTargetCamera(secondary_window_camera)；",
            "  - 🔧 IsDefaultUiCamera 标记可指定默认 UI 相机——避免自动选择歧义；",
        ],
        "knowledge": [
            "知：<br>- RenderLayers 渲染层级分离；<br>- scale_factor_override 缩放覆盖；<br>- Text2d 跨层渲染。",
            "例：<br>- window/multiple_windows.rs(222)；<br>- 2D/text2d.rs(11)。",
        ],
    },
    "monitor_info.rs": {
        "seq": 224,
        "cat": "窗口管理",
        "filename": "`monitor_info.rs`",
        "intent": [
            "**意图**：显示可用显示器信息——Monitor 组件自动检测 + 每个显示器创建独立窗口；⭐⭐",
            "- **Monitor 组件**:",
            "  - Query<(Entity, &Monitor), Added<Monitor>> 监听新显示器加入；",
            "  - monitor.name / physical_height / physical_width / refresh_rate_millihertz / scale_factor 显示器属性；",
            "  - ⚠️ Monitor 由系统自动创建——应用启动后按检测顺序添加；",
            "- **每显示器一个窗口**:",
            "  - Window { mode: Fullscreen(MonitorSelection::Entity(entity)) } 全屏到指定显示器；",
            "  - WindowPosition::Centered(MonitorSelection::Entity(entity)) 窗口居中于指定显示器；",
            "  - 🔧 实现多显示器独立内容——每个显示器显示自己的信息面板；",
            "- **RemovedComponents<Monitor>**:",
            "  - 监听显示器移除事件——断开的显示器自动清理对应窗口；",
            "  - monitor_refs Query 查找关联实体——通过 MonitorRef(Entity) 组件追踪；",
            "- **ExitCondition::DontExit**:",
            "  - 关闭所有窗口后应用继续运行——等待新显示器连接；",
            "  - 🔧 适合多显示器管理工具/数字标牌应用；",
        ],
        "knowledge": [
            "知：<br>- Monitor 显示器组件；<br>- MonitorSelection 显示器选择；<br>- ExitCondition::DontExit。",
            "例：<br>- window/window_settings.rs(214)。",
        ],
    },
    "custom_cursor_image.rs": {
        "seq": 225,
        "cat": "窗口管理",
        "filename": "`custom_cursor_image.rs`",
        "intent": [
            "**意图**：纹理图集自定义鼠标光标——CustomCursor::Image + TextureAtlas 动画光标；⭐⭐",
            "- **CustomCursor::Image 配置**:",
            "  - CustomCursorImage { handle, texture_atlas, flip_x, flip_y, rect, hotspot } 完整配置；",
            "  - handle: 加载光标纹理——支持纹理图集；",
            "  - hotspot: (0, 0) 光标热点——鼠标点击的精确位置；",
            "  - 🔧 hotspot 偏移可实现十字准星/手型等非标准光标对齐；",
            "- **TextureAtlas 动画**:",
            "  - TextureAtlasLayout::from_grid(UVec2::splat(64), 20, 10) 20×10 网格的 64px 光标帧；",
            "  - AnimationConfig { first, last, increment, fps, frame_timer } 帧动画配置；",
            "  - execute_animation 系统每帧推进 atlas.index——循环播放 200 帧动画；",
            "- **运行时切换**:",
            "  - T 键切换 texture_atlas 有/无——展示有无动画的效果差异；",
            "  - X/Y 键切换 flip_x/flip_y——水平/垂直翻转光标；",
            "  - C 键循环 rect 裁剪区域——从光标纹理中选择不同部分；",
            "  - 🔧 Local<Option<TextureAtlas>> 缓存之前的 atlas——切换时恢复；",
            "- **注意事项**:",
            "  - ⚠️ 光标纹理必须已加载到 AssetServer——否则光标不可见；",
            "  - 🔧 64px 光标在高 DPI 屏幕上可能偏小——可缩放纹理；",
        ],
        "knowledge": [
            "知：<br>- CustomCursor::Image 自定义光标；<br>- TextureAtlas 动画光标；<br>- hotspot 热点定位。",
            "例：<br>- window/window_settings.rs(214)；<br>- 2D/sprite_sheet.rs(10)。",
        ],
    },
    # ── picking ──────────────────────────────────────────────────
    "simple_picking.rs": {
        "seq": 226,
        "cat": "拾取交互",
        "filename": "`simple_picking.rs`",
        "intent": [
            "**意图**：UI 和 Mesh 实体的简单拾取事件——Observer 模式处理 Click/Over/Out/Drag 事件；⭐⭐",
            "- **MeshPickingPlugin**:",
            "  - .add_plugins(MeshPickingPlugin) 启用 Mesh 拾取后端——⚠️ 非默认插件；",
            "  - 🔧 拾取后端自动为所有 Mesh 实体添加射线检测；",
            "- **Observer 拾取事件**:",
            "  - observe(on_click_spawn_cube) 点击事件处理——On<Pointer<Click>>；",
            "  - observe(|out: On<Pointer<Out>>, ...| 鼠标离开——恢复颜色；",
            "  - observe(|over: On<Pointer<Over>>, ...| 鼠标悬停——高亮颜色；",
            "  - 🔧 Observer 模式比 Query + Changed 更简洁——直接在实体上注册回调；",
            "- **Drag 旋转**:",
            "  - on_drag_rotate(drag: On<Pointer<Drag>>) 拖拽旋转实体；",
            "  - drag.delta.x/y 获取拖拽增量——乘以灵敏度系数；",
            "  - 🔧 新生成的实体也需要 .observe(on_drag_rotate)——动态添加观察者；",
            "- **Local 计数器**:",
            "  - Local<usize> 追踪已生成的方块数量——控制垂直堆叠位置；",
            "  - 0.25 + 0.55 * *num 避免重叠——每个方块偏移 0.55 单位；",
        ],
        "knowledge": [
            "知：<br>- MeshPickingPlugin Mesh 拾取；<br>- Pointer<Click/Over/Out/Drag> 事件；<br>- Observer 观察者模式。",
            "例：<br>- 3D/3d_scene.rs(32)；<br>- ui/button.rs(230)。",
        ],
    },
    "mesh_picking.rs": {
        "seq": 227,
        "cat": "拾取交互",
        "filename": "`mesh_picking.rs`",
        "intent": [
            "**意图**：3D Mesh 拾取——命中测试选中物体 + Gizmos 可视化命中点/法线 + 多种形状；⭐⭐⭐",
            "- **MeshPickingPlugin 配置**:",
            "  - 默认对所有 Mesh 实体进行射线检测——调试时非常方便；",
            "  - MeshPickingSettings::require_markers = true 可切换为 opt-in 模式——需添加 Pickable 组件；",
            "  - 🔧 生产环境建议 opt-in——避免不必要的射线检测开销；",
            "- **Observer 事件链**:",
            "  - Pointer<Over> → hover_matl 高亮材质；",
            "  - Pointer<Out> → white_matl 恢复原材质；",
            "  - Pointer<Press> → pressed_matl 按下材质；",
            "  - Pointer<Release> → hover_matl 恢复高亮；",
            "  - 🧩 闭包捕获材质 Handle——避免为每种事件写单独的观察者；",
            "- **Gizmos 命中可视化**:",
            "  - PointerInteraction::get_nearest_hit() 获取最近命中点——position + normal；",
            "  - gizmos.sphere(point, 0.05, RED) 绘制命中点球体；",
            "  - gizmos.arrow(point, point + normal * 0.5, PINK) 绘制法线箭头；",
            "  - 🔧 调试拾取精度时非常有用——可视化射线与表面的交点；",
            "- **Pickable::IGNORE**:",
            "  - 地面 Plane3d 添加 Pickable::IGNORE——忽略拾取检测；",
            "  - 🔧 大型背景物体应忽略拾取——避免干扰前景物体的选择；",
            "- **多种 3D 形状**:",
            "  - Cuboid/Tetrahedron/Capsule3d/Torus/Cylinder/Cone/ConicalFrustum/Sphere 9 种；",
            "  - Extrusion 2D→3D 挤压形状 7 种——展示拾取对所有 Mesh 类型通用；",
        ],
        "knowledge": [
            "知：<br>- MeshPickingPlugin 配置；<br>- PointerInteraction 命中信息；<br>- Pickable::IGNORE 忽略拾取。",
            "例：<br>- picking/simple_picking.rs(226)。",
        ],
    },
    "sprite_picking.rs": {
        "seq": 228,
        "cat": "拾取交互",
        "filename": "`sprite_picking.rs`",
        "intent": [
            "**意图**：Sprite 和 Sprite Atlas 拾取——基于纹理 alpha 通道的精确像素级检测；⭐⭐",
            "- **SpritePickingPlugin**:",
            "  - 自动为所有 Sprite 实体添加拾取检测——⚠️ 基于 alpha 通道；",
            "  - 透明像素不触发拾取——仅不透明区域响应鼠标事件；",
            "  - 🔧 比 Mesh 拾取更高效——2D 纹理检测比 3D 射线更快；",
            "- **alpha 阈值检测**:",
            "  - Sprite 拾取检查纹理对应像素的 alpha 值；",
            "  - alpha > 0 的像素才触发拾取——允许精确的非矩形交互区域；",
            "  - ⚠️ 大型 Sprite 的拾取检测可能有性能开销——考虑使用简化碰撞体；",
            "- **与 Mesh 拾取的区别**:",
            "  - Sprite 拾取基于纹理 alpha，Mesh 拾取基于几何射线；",
            "  - 🧩 两者可同时启用——UI/精灵用 SpritePicking，3D 用 MeshPicking；",
            "- **注意事项**:",
            "  - ⚠️ SpriteAtlas 需要正确的纹理图集——拾取区域基于当前帧的纹理；",
            "  - 🔧 适合 2D 游戏的点击/拖拽交互——角色点击/物品拾取/地图选择；",
        ],
        "knowledge": [
            "知：<br>- SpritePickingPlugin Sprite 拾取；<br>- alpha 通道检测；<br>- SpriteAtlas 拾取。",
            "例：<br>- picking/simple_picking.rs(226)。",
        ],
    },
    "dragdrop_picking.rs": {
        "seq": 229,
        "cat": "拾取交互",
        "filename": "`dragdrop_picking.rs`",
        "intent": [
            "**意图**：使用拾取事件实现拖放功能——DragStart/DragOver/DragDrop/DragEnter/DragLeave 完整生命周期；⭐⭐⭐",
            "- **拖放事件生命周期**:",
            "  - DragStart → DragOver(持续) → DragDrop(放下) 或 DragLeave(离开目标)；",
            "  - event.propagate(false) 阻止事件向上传播——防止父节点响应；",
            "  - ⚠️ 必须在适当的时机调用 propagate(false)——否则事件会穿透到其他实体；",
            "- **GhostPreview 幽灵预览**:",
            "  - DragEnter 时创建半透明圆形跟随鼠标——视觉反馈；",
            "  - DragOver 时更新幽灵位置——使用 event.hit.position 世界坐标；",
            "  - DragDrop/DragLeave 时 despawn 幽灵——清理临时实体；",
            "  - 🔧 幽灵预览让用户清楚知道拖拽目标位置；",
            "- **DraggableButton 组件**:",
            "  - DraggableButton 标记可拖拽实体；",
            "  - DragStart 时变橙色，DragEnd 时恢复红色——状态反馈；",
            "  - 🔧 组件标记比 Tag 更 ECS 友好——支持多个独立的可拖拽实体；",
            "- **DropArea 组件**:",
            "  - DropArea 标记放置区域——Mesh2d 绿色矩形；",
            "  - DragDrop 时在放置位置创建 DroppedElement——完成放置；",
            "  - 🔧 DropArea 和 DraggableButton 可在同一实体上——实现自拖放；",
            "- **注意事项**:",
            "  - ⚠️ event.hit.position 是世界坐标——直接用于 Transform::translation；",
            "  - 🔧 Mesh2d + MeshMaterial2d 比 Sprite 更灵活——可自定义形状；",
        ],
        "knowledge": [
            "知：<br>- DragStart/DragOver/DragDrop/DragEnter/DragLeave 事件；<br>- event.propagate(false) 传播控制；<br>- GhostPreview 幽灵预览。",
            "例：<br>- picking/simple_picking.rs(226)；<br>- ui/button.rs(230)。",
        ],
    },
    "debug_picking.rs": {
        "seq": 230,
        "cat": "拾取交互",
        "filename": "`debug_picking.rs`",
        "intent": [
            "**意图**：拾取调试设置——DebugPickingPlugin 三级调试模式（Disabled/Normal/Noisy）；⭐⭐",
            "- **DebugPickingPlugin**:",
            "  - .add_plugins(DebugPickingPlugin) 启用拾取调试——显示拾取命中信息；",
            '  - 配合 LogPlugin { filter: "bevy_dev_tools=trace" } 启用 trace 级别日志；',
            "  - 🔧 开发时启用可快速定位拾取问题——生产时禁用避免性能开销；",
            "- **DebugPickingMode 三级模式**:",
            "  - Disabled: 完全禁用调试输出；",
            "  - Normal: 仅输出拾取命中/丢失信息；",
            "  - Noisy: 输出所有拾取检测详情——信息量大但有用；",
            "  - ⚠️ Noisy 模式会产生大量日志——仅在调试特定问题时使用；",
            "- **F3 键循环切换**:",
            "  - distributive_run_if(input_just_pressed(KeyCode::F3)) 条件系统——仅在 F3 按下时运行；",
            "  - 三级循环：Disabled → Normal → Noisy → Disabled；",
            "  - 🔧 F3 是游戏调试的标准快捷键——用户直觉友好；",
            "- **Name 组件辅助**:",
            '  - Name::new("Base") 为实体命名——调试日志中显示实体名称而非 Entity(ID)；',
            "  - 🔧 给关键实体添加 Name 组件——大幅提升调试效率；",
            "- **注意事项**:",
            "  - ⚠️ DebugPickingPlugin 不影响拾取功能本身——仅添加调试输出；",
            "  - 🔧 配合 MeshPickingPlugin 使用——调试 Mesh 拾取问题；",
        ],
        "knowledge": [
            "知：<br>- DebugPickingPlugin 拾取调试；<br>- DebugPickingMode 三级模式；<br>- Name 实体命名。",
            "例：<br>- picking/simple_picking.rs(226)。",
        ],
    },
    # ── UI (placeholders 261-280) ───────────────────────────────
    "ui_texture_slice.rs": {
        "seq": 261,
        "cat": "UI",
        "filename": "`ui_texture_slice.rs`",
        "intent": [
            "**意图**：UI 纹理九宫格切片——TextureSlicer 保持按钮边角不失真，NodeImageMode::Sliced 渲染；⭐⭐",
            "- **TextureSlicer 配置**:",
            "  - TextureSlicer { border: BorderRect::all(22.0), center_scale_mode, sides_scale_mode, max_corner_scale } 定义切片规则；",
            "  - border: 四边切割线距边缘 22 像素——四角不缩放，四边单向缩放，中心双向缩放；",
            "  - center_scale_mode: SliceScaleMode::Stretch 拉伸填满中心；",
            "  - sides_scale_mode: SliceScaleMode::Stretch 拉伸填满侧边；",
            "  - 🔧 max_corner_scale: 1.0 限制角的最大缩放——防止角被过度拉伸；",
            "- **NodeImageMode::Sliced**:",
            "  - ImageNode { image_mode: NodeImageMode::Sliced(slicer), .. } 应用切片模式；",
            "  - ⚠️ 切片纹理必须有足够的边距——否则切片重叠导致视觉异常；",
            "- **三种尺寸按钮**:",
            "  - 150×150 / 300×150 / 150×300 三种尺寸——验证切片在不同宽高比下的表现；",
            "  - 🔧 九宫格切片是 UI 按钮/面板/对话框的必备技术；",
            "- **Interaction 状态**:",
            '  - Pressed: 文本变 "Press"，颜色变 GOLD；',
            '  - Hovered: 文本变 "Hover"，颜色变 ORANGE；',
            '  - None: 文本变 "Button"，颜色变 WHITE；',
        ],
        "knowledge": [
            "知：<br>- TextureSlicer 九宫格切片；<br>- NodeImageMode::Sliced 渲染模式；<br>- BorderRect 切割线定义。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "ui_texture_slice_flip_and_tile.rs": {
        "seq": 262,
        "cat": "UI",
        "filename": "`ui_texture_slice_flip_and_tile.rs`",
        "intent": [
            "**意图**：九宫格中翻转和平铺图像——SliceScaleMode::Tile 平铺填充 + flip_x/flip_y 镜像；⭐⭐",
            "- **SliceScaleMode::Tile 平铺**:",
            "  - center_scale_mode: Tile { stretch_value: 1.0 } 中心区域平铺填充；",
            "  - sides_scale_mode: Tile { stretch_value: 1.0 } 侧边区域平铺填充；",
            "  - stretch_value: 1.0 每张 tile 与原始尺寸相同——0=紧密排列，>1=重叠；",
            "  - 🔧 平铺模式适合重复纹理（砖墙/草地/网格）——比拉伸更自然；",
            "- **ImageSampler::nearest()**:",
            "  - load_with_settings 设置 nearest 采样——⚠️ 平铺必须用 nearest，否则纹理出血；",
            "  - 🔧 线性采样会在 tile 边缘产生杂色条纹——像素风纹理尤其明显；",
            "- **flip_x/flip_y 翻转**:",
            "  - ImageNode { flip_x, flip_y } 水平/垂直翻转——4 种组合展示；",
            "  - 🧩 翻转 + 平铺可产生镜像重复图案——适合对称纹理；",
            "- **Grid 布局**:",
            "  - Display::Grid + flex_wrap + column/row_gap 网格展示；",
            "  - 5 种尺寸 × 4 种翻转 = 20 种组合——全面测试切片行为；",
        ],
        "knowledge": [
            "知：<br>- SliceScaleMode::Tile 平铺填充；<br>- ImageSampler::nearest 采样；<br>- flip_x/flip_y 翻转。",
            "例：<br>- ui/ui_texture_slice.rs(261)。",
        ],
    },
    "ui_texture_atlas_slice.rs": {
        "seq": 263,
        "cat": "UI",
        "filename": "`ui_texture_atlas_slice.rs`",
        "intent": [
            "**意图**：纹理图集九宫格切片——TextureAtlas + TextureSlicer 组合，按钮切换图集帧；⭐⭐",
            "- **TextureAtlas + Slicer 组合**:",
            "  - ImageNode::from_atlas_image(texture, TextureAtlas { index, layout }) 从图集创建；",
            "  - .with_mode(NodeImageMode::Sliced(slicer)) 应用切片模式；",
            "  - ⚠️ 图集帧的每个 Sprite 都需要独立的切片配置——border 值可能不同；",
            "- **图集布局**:",
            "  - TextureAtlasLayout::from_grid(UVec2::new(50, 50), 6, 6, padding) 6×6 网格；",
            "  - 每帧 50×50 像素，padding: Some(UVec2::splat(2)) 帧间距 2 像素；",
            "  - 🔧 padding 消除相邻帧的纹理出血——线性采样时尤其重要；",
            "- **Interaction 帧切换**:",
            "  - Pressed: atlas.index = (index + 1) % 30 点击切换到下一帧；",
            "  - 🔧 30 帧循环——6×6 网格共 36 帧，只用前 30 帧；",
            "- **三种按钮尺寸**:",
            "  - 索引 0/7/13 对应三种不同的边框样式——验证切片对不同帧的效果；",
        ],
        "knowledge": [
            "知：<br>- TextureAtlas + TextureSlicer 组合；<br>- 帧索引切换；<br>- padding 消除出血。",
            "例：<br>- ui/ui_texture_slice.rs(261)；<br>- ui/ui_texture_atlas.rs(260)。",
        ],
    },
    "scroll.rs": {
        "seq": 264,
        "cat": "UI",
        "filename": "`scroll.rs`",
        "intent": [
            "**意图**：UI 滚动功能——Overflow::scroll + ScrollPosition + 自定义 Scroll EntityEvent；⭐⭐⭐",
            "- **Overflow::scroll 模式**:",
            "  - Overflow::scroll_x() 仅水平滚动——内容超出容器宽度时出现水平滚动条；",
            "  - Overflow::scroll_y() 仅垂直滚动——内容超出容器高度时出现垂直滚动条；",
            "  - Overflow::scroll() 双向滚动——水平和垂直都可滚动；",
            "  - ⚠️ 必须设置 overflow 才能启用滚动——默认 Overflow::visible() 不支持滚动；",
            "- **ScrollPosition 组件**:",
            "  - ScrollPosition(Vec2::ZERO) 初始滚动位置——(0,0) 为左上角；",
            "  - scroll_position.x / .y 水平/垂直滚动偏移量——逻辑像素单位；",
            "  - 🔧 修改 ScrollPosition 可实现程序化滚动——如 scrollToTop/scrollToBottom；",
            "- **自定义 Scroll EntityEvent**:",
            "  - #[derive(EntityEvent)] struct Scroll { entity, delta } 定义滚动事件；",
            "  - #[entity_event(propagate, auto_propagate)] 支持冒泡传播；",
            "  - send_scroll_events 系统将 MouseWheel 事件转换为 Scroll 事件；",
            "  - 🔧 EntityEvent 比 EventWriter 更轻量——直接附加到目标实体；",
            "- **HoverMap 精确定位**:",
            "  - hover_map.values() 获取当前悬停的实体——仅对悬停区域发送滚动事件；",
            "  - 🔧 鼠标悬停在哪个子区域就滚动哪个——支持嵌套滚动容器；",
            "- **四种滚动容器**:",
            "  - 水平滚动列表 / 垂直滚动列表 / 双向滚动列表 / 嵌套滚动列表；",
            "  - 🔧 嵌套滚动：外层双向 + 内层垂直——验证滚动事件的传播控制；",
        ],
        "knowledge": [
            "知：<br>- Overflow::scroll 滚动模式；<br>- ScrollPosition 滚动位置；<br>- EntityEvent 自定义事件。",
            "例：<br>- ui/overflow.rs(241)。",
        ],
    },
    "scrollbars.rs": {
        "seq": 265,
        "cat": "UI",
        "filename": "`scrollbars.rs`",
        "intent": [
            "**意图**：滚动条演示——ScrollbarPlugin + Scrollbar + CoreScrollbarThumb 组件化滚动条；⭐⭐",
            "- **ScrollbarPlugin**:",
            "  - .add_plugins(ScrollbarPlugin) 启用滚动条组件——⚠️ 非默认插件；",
            "  - Scrollbar { orientation, target, min_thumb_length } 定义滚动条；",
            "  - orientation: ControlOrientation::Vertical/Horizontal 滚动条方向；",
            "  - target: scroll_area_id 绑定到滚动区域实体；",
            "  - min_thumb_length: 8.0 滑块最小长度——防止滑块过小无法操作；",
            "- **CoreScrollbarThumb 滑块**:",
            "  - 子实体的 CoreScrollbarThumb 标记滚动条滑块；",
            "  - Hovered 组件追踪鼠标悬停状态——悬停时变亮色；",
            "  - CoreScrollbarDragState 追踪拖拽状态——拖拽中变亮色；",
            "  - 🔧 update_scrollbar_thumb 系统根据悬停/拖拽状态更新颜色；",
            "- **Grid 布局**:",
            "  - Display::Grid + grid_template_columns/rows 网格布局滚动区域和滚动条；",
            "  - 🧩 网格布局精确控制滚动区域和滚动条的位置关系；",
            "- **TabGroup 导航**:",
            "  - TabGroup::default() 启用 Tab 键导航——TabNavigationPlugin 提供；",
            "  - 🔧 滚动区域支持键盘导航——无障碍访问的重要特性；",
        ],
        "knowledge": [
            "知：<br>- ScrollbarPlugin 滚动条插件；<br>- Scrollbar 滚动条组件；<br>- CoreScrollbarThumb 滑块。",
            "例：<br>- ui/scroll.rs(264)。",
        ],
    },
    "drag_to_scroll.rs": {
        "seq": 266,
        "cat": "UI",
        "filename": "`drag_to_scroll.rs`",
        "intent": [
            "**意图**：拖拽实现滚动——Pointer<Drag> 事件驱动 ScrollPosition 更新 + Grid 彩色网格；⭐⭐",
            "- **拖拽滚动原理**:",
            "  - Pointer<DragStart> 记录起始滚动位置——ScrollStart(Vec2) 组件；",
            "  - Pointer<Drag> 更新滚动位置——scroll_position.0 = (start - drag.distance / ui_scale).max(ZERO)；",
            "  - ⚠️ 除以 ui_scale 是因为 drag.distance 是逻辑像素，scroll_position 是物理像素；",
            "- **ScrollPosition 组件**:",
            "  - ScrollPosition(Vec2::ZERO) 初始位置——与 Overflow::scroll 配合使用；",
            "  - .max(Vec2::ZERO) 防止负值——滚动到左上角后停止；",
            "  - 🔧 未实现右边界限制——可扩展为 max_offset 限制；",
            "- **彩色网格**:",
            "  - 60×40 Grid 网格——每个格子根据 (x+y)%2 和坐标计算颜色；",
            "  - Color::hsl(hue, 1., 0.5) 彩虹色渐变——直观展示滚动效果；",
            "  - 🔧 高对比度颜色便于观察滚动位置变化；",
            "- **Pickable 配置**:",
            "  - 网格外层: Pickable { is_hoverable: false, should_block_lower: true } 阻止拾取但不悬停；",
            "  - 单个格子: Pickable { should_block_lower: false, is_hoverable: true } 可悬停但不阻止；",
            "  - 🧩 分层拾取配置实现「悬停高亮但不阻止滚动」的效果；",
        ],
        "knowledge": [
            "知：<br>- Pointer<Drag> 拖拽事件；<br>- ScrollPosition 滚动位置；<br>- Pickable 拾取配置。",
            "例：<br>- ui/scroll.rs(264)。",
        ],
    },
    "directional_navigation.rs": {
        "seq": 267,
        "cat": "UI",
        "filename": "`directional_navigation.rs`",
        "intent": [
            "**意图**：方向导航——键盘/手柄在 UI 按钮间导航，手动构建导航图实现精确控制；⭐⭐⭐",
            "- **DirectionalNavigationPlugin**:",
            "  - .add_plugins(DirectionalNavigationPlugin) 启用方向导航——⚠️ 需配合 InputDispatchPlugin；",
            "  - InputFocusVisible(true) 显示焦点指示器——方便调试；",
            "  - 🔧 方向导航比 Tab 导航更直接——适合网格/十字键布局；",
            "- **DirectionalNavigationMap 手动构建**:",
            "  - DirectionalNavigationMap::from_graph(graph) 从导航图创建；",
            "  - graph.add_edge(from, to, direction) 添加导航边——指定方向连接；",
            "  - 🔧 手动构建比自动生成更精确——可定义复杂的导航路径；",
            "- **CompassOctant 方向**:",
            "  - North/East/South/West/NE/SE/SW/NW 八个方向——对应键盘/手柄方向；",
            "  - 🔧 八方向导航支持对角线移动——适合网格布局；",
            "- **InputFocus 焦点管理**:",
            "  - InputFocus(entity) 当前聚焦的实体——导航系统自动更新；",
            "  - InputFocusVisible(true) 显示焦点边框——蓝色 BorderOutline；",
            "  - 🔧 focus_visible 系统根据 InputFocus 状态切换边框样式；",
            "- **Universal 点击行为**:",
            "  - universal_button_click_behavior Observer 处理所有按钮点击；",
            "  - 🔧 通用 Observer 比为每个按钮单独注册更高效——代码复用；",
        ],
        "knowledge": [
            "知：<br>- DirectionalNavigationPlugin 方向导航；<br>- DirectionalNavigationMap 导航图；<br>- InputFocus 焦点管理。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "auto_directional_navigation.rs": {
        "seq": 268,
        "cat": "UI",
        "filename": "`auto_directional_navigation.rs`",
        "intent": [
            "**意图**：自动方向导航——零配置基于屏幕位置自动生成导航图，比手动构建更便捷；⭐⭐",
            "- **自动导航图生成**:",
            "  - DirectionalNavigationMap 自动生成——基于节点的屏幕位置计算方向连接；",
            "  - ⚠️ 自动模式可能产生意外的导航路径——复杂布局建议手动构建；",
            "  - 🔧 适合规则网格/列表/工具栏等简单布局——零配置即可工作；",
            "- **与手动模式的区别**:",
            "  - 手动: DirectionalNavigationMap::from_graph() 精确控制每条边；",
            "  - 自动: DirectionalNavigationMap::default() 基于位置启发式；",
            "  - 🧩 简单布局用自动模式，复杂布局用手动模式——混合使用也可；",
            "- **焦点视觉反馈**:",
            "  - 蓝色 BorderOutline 显示当前聚焦的按钮；",
            "  - 🔧 视觉反馈让用户清楚知道导航位置——无障碍访问的关键；",
            "- **注意事项**:",
            "  - ⚠️ 自动导航对动态布局（如 FlexWrap）支持有限——可能需要手动调整；",
            "  - 🔧 InputFocusVisible(true) 始终显示焦点——调试时非常有用；",
        ],
        "knowledge": [
            "知：<br>- DirectionalNavigationMap 自动导航图；<br>- 屏幕位置启发式；<br>- 焦点视觉反馈。",
            "例：<br>- ui/directional_navigation.rs(267)。",
        ],
    },
    "tab_navigation.rs": {
        "seq": 269,
        "cat": "UI",
        "filename": "`tab_navigation.rs`",
        "intent": [
            "**意图**：Tab 导航——TabNavigationPlugin 实现 Tab 键在 UI 控件间顺序导航；⭐⭐",
            "- **TabNavigationPlugin**:",
            "  - .add_plugins(TabNavigationPlugin) 启用 Tab 导航——⚠️ 需配合 InputDispatchPlugin；",
            "  - Tab 键前进，Shift+Tab 后退——标准键盘导航行为；",
            "  - 🔧 Tab 导航是无障碍访问的基本要求——WCAG 2.1 Level A；",
            "- **TabGroup 组件**:",
            "  - TabGroup::default() 标记可导航的控件组；",
            "  - 同一 TabGroup 内的控件按 spawn 顺序导航；",
            "  - 🔧 多个 TabGroup 可实现区域切换——如主菜单/设置面板/游戏 HUD；",
            "- **InputFocus 联动**:",
            "  - Tab 导航自动更新 InputFocus——聚焦到下一个/上一个控件；",
            "  - 🔧 InputFocus + InputFocusVisible 焦点系统统一管理所有导航方式；",
            "- **注意事项**:",
            "  - ⚠️ 需要 InputDispatchPlugin 才能接收键盘输入——否则 Tab 键无响应；",
            "  - 🔧 可见性为 Hidden 的控件自动跳过导航；",
        ],
        "knowledge": [
            "知：<br>- TabNavigationPlugin Tab 导航；<br>- TabGroup 导航组；<br>- InputFocus 焦点联动。",
            "例：<br>- ui/directional_navigation.rs(267)。",
        ],
    },
    "feathers.rs": {
        "seq": 270,
        "cat": "UI",
        "filename": "`feathers.rs`",
        "intent": [
            "**意图**：Bevy Feathers 控件的综合使用——内置 UI 控件库提供标准化的按钮/滑块/复选框等；⭐⭐",
            "- **Feathers 控件库**:",
            "  - bevy::ui_widgets 提供预制 UI 控件——避免从零构建常用组件；",
            "  - ⚠️ Feathers 是实验性功能——API 可能在未来版本变更；",
            "  - 🔧 适合快速原型开发——预制控件比自定义组件更高效；",
            "- **控件类型**:",
            "  - Button / Slider / Checkbox / RadioButton / ScrollView 等标准控件；",
            "  - 每个控件内置交互状态/无障碍支持/主题样式；",
            "  - 🧩 控件组合可构建复杂的设置面板/对话框/工具栏；",
            "- **主题系统**:",
            "  - 控件支持自定义主题——颜色/字体/间距等可配置；",
            "  - 🔧 统一主题确保 UI 一致性——避免逐个控件调整样式；",
            "- **注意事项**:",
            "  - ⚠️ Feathers 依赖 InputDispatchPlugin + TabNavigationPlugin；",
            "  - 🔧 生产环境建议评估稳定性——实验性 API 可能 breaking change；",
        ],
        "knowledge": [
            "知：<br>- Feathers UI 控件库；<br>- 预制控件类型；<br>- 主题系统。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "standard_widgets.rs": {
        "seq": 271,
        "cat": "UI",
        "filename": "`standard_widgets.rs`",
        "intent": [
            "**意图**：bevy_ui_widgets 标准控件使用——Button/Slider/Checkbox 等控件的创建和配置；⭐⭐",
            "- **标准控件创建**:",
            "  - bevy_ui_widgets 模块提供预制控件——简化 UI 开发；",
            "  - 每个控件包含 Node + 交互组件 + 无障碍组件——开箱即用；",
            "  - 🔧 比手动构建 Button 更高效——内置 Interaction 处理和无障碍支持；",
            "- **控件配置**:",
            "  - 控件属性通过组件配置——如 Button { text, color }；",
            "  - 运行时修改控件状态——如设置 disabled/enabled；",
            "  - 🧩 控件组合构建复杂 UI——如设置面板包含多种控件类型；",
            "- **事件处理**:",
            "  - 控件通过 Observer 或 Changed<Interaction> 发送交互事件；",
            "  - 🔧 Observer 模式比 Query + Changed 更简洁——直接在控件上注册回调；",
            "- **注意事项**:",
            "  - ⚠️ 标准控件样式可能与自定义主题冲突——需统一管理；",
            "  - 🔧 适合内部工具/调试面板——快速构建功能型 UI；",
        ],
        "knowledge": [
            "知：<br>- bevy_ui_widgets 标准控件；<br>- 控件配置属性；<br>- Observer 事件处理。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "standard_widgets_observers.rs": {
        "seq": 272,
        "cat": "UI",
        "filename": "`standard_widgets_observers.rs`",
        "intent": [
            "**意图**：UI Widgets 配合 Observer 事件——观察者模式处理控件生命周期和交互事件；⭐⭐",
            "- **Observer 事件系统**:",
            "  - observe(On<Pointer<Click>>) 处理点击事件——直接在实体上注册；",
            "  - observe(On<Pointer<Over>>) 处理悬停事件——高亮/取消高亮；",
            "  - 🔧 Observer 比 Query + Changed 更高效——仅在事件发生时运行；",
            "- **生命周期观察**:",
            "  - OnAdd/OnInsert/OnRemove 观察组件生命周期；",
            "  - 🔧 适合实现自动初始化/清理——如组件添加时自动设置默认值；",
            "- **事件传播控制**:",
            "  - event.propagate(false) 阻止事件向上传播；",
            "  - ⚠️ 必须在适当的时机调用——否则父节点也会响应点击；",
            "  - 🔧 按钮点击后阻止传播——防止穿透到后面的 UI 层；",
            "- **注意事项**:",
            "  - ⚠️ Observer 是全局注册的——同一类型事件只有一个处理函数；",
            "  - 🔧 多个 Observer 可处理同一事件——通过 query 过滤目标实体；",
        ],
        "knowledge": [
            "知：<br>- Observer 观察者模式；<br>- 生命周期事件；<br>- event.propagate(false) 传播控制。",
            "例：<br>- ecs/observers.rs(132)；<br>- ui/standard_widgets.rs(271)。",
        ],
    },
    "vertical_slider.rs": {
        "seq": 273,
        "cat": "UI",
        "filename": "`vertical_slider.rs`",
        "intent": [
            "**意图**：垂直/水平滑块控件——Slider 组件实现值选择，支持键盘和鼠标交互；⭐⭐",
            "- **Slider 组件**:",
            "  - Slider 控件支持水平和垂直方向——通过 Orientation 配置；",
            "  - min/max/step 配置滑块范围和步长；",
            "  - 🔧 滑块是设置面板的核心控件——音量/亮度/缩放等常用场景；",
            "- **交互模式**:",
            "  - 鼠标拖拽：Pointer<Drag> 事件更新滑块值；",
            "  - 键盘：ArrowUp/Down 或 ArrowLeft/Right 调整值；",
            "  - 滚轮：MouseWheel 事件微调值；",
            "  - 🔧 多种输入方式确保无障碍访问——键盘/鼠标/手柄都可操作；",
            "- **视觉反馈**:",
            "  - 滑块轨道和滑块手柄独立渲染——颜色变化表示交互状态；",
            "  - 🔧 悬停/拖拽时高亮——提供清晰的操作反馈；",
            "- **注意事项**:",
            "  - ⚠️ 垂直滑块的方向与常规 Y 轴相反——向上是增加；",
            "  - 🔧 配合 InputFocus 可实现纯键盘导航——Tab 选中 + Arrow 调整；",
        ],
        "knowledge": [
            "知：<br>- Slider 滑块控件；<br>- Orientation 方向配置；<br>- 多输入模式。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "viewport_node.rs": {
        "seq": 274,
        "cat": "UI",
        "filename": "`viewport_node.rs`",
        "intent": [
            "**意图**：视口节点——UI 中嵌入 3D 视口，ViewportNode 组件实现画中画效果；⭐⭐⭐",
            "- **ViewportNode 组件**:",
            "  - ViewportNode 组件标记视口 UI 节点——绑定到特定相机渲染目标；",
            "  - 🔧 实现 UI 中嵌入 3D 内容——如小地图/预览窗口/角色肖像；",
            "- **RenderTarget::Image**:",
            "  - Camera 渲染到纹理——RenderTarget::Image(handle)；",
            "  - 纹理作为 ImageNode 的图像源——在 UI 中显示 3D 渲染结果；",
            "  - 🔧 与 render_to_texture.rs 类似——但通过 ViewportNode 简化了绑定；",
            "- **多相机渲染**:",
            "  - 主相机渲染游戏场景；",
            "  - 视口相机渲染到纹理——绑定到 ViewportNode；",
            "  - 🧩 两个相机可有不同的 RenderLayers/视角/后处理；",
            "- **注意事项**:",
            "  - ⚠️ 渲染到纹理有性能开销——纹理分辨率影响 GPU 负载；",
            "  - 🔧 动态调整纹理分辨率可平衡画质与性能——如缩小远距离小地图；",
        ],
        "knowledge": [
            "知：<br>- ViewportNode 视口节点；<br>- RenderTarget::Image 纹理渲染；<br>- 画中画效果。",
            "例：<br>- 3D/render_to_texture.rs(56)；<br>- ui/button.rs(230)。",
        ],
    },
    "render_ui_to_texture.rs": {
        "seq": 275,
        "cat": "UI",
        "filename": "`render_ui_to_texture.rs`",
        "intent": [
            "**意图**：UI 渲染到纹理并在 3D 空间显示——Camera 渲染 UI 到纹理，再贴到 3D Mesh 上；⭐⭐⭐",
            "- **UI 渲染到纹理**:",
            "  - Camera { render_target: RenderTarget::Image(handle) } 将 UI 渲染到纹理；",
            "  - Image::new_target_texture 创建可渲染纹理——指定尺寸和格式；",
            "  - 🔧 实现游戏内 UI 屏幕——如电视/电脑屏幕/海报/广告牌；",
            "- **3D 空间显示**:",
            "  - 纹理作为 MeshMaterial3d 的 base_color_texture——贴到 3D 平面上；",
            "  - Plane3d + 纹理材质 = 3D 空间中的 UI 屏幕；",
            "  - 🔧 配合光照/阴影可产生真实的游戏内屏幕效果；",
            "- **RenderLayers 分离**:",
            "  - UI 相机和游戏相机使用不同的 RenderLayers；",
            "  - 🧩 UI 相机仅渲染 UI 实体，游戏相机仅渲染 3D 实体——互不干扰；",
            "- **注意事项**:",
            "  - ⚠️ 纹理分辨率影响 UI 清晰度——过低会导致模糊；",
            "  - 🔧 动态分辨率可优化性能——根据距离调整纹理大小；",
        ],
        "knowledge": [
            "知：<br>- Camera 渲染到纹理；<br>- RenderTarget::Image；<br>- RenderLayers 分离。",
            "例：<br>- 3D/render_to_texture.rs(56)。",
        ],
    },
    "ui_drag_and_drop.rs": {
        "seq": 276,
        "cat": "UI",
        "filename": "`ui_drag_and_drop.rs`",
        "intent": [
            "**意图**：UI 节点间拖放——Pointer<Drag> 事件实现 UI 元素的拖拽移动和放置；⭐⭐",
            "- **UI 拖拽原理**:",
            "  - Pointer<DragStart> 记录拖拽起始位置——获取目标 UI 节点；",
            "  - Pointer<Drag> 更新节点位置——修改 UiTransform 或 Node position；",
            "  - Pointer<DragEnd> 完成拖拽——放置到目标位置；",
            "  - 🔧 UI 拖拽比 Mesh 拖拽更直接——不需要坐标转换；",
            "- **DropZone 放置区域**:",
            "  - 标记可接受拖拽的 UI 区域——DropZone 组件；",
            "  - DragEnter/DragLeave 视觉反馈——悬停时高亮；",
            "  - 🔧 DropZone 可设置接受的拖拽类型——实现类型过滤；",
            "- **注意事项**:",
            "  - ⚠️ UI 拖拽需要 Pickable 组件——确保 UI 节点可拾取；",
            "  - 🔧 拖拽时 z-index 可能需要调整——确保拖拽中的节点在最上层；",
        ],
        "knowledge": [
            "知：<br>- Pointer<Drag> UI 拖拽；<br>- DropZone 放置区域；<br>- UiTransform 位置更新。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "virtual_keyboard.rs": {
        "seq": 277,
        "cat": "UI",
        "filename": "`virtual_keyboard.rs`",
        "intent": [
            "**意图**：虚拟键盘控件——触屏/手柄场景下的屏幕键盘输入方案；⭐⭐",
            "- **虚拟键盘概念**:",
            "  - 屏幕上的键盘 UI——用户通过点击/手柄选择字符输入；",
            "  - 🔧 适合移动端/主机/触屏设备——无物理键盘时的输入方案；",
            "- **字符选择交互**:",
            "  - 方向键/摇杆在键盘布局间导航——高亮当前选中字符；",
            "  - 确认键输入选中字符——添加到输入缓冲区；",
            "  - 🔧 预测文本/自动补全可减少输入步骤——提升用户体验；",
            "- **布局管理**:",
            "  - QWERTY/AZERTY 等不同布局支持——可切换；",
            "  - 数字/符号/表情符号子布局——通过切换键访问；",
            "  - 🧩 布局配置可通过 Resource 存储——运行时动态切换；",
            "- **注意事项**:",
            "  - ⚠️ 虚拟键盘会覆盖部分游戏内容——需要合理布局；",
            "  - 🔧 输入完成时隐藏键盘——仅在需要输入时显示；",
        ],
        "knowledge": [
            "知：<br>- 虚拟键盘控件；<br>- 字符导航选择；<br>- 布局切换。",
            "例：<br>- ui/feathers.rs(270)。",
        ],
    },
    "window_fallthrough.rs": {
        "seq": 278,
        "cat": "UI",
        "filename": "`window_fallthrough.rs`",
        "intent": [
            "**意图**：鼠标事件穿透透明窗口——配合 transparent 窗口实现点击穿透效果；⭐⭐",
            "- **事件穿透原理**:",
            "  - 透明窗口中未被 UI 拦截的鼠标事件自动穿透到下层窗口；",
            "  - 🔧 适合覆盖层/小组件/OSD 信息——不影响下层窗口交互；",
            "- **与 transparent_window.rs 配合**:",
            "  - Window { transparent: true } 启用透明；",
            "  - ClearColor(Color::NONE) 背景透明；",
            "  - 🔧 两者结合实现真正的点击穿透窗口；",
            "- **注意事项**:",
            "  - ⚠️ 仅部分平台支持事件穿透——macOS/Linux/Windows 行为不同；",
            "  - 🔧 不透明的 UI 元素会正常接收事件——仅透明区域穿透；",
        ],
        "knowledge": [
            "知：<br>- 鼠标事件穿透；<br>- 透明窗口配合；<br>- 平台兼容性。",
            "例：<br>- window/transparent_window.rs(217)。",
        ],
    },
    "context_menu.rs": {
        "seq": 279,
        "cat": "UI",
        "filename": "`context_menu.rs`（usage）",
        "intent": [
            "**意图**：右键上下文菜单——ContextMenu 组件实现右键弹出菜单，点击选项改变清除颜色；⭐⭐",
            "- **ContextMenu 组件**:",
            "  - ContextMenu 标记右键菜单容器——右键点击时显示；",
            "  - 🔧 内置交互处理——点击菜单外区域自动关闭；",
            "- **菜单选项**:",
            "  - 每个选项是一个 Button + Text 组合——点击触发对应操作；",
            "  - 本例中选项改变 ClearColor——演示菜单与全局状态的交互；",
            "  - 🔧 菜单项可扩展为任意操作——打开对话框/执行命令/切换设置；",
            "- **弹出位置**:",
            "  - 菜单位于鼠标点击位置——PositionType::Absolute + 鼠标坐标；",
            "  - 🔧 边界检测确保菜单不超出窗口——自动调整弹出方向；",
            "- **注意事项**:",
            "  - ⚠️ ContextMenu 右键拦截——标准左键点击不受影响；",
            "  - 🔧 多层嵌套菜单可实现子菜单——但复杂度会增加；",
        ],
        "knowledge": [
            "知：<br>- ContextMenu 右键菜单；<br>- ClearColor 全局状态；<br>- 弹出位置计算。",
            "例：<br>- ui/button.rs(230)。",
        ],
    },
    "cooldown.rs": {
        "seq": 280,
        "cat": "UI",
        "filename": "`cooldown.rs`（usage）",
        "intent": [
            "**意图**：UI 冷却（CD）实现——Timer 驱动按钮冷却动画，进度条可视化剩余时间；⭐⭐",
            "- **Cooldown Timer**:",
            "  - Timer::new(duration, TimerMode::Once) 一次性冷却计时器；",
            "  - timer.tick(time.delta()) 每帧推进；",
            "  - timer.fraction() 0.0→1.0 进度值——用于进度条动画；",
            "  - 🔧 TimerMode::Once 确保冷却只执行一次——Repeating 会循环触发；",
            "- **进度条可视化**:",
            "  - Node { width: percent(fraction * 100) } 进度条宽度随冷却进度变化；",
            "  - BackgroundColor 动态颜色——冷却中红色，就绪绿色；",
            "  - 🔧 视觉反馈让用户清楚知道冷却状态——提升游戏体验；",
            "- **按钮交互**:",
            "  - 点击按钮启动冷却——timer.reset() 重置计时器；",
            "  - 冷却期间按钮不可交互——disabled 状态或 Ignore 输入；",
            "  - ⚠️ 必须检查 timer.is_finished() 才能再次触发——防止冷却中重复操作；",
            "- **与 Time 集成**:",
            "  - 🔧 Time<Fixed> 可获得确定性冷却——不受帧率波动影响；",
            "  - 🧩 配合 AnimationTimer 可实现冷却旋转/闪烁等特效；",
        ],
        "knowledge": [
            "知：<br>- Timer 冷却计时；<br>- fraction() 进度值；<br>- 进度条可视化。",
            "例：<br>- time/timers.rs(175)；<br>- ui/button.rs(230)。",
        ],
    },
    "reflection.rs": {
        "seq": 281,
        "cat": "反射",
        "filename": "`reflection.rs`",
        "intent": [
            "**意图**：反射基础——Reflect 派生启用运行时类型反射，动态访问字段/方法/属性；⭐⭐⭐",
            "- **Reflect 派生**:",
            "  - #[derive(Reflect)] 为结构体/枚举启用运行时反射——⚠️ 需要 'static 生命周期；",
            "  - Reflect 要求所有字段也是 Reflect 类型——Option/Vec/HashMap 等内置支持；",
            "  - 🔧 Reflect 是 Bevy 序列化/编辑器/热重载的基础——几乎所有数据类型都应派生；",
            "- **动态字段访问**:",
            '  - reflect.get_field::<T>("name") 动态读取字段值——返回 Option<&T>；',
            '  - reflect.get_field_mut::<T>("name") 动态修改字段值——返回 Option<&mut T>；',
            "  - ⚠️ 字段名必须匹配——编译时类型检查消失，运行时可能 panic；",
            "- **ReflectReflectable**:",
            '  - 动态调用方法——reflect.call("method_name", args)；',
            "  - 🔧 方法必须标记 #[reflect] 才能通过反射调用；",
            "- **ReflectSerializer**:",
            "  - ReflectSerializer::new(&value) 将 Reflect 值序列化为二进制/JSON；",
            "  - 反序列化还原完整类型——不需要原始类型信息（通过 TypePath）；",
            "  - 🔧 序列化是存档/网络传输/编辑器保存的核心机制；",
            "- **注意事项**:",
            "  - ⚠️ 反射有运行时开销——频繁调用应缓存结果；",
            "  - 🔧 集合类型（Vec/HashMap）的反射需要额外的 trait 实现；",
        ],
        "knowledge": [
            "知：<br>- Reflect 派生；<br>- 动态字段访问；<br>- ReflectSerializer 序列化。",
            "例：<br>- ecs/ecs_guide.rs(124)。",
        ],
    },
}


def build_intent_text(intent_lines):
    """Join intent lines with <br> separator."""
    return "<br>".join(intent_lines)


def build_knowledge_text(knowledge_lines):
    """Join knowledge lines with <br> separator."""
    return "<br>".join(knowledge_lines)


def build_entry_line(entry):
    """Build a catalog table row from entry dict."""
    intent = build_intent_text(entry["intent"])
    knowledge = build_knowledge_text(entry["knowledge"])
    return (
        f"| {entry['seq']} | {entry['cat']} | {entry['filename']} "
        f"| {intent} | {knowledge} |"
    )


def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []
    replaced = set()

    for line in lines:
        matched = False
        for key, entry in ENTRIES.items():
            # Match by sequence number in the table row
            pattern = rf"^\| {entry['seq']} \|"
            if re.match(pattern, line.strip()):
                new_line = build_entry_line(entry) + "\n"
                new_lines.append(new_line)
                replaced.add(key)
                matched = True
                break
        if not matched:
            new_lines.append(line)

    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        f.writelines(new_lines)

    print(f"Replaced {len(replaced)} entries:")
    for key in sorted(replaced, key=lambda k: ENTRIES[k]["seq"]):
        e = ENTRIES[key]
        print(f"  seq {e['seq']:3d}: {key}")


if __name__ == "__main__":
    main()
