#!/usr/bin/env python3
"""Replace catalog entries 81-107 (3D remaining + Animation) with detailed content."""

import re

CATALOG = "/Users/lf380/Code/Bevy/a1/bevy_examples_catalog.md"

DATA = [
    # 81 - mixed_lighting
    (
        81,
        "混合光照",
        [
            "**意图**：在同一场景中组合烘焙(Baked)与实时(RealTime)光照——静态物体用光照贴图，动态物体用实时光照。⭐⭐⭐",
            "- **四种光照模式**:",
            "  - Baked：所有物体使用光照贴图，含间接光照(红色底反光)，球体不能移动；",
            "  - MixedDirect：静态物体烘焙，动态球体实时直接光——球体可动但无间接光；",
            "  - MixedIndirect：静态物体烘焙间接光+实时直接光，球体实时直接光——球体投射阴影；",
            "  - RealTime：所有物体实时光照——灵活性最高但无间接光；",
            "- **光照贴图切换**:",
            "  - update_lightmaps 系统监听 LightingModeChanged 事件，按模式加载不同光照贴图；",
            "  - 每个模式有独立的预烘焙光照贴图(Baked/MixedDirect/MixedIndirect)；",
            "  - Lightmap::uv_rect 定义物体在光照贴图纹理中的 UV 区域；",
            "- **Picking 移动球体**:",
            "  - 使用 MeshPickingPlugin 实现点击场景移动球体；",
            "  - Pickable::IGNORE 标记球体自身不可点击(防止点击球体本身)；",
            "  - 球体在 Baked 模式下位置固定(光照已烘焙无法改变)；",
            "- **uv_rect_opengl 坐标转换**:",
            "  - 编译时将 OpenGL UV 坐标(左下原点)转为 Vulkan 坐标(左上原点)；",
            "  - 🔧 光照烘焙工具通常使用 OpenGL 约定，Bevy 使用 Vulkan——需做 UV 翻转；",
            "- **Message 事件驱动**:",
            "  - #[derive(Message)] LightingModeChanged 事件在模式切换时广播；",
            "  - MessageReader / MessageWriter 替代旧版 EventReader/EventWriter；",
            "  - 🔧 这是大型游戏常用的混合光照策略(静态 GI + 动态直接光)；",
        ],
        [
            "Lightmap 多种模式(Baked/Mixed/RealTime)；",
            "uv_rect 坐标转换(OpenGL→Vulkan)；",
            "MeshPicking 交互移动物体；",
            "MessageReader/Writer 事件通信。",
        ],
        [
            "3D/lightmaps.rs(80)。",
        ],
    ),
    # 82 - visibility_range
    (
        82,
        "可见性范围",
        [
            "**意图**：演示 VisibilityRange（HLOD）——根据相机距离切换高/低多边形模型，实现 LOD 效果。⭐⭐⭐",
            "- **VisibilityRange 组件**:",
            "  - start_margin / end_margin 定义可见距离范围；",
            "  - 高模 HighPoly：0~4m 可见，低模 LowPoly：3~9m 可见，重叠区域平滑过渡；",
            "  - use_aabb=false 使用包围球而非 AABB 做距离计算；",
            "- **动态切换模式**:",
            "  - AppStatus Resource 存储当前模式(仅高模/仅低模/自动切换)；",
            "  - 按键 1/2/3 切换 show_one_model_only 选项；",
            "  - INVISIBLE_VISIBILITY_RANGE = (0,0) 完全隐藏模型；",
            "- **Added<Mesh3d> 过滤器**:",
            "  - set_visibility_ranges 系统检测新加载的 Mesh，自动添加 VisibilityRange 组件；",
            "  - 向上遍历 ChildOf 链查找 MainModel 标记组件；",
            "  - ⚠️ glTF 不支持 visibility range 元数据，需代码手动添加；",
            "- **Prepass 切换**:",
            "  - DepthPrepass + NormalPrepass 提升阴影/法线质量但增加 GPU 开销；",
            "  - Space 键切换 prepass，观察对渲染结果的影响；",
            "- **环境贴图 IBL**:",
            "  - EnvironmentMapLight 提供基于图像的间接光照(diffuse + specular)；",
            "  - 🔧 HLOD 是开放世界游戏必备技术——远处用低模节省性能；",
        ],
        [
            "VisibilityRange 组件(start/end margin)；",
            "HLOD 高低模切换机制；",
            "Added<T> 过滤器检测新实体；",
            "EnvironmentMapLight 环境光照。",
        ],
        [
            "3D/3d_scene.rs(32)；",
            "3D/lighting.rs(35)。",
        ],
    ),
    # 83 - decal
    (
        83,
        "贴花渲染",
        [
            "**意图**：Forward 模式下使用 ForwardDecal 将纹理投射到 3D 表面（贴花/投影效果）。⭐⭐",
            "- **ForwardDecal 组件**:",
            "  - ForwardDecal 标记组件激活前向贴花渲染；",
            "  - ForwardDecalMaterial<StandardMaterial> 包装 StandardMaterial；",
            "  - depth_fade_factor 控制深度淡入因子(越大越柔和)；",
            "- **DepthPrepass 必需**:",
            "  - ⚠️ 相机必须附加 DepthPrepass 才能渲染 ForwardDecal；",
            "  - Msaa::Off 关闭多重采样（WebGPU 贴花必须）；",
            "  - Fxaa::default() 作为 MSAA 的替代抗锯齿方案；",
            "- **FreeCamera 插件**:",
            "  - FreeCameraPlugin 提供 WASD+鼠标 的自由摄像机控制；",
            "  - 🔧 开发 3D 场景时 FreeCamera 比手动实现相机控制方便得多；",
            "- **随机旋转方块**:",
            "  - ChaCha8Rng 确定性随机生成旋转轴和角度；",
            "  - Quat::from_axis_angle 随机旋转展示贴花在非平面几何上的效果；",
            "  - 🔧 贴花常用于弹痕、污渍、血迹等表面效果；",
        ],
        [
            "ForwardDecal 组件与材质包装；",
            "DepthPrepass 渲染依赖；",
            "FreeCamera 自由相机。",
        ],
        [
            "3D/3d_scene.rs(32)；",
            "3D/lighting.rs(35)。",
        ],
    ),
    # 84 - clustered_decals
    (
        84,
        "聚类贴花",
        [
            "**意图**：使用 ClusteredDecal 将贴花附着到 3D 表面，支持多贴花、自定义着色器和交互控制。⭐⭐⭐",
            "- **ClusteredDecal 组件**:",
            "  - base_color_texture 贴花颜色纹理；",
            "  - tag 字段传递给自定义着色器(0~3)，实现不同贴花的不同视觉效果；",
            "  - 🔧 tag 是整数标识符，可在 fragment shader 中 switch 分支处理；",
            "- **平台检测**:",
            "  - decal::clustered::clustered_decals_are_usable 检查 GPU 是否支持聚类贴花；",
            "  - ⚠️ 不支持时需要优雅降级(显示错误提示并退出)；",
            "- **ExtendedMaterial 自定义扩展**:",
            "  - CustomDecalExtension 实现 MaterialExtension trait；",
            "  - fragment_shader() 返回自定义 WGSL 着色器路径；",
            "  - 🧩 ExtendedMaterial = StandardMaterial + MaterialExtension 组合模式；",
            "- **球面坐标移动**:",
            "  - 将笛卡尔坐标转为球面坐标(θ, φ, r)实现环绕移动；",
            "  - AccumulatedMouseMotion 累积鼠标位移控制移动/缩放/旋转；",
            "- **交互控制**:",
            "  - Selection 枚举(Camera/DecalA/DecalB) 选择操作对象；",
            "  - DragMode 枚举(Move/Scale/Roll) 通过悬停按钮切换拖拽模式；",
            "  - 🔧 Gizmos::primitive_3d 可视化贴花包围盒边界；",
        ],
        [
            "ClusteredDecal 组件与 tag 机制；",
            "ExtendedMaterial MaterialExtension 扩展；",
            "MaterialPlugin 注册自定义材质；",
            "球面坐标变换移动控制。",
        ],
        [
            "3D/decal.rs(83)；",
            "shader/shader_material.rs(294)。",
        ],
    ),
    # 85 - clustered_decal_maps
    (
        85,
        "聚类贴花贴图",
        [
            "**意图**：演示聚类贴花的法线贴图、金属粗糙度贴图和自发光贴图效果。⭐⭐",
            "- **贴花纹理通道**:",
            "  - base_color_texture 基础颜色(Bevy Logo)；",
            "  - normal_map_texture 法线贴图(浮雕凸起效果)；",
            "  - metallic_roughness_texture 金属粗糙度贴图(蓝=G通道金属，绿=R通道粗糙度)；",
            "  - emissive_texture 自发光贴图(白色鸟形发光)；",
            "- **FromWorld 资源加载**:",
            "  - AppTextures Resource 实现 FromWorld trait，在 World 中预加载所有贴花纹理；",
            "  - 🔧 FromWorld 比 Startup 系统更适合全局资源初始化——保证使用前已加载；",
            "- **is_srgb = false 设置**:",
            "  - 法线/金属粗糙度贴图必须以线性空间加载；",
            "  - ⚠️ 错误设置 is_srgb=true 会导致光照计算偏差，贴花效果不正确；",
            "- **贴花生命周期动画**:",
            "  - ExampleDecalState 三态状态机：AnimatingIn → Idling → AnimatingOut；",
            "  - Timer::new(duration, TimerMode::Once) 驱动每个阶段；",
            "  - scale = size × fraction 实现生长/缩小动画；",
            "- **ChaCha8Rng 确定性随机**:",
            "  - Resource 包装 RNG 保证可复现的贴花位置和大小；",
            "  - 🔧 确定性随机是回放系统和测试的基础；",
        ],
        [
            "ClusteredDecal 纹理通道(color/normal/metallic_roughness/emissive)；",
            "FromWorld 资源初始化模式；",
            "is_srgb=false 线性空间加载；",
            "Timer 状态机动画。",
        ],
        [
            "3D/clustered_decals.rs(84)。",
        ],
    ),
    # 86 - wireframe
    (
        86,
        "线框渲染",
        [
            "**意图**：使用 WireframePlugin 开启 3D Mesh 线框渲染，演示全局/单实体线框控制和颜色覆盖。⭐⭐",
            "- **启用前提**:",
            "  - RenderPlugin 需设置 WgpuFeatures::POLYGON_MODE_LINE；",
            "  - ⚠️ 仅 DX12/Vulkan/Metal 支持，WebGL/WebGPU 不可用；",
            "  - WireframePlugin::default() 添加到插件组；",
            "- **三级线框控制**:",
            "  - NoWireframe 组件：实体始终不显示线框(无视全局开关)；",
            "  - Wireframe 组件：实体始终显示线框(无视全局开关)；",
            "  - 无标记：跟随 WireframeConfig::global 设置；",
            "  - 🔧 不同粒度允许混合：大部分关线框，少数关键物体开线框；",
            "- **WireframeColor 颜色覆盖**:",
            "  - WireframeConfig::default_color 全局默认颜色；",
            "  - WireframeColor { color } 组件覆盖单实体线框颜色；",
            "  - Z/X/C 键交互切换全局开关/全局颜色/单实体颜色；",
            "- **调试用途**:",
            "  - 🔧 线框模式常用于调试碰撞体/物理边界/网格拓扑；",
            "  - ⚠️ 线框模式下纹理/材质不显示，仅显示三角网格线；",
            "  - 🔬 大量线框网格会占用额外 GPU 管线；",
        ],
        [
            "WireframePlugin / WireframeConfig；",
            "WgpuFeatures::POLYGON_MODE_LINE；",
            "Wireframe / NoWireframe / WireframeColor 组件。",
        ],
        [
            "3D/3d_scene.rs(32)；",
            "2D/wireframe_2d.rs(26)。",
        ],
    ),
    # 87 - lines
    (
        87,
        "自定义材质",
        [
            "**意图**：使用自定义 Material 着色器和 PrimitiveTopology::LineList/LineStrip 绘制 3D 线条。⭐⭐⭐",
            "- **LineList 线段列表**:",
            "  - LineList { lines: vec![(start, end)] } 每对顶点定义一条独立线段；",
            "  - PrimitiveTopology::LineList 每两个顶点绘制一条线段；",
            "  - 🔧 适合不连续的线条(如网格线、辅助线)；",
            "- **LineStrip 线段条带**:",
            "  - LineStrip { points: vec![...] } 连续点之间依次连线；",
            "  - PrimitiveTopology::LineStrip 每两个相邻顶点绘制一条线段；",
            "  - 🔧 适合连续路径(如轨迹、轮廓)；",
            "- **自定义 Material 实现**:",
            "  - LineMaterial #[uniform(0)] color: LinearRgba 传递颜色到着色器；",
            "  - Material trait 的 specialize() 方法设置 PolygonMode::Line；",
            "  - ⚠️ PolygonMode::Line 是渲染管线级别的线框模式，不是几何级别的；",
            "- **Mesh::new 手动构建**:",
            "  - Mesh::new(PrimitiveTopology, RenderAssetUsages) 手动创建网格；",
            "  - with_inserted_attribute 注入顶点位置数据；",
            "  - 🔧 从零构建网格时需要理解顶点属性与拓扑的关系；",
        ],
        [
            "LineList / LineStrip 拓扑；",
            "Material trait specialize() 覆盖；",
            "PolygonMode::Line 渲染模式；",
            "Mesh::new 手动构建网格。",
        ],
        [
            "shader/shader_material.rs(294)；",
            "3D/3d_shapes.rs(33)。",
        ],
    ),
    # 88 - atmosphere
    (
        88,
        "大气散射",
        [
            "**意图**：使用 PBR 大气散射(Atmosphere)模拟真实天空光照，配合体积雾和水面材质。⭐⭐⭐",
            "- **Atmosphere 组件**:",
            "  - Atmosphere::earthlike(scattering_medium) 创建类地大气模型；",
            "  - ScatteringMedium 定义散射参数(默认地球大气)；",
            "  - AtmosphereSettings 控制渲染质量和场景缩放；",
            "- **渲染方法切换**:",
            "  - AtmosphereMode::LookupTexture 查找表渲染(快速)；",
            "  - AtmosphereMode::Raymarched 光线步进渲染(高质量)；",
            "  - 🔧 LookupTexture 适合实时场景，Raymarched 适合离线/截图；",
            "- **AtmosphereEnvironmentMapLight**:",
            "  - 驱动 IBL(基于图像的间接光照)和反射；",
            "  - 大气散射自动生成环境贴图，无需手动加载；",
            "- **ExtendedMaterial 水面**:",
            "  - Water MaterialExtension 实现水面波纹动画；",
            "  - deferred_fragment_shader 使用延迟渲染路径；",
            "  - WaterSettings 控制波浪八度/缩放/强度参数；",
            "- **VolumetricFog 体积雾**:",
            "  - FogVolume 组件 + VolumetricLight 光源标记实现体积光效果；",
            "  - 🔧 RAW_SUNLIGHT 照度值推荐用于大气散射——它是大气过滤前的太阳光；",
            "  - ⚠️ 大气散射 + 体积雾 + Bloom 组合对 GPU 性能要求高；",
        ],
        [
            "Atmosphere / AtmosphereSettings 大气组件；",
            "ScatteringMedium 散射介质；",
            "AtmosphereEnvironmentMapLight IBL；",
            "VolumetricFog 体积雾。",
        ],
        [
            "3D/3d_scene.rs(32)；",
            "3D/lighting.rs(35)。",
        ],
    ),
    # 89 - pcss
    (
        89,
        "软阴影",
        [
            "**意图**：演示 PCSS(百分比渐近软阴影)——根据距离自动调整阴影柔和度，支持方向光/点光/聚光。⭐⭐⭐",
            "- **ShadowFilteringMethod**:",
            "  - Gaussian(Castano '13) 非时间性滤波，适合无 TAA 场景；",
            "  - Temporal(Jimenez '14) 时间性滤波，配合 TAA 效果最佳；",
            "  - ⚠️ Temporal 模式需要 DepthPrepass + MotionVectorPrepass + TAA；",
            "- **soft_shadow_size 参数**:",
            "  - DirectionalLight 的 soft_shadow_size 控制阴影柔和度(单位：世界单位)；",
            "  - None = 硬阴影(无 PCSS)；Some(radius) = 软阴影；",
            "  - 🔧 radius 越大阴影越柔和，但性能开销也越大；",
            "- **光源类型切换**:",
            "  - LightType 枚举(Directional/Point/Spot) 动态切换光源组件；",
            "  - PointLight/SpotLight 使用 soft_shadows_enabled 布尔开关；",
            "  - ⚠️ 切换光源需要移除旧组件插入新组件(非修改现有组件)；",
            "- **shadow_depth_bias 调优**:",
            "  - 方向光 0.20、点光 0.35 避免阴影痤疮(shadow acne)；",
            "  - ⚠️ bias 过大会导致 Peter Panning(阴影与物体分离)；",
            "- **TAA + Skybox**:",
            "  - TemporalAntiAliasing::default() 时间性抗锯齿；",
            "  - Skybox 组件 + 天空纹理提供背景天空；",
            "  - 🔧 PCSS + TAA 是现代游戏的主流阴影方案；",
        ],
        [
            "ShadowFilteringMethod(Gaussian/Temporal)；",
            "soft_shadow_size PCSS 柔和度；",
            "shadow_depth_bias 阴影痤疮；",
            "TAA 时间性抗锯齿。",
        ],
        [
            "3D/shadow_biases.rs(58)；",
            "3D/lighting.rs(35)。",
        ],
    ),
    # 90 - meshlet
    (
        90,
        "Meshlet渲染",
        [
            "**意图**：使用 MeshletPlugin 进行 Meshlet 渲染——将高密度网格拆分为小簇(meshlet)实现 GPU 驱动的渲染管线。⭐⭐⭐",
            "- **MeshletPlugin 插件**:",
            "  - MeshletPlugin { cluster_buffer_slots } 配置 meshlet 缓冲区大小；",
            "  - MeshletMesh3d 组件替代 Mesh3d 用于 meshlet 网格；",
            "  - ⚠️ 实验性 API，仅用于高密度场景(数十万三角面以上)；",
            "- **MeshletMesh 加载**:",
            "  - 自定义 .meshlet_mesh 格式(预处理后的 meshlet 数据)；",
            "  - 需要 meshlet_processor cargo feature 启用 MeshletMesh::from_mesh 转换；",
            "  - 🔧 meshlet 预处理是离线步骤，运行时直接加载预处理结果；",
            "- **MeshletDebugMaterial**:",
            "  - 空 MaterialExtension 实现，用于调试可视化；",
            "  - 🔧 meshlet 渲染管线会自动可视化 cluster 边界；",
            "- **性能配置**:",
            "  - DirectionalLightShadowMap { size: 4096 } 高分辨率阴影贴图；",
            "  - CascadeShadowConfigBuilder { num_cascades: 1 } 单级联简化阴影；",
            "  - 🔧 meshlet 渲染的核心优势：GPU 驱动的遮挡剔除和 LOD；",
        ],
        [
            "MeshletPlugin / MeshletMesh3d；",
            "meshlet_processor 预处理；",
            "GPU 驱动渲染管线。",
        ],
        [
            "3D/3d_scene.rs(32)；",
            "3D/occlusion_culling.rs(91)。",
        ],
    ),
    # 91 - occlusion_culling
    (
        91,
        "遮挡剔除",
        [
            "**意图**：演示 GPU 驱动的遮挡剔除——被遮挡的 Mesh 不发送到 GPU 渲染，实时显示剔除统计。⭐⭐⭐",
            "- **OcclusionCulling 组件**:",
            "  - 相机附加 OcclusionCulling + DepthPrepass 激活遮挡剔除；",
            "  - Space 键运行时切换开/关对比效果；",
            "  - ⚠️ 需要 DepthPrepass 提供深度信息供剔除算法使用；",
            "- **GPU→CPU 间接参数回读**:",
            "  - ReadbackIndirectParametersPlugin 自定义渲染图节点；",
            "  - RenderGraph::add_render_graph_node 在 Core3d 图中插入回读节点；",
            "  - IndirectParametersBuffers 存储 GPU 间接绘制参数；",
            "- **Staging Buffer 机制**:",
            "  - wgpu 不允许直接映射 IndirectParameters 缓冲区；",
            "  - 需先 copy_buffer_to_buffer 到 staging buffer，再 map_async 回读；",
            "  - 🔧 这是 GPU→CPU 数据回读的标准模式；",
            "- **Arc<Mutex<>> 跨线程共享**:",
            "  - SavedIndirectParameters 使用 Arc<Mutex> 在渲染线程和主线程间共享数据；",
            "  - 渲染线程写入 → 主线程读取显示渲染统计；",
            "  - 🔧 不需要精确同步——渲染比主逻辑提前至少一帧；",
            "- **渲染统计显示**:",
            "  - 实际渲染数量/总 Mesh 数量 实时显示；",
            "  - 🔧 遮挡剔除是大场景性能优化的核心技术；",
        ],
        [
            "OcclusionCulling 组件；",
            "IndirectParametersBuffers GPU 回读；",
            "RenderGraph 自定义节点；",
            "Staging Buffer 映射回读。",
        ],
        [
            "3D/3d_scene.rs(32)；",
            "3D/meshlet.rs(90)。",
        ],
    ),
    # 92 - solari
    (
        92,
        "实时光追",
        [
            "**意图**：使用 Bevy Solari 实现动态实时光线追踪——直接光/间接光/反射/全局光照实时计算。⭐⭐⭐",
            "- **SolariPlugins 插件组**:",
            "  - SolariPlugins 包含所有 Solari 光照子系统；",
            "  - RaytracingMesh3d 组件替代 Mesh3d 用于光追网格；",
            "  - ⚠️ Msaa::Off + CameraMainTextureUsages::STORAGE_BINDING 是必需配置；",
            "- **SolariLighting 组件**:",
            "  - 附加到相机启用实时光照计算；",
            "  - 替代传统阴影映射——Solari 自动生成阴影；",
            "  - 🔧 shadows_enabled: false 可以关闭传统阴影(由 Solari 接管)；",
            "- **Pathtracer 参考路径**:",
            "  - PathtracingPlugin 提供离线参考路径追踪；",
            "  - --pathtracer 命令行参数切换实时/离线模式；",
            "  - 🔧 参考路径用于验证实时光照质量；",
            "- **Solari 兼容性处理**:",
            "  - 缺少 UV 的网格需添加 UV0 和切线；",
            "  - generate_tangents() 自动生成切线属性；",
            "  - ⚠️ Mesh 必须有 UV0 + Tangent 才能正确参与 Solari 光照；",
            "- **性能诊断**:",
            "  - DiagnosticsStore + RenderDiagnosticsPlugin 采集 GPU 性能数据；",
            "  - light_tiles / world_cache / direct_lighting 等阶段耗时统计；",
            "  - 🔧 DLSS Ray Reconstruction 建议启用——去噪+超采样大幅提升性能；",
        ],
        [
            "SolariPlugins / SolariLighting；",
            "RaytracingMesh3d 光追网格；",
            "Pathtracer 参考路径；",
            "CameraMainTextureUsages STORAGE_BINDING。",
        ],
        [
            "3D/3d_scene.rs(32)；",
            "3D/lighting.rs(35)。",
        ],
    ),
    # 93 - mesh_ray_cast
    (
        93,
        "网格射线",
        [
            "**意图**：使用 MeshRayCast 系统参数进行链式多次射线投射并反弹，演示光线反射可视化。⭐⭐⭐",
            "- **MeshRayCast 系统参数**:",
            "  - MeshRayCast 作为 SystemParam 直接在系统中使用；",
            "  - cast_ray(ray, settings) 返回按距离排序的交点列表；",
            "  - 🔧 比旧版 RayCaster 组件更灵活——不需要实体存储射线；",
            "- **链式反弹逻辑**:",
            "  - ray.direction.reflect(hit.normal) 计算反射方向；",
            "  - ray.origin = hit.point + direction × 1e-6 避免自相交；",
            "  - 🔧 1e-6 偏移量防止射线起点恰好在表面上导致重复命中；",
            "- **RayMap 鼠标射线**:",
            "  - Res<RayMap> 存储光标发射的所有射线；",
            "  - ray_map.iter() 获取光标在场景中的所有交点；",
            "  - 🧩 光标射线 + 自动射线两种模式同时演示；",
            "- **Gizmos 可视化**:",
            "  - gizmos.sphere 标记射线源点；",
            "  - gizmos.linestrip_gradient 彩色渐变线段条带显示反弹路径；",
            "  - 🔧 Bloom::default() + Tonemapping::TonyMcMapface 增强光线发光效果；",
        ],
        [
            "MeshRayCast 系统参数；",
            "Ray3d::reflect 反射计算；",
            "RayMap 光标射线。",
        ],
        [
            "picking/mesh_picking.rs(325)；",
            "3D/3d_viewport_to_world.rs(94)。",
        ],
    ),
    # 94 - 3d_viewport_to_world
    (
        94,
        "坐标转换",
        [
            "**意图**：使用 Camera::viewport_to_world 将屏幕光标位置转换为 3D 世界空间射线并与地面求交。⭐⭐⭐",
            "- **viewport_to_world 核心**:",
            "  - camera.viewport_to_world(transform, cursor_pos) 返回 Result<Ray3d>；",
            "  - ⚠️ 可能失败(点在视口外)，需 if-let 安全解包；",
            "  - 🔧 这是 3D 点击/选择功能的基础 API；",
            "- **plane_intersection_point**:",
            "  - ray.plane_intersection_point(origin, InfinitePlane3d) 计算射线与平面交点；",
            "  - InfinitePlane3d::new(up) 定义无限平面法线方向；",
            "  - 返回 Option<Vec3>——射线与平面平行时为 None；",
            "- **Single 查询模式**:",
            "  - Single<(&Camera, &GlobalTransform)> 确保只有一个相机匹配；",
            "  - Single<&GlobalTransform, With<Ground>> 定位地面实体；",
            "  - 🔧 Single 在编译时保证查询唯一性，比 Query 更安全；",
            "- **Gizmos 圆形标记**:",
            "  - gizmos.circle 在交点位置绘制圆形光标；",
            "  - Isometry3d::new 构建 3D 等距变换(位置+旋转)；",
            "  - 🔧 此模式常用于 3D 策略游戏的格子选择/移动指示；",
        ],
        [
            "Camera::viewport_to_world 射线转换；",
            "Ray3d::plane_intersection_point 平面求交；",
            "Single 查询保证唯一性。",
        ],
        [
            "2D/2d_viewport_to_world.rs(25)；",
            "picking/mesh_picking.rs(325)。",
        ],
    ),
    # 95 - animated_transform
    (
        95,
        "变换动画",
        [
            "**意图**：用代码定义并播放操作 Transform 组件的动画——行星轨道/卫星旋转/缩放脉冲。⭐⭐⭐",
            "- **AnimationClip 关键帧曲线**:",
            "  - AnimationClip::default() 创建空动画剪辑；",
            "  - add_curve_to_target(target_id, curve) 将曲线绑定到实体路径；",
            "  - UnevenSampleAutoCurve 不等间距自动插值曲线；",
            "- **animated_field! 宏**:",
            "  - animated_field!(Transform::translation) 指定动画目标字段；",
            "  - 自动推导类型为 AnimatableProperty；",
            "  - 🔧 仅支持 Transform/UiTransform 的可动画化字段；",
            "- **AnimationTargetId 路径寻址**:",
            "  - AnimationTargetId::from_name(&name) 按名称定位实体；",
            "  - from_names([parent, child]) 多级路径定位嵌套实体；",
            "  - 🧩 层级路径遍历机制：从根到目标逐级匹配 Name 组件；",
            "- **AnimationGraph + AnimationPlayer**:",
            "  - AnimationGraph::from_clip(handle) 从剪辑创建图并返回节点索引；",
            "  - player.play(index).repeat() 循环播放；",
            "  - 🔧 AnimationGraph 是 Bevy 0.18+ 的核心动画架构；",
            "- **AnimatedBy 标记**:",
            "  - AnimatedBy(entity) 标记实体被哪个 AnimationPlayer 驱动；",
            "  - 多个子实体可共享同一个动画玩家；",
            "  - ⚠️ 必须显式设置 AnimatedBy，否则动画系统不处理该实体；",
        ],
        [
            "AnimationClip / AnimatableCurve 关键帧；",
            "animated_field! 宏；",
            "AnimationTargetId 路径寻址；",
            "AnimationGraph / AnimationPlayer。",
        ],
        [
            "animation/easing_functions.rs(96)；",
            "transforms/transform.rs(30)。",
        ],
    ),
    # 96 - easing_functions
    (
        96,
        "缓动函数",
        [
            "**意图**：可视化展示所有内置 EaseFunction 缓动函数的曲线行为——36 种缓动类型实时动画。⭐⭐",
            "- **EaseFunction 枚举**:",
            "  - In 系列(Sine/Quadratic/Cubic/Quartic/Quintic/SmoothStep/SmootherStep/Circular/Exponential/Elastic/Back/Bounce) 12 种；",
            "  - Out / InOut 系列各 12 种，共 36 种标准缓动；",
            "  - Linear + Steps(4, JumpAt) + Elastic(50.0) 特殊变体；",
            "- **EasingCurve 曲线构建**:",
            "  - EasingCurve::new(start, end, function) 参数化插值曲线；",
            "  - curve.graph() 获取采样器，spaced_points(N) 均匀采样；",
            "  - curve.sample(t) 在 [0,1] 区间内插值；",
            "- **Gizmos::curve_2d 可视化**:",
            "  - curve_2d 绘制 2D 曲线(100 个采样点)；",
            "  - linestrip_2d 绘制边框和进度条；",
            "  - 🔧 曲线可视化是调试缓动效果的最佳方式；",
            "- **实时进度动画**:",
            "  - time.elapsed_secs() % (duration + margin) 实现循环进度；",
            "  - clamp(0.0, 1.0) 确保采样范围在曲线定义域内；",
            "  - 🔧 每种缓动函数有独立的可视化方块+曲线+进度指示器；",
        ],
        [
            "EaseFunction 36 种标准缓动；",
            "EasingCurve 参数化插值；",
            "Gizmos::curve_2d 曲线可视化。",
        ],
        [
            "animation/animated_transform.rs(95)；",
            "animation/eased_motion.rs(97)。",
        ],
    ),
    # 97 - eased_motion
    (
        97,
        "缓动运动",
        [
            "**意图**：使用 EasingCurve + ping_pong + reparametrize_linear 实现平滑往返缓动动画。⭐⭐⭐",
            "- **EasingCurve + reparametrize_linear**:",
            "  - EasingCurve::new(start, end, function) 创建缓动曲线；",
            "  - .reparametrize_linear(interval) 重新参数化到指定时间区间；",
            "  - 🔧 缓动函数默认参数化在 [0,1]，reparametrize 将其映射到真实时间；",
            "- **ping_pong 来回播放**:",
            "  - .ping_pong() 曲线正向播放后自动反向播放；",
            "  - ⚠️ ping_pong 会翻倍动画时长(3s 去 + 3s 回 = 6s)；",
            "  - 🔧 适合循环往复运动(如电梯/呼吸动画)；",
            "- **多属性混合动画**:",
            "  - 翻译曲线 CubicInOut + 旋转曲线 ElasticInOut；",
            "  - 不同属性可以使用不同的缓动函数和时间区间；",
            "  - 🔧 旋转的 ElasticInOut 产生弹性旋转效果(对称立方体的视觉错觉)；",
            "- **AnimationInfo 辅助结构**:",
            "  - 封装 target_name / target_id / graph / node_index；",
            "  - 🔧 将动画创建逻辑封装为独立函数，保持 setup 系统简洁；",
            "- **AnimationGraph::from_clip**:",
            "  - 从单个 AnimationClip 创建图；",
            "  - 🔧 即使只有一个动画剪辑也推荐使用 AnimationGraph 架构；",
        ],
        [
            "EasingCurve 参数化；",
            "reparametrize_linear 时间映射；",
            "ping_pong 来回播放。",
        ],
        [
            "animation/animated_transform.rs(95)；",
            "animation/easing_functions.rs(96)。",
        ],
    ),
    # 98 - color_animation
    (
        98,
        "颜色动画",
        [
            "**意图**：在不同颜色空间中动画化颜色——样条曲线(线性空间)和混合插值(任意空间)两种方式。⭐⭐⭐",
            "- **曲线方式(CubicBezier)**:",
            "  - LinearRgba / Oklaba / Xyza 空间支持贝塞尔曲线(线性/感知线性)；",
            "  - CubicBezier::new(control_points).to_curve() 构建三次贝塞尔曲线；",
            "  - curve.position(t) 在 [0,1] 区间插值颜色；",
            "  - ⚠️ Srgba/Hsva 不支持曲线——需要物理/感知线性空间；",
            "- **混合方式(Mix trait)**:",
            "  - Hsla / Srgba / Oklcha 空间使用 Mix trait 做逐段线性混合；",
            "  - mix(&target, weight) 在两色之间混合；",
            "  - 🔧 Mix trait 适用于任何颜色空间，但不如曲线平滑；",
            "- **泛型抽象**:",
            "  - CurveColor trait 约束 VectorSpace + Into<Color>；",
            "  - MixedColor trait 约束 Mix + Into<Color>；",
            "  - 🧩 同一逻辑应用于 6 种颜色空间的 Sprite 动画；",
            "- **时间驱动**:",
            "  - (sin(time) + 1) / 2 将 [-1,1] 映射到 [0,1] 做往返运动；",
            "  - sprite.color = 曲线/混合结果 赋值到 Sprite 颜色；",
            "  - 🔧 上半部分曲线控制，下半部分混合控制，便于对比效果；",
        ],
        [
            "CubicBezier 颜色曲线(Spaces)；",
            "Mix trait 颜色混合；",
            "LinearRgba / Oklaba / Hsla / Oklcha 颜色空间。",
        ],
        [
            "animation/easing_functions.rs(96)；",
            "2D/sprite.rs(2)。",
        ],
    ),
    # 99 - animation_events
    (
        99,
        "动画事件",
        [
            "**意图**：使用 AnimationEvent 在动画特定时间点触发游戏逻辑——通过 Observer 观察事件。⭐⭐⭐",
            "- **AnimationEvent derive**:",
            "  - #[derive(AnimationEvent, Clone)] 定义自定义动画事件；",
            "  - SetMessage { value, color } 携带文本和颜色数据；",
            "  - 🔧 AnimationEvent 是标记 trait，配合 AnimationClip::add_event 使用；",
            "- **add_event 时间绑定**:",
            "  - animation.add_event(time, SetMessage {...}) 在指定时间点插入事件；",
            "  - animation.set_duration(2.0) 延长动画时长以覆盖最后事件；",
            "  - ⚠️ 默认动画时长为最后一帧时间，需要显式设置更长；",
            "- **Observer 观察模式**:",
            "  - .add_observer(on_set_message) 注册全局观察者；",
            "  - fn on_set_message(On<SetMessage>, Single<...>) 接收事件触发；",
            "  - 🔧 Observer 是 Bevy 0.18+ 的事件处理新模式，替代事件轮询；",
            "- **animate_text_opacity 系统**:",
            "  - Query<&mut TextColor> 获取文本颜色组件；",
            "  - color.set_alpha(a - delta_secs) 每帧降低透明度实现淡出；",
            "  - 🔧 动画事件控制文本内容，系统控制透明度——逻辑分离；",
            "- **Bloom 辉光效果**:",
            "  - Bloom::NATURAL 自然泛光；",
            "  - 🔧 黑色背景 + Bloom 让文字发光效果更明显；",
        ],
        [
            "AnimationEvent derive 定义事件；",
            "AnimationClip::add_event 时间绑定；",
            "add_observer 观察者模式；",
            "Bloom 自然泛光。",
        ],
        [
            "animation/animated_mesh_events.rs(104)；",
            "animation/animated_mesh.rs(102)。",
        ],
    ),
    # 100 - animation_graph
    (
        100,
        "动画图",
        [
            "**意图**：使用 AnimationGraph 混合多个动画的权重——可视化拖拽调整 Idle/Walk/Run 混合比例。⭐⭐⭐",
            "- **AnimationGraph 构建**:",
            "  - AnimationGraph::new() 创建空图；",
            "  - add_blend(weight, parent) 添加混合节点(加权混合)；",
            "  - add_clip(handle, weight, parent) 添加动画剪辑节点；",
            "  - 🔧 图结构：Root → Blend(0.5) → [Walk, Run]；Root → Idle；",
            "- **序列化/反序列化**:",
            "  - SerializedAnimationGraph → ron::ser::to_string_pretty 序列化到 .animgraph.ron；",
            "  - asset_server.load(path) 加载预序列化的动画图资产；",
            "  - 🔧 --save 生成资产文件，--no-load 跳过加载使用代码创建；",
            "- **UI 交互调权**:",
            "  - ClipNode 组件 + Interaction::Pressed + RelativeCursorPosition 读取拖拽位置；",
            "  - pos.x.clamp(0., 1.) 将鼠标位置映射为权重值；",
            "  - 🧩 handle_weight_drag → update_ui → sync_weights 三系统链；",
            "- **AnimationPlayer 权重同步**:",
            "  - animation_mut(node_index).set_weight(weight) 设置动画混合权重；",
            "  - is_playing_animation + play 确保动画正在播放；",
            "  - 🔧 混合节点的权重由图自动计算，叶子节点权重由代码设置；",
            "- **GltfAssetLabel 动画加载**:",
            "  - GltfAssetLabel::Animation(index) 从 glTF 加载指定索引的动画；",
            "  - GltfAssetLabel::Scene(index) 加载场景(含骨骼和动画玩家)；",
            "  - 🔧 Fox.glb 包含 Idle(0)/Walk(1)/Run(2) 三个动画；",
        ],
        [
            "AnimationGraph 构建(blend/clip)；",
            "SerializedAnimationGraph 序列化；",
            "AnimationPlayer 权重控制。",
        ],
        [
            "animation/animated_transform.rs(95)；",
            "animation/animation_masks.rs(101)。",
        ],
    ),
    # 101 - animation_masks
    (
        101,
        "动画遮罩",
        [
            "**意图**：使用 AnimationMask 限制动画作用的骨骼范围——为不同骨骼组分配不同动画（头/四肢/尾巴）。⭐⭐⭐",
            "- **Mask Group 定义**:",
            "  - 6 个遮罩组(Head/LeftFrontLeg/RightFrontLeg/LeftHindLeg/RightHindLeg/Tail)；",
            "  - MASK_GROUP_PATHS 定义每组的骨骼链路径(前缀+后缀)；",
            "  - add_target_to_mask_group(target_id, group_index) 将骨骼添加到组；",
            "- **位掩码控制**:",
            "  - animation_node.mask 为 u32 位掩码，每位控制一个遮罩组；",
            "  - mask &= !(1 << group_id) 清除位=允许动画；",
            "  - mask |= 1 << group_id 置位=禁止动画；",
            "  - 🔧 32 位掩码支持最多 32 个遮罩组；",
            "- **add_clip_with_mask**:",
            "  - animation_graph.add_clip_with_mask(handle, mask, weight, parent) 添加带初始掩码的剪辑；",
            "  - Idle(索引 0) mask=0 全骨骼播放；Walk/Run mask=0x3f 初始隐藏全部；",
            "  - 🔧 运行时通过修改 node.mask 动态切换遮罩；",
            "- **交互控制 UI**:",
            "  - 每组 4 个按钮(Run/Walk/Idle/Off) 切换该组播放的动画；",
            "  - Changed<Interaction> 过滤器仅在状态变化时触发；",
            "  - 🔧 按钮颜色/文本颜色联动显示当前选择状态；",
            "- **AnimationTargetId 清理**:",
            "  - 移除不在任何遮罩组的骨骼的 AnimationTargetId/AnimatedBy；",
            "  - ⚠️ 不清理会导致未分组骨骼同时播放所有动画(视觉混乱)；",
        ],
        [
            "add_target_to_mask_group 遮罩组；",
            "animation_node.mask 位掩码；",
            "add_clip_with_mask 初始掩码；",
            "Changed<Interaction> 交互过滤。",
        ],
        [
            "animation/animation_graph.rs(100)；",
            "animation/animated_mesh.rs(102)。",
        ],
    ),
    # 102 - animated_mesh
    (
        102,
        "蒙皮动画",
        [
            "**意图**：加载 skinned glTF 狐狸模型并自动播放运行动画——最简动画播放模板。⭐⭐⭐",
            "- **AnimationGraph::from_clip**:",
            "  - 从 GltfAssetLabel::Animation(2) 加载 Run 动画；",
            "  - 返回 (graph, node_index) 图和节点索引；",
            "  - 🔧 AnimationGraph 是 Bevy 0.18+ 的动画核心架构；",
            "- **SceneInstanceReady 观察者**:",
            "  - .observe(play_animation_when_ready) 监听场景加载完成；",
            "  - On<SceneInstanceReady> 触发时搜索子实体的 AnimationPlayer；",
            "  - 🔧 场景异步加载——动画必须在场景 spawn 后才能附加；",
            "- **AnimationPlayer 播放**:",
            "  - player.play(index).repeat() 循环播放动画；",
            "  - commands.entity(child).insert(AnimationGraphHandle(...)) 连接图到玩家；",
            "  - ⚠️ AnimationGraphHandle 必须插入到 AnimationPlayer 所在实体；",
            "- **AnimationToPlay 组件模式**:",
            "  - 自定义组件存储 graph_handle + index；",
            "  - 父实体持有此组件，子实体(AnimationPlayer)播放时读取；",
            "  - 🧩 这是 glTF 动画播放的标准模式；",
            "- **CascadeShadowConfigBuilder**:",
            "  - first_cascade_far_bound: 200.0 近处阴影精度；",
            "  - maximum_distance: 400.0 阴影最大渲染距离；",
            "  - 🔧 大场景需要更宽的级联配置以覆盖远景阴影；",
        ],
        [
            "AnimationGraph::from_clip；",
            "SceneInstanceReady 观察者；",
            "AnimationPlayer / AnimationGraphHandle。",
        ],
        [
            "3D/3d_scene.rs(32)；",
            "glTF/load_gltf.rs(285)。",
        ],
    ),
    # 103 - animated_mesh_control
    (
        103,
        "动画控制",
        [
            "**意图**：控制 skinned glTF 动画播放——暂停/变速/跳转/切换/重复次数全交互控制。⭐⭐⭐",
            "- **AnimationTransitions 过渡**:",
            "  - AnimationTransitions::new() 创建过渡管理器；",
            "  - transitions.play(&mut player, index, duration) 带淡入淡出切换动画；",
            "  - 🔧 必须通过 AnimationTransitions 启动动画，不能直接操作 AnimationPlayer；",
            "- **键盘控制矩阵**:",
            "  - Space 暂停/恢复 is_paused() + resume() / pause()；",
            "  - ↑/↓ 变速 set_speed(speed × 1.2 / 0.8)；",
            "  - ←/→ 跳转 seek_to(elapsed ± 0.1)；",
            "  - Enter 切换动画 transitions.play(next, 250ms)；",
            "  - 1/2/3 设置重复次数 RepeatAnimation::Count(N)；",
            "  - L 无限循环 RepeatAnimation::Forever；",
            "- **AnimationGraph::from_clips**:",
            "  - from_clips([...]) 一次加载多个动画剪辑；",
            "  - 返回 (graph, Vec<node_index>) 多个节点索引；",
            "  - 🔧 比多次 from_clip 更高效；",
            "- **Added<AnimationPlayer> 检测**:",
            "  - Query<(Entity, &mut AnimationPlayer), Added<AnimationPlayer>> 检测新玩家；",
            "  - 🔧 glTF 加载后自动添加 AnimationPlayer，Added 过滤器确保只初始化一次；",
            "- **Animations Resource 模式**:",
            "  - Resource 存储动画索引和图句柄；",
            "  - Startup 创建 → Update 读取(异步加载后)；",
            "  - 🔧 Resource 比组件更适合全局共享数据；",
        ],
        [
            "AnimationTransitions 淡入淡出；",
            "RepeatAnimation 重复模式；",
            "seek_to / set_speed / pause/resume。",
        ],
        [
            "animation/animated_mesh.rs(102)；",
            "animation/animated_mesh_events.rs(104)。",
        ],
    ),
    # 104 - animated_mesh_events
    (
        104,
        "动画事件",
        [
            "**意图**：在 glTF 动画中嵌入自定义事件——狐狸脚着地时触发粒子喷射效果。⭐⭐⭐",
            "- **AnimationEvent + Observer**:",
            "  - #[derive(AnimationEvent, Reflect, Clone)] Step 事件标记着地；",
            "  - .add_observer(observe_on_step) 全局观察者响应事件；",
            "  - 🔧 事件在动画的精确时间点触发，与帧率无关；",
            "- **add_event_to_target**:",
            "  - clip.add_event_to_target(target_id, time, Step) 在特定骨骼+时间触发事件；",
            "  - 0.625 = 15帧 / 24fps 帧率换算为时间；",
            "  - ⚠️ 需要知道动画帧率才能精确计算事件时间点；",
            "- **AnimationTargetId 骨骼寻址**:",
            "  - FoxFeetTargets Resource 存储四只脚的 AnimationTargetId；",
            "  - 从骨骼路径字符串(如 root/_rootJoint/.../b_LeftHand_011) 构建；",
            "  - 🔧 动画事件绑定到骨骼而非实体——即使骨骼移动也跟随；",
            "- **粒子系统**:",
            "  - On<Step> 触发时 spawn 14 个粒子实体；",
            "  - Particle 组件: lifetime_timer + size + velocity；",
            "  - smooth_nudge(&Vec3::ZERO, 4.0, dt) 速度衰减实现自然减速；",
            "- **ParticleAssets FromWorld**:",
            "  - world.add_asset 从 World 直接添加资产(无需 Handle)；",
            "  - 🔧 共享粒子 Mesh/Material 避免重复创建；",
        ],
        [
            "AnimationEvent derive + Observer；",
            "add_event_to_target 骨骼绑定事件；",
            "AnimationTargetId 骨骼路径。",
        ],
        [
            "animation/animated_mesh.rs(102)；",
            "animation/animation_events.rs(99)。",
        ],
    ),
    # 105 - morph_targets
    (
        105,
        "变形目标",
        [
            "**意图**：播放 Morph Target(变形目标)动画并读取变形目标名称——网格形变动画演示。⭐⭐",
            "- **Morph Target 动画**:",
            "  - glTF 文件内嵌 morph target 权重动画；",
            "  - AnimationPlayer 自动驱动 morph target 权重变化；",
            "  - 🔧 Morph target 常用于面部表情、肌肉变形等效果；",
            "- **morph_target_names() API**:",
            "  - mesh.morph_target_names() 返回 Option<&[String]>；",
            "  - 遍历 AssetEvent<Mesh>::Added 检测新加载的 Mesh；",
            "  - 🔧 运行时读取 morph target 名称用于调试/动画控制；",
            "- **AnimationToPlay 模式**:",
            "  - 与 animated_mesh.rs 相同的组件模式；",
            "  - SceneInstanceReady 观察者 → 搜索 AnimationPlayer → play(index).repeat()；",
            "  - 🔧 标准 glTF 动画播放模板(适用于所有类型动画)；",
            "- **AssetEvent 事件处理**:",
            "  - MessageReader<AssetEvent<Mesh>> 读取网格资产事件；",
            "  - AssetEvent::Added { id } 检测新加载的网格；",
            "  - asset_server.get_path(id) 获取资产文件路径用于日志；",
            "  - 🔧 MorphStressTest.gltf 包含多个变形目标用于压力测试；",
        ],
        [
            "Morph Target 变形目标动画；",
            "mesh.morph_target_names() 名称读取；",
            "AssetEvent<Mesh> 资产事件。",
        ],
        [
            "animation/animated_mesh.rs(102)；",
            "3D/3d_shapes.rs(33)。",
        ],
    ),
    # 106 - custom_skinned_mesh
    (
        106,
        "自定义蒙皮",
        [
            "**意图**：完全用代码定义骨骼/关节/蒙皮网格数据——理解蒙皮渲染的底层机制。⭐⭐⭐",
            "- **Mesh 手动构建**:",
            "  - Mesh::new(PrimitiveTopology::TriangleList, RENDER_WORLD) 创建空网格；",
            "  - ATTRIBUTE_POSITION / ATTRIBUTE_UV_0 / ATTRIBUTE_NORMAL 顶点属性；",
            "  - Indices::U16 索引数组定义三角面；",
            "  - 🔧 10 个顶点 × 2 关节 = 最小蒙皮网格；",
            "- **蒙皮属性**:",
            "  - ATTRIBUTE_JOINT_INDEX: VertexAttributeValues::Uint16x4 每顶点 4 个关节索引；",
            "  - ATTRIBUTE_JOINT_WEIGHT: Vec<[f32; 4]> 每顶点 4 个关节权重(和为 1)；",
            "  - ⚠️ 权重必须归一化(sum=1)，否则蒙皮变形不正确；",
            "- **SkinnedMesh 组件**:",
            "  - inverse_bindposes: Handle<SkinnedMeshInverseBindposes> 逆绑定姿态矩阵；",
            "  - joints: Vec<Entity> 关节实体列表(对应逆绑定姿态的顺序)；",
            "  - 🔧 关节实体层级关系决定蒙皮的骨骼链行为；",
            "- **关节动画**:",
            "  - AnimatedJoint(isize) 标记需要动画的关节；",
            "  - 根据 isize 值执行不同动画(旋转/缩放/平移)；",
            "  - 🔧 -5~-3 旋转、-2~-1 缩放、0~3 平移组合演示不同效果；",
            "- **Gizmos::axes 可视化**:",
            "  - gizmos.axes(transform, length) 显示关节坐标轴；",
            "  - 🔧 调试蒙皮网格时坐标轴可视化非常有用；",
        ],
        [
            "Mesh 手动构建(JOINT_INDEX/WEIGHT)；",
            "SkinnedMesh / SkinnedMeshInverseBindposes；",
            "关节实体层级与蒙皮。",
        ],
        [
            "animation/animated_mesh.rs(102)；",
            "3D/3d_shapes.rs(33)。",
        ],
    ),
    # 107 - animated_ui
    (
        107,
        "UI动画",
        [
            "**意图**：使用动画剪辑驱动 UI 属性动画——UiTransform::scale 缩放脉冲 + 自定义 TextColorProperty 颜色渐变。⭐⭐⭐",
            "- **UiTransform::scale 动画**:",
            "  - animated_field!(UiTransform::scale) 指定动画目标字段；",
            "  - AnimatableKeyframeCurve 关键帧曲线(时间→值)；",
            "  - 0.3→1.0→0.3 循环缩放脉冲效果；",
            "  - 🔧 UI 动画与 3D 动画使用完全相同的 AnimationClip 机制；",
            "- **自定义 AnimatableProperty**:",
            "  - TextColorProperty 实现 AnimatableProperty trait；",
            "  - get_mut() 返回 &mut Srgba 引用(TextColor 内的颜色)；",
            "  - 🔧 自定义属性允许动画化任意组件的任意字段；",
            "- **AnimatableProperty trait 要求**:",
            "  - type Property = Srgba 属性类型；",
            "  - evaluator_id() 返回 TypeId 用于去重；",
            "  - get_mut(entity) 从 AnimationEntityMut 提取可变引用；",
            "  - ⚠️ ComponentNotPresent / PropertyNotPresent 错误需正确处理；",
            "- **AnimatedBy 关联**:",
            "  - AnimatedBy(player_entity) 标记文本被父节点的 AnimationPlayer 驱动；",
            "  - animation_target_id + animation_target_name 定位动画目标；",
            "  - 🔧 父节点持有 AnimationPlayer + AnimationGraphHandle；",
            "- **无需额外系统**:",
            "  - Bevy 自动每帧更新动画——不需要手动系统；",
            "  - 🔧 setup 系统构建 UI + 动画后，引擎自动驱动动画播放；",
        ],
        [
            "UiTransform::scale 动画；",
            "AnimatableProperty 自定义属性；",
            "AnimatedBy 动画关联。",
        ],
        [
            "animation/animated_transform.rs(95)；",
            "ui/button.rs(226)。",
        ],
    ),
]


FNAME_MAP = {
    81: "mixed_lighting.rs",
    82: "visibility_range.rs",
    83: "decal.rs",
    84: "clustered_decals.rs",
    85: "clustered_decal_maps.rs",
    86: "wireframe.rs",
    87: "lines.rs",
    88: "atmosphere.rs",
    89: "pcss.rs",
    90: "meshlet.rs",
    91: "occlusion_culling.rs",
    92: "solari.rs",
    93: "mesh_ray_cast.rs",
    94: "3d_viewport_to_world.rs",
    95: "animated_transform.rs",
    96: "easing_functions.rs",
    97: "eased_motion.rs",
    98: "color_animation.rs",
    99: "animation_events.rs",
    100: "animation_graph.rs",
    101: "animation_masks.rs",
    102: "animated_mesh.rs",
    103: "animated_mesh_control.rs",
    104: "animated_mesh_events.rs",
    105: "morph_targets.rs",
    106: "custom_skinned_mesh.rs",
    107: "animated_ui.rs",
}


def build_line(seq, cat, intent_lines, knowledge_items, example_items):
    """Build a catalog table line from DATA tuple."""
    intent_str = "<br>".join(intent_lines)
    # Join knowledge items with semicolons, removing trailing semicolons from items
    knowledge_parts = [k.rstrip("；。") for k in knowledge_items]
    example_parts = [e.rstrip("。；") for e in example_items]
    knowledge_str = (
        "知：<br>"
        + "；<br>".join(knowledge_parts)
        + "。<br>例：<br>"
        + "；<br>".join(example_parts)
        + "。"
    )
    fname = FNAME_MAP.get(seq, "unknown.rs")
    return f"| {seq} | {cat} | `{fname}` | {intent_str} | {knowledge_str} |"


def main():
    with open(CATALOG, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")

    # Build a map: seq_num -> entry data
    data_map = {}
    for seq, cat, intent, knowledge, examples in DATA:
        data_map[seq] = (cat, intent, knowledge, examples)

    new_lines = []
    replaced = 0

    for line in lines:
        m = re.match(r"\|\s*(\d+)\s*\|", line)
        if m:
            seq = int(m.group(1))
            if seq in data_map:
                cat, intent, knowledge, examples = data_map[seq]
                new_lines.append(build_line(seq, cat, intent, knowledge, examples))
                replaced += 1
                continue
        new_lines.append(line)

    with open(CATALOG, "w", encoding="utf-8") as f:
        f.write("\n".join(new_lines))

    print(f"Replaced {replaced} entries (expected {len(DATA)})")
    assert replaced == len(DATA), f"Expected {len(DATA)} replacements, got {replaced}"


if __name__ == "__main__":
    main()
