#!/usr/bin/env python3
"""Replace catalog entries 152, 158, 260, 282-289, 290-298, 299-315."""

import re

CATALOG = "/Users/lf380/Code/Bevy/a1/bevy_examples_catalog.md"

# (seq, category, intent_lines, knowledge, examples) — each field is a list of lines
DATA = [
    (
        152,
        "动态组件",
        [
            "**意图**：运行时动态创建组件和实体，通过 unsafe API 操作 ComponentDescriptor 和 OwningPtr；⭐⭐⭐",
            "- **ComponentDescriptor 动态注册**:",
            "  - ComponentDescriptor::new_with_layout(name, StorageType::Table, layout, None, true, ComponentCloneBehavior::Default, None) 动态创建组件描述符；",
            "  - Layout::array::<u64>(size) 按 u64 数组大小分配内存布局——⚠️ unsafe 代码，必须保证 Layout 和数据布局匹配；",
            "  - world.register_component_with_descriptor() 将动态组件注册到 World，返回 ComponentId（运行时标识符）；",
            "- **entity.insert_by_ids() 批量插入**:",
            "  - entity.insert_by_ids(&component_ids, owning_ptrs) 按 ComponentId 批量插入数据——⚠️ 指针必须指向有效内存，生命周期由调用方保证；",
            "  - OwningPtr::new(non_null) 从 NonNull 裸指针包装为 owned 指针——数据按组件描述的 Layout 布局存储；",
            "  - 🔧 to_owning_ptrs() 辅助函数将 Vec<Vec<u64>> 转换为 Vec<OwningPtr>，共享生命周期防止提前释放；",
            "- **QueryBuilder 动态查询**:",
            "  - QueryBuilder::<FilteredEntityMut>::new(&mut world) 构建运行时动态查询——⚠️ 静态查询在编译期确定，QueryBuilder 是唯一运行时方式；",
            "  - builder.ref_id(id) / builder.mut_id(id) 按 ComponentId 添加读/写访问；",
            "  - builder.with_id(id) / builder.optional(|b| ...) / builder.or(|b| ...) 组合过滤条件；",
            "- **get_by_id / get_mut_by_id**:",
            "  - filtered_entity.get_by_id(id) 按 ComponentId 读取组件数据（返回 OwnedPtr）；",
            "  - ⚠️ 不可变组件调用 get_mut_by_id 会返回 Err——运行时不可变保证；",
            "  - 🔧 与 immutable_components.rs(135) 配合展示动态不可变组件的完整生命周期；",
            "- **交互式 CLI 模式**:",
            "  - stdin 逐行读取命令，HashMap<String, ComponentId> 维护名称到 ID 的映射；",
            "  - 🔧 comp/spawn/query 三种命令分别对应创建组件、生成实体、查询实体三种操作；",
        ],
        [
            "知：",
            "- ComponentDescriptor::new_with_layout() 动态组件注册；",
            "- insert_by_ids() / get_by_id() 按 ComponentId 操作；",
            "- QueryBuilder 动态查询构建。",
        ],
        [
            "例：",
            "- ecs/immutable_components.rs(135)；",
            "- ecs/ecs_guide.rs(124)。",
        ],
    ),
    (
        158,
        "资产管理",
        [
            "**意图**：演示多种加载资产的方式——AssetServer::load、load_with_settings、load_folder 和直接添加到 Assets<T>；⭐⭐",
            "- **AssetServer::load 异步加载**:",
            "  - asset_server.load(path) 异步加载资产文件，返回 Handle<T>——⚠️ 路径相对于 assets/ 目录；",
            "  - GltfAssetLabel::Primitive{mesh:0,primitive:0}.from_asset(path) 从 glTF 加载特定 Mesh Primitive；",
            "  - ⚠️ 资产异步加载，首次调用 meshes.get() 时可能还未加载完成——返回 None；",
            "- **load_folder 批量加载**:",
            "  - asset_server.load_folder(path) 加载整个文件夹——返回 Handle<LoadedFolder>；",
            "  - 🔧 LoadedFolder 持有文件夹内所有资产的句柄，等待 AssetEvent::LoadedWithDependencies 确认全部加载完成；",
            "  - ⚠️ 存储返回的 Handle 以保持资产存活——Drop 后资产可能被卸载；",
            "- **已加载文件夹中取特定资产**:",
            "  - 再次 load 同一路径不会重复加载——返回已缓存的 Handle；",
            "  - 🔧 比 LoadedFolder 加载后查找句柄更简洁直接；",
            "- **直接添加到 Assets<T>**:",
            "  - materials.add(StandardMaterial{...}) 直接构造并添加材质——不经过文件加载；",
            "  - 🔧 适用于程序化生成的材质/网格等不需要文件的资产；",
            "- **3D 场景搭建**:",
            "  - Mesh3d + MeshMaterial3d + Transform 三件套渲染实体；",
            "  - PointLight + Camera3d 标准 3D 场景模板；",
        ],
        [
            "知：",
            "- AssetServer::load/load_folder 异步加载；",
            "- LoadedFolder 管理加载组；",
            "- Assets<T> 直接添加。",
        ],
        [
            "例：",
            "- 2D/sprite.rs(2)；",
            "- 3D/3d_scene.rs(32)。",
        ],
    ),
    (
        260,
        "UI纹理切片",
        [
            "**意图**：使用 TextureSlicer 实现 UI 九宫格切片按钮——按钮缩放时边角保持不变形；⭐⭐",
            "- **TextureSlicer 配置**:",
            "  - TextureSlicer { border: BorderRect::all(22.0) } 定义四边切割线为 22 像素；",
            "  - center_scale_mode: SliceScaleMode::Stretch 中心区域拉伸填充；",
            "  - sides_scale_mode: SliceScaleMode::Stretch 四边单向拉伸；",
            "  - max_corner_scale: 1.0 限制角的最大缩放比例——⚠️ 防止角被过度拉伸变形；",
            "- **NodeImageMode::Sliced**:",
            "  - ImageNode { image_mode: NodeImageMode::Sliced(slicer.clone()) } 将纹理以九宫格模式渲染；",
            "  - ⚠️ 切片纹理边角不失真，中心和四边按按钮尺寸拉伸——UI 面板/按钮必备技术；",
            "  - 🔧 slicer 可 clone 复用——多个按钮共享同一份切片配置；",
            "- **按钮交互系统**:",
            "  - Query<(&Interaction, &Children, &mut ImageNode), (Changed<Interaction>, With<Button>)> 过滤交互变化；",
            "  - Interaction::Pressed/Hovered/None 三种状态切换文本和颜色；",
            "  - 🔧 Changed<Interaction> 仅在状态变化时触发——避免每帧重复查询；",
            "- **多种尺寸测试**:",
            "  - [[150.0, 150.0], [300.0, 150.0], [150.0, 300.0]] 三种不同宽高比测试切片效果；",
            "  - 🔧 九宫格切片在任意尺寸下都能保持边角比例——核心优势；",
            "- **布局与字体**:",
            "  - Node { align_items: AlignItems::Center, justify_content: JustifyContent::Center } 居中文本；",
            "  - TextFont { font_size: 33.0 } + TextColor 控制文本样式；",
        ],
        [
            "知：",
            "- TextureSlicer 九宫格切片配置；",
            "- NodeImageMode::Sliced 切片模式；",
            "- Interaction 按钮交互状态。",
        ],
        [
            "例：",
            "- ui/button.rs(232)；",
            "- 2D/sprite_slice.rs(8)。",
        ],
    ),
    (
        282,
        "反射",
        [
            "**意图**：泛型 Rust 类型的反射——每个泛型单态化实例需要单独注册；⭐⭐",
            "- **泛型类型注册**:",
            "  - .register_type::<MyType<u32>>() 手动注册泛型实例——⚠️ MyType<String> 未注册则不会出现在 TypeRegistry 中；",
            "  - #[derive(Reflect)] 宏自动为泛型参数 T 添加 Reflect + GetTypeRegistration 约束；",
            "  - 🔧 每个具体的泛型实例（如 MyType<u32>、MyType<f64>）都必须单独注册；",
            "- **TypeId 查询**:",
            "  - type_registry.get(TypeId::of::<MyType<u32>>()) 按 TypeId 查询已注册的类型；",
            "  - registration.type_info().type_path() 获取类型的完整路径字符串；",
            "  - ⚠️ TypeId::of::<MyType<String>>().get() 返回 None——未注册的泛型实例不存在；",
            "- **实际应用场景**:",
            "  - 🧩 数据驱动系统中，不同类型实体需要注册不同泛型组件——如 Health<i32> vs Health<f32>；",
            "  - 🔧 编译期无法枚举所有泛型实例——需要在 Plugin::build() 中逐一注册；",
        ],
        [
            "知：",
            "- register_type::<T>() 泛型实例注册；",
            "- TypeId 泛型类型查询。",
        ],
        [
            "例：",
            "- reflection/reflection.rs(281)。",
        ],
    ),
    (
        283,
        "反射",
        [
            "**意图**：在反射类型上注册和访问自定义属性——通过 #[reflect(@...)] 语法附加元数据；⭐⭐",
            "- **字段级自定义属性**:",
            "  - #[reflect(@RangeInclusive::<f32>::new(0.0, 1.0))] 为字段注册范围约束；",
            "  - #[reflect(@0.0..=1.0_f32)] 简写语法——等价于上面的 RangeInclusive 写法；",
            "  - ⚠️ 同类型属性会覆盖：两个同类型 @attr 后者覆盖前者——不是追加；",
            "- **类型级自定义属性**:",
            '  - #[reflect(@Required, @Tooltip::new("An ID is required!"))] 为类型本身注册属性；',
            "  - TypeInfo::TupleStruct/Enum/Struct 上均可挂载属性——attribute 附着在 type_info 或 variant 上；",
            "- **运行时访问**:",
            "  - field.get_attribute::<RangeInclusive<f32>>() 按类型获取属性值——返回 Option<&T>；",
            "  - type_info.has_attribute::<Required>() 检查属性是否存在（不关心值）；",
            "  - type_info.get_attribute_by_id(TypeId::of::<Tooltip>()) 动态类型获取属性——返回 &dyn Reflect；",
            "- **枚举变体属性**:",
            "  - #[reflect(@true)] / #[reflect(@false)] 可挂在 enum variant 上；",
            "  - 🔧 变体属性适合存储编辑器元数据/校验规则/配置提示等；",
            "- **注意事项**:",
            "  - 🔧 属性值必须实现 Reflect——自定义类型需 #[derive(Reflect)]；",
            "  - ⚠️ 属性基于 TypeId 去重——两个 Tooltip 实例只保留最后一个；",
        ],
        [
            "知：",
            "- #[reflect(@...)] 属性注册语法；",
            "- get_attribute::<T>() 运行时获取；",
            "- has_attribute::<T>() 存在性检查。",
        ],
        [
            "例：",
            "- reflection/reflection.rs(281)。",
        ],
    ),
    (
        284,
        "反射",
        [
            "**意图**：通过反射动态调用 Rust 函数——DynamicFunction 在运行时检查参数类型并执行；⭐⭐⭐",
            "- **IntoFunction 转换**:",
            "  - add.into_function() 将普通函数转为 DynamicFunction——运行时检查参数类型；",
            "  - 闭包捕获不可变引用时也可转为 DynamicFunction——如 clamp 闭包；",
            "  - 🔧 DynamicFunction 不接受编译时参数信息——完全运行时类型检查；",
            "- **ArgList 参数构建**:",
            "  - ArgList::new().with_owned(2_i32).with_owned(2_i32) 构建参数列表；",
            "  - .with_owned() 拥有所有权，.with_ref() 不可变借用，.with_mut() 可变借用；",
            "  - ⚠️ 参数顺序和类型必须匹配函数签名——运行时类型不匹配会返回 Err；",
            "- **Return 返回值**:",
            "  - function.call(args) 返回 Result<Return, FunctionResult>；",
            "  - return_value.unwrap_owned() 取出拥有所有权的返回值——Box<dyn PartialReflect>；",
            "  - value.try_take::<i32>() 从反射值中取出具体类型——失败返回 Err；",
            "- **DynamicFunctionMut 可变闭包**:",
            "  - increment.into_function_mut() 捕获可变环境的闭包——⚠️ 必须 call_once() 或 drop() 后才能再次访问环境变量；",
            "  - 🔧 DynamicFunctionMut 持有 &mut 环境借用——与普通 Rust 借用规则一致；",
            "- **函数重载(with_overload)**:",
            "  - stringify::<i32>.into_function().with_overload(stringify::<f32>) 同一 DynamicFunction 表示多个函数；",
            "  - 🔧 按参数类型自动选择匹配的重载——支持变长参数（0/1/2/3 参数）；",
            "- **方法反射**:",
            "  - Data::set_value.into_function() 反射方法——self 作为第一个参数；",
            "  - ArgList::new().with_mut(&mut data) 传入可变 self 引用；",
            "  - 🔧 仅 &self 和 &mut self 方法支持——返回值生命周期绑定第一个参数；",
            "- **手动创建 DynamicFunction**:",
            "  - DynamicFunction::new(closure, SignatureInfo::named(...).with_arg::<T>(name).with_return::<R>()) 手动构建；",
            "  - 🔧 适用于返回值生命周期不绑定第一个参数的函数——如 get_or_insert；",
        ],
        [
            "知：",
            "- DynamicFunction / DynamicFunctionMut 反射函数；",
            "- IntoFunction / IntoFunctionMut trait；",
            "- ArgList 参数构建与 Return 返回值。",
        ],
        [
            "例：",
            "- reflection/reflection.rs(281)。",
        ],
    ),
    (
        285,
        "反射",
        [
            "**意图**：动态类型（DynamicStruct/Enum/Array/Map/List/Set/Tuple）的创建、apply 和反序列化；⭐⭐⭐",
            "- **Concrete → Dynamic 转换**:",
            "  - reflected.to_dynamic() 将具体类型转为 DynamicStruct——保留字段和结构信息；",
            "  - ⚠️ Dynamic 类型不能直接 as_reflect()——底层类型是 DynamicStruct 而非原始类型；",
            "  - 🔧 Dynamic 类型是反射反序列化的基础——反序列器无法预知具体类型；",
            "- **Dynamic → Concrete 转换**:",
            "  - 方法 1：value.apply(deserialized.as_ref()) 将动态值应用到具体实例——需先构造默认值；",
            "  - 方法 2：Player::from_reflect(deserialized.as_ref()) FromReflect trait 直接转换；",
            "  - 🔧 不知道具体类型时用 ReflectDefault::default() 构造 + apply——运行时多态；",
            "- **represents 与 represents**:",
            "  - deserialized.represents::<Player>() 检查动态值是否代表 Player 类型；",
            "  - ⚠️ DynamicStruct.represents::<Player>() 为 true，但底层类型是 DynamicStruct——不能直接转换；",
            "- **手动构造 Dynamic 类型**:",
            "  - DynamicList::from_iter([1u32, 2u32, 3u32]) 手动构建动态列表——无需编译时类型；",
            "  - my_dynamic_list.set_represented_type(Some(<Vec<u32>>::type_info())) 配置代理类型——represents 返回 true；",
            "- **全部动态类型参考**:",
            "  - DynamicTuple / DynamicArray / DynamicList / DynamicSet / DynamicMap / DynamicStruct / DynamicTupleStruct / DynamicEnum；",
            "  - 每种类型支持 insert/remove/contains/apply 操作——与具体类型 API 对应；",
            '  - 🔧 DynamicEnum::new("Variant", DynamicVariant::Tuple(values)) 构造枚举变体——支持 Unit/Tuple/Struct 三种变体；',
        ],
        [
            "知：",
            "- DynamicStruct/Enum/Array/Map 等动态类型；",
            "- apply() 与 FromReflect 类型转换；",
            "- represents() 代理类型检查。",
        ],
        [
            "例：",
            "- reflection/reflection.rs(281)。",
        ],
    ),
    (
        286,
        "反射",
        [
            "**意图**：反射序列化/反序列化——无需 serde derive，仅需 #[derive(Reflect)] 即可序列化；⭐⭐",
            "- **ReflectSerializer 序列化**:",
            "  - ReflectSerializer::new(&value, &type_registry) 将 Reflect 值序列化为 serde 格式；",
            "  - serde_json::to_string(&serializer) 转为 JSON 字符串——⚠️ 类型必须在 TypeRegistry 中注册；",
            "  - 🔧 derive(Reflect) 自动注册 SerializationData——无需额外 derive serde 的 Serialize；",
            "- **ReflectDeserializer 反序列化**:",
            "  - ReflectDeserializer::new(&type_registry) 创建反序列化器；",
            "  - deserializer.deserialize(value) 从 serde_json::Value 反射还原——返回 Box<dyn Reflect>；",
            '  - ⚠️ JSON 键必须是完整类型路径（如 "serialization::Player"）——TypeRegistry 据此查找类型；',
            "- **TypedReflectDeserializer 已知类型**:",
            "  - 当类型已知时可用 TypedReflectDeserializer——直接指定 TypeRegistration；",
            "  - 🔧 比 ReflectDeserializer 更高效——跳过类型查找步骤；",
            "- **insert_reflect 模式**:",
            "  - 反序列化后可直接 commands.insert_reflect(reflect_value) 插入为组件；",
            "  - 🔧 这是配置热重载/存档加载的标准模式——反序列化 → 反射插入；",
            "- **注意事项**:",
            "  - ⚠️ 反射序列化依赖 TypePath 识别类型——路径必须完全匹配；",
            "  - 🔧 枚举/Option/Vec 等复合类型自动递归序列化——无需手动处理嵌套结构；",
        ],
        [
            "知：",
            "- ReflectSerializer / ReflectDeserializer 反射序列化；",
            "- derive(Reflect) 自动注册 SerializationData。",
        ],
        [
            "例：",
            "- reflection/reflection.rs(281)。",
        ],
    ),
    (
        287,
        "反射",
        [
            "**意图**：TypeData 的创建和使用——将 trait 方法挂载到反射类型上，实现运行时多态调用；⭐⭐⭐",
            "- **TypeData 概念**:",
            "  - TypeData 是与类型关联的元数据——通过 TypeRegistry 在运行时查询和调用；",
            "  - 🔧 TypeData 可存储函数指针到 trait 方法——实现 dyn Reflect → dyn Trait 的转换；",
            "- **自定义 ReflectDamageable**:",
            "  - struct ReflectDamageable { damage: fn(&mut dyn Reflect, Box<dyn Reflect>) } 存储 trait 方法指针；",
            "  - impl FromType<T> for ReflectDamageable 为所有实现 Damageable 的类型自动生成 TypeData；",
            "  - 🔧 fn 指针接收 dyn Reflect 参数——运行时 downcast 到具体类型后调用；",
            "- **register_type_data 注册**:",
            "  - registry.register_type_data::<Zombie, ReflectDamageable>() 手动注册 TypeData；",
            "  - #[reflect(Damageable)] 属性自动注册——编译时自动查找 ReflectDamageable 类型；",
            "  - ⚠️ 类型名必须以 Reflect 为前缀——derive(Reflect) 宏自动查找该约定名称；",
            "- **#[reflect_trait] 宏**:",
            "  - #[reflect_trait] trait Health { fn health(&self) -> u32; } 自动生成 ReflectHealth TypeData；",
            "  - reflect_health.get(value.as_reflect()) 将 &dyn Reflect 转为 &dyn Health——⚠️ object-safe trait；",
            "  - 🔧 get/get_mut/get_boxed 三种方法覆盖不可变/可变/拥有所有权三种借用场景；",
            "- **Bevy 内置 TypeData**:",
            "  - ReflectDefault / ReflectFromWorld / ReflectComponent / ReflectResource / ReflectSerialize / ReflectDeserialize；",
            "  - 🔧 ReflectFromPtr 和 ReflectFromReflect 由 derive(Reflect) 自动注册；",
        ],
        [
            "知：",
            "- TypeData 自定义与 FromType blanket impl；",
            "- register_type_data 注册；",
            "- #[reflect_trait] 自动生成 TypeData。",
        ],
        [
            "例：",
            "- reflection/reflection.rs(281)。",
        ],
    ),
    (
        288,
        "反射",
        [
            "**意图**：无 inventory 平台的静态自动注册反射类型——通过 load_type_registrations! 宏收集注册函数；⭐",
            "- **load_type_registrations! 宏**:",
            "  - load_type_registrations!() 在 main() 前调用——收集所有 #[derive(Reflect)] 类型的注册函数；",
            "  - ⚠️ 必须在 App::new() 前执行——宏生成的静态数组在编译时链接；",
            "  - 🔧 适用于不支持 inventory 的平台（如 WASM/某些嵌入式）——替代运行时自动发现；",
            "- **跨 crate 注册**:",
            "  - 被注册的类型必须定义在不同 crate 中——auto_register_static/src/lib.rs 中的 Struct 被 bin crate 注册；",
            "  - 🔧 同 crate 内的类型不保证自动注册——分离库和二进制是常见模式；",
            "- **私有类型支持**:",
            "  - private::very_private::PrivateStruct 虽然私有但仍被注册——derive(Reflect) 生成全局注册函数；",
            "  - ⚠️ 私有类型不暴露给外部——但 TypeRegistry 可通过 type_path 字符串查询；",
            "- **startup 验证**:",
            "  - reg.read().contains(TypeId::of::<Struct>()) 检查类型是否已注册；",
            '  - registry.get_with_short_type_path("PrivateStruct") 按短路径查找私有类型——验证注册成功；',
        ],
        [
            "知：",
            "- load_type_registrations!() 静态注册宏；",
            "- 跨 crate 反射注册模式。",
        ],
        [
            "例：",
            "- reflection/reflection.rs(281)。",
        ],
    ),
    (
        289,
        "反射",
        [
            "**意图**：静态自动注册反射类型的二进制入口——调用宏后转发到库的 main 函数；⭐",
            "- **入口结构**:",
            "  - load_type_registrations!() 必须在最前面——收集所有库 crate 的反射注册函数；",
            "  - use auto_register_static::main as lib_main 转发到库的主函数；",
            "  - 🔧 分离入口点确保宏的静态注册在 App 构建前完成；",
            "- **编译时注册链**:",
            "  - 宏展开 → 生成 inventory::collect! 调用 → 链接时收集所有注册函数；",
            "  - ⚠️ 任何遗漏的 #[derive(Reflect)] 类型不会出现在 TypeRegistry 中——需验证；",
            "  - 🔧 与 auto_register_static/src/lib.rs 配合——lib 定义类型，bin 触发注册；",
        ],
        [
            "知：",
            "- load_type_registrations!() 调用时机；",
            "- 库/二进制分离注册模式。",
        ],
        [
            "例：",
            "- reflection/auto_register_static/src/lib.rs(288)。",
        ],
    ),
    (
        290,
        "glTF资产",
        [
            "**意图**：加载并渲染 glTF 文件作为场景——EnvironmentMapLight 环境光 + DirectionalLight 方向光 + SceneRoot；⭐⭐⭐",
            "- **SceneRoot 加载**:",
            "  - SceneRoot(asset_server.load(GltfAssetLabel::Scene(0).from_asset(path))) 加载 glTF 场景——⚠️ GltfAssetLabel::Scene(0) 指定第 0 个场景；",
            "  - 🔧 一个 glTF 文件可包含多个场景——Scene(0) 通常是最小完整场景；",
            "- **EnvironmentMapLight 环境光**:",
            "  - diffuse_map + specular_map 加载预过滤环境贴图（.ktx2 格式）——提供间接光照；",
            "  - intensity: 250.0 控制环境光强度——⚠️ 值过低场景偏暗，过高过曝；",
            "  - 🔧 KTX2 格式比 PNG/JPG 高效——支持 GPU 直接解压和 mip 链；",
            "- **CascadeShadowConfigBuilder 级联阴影**:",
            "  - num_cascades: 1 单级联——小场景足够，减少渲染开销；",
            "  - maximum_distance: 1.6 阴影最大距离——⚠️ 超出范围无阴影；",
            "  - 🔧 DirectionalLightShadowMap { size: 4096 } 增大阴影贴图分辨率——提升阴影质量；",
            "- **animate_light_direction**:",
            "  - Quat::from_euler(EulerRot::ZYX, 0.0, time * PI / 5.0, -FRAC_PI_4) 动态旋转光源；",
            "  - 🔧 光源动画展示阴影在不同角度的表现——常用于场景预览；",
        ],
        [
            "知：",
            "- SceneRoot glTF 场景加载；",
            "- EnvironmentMapLight 环境光照；",
            "- CascadeShadowConfig 级联阴影。",
        ],
        [
            "例：",
            "- 3D/3d_scene.rs(32)。",
        ],
    ),
    (
        291,
        "glTF资产",
        [
            "**意图**：更新已加载的 glTF 场景——通过 Children 遍历子实体并修改 Transform；⭐⭐",
            "- **SceneRoot 实体挂载**:",
            "  - SceneRoot(handle) 作为组件直接 spawn——glTF 场景自动展开为子实体层级；",
            "  - 🔧 可附加自定义组件（如 MovedScene）标记目标场景——后续按组件查询；",
            "- **iter_descendants 深度遍历**:",
            "  - children.iter_descendants(entity) 递归遍历实体的所有后代——⚠️ 包含所有层级的子实体；",
            "  - transforms.get_mut(entity) 获取子实体的 Transform 并修改；",
            "  - 🔧 场景内部的 Mesh/Skeleton 等子实体也会被遍历——需谨慎过滤；",
            "- **MovedScene 标记组件**:",
            "  - #[derive(Component)] struct MovedScene 零大小标记组件——用于区分场景实例；",
            "  - Query<Entity, With<MovedScene>> 仅查询带标记的场景根实体；",
            "  - 🧩 标记组件模式是管理多个同一 glTF 实例的标准做法；",
            "- **动画效果**:",
            "  - sin/cos 驱动子实体位移——每个子实体 offset 递增产生波浪效果；",
            "  - 🔧 场景内所有子实体独立运动——展示层级遍历的实际效果；",
        ],
        [
            "知：",
            "- SceneRoot 场景实例化；",
            "- Children::iter_descendants 深度遍历；",
            "- 标记组件区分实例。",
        ],
        [
            "例：",
            "- gltf/load_gltf.rs(290)。",
        ],
    ),
    (
        292,
        "glTF资产",
        [
            "**意图**：在 glTF 场景生成后动态修改材质——通过 GltfMaterialName 匹配特定材质并替换颜色；⭐⭐⭐",
            "- **SceneInstanceReady 观察者**:",
            "  - .observe(change_material) 在场景加载完成后触发——⚠️ 场景实体在加载时才创建；",
            "  - On<SceneInstanceReady> 事件包含 entity 字段——标识哪个 SceneRoot 触发了完成；",
            "  - 🔧 观察者模式比轮询 Query 更高效——仅在场景就绪时执行一次；",
            "- **GltfMaterialName 材质匹配**:",
            "  - Query<(&MeshMaterial3d<StandardMaterial>, &GltfMaterialName)> 获取材质句柄和名称；",
            '  - material_name.0.as_str() == "LeatherPartsMat" 按名称匹配——⚠️ 名称来自 glTF 文件的材质名；',
            "  - 🔧 GltfMaterialName 是 glTF 加载器自动附加的组件——包含原始材质字符串名；",
            "- **材质克隆与覆盖**:",
            "  - material.clone() 克隆 StandardMaterial——⚠️ 多个相同材质不共享 Handle 会增加显存开销；",
            "  - new_material.base_color = color_override.0 修改基础颜色——仅改颜色不影响其他 PBR 属性；",
            "  - commands.entity(descendant).insert(MeshMaterial3d(new_handle)) 替换材质组件——立即生效；",
            "- **ColorOverride 组件**:",
            "  - #[derive(Component)] struct ColorOverride(Color) 标记需要调色的场景实例；",
            "  - 🔧 无 ColorOverride 的场景保持原始材质——选择性修改模式；",
            "- **注意事项**:",
            "  - ⚠️ 音频插件禁用——.disable::<AudioPlugin>() 避免场景中嵌入音频的干扰；",
            "  - 🔧 iter_descendants 递归所有子实体——需逐个检查 GltfMaterialName 才能精准修改；",
        ],
        [
            "知：",
            "- SceneInstanceReady 观察者事件；",
            "- GltfMaterialName 材质名称匹配；",
            "- MeshMaterial3d 材质替换。",
        ],
        [
            "例：",
            "- gltf/load_gltf.rs(290)。",
        ],
    ),
    (
        293,
        "glTF资产",
        [
            "**意图**：加载 glTF 并列出所有 extras 数据——GltfSceneExtras/GltfExtras/GltfMeshExtras/GltfMaterialExtras 四种类型；⭐⭐",
            "- **四种 GltfExtras 组件**:",
            "  - GltfSceneExtras：场景级别 extras——附加在 SceneRoot 实体上；",
            "  - GltfExtras：primitive 级别 extras——附加在网格实体上；",
            "  - GltfMeshExtras：网格级别 extras——附加在 Mesh3d 实体上；",
            "  - GltfMaterialExtras：材质级别 extras——附加在 MeshMaterial3d 实体上；",
            "  - 🔧 extras 是 glTF 规范中用户自定义的 JSON 数据——可携带任意元信息；",
            "- **Query 同时查询四种**:",
            "  - Query<(Entity, Option<&Name>, Option<&GltfSceneExtras>, Option<&GltfExtras>, Option<&GltfMeshExtras>, Option<&GltfMaterialExtras>)> 同时获取所有 extras；",
            "  - Option 确保即使没有 extras 的实体也能被查询到——⚠️ None 表示该实体无此类型 extras；",
            "- **ExampleDisplay 文本显示**:",
            "  - Single<&mut Text, With<ExampleDisplay>> 获取显示文本——确保只有一个显示实体；",
            "  - 🔧 将 extras 信息格式化为文本直接渲染在屏幕上——调试 glTF 元数据的便捷方式；",
            "- **实际应用**:",
            "  - 🧩 extras 可携带碰撞体参数/触发器区域/对话文本等游戏逻辑数据；",
            "  - 🔧 场景编辑器导出的自定义属性通过 extras 传递到 Bevy 运行时；",
        ],
        [
            "知：",
            "- GltfSceneExtras / GltfExtras / GltfMeshExtras / GltfMaterialExtras；",
            "- glTF extras 用户自定义数据。",
        ],
        [
            "例：",
            "- gltf/load_gltf.rs(290)。",
        ],
    ),
    (
        294,
        "glTF资产",
        [
            "**意图**：查询 glTF 场景中特定材质和顶点数据——按 GltfMaterialName 查找材质并修改颜色和顶点位置；⭐⭐⭐",
            "- **按材质名定位**:",
            '  - GltfMaterialName 组件包含 glTF 材质名称——name.0 == "Top" 匹配目标材质；',
            "  - MeshMaterial3d<StandardMaterial> 获取材质句柄——materials.get_mut() 修改材质属性；",
            "  - 🔧 Hsla 旋转色相实现颜色循环动画——hsla.rotate_hue(delta)；",
            "- **顶点位置修改**:",
            "  - meshes.get_mut(mesh_handle) 获取可变网格引用；",
            "  - mesh.attribute_mut(Mesh::ATTRIBUTE_POSITION) 获取顶点位置数组——Float32x3 格式；",
            "  - position[1] = 1.5 + 0.5 * sin(time) 修改 Y 坐标——实现顶点波浪动画；",
            "  - ⚠️ attribute_mut 修改会触发网格缓冲区重建——频繁修改影响性能；",
            "- **多 Primitive 查询**:",
            "  - 一个 glTF Mesh 可包含多个 Primitive——每个 Primitive 有独立的材质和顶点数据；",
            "  - 🔧 Query 同时匹配 MeshMaterial3d + Mesh3d + GltfMaterialName 三元组——精准定位特定 Primitive；",
            "- **注意事项**:",
            "  - ⚠️ 顶点数据修改是 CPU 侧操作——每帧修改会传输大量数据到 GPU；",
            "  - 🔧 仅在需要运行时变形时才修改顶点——静态网格不要触碰顶点属性；",
        ],
        [
            "知：",
            "- GltfMaterialName 材质名查询；",
            "- Mesh::ATTRIBUTE_POSITION 顶点修改；",
            "- 顶点变形动画模式。",
        ],
        [
            "例：",
            "- gltf/load_gltf.rs(290)。",
        ],
    ),
    (
        295,
        "glTF资产",
        [
            "**意图**：从 glTF 加载蒙皮网格（SkinnedMesh）并通过关节层级动画驱动骨骼；⭐⭐⭐",
            "- **SkinnedMesh 组件**:",
            "  - glTF 加载器自动创建 SkinnedMesh 组件——附加在网格实体上；",
            "  - ChildOf + Children 遍历关节层级——⚠️ 关节是网格的子实体层级结构；",
            "  - 🔧 SkinnedMesh 包含关节矩阵引用——Transform 修改后自动驱动网格变形；",
            "- **关节层级遍历**:",
            "  - child_of.parent() 获取网格节点实体——父级是 Mesh node（无 Mesh3d 组件）；",
            "  - parents.get(mesh_node_entity).unwrap() 获取 Children——第一个子实体是 SkinnedMesh，后续是关节；",
            "  - mesh_node_parent[1] 跳过 SkinnedMesh 实体取第一个关节——⚠️ 索引硬编码依赖 glTF 结构；",
            "- **关节动画**:",
            "  - Quat::from_rotation_z(FRAC_PI_2 * sin(time)) 正弦驱动关节旋转——简单摆动动画；",
            "  - 🔧 动画修改的是关节的 Transform——SkinnedMesh 自动根据关节矩阵变形网格顶点；",
            "- **GlobalAmbientLight**:",
            "  - brightness: 750.0 提供充足环境光——蒙皮网格通常需要均匀照明才能看清变形；",
            "  - 🔧 简单场景省略复杂光照——聚焦蒙皮变形效果；",
            "- **注意事项**:",
            "  - ⚠️ glTF 蒙皮模型的关节命名和层级由建模工具决定——不可假设特定结构；",
            "  - 🔧 生产环境应用 AnimationPlayer 替代手动关节动画——更灵活且支持多动画混合；",
        ],
        [
            "知：",
            "- SkinnedMesh 蒙皮网格组件；",
            "- glTF 关节层级结构；",
            "- 关节 Transform 驱动变形。",
        ],
        [
            "例：",
            "- animation/animated_mesh.rs(102)。",
        ],
    ),
    (
        296,
        "glTF资产",
        [
            "**意图**：2D 渲染 glTF Mesh 带自定义顶点属性（重心坐标）——Material2d + custom vertex attribute；⭐⭐⭐",
            "- **MeshVertexAttribute 自定义属性**:",
            '  - MeshVertexAttribute::new("Barycentric", 2137464976, VertexFormat::Float32x3) 定义重心坐标属性；',
            "  - 三个分量分别对应三角形三个角——值为 1.0 表示在该角，0.0 表示在对边；",
            "  - 🔧 重心坐标用于着色器中计算边距——实现三角形边框/线框效果；",
            "- **GltfPlugin 自定义属性映射**:",
            '  - .add_custom_vertex_attribute("_BARYCENTRIC", ATTRIBUTE_BARYCENTRIC) 将 glTF 属性名映射到 Bevy 属性；',
            "  - ⚠️ glTF 文件中属性名带双下划线——Bevy 内部会去掉一个进行比较；",
            "  - 🔧 映射后自定义属性可直接在着色器中通过 @location 访问；",
            "- **Material2d 自定义材质**:",
            "  - struct CustomMaterial {} + AsBindGroup + Material2d trait——2D 自定义材质模板；",
            "  - specialize() 方法手动指定顶点布局——⚠️ 必须包含 POSITION + COLOR + BARYCENTRIC 三个属性；",
            "  - 🔧 vertex_layout = layout.0.get_layout(&[...]) 构建管线布局——着色器输入必须匹配；",
            "- **Mesh2d 渲染**:",
            "  - Mesh2d(mesh) + MeshMaterial2d(material) + Transform::from_scale(150.0 * Vec3::ONE) 2D 渲染；",
            "  - 🔧 从 glTF 加载的 Mesh 可直接用于 2D 渲染——Mesh 类型在 2D/3D 间通用；",
        ],
        [
            "知：",
            "- MeshVertexAttribute 自定义顶点属性；",
            "- GltfPlugin::add_custom_vertex_attribute 属性映射；",
            "- Material2d 2D 自定义材质。",
        ],
        [
            "例：",
            "- gltf/load_gltf.rs(290)；",
            "- shader/shader_material_2d.rs(300)。",
        ],
    ),
    (
        297,
        "glTF资产",
        [
            "**意图**：使用 GltfExtensionHandler 在 glTF 加载过程中拦截并处理动画——创建 AnimationGraph 并播放；⭐⭐⭐",
            "- **GltfExtensionHandler trait**:",
            "  - impl GltfExtensionHandler for MyHandler 拦截 glTF 加载过程的各个阶段；",
            '  - on_animation() 按名称筛选动画——本例筛选 "Walk" 动画片段；',
            "  - on_animations_collected() 获取所有动画根节点索引——用于后续挂载组件；",
            "- **加载阶段回调**:",
            "  - on_gltf_node() 在每个节点加载时触发——记录动画根实体 ID；",
            "  - on_scene_completed() 在场景加载完成时触发——创建 AnimationGraph 并挂载组件；",
            "  - 🔧 load_context.add_labeled_asset() 在加载过程中创建新资产——动画图与场景同生命周期；",
            "- **AnimationGraph 构建**:",
            "  - AnimationGraph::from_clip(clip_handle) 从单个剪辑创建动画图——返回 (graph, node_index)；",
            "  - AnimationToPlay { graph_handle, index } 组件存储图句柄和节点索引；",
            "  - 🔧 AnimationGraph 控制动画混合/过渡/权重——比直接播放更灵活；",
            "- **SceneInstanceReady 观察者播放**:",
            "  - .observe(play_animation_when_ready) 场景就绪后播放动画；",
            "  - player.play(index).repeat() 播放并循环——⚠️ 必须在 AnimationPlayer 存在时才能播放；",
            "  - commands.entity(child).insert(AnimationGraphHandle(graph_handle)) 连接动画图到播放器；",
            "- **Plugin 注册**:",
            "  - GltfExtensionHandlers::0.write_blocking().push(Box::new(handler)) 注册处理器——⚠️ write_blocking() 阻塞写入；",
        ],
        [
            "知：",
            "- GltfExtensionHandler 拦截加载过程；",
            "- AnimationGraph 动画图构建；",
            "- on_animation / on_scene_completed 回调。",
        ],
        [
            "例：",
            "- animation/animation_graph.rs(100)；",
            "- gltf/load_gltf.rs(290)。",
        ],
    ),
    (
        298,
        "glTF资产",
        [
            "**意图**：使用 GltfExtensionHandler 将 glTF 3D Mesh 自动转换为 2D Mesh——运行时替换组件；⭐⭐",
            "- **GltfExtensionHandlerToMesh2d**:",
            "  - on_spawn_mesh_and_material() 在网格和材质生成时拦截——⚠️ 替换发生在加载过程中而非加载后；",
            "  - entity.get::<Mesh3d>() 检查是否存在 3D 网格——仅处理 Mesh3d 实体；",
            "  - entity.remove::<(Mesh3d, MeshMaterial3d<StandardMaterial>)>() 移除 3D 组件；",
            "  - entity.insert((Mesh2d(mesh_handle), MeshMaterial2d(material_handle))) 插入 2D 组件；",
            "- **材质替换**:",
            '  - load_context.add_labeled_asset("AColorMaterial", CustomMaterial{}) 创建 2D 材质——在加载上下文中创建；',
            "  - 🔧 mesh_handle 直接复用——Mesh 资产在 2D/3D 间共享，无需重新加载；",
            "- **GltfToMesh2dPlugin**:",
            "  - impl Plugin 将处理器注册到 GltfExtensionHandlers——write_blocking() 阻塞写入确保顺序；",
            "  - 🔧 Material2dPlugin::<CustomMaterial>::default() 注册 2D 材质插件——必需否则材质不渲染；",
            "- **ATTRIBUTE_BARYCENTRIC 复用**:",
            "  - 与 custom_gltf_vertex_attribute.rs(296) 相同的重心坐标属性——用于边框着色；",
            "  - 🔧 同一 glTF 文件可被两个不同示例以不同方式渲染——展示扩展处理器的灵活性；",
        ],
        [
            "知：",
            "- GltfExtensionHandler 拦截网格/材质生成；",
            "- Mesh3d → Mesh2d 运行时替换；",
            "- load_context.add_labeled_asset 创建资产。",
        ],
        [
            "例：",
            "- gltf/load_gltf.rs(290)。",
        ],
    ),
    (
        299,
        "着色器",
        [
            "**意图**：基本自定义着色器和材质——AsBindGroup 桥接 Rust 结构体到 GPU uniform；⭐⭐⭐",
            "- **AsBindGroup 派生**:",
            "  - #[derive(Asset, TypePath, AsBindGroup)] 自动为 struct 生成 GPU 绑定组布局；",
            "  - #[uniform(0)] color: LinearRgba 标记为 uniform buffer binding 0——⚠️ binding 号必须在着色器中匹配；",
            "  - #[texture(1)] #[sampler(2)] 分别绑定纹理和采样器到 binding 1 和 2；",
            "  - 🔧 Option<Handle<Image>> 纹理可选——未设置时使用 FallbackImage；",
            "- **Material trait 实现**:",
            "  - impl Material for CustomMaterial 实现 Material trait——至少需指定 fragment_shader()；",
            "  - fn fragment_shader() -> ShaderRef 返回着色器文件路径——SHADER_ASSET_PATH.into()；",
            "  - fn alpha_mode(&self) -> AlphaMode 返回透明模式——Blend/Mask/Opaque 三选一；",
            "- **MaterialPlugin 注册**:",
            "  - MaterialPlugin::<CustomMaterial>::default() 注册自定义材质插件——⚠️ 必须在 DefaultPlugins 之后添加；",
            "  - MeshMaterial3d(materials.add(CustomMaterial{...})) 绑定材质到网格实体；",
            "  - 🔧 材质修改后自动重新绑定 GPU 绑定组——无需手动更新；",
            "- **场景搭建**:",
            "  - Mesh3d + MeshMaterial3d + Transform 三件套——标准 3D 网格渲染模式；",
            "  - Camera3d::default() + Transform::looking_at 相机定位；",
            "  - 🔧 最小自定义着色器示例——作为所有着色器示例的基础模板；",
        ],
        [
            "知：",
            "- AsBindGroup 派生宏与绑定组布局；",
            "- Material trait fragment_shader/alpha_mode；",
            "- MaterialPlugin 注册自定义材质。",
        ],
        [
            "例：",
            "- 3D/3d_shapes.rs(33)。",
        ],
    ),
    (
        300,
        "着色器",
        [
            "**意图**：2D 自定义着色器和材质——Material2d trait + AsBindGroup 用于 Mesh2d 渲染；⭐⭐",
            "- **Material2d trait**:",
            "  - impl Material2d for CustomMaterial 实现 2D 材质——与 Material trait 类似但用于 2D；",
            "  - fn alpha_mode(&self) -> AlphaMode2d 返回 2D 透明模式——Mask(0.5)/Blend/Opaque；",
            "  - 🔧 Material2dPlugin::<CustomMaterial>::default() 注册 2D 材质插件——⚠️ 不同于 MaterialPlugin；",
            "- **AsBindGroup 2D 绑定**:",
            "  - #[uniform(0)] color: LinearRgba uniform 绑定——与 3D 材质完全相同的属性语法；",
            "  - #[texture(1)] #[sampler(2)] 纹理和采样器绑定——binding 号独立于 3D 材质；",
            "  - 🔧 2D 材质和 3D 材质的 binding 布局互不影响——可同时使用；",
            "- **Mesh2d 渲染**:",
            "  - Mesh2d(meshes.add(Rectangle::default())) + MeshMaterial2d(material) 2D 网格；",
            "  - Transform::default().with_scale(Vec3::splat(128.)) 缩放到 128x128 像素；",
            "  - 🔧 Rectangle::default() 创建 1x1 单位矩形——用 scale 控制实际尺寸；",
            "- **与 3D 着色器的区别**:",
            "  - 2D 使用 Material2d/Mesh2d/MeshMaterial2d——⚠️ 不能混用 3D 的 Material/Mesh3d/MeshMaterial3d；",
            "  - 2D 着色器文件不同（custom_material_2d.wgsl）——顶点着色器输出 2D 坐标；",
        ],
        [
            "知：",
            "- Material2d 2D 材质 trait；",
            "- Mesh2d 2D 网格组件；",
            "- AlphaMode2d 2D 透明模式。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        301,
        "着色器",
        [
            "**意图**：使用 GLSL 着色语言编写材质——分离的 .vert 和 .frag 文件替代 WGSL；⭐⭐",
            "- **GLSL 着色器文件**:",
            '  - VERTEX_SHADER_ASSET_PATH = "shaders/custom_material.vert" 顶点着色器；',
            '  - FRAGMENT_SHADER_ASSET_PATH = "shaders/custom_material.frag" 片段着色器；',
            "  - ⚠️ GLSL 需要分别指定顶点和片段着色器——WGSL 可合并为单文件；",
            "- **Material 实现**:",
            "  - fn vertex_shader() -> ShaderRef 返回顶点着色器路径——⚠️ 使用 GLSL 时必须重写此方法；",
            "  - fn fragment_shader() -> ShaderRef 返回片段着色器路径；",
            "  - 🔧 默认 Material trait 使用内置 WGSL 顶点着色器——自定义顶点着色器时才需覆盖；",
            "- **AsBindGroup 绑定**:",
            "  - struct CustomMaterial 完全相同的 AsBindGroup 属性——uniform/texture/sampler 绑定方式不变；",
            "  - 🔧 Rust 侧结构体与 WGSL 示例完全一致——仅着色器文件格式不同；",
            "- **注意事项**:",
            "  - ⚠️ Bevy 内部使用 naga 将 GLSL 转换为 WGSL——性能略低于原生 WGSL；",
            "  - 🔧 GLSL 适合从 OpenGL/Vulkan 项目迁移——已有 GLSL 着色器可直接复用；",
        ],
        [
            "知：",
            "- GLSL .vert/.frag 着色器文件；",
            "- vertex_shader() 覆盖默认顶点着色器。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        302,
        "着色器",
        [
            "**意图**：使用 WESL 着色语言编写材质——支持模块化导入的着色器语言；⭐⭐",
            "- **WESL 着色器**:",
            '  - FRAGMENT_SHADER_ASSET_PATH = "shaders/custom_material.wesl" WESL 片段着色器；',
            "  - 🔧 WESL 支持 mod/import 模块化——可复用公共着色器代码（如 util.wesl）；",
            "- **CustomMaterialPlugin 加载工具着色器**:",
            '  - app.world_mut().resource_mut::<AssetServer>().load::<Shader>("shaders/util.wesl") 显式加载依赖；',
            "  - UtilityShader(Handle<Shader>) Resource 保持强引用——⚠️ 弱引用可能导致着色器被卸载；",
            "  - 🔧 WESL 的 import 依赖需要主着色器加载前就存在于 Assets 中；",
            "- **BindGroupData 着色器变体**:",
            "  - #[bind_group_data(CustomMaterialKey)] 标记需要 specialize 的属性；",
            "  - CustomMaterialKey { party_mode: bool } 控制着色器行为分支；",
            "  - 🔧 specialize() 方法根据 key 注入 ShaderDefVal——如 PARTY_MODE bool 宏；",
            "- **时间 uniform**:",
            "  - #[uniform(0)] time: Vec4 传递时间到着色器——⚠️ Vec4 对齐满足 WebGL2 的 16 字节要求；",
            "  - 🔧 party_mode 按空格键切换——展示运行时着色器变体切换；",
            "- **注意事项**:",
            "  - ⚠️ WESL 需要额外插件支持——Bevy 内置 naga_oil 处理 WESL 导入；",
            "  - 🔧 WESL 是 WGSL 的超集——有效 WGSL 也是有效 WESL；",
        ],
        [
            "知：",
            "- WESL 模块化着色器；",
            "- BindGroupData 着色器变体；",
            "- ShaderDefVal 条件编译。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        303,
        "着色器",
        [
            "**意图**：Bindless 纹理材质——多个材质共享绑定数组，减少 draw call 和绑定切换；⭐⭐⭐",
            "- **#[bindless(limit(4))]**:",
            "  - 结构级属性指定每组最多 4 个材质——Bevy 自动将材质分批到绑定组中；",
            "  - ⚠️ limit 值影响 GPU 绑定组大小——过高可能超出 GPU 限制（通常 16-64）；",
            "  - 🔧 Bindless 模式下多个材质共享一次绑定——大幅提升合批率；",
            "- **binding_array 绑定**:",
            "  - #[uniform(0, BindlessMaterialUniform, binding_array(10))] uniform 数据放入绑定数组——每组 10 个元素；",
            "  - #[texture(1)] #[sampler(2)] 纹理和采样器自动放入绑定数组——⚠️ Option Handle 表示可选纹理；",
            "  - 🔧 binding_array 在着色器中声明为 array<texture_2d<f32>>——按索引访问不同材质的纹理；",
            "- **ShaderType uniform 转换**:",
            "  - struct BindlessMaterialUniform { color: LinearRgba } GPU 端数据结构——Derive ShaderType；",
            "  - impl From<&BindlessMaterial> for BindlessMaterialUniform CPU→GPU 数据转换；",
            "  - 🔧 ShaderType 控制内存对齐——确保 GPU 读取正确的字节布局；",
            "- **多材质演示**:",
            "  - 蓝色纹理圆柱 + 红色纹理圆柱——不同材质共享同一 Mesh 和 Material 类型；",
            "  - 🔧 自动合批：相同 Mesh + 相同 Material 类型 = 一次 draw call 渲染所有实例；",
        ],
        [
            "知：",
            "- #[bindless] 绑定组分批；",
            "- binding_array 绑定数组；",
            "- ShaderType GPU 数据类型。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        304,
        "着色器",
        [
            "**意图**：屏幕空间纹理采样——使用视图无关 UV 坐标实现固定纹理映射效果；⭐⭐",
            "- **屏幕空间 UV**:",
            "  - 着色器中使用屏幕空间坐标（非模型 UV）采样纹理——纹理随视角变化产生视差效果；",
            "  - 🔧 屏幕空间采样适合水面反射/折射/全息投影等效果；",
            "- **CustomMaterial**:",
            "  - #[texture(0)] #[sampler(1)] texture: Handle<Image> 绑定纹理——标准 AsBindGroup 用法；",
            "  - Material::fragment_shader() 返回自定义着色器——着色器中计算屏幕空间 UV；",
            "  - 🔧 无额外 uniform——纯着色器端计算屏幕坐标；",
            "- **rotate_camera 动画**:",
            "  - Single<&mut Transform, With<MainCamera>> 获取相机变换——Single 确保唯一相机；",
            "  - transform.rotate_around(Vec3::ZERO, Quat::from_axis_angle(...)) 轨道旋转相机；",
            "  - transform.look_at(Vec3::ZERO, Vec3::Y) 始终朝向原点——展示不同视角下纹理采样变化；",
            "- **应用场景**:",
            "  - 🧩 配合 NormalPrepass 可实现屏幕空间环境光遮蔽（SSAO）；",
            "  - 🔧 纹理坐标基于片段屏幕位置——旋转相机时纹理固定在屏幕上而非模型上；",
        ],
        [
            "知：",
            "- 屏幕空间 UV 纹理采样；",
            "- rotate_around 轨道旋转。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        305,
        "着色器",
        [
            "**意图**：在着色器中使用动态数据（时间）——通过 globals binding 访问 Time 等全局数据；⭐⭐",
            "- **globals binding**:",
            "  - 着色器通过 mesh_view_bindings 导入获得 globals binding——包含 time/delta_time/frame_count 等；",
            "  - 🔧 globals 是 Bevy 着色器的全局常量绑定——无需额外 uniform 传递时间；",
            "- **CustomMaterial 空结构体**:",
            "  - struct CustomMaterial {} 无任何字段——纯着色器端动画，无需 Rust 传数据；",
            "  - 🔧 最简材质结构——仅需 AsBindGroup 派生和 fragment_shader() 实现；",
            "- **着色器动画**:",
            "  - 着色器内使用 time.elapsed_secs 驱动颜色/位置变化——GPU 端实时计算；",
            "  - 🔧 GPU 时间动画比 CPU 传递 uniform 更高效——无 CPU→GPU 数据传输开销；",
            "- **注意事项**:",
            "  - ⚠️ globals binding 在所有 Bevy 着色器中自动可用——不需要手动声明；",
            "  - 🔧 适合周期性动画（呼吸灯/波浪/旋转）——GPU 并行计算性能极佳；",
        ],
        [
            "知：",
            "- globals binding 全局数据；",
            "- 着色器端时间动画。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        306,
        "着色器",
        [
            "**意图**：使用 Shader Defs 选择性切换着色器代码——通过 specialize 注入条件编译宏；⭐⭐⭐",
            "- **BindGroupData 与 specialize**:",
            "  - #[bind_group_data(CustomMaterialKey)] 标记需要 specialize 的材质属性；",
            "  - CustomMaterialKey { is_red: bool } 控制着色器变体——⚠️ key 字段变化触发不同着色器变体；",
            '  - 🔧 specialize() 方法根据 key 注入 shader_defs——如 fragment.shader_defs.push("IS_RED".into())；',
            "- **着色器条件编译**:",
            "  - 着色器中 #ifdef IS_RED 控制代码分支——编译时选择不同代码路径；",
            "  - ⚠️ 每种 shader_def 组合产生独立的着色器变体——组合爆炸需谨慎控制；",
            '  - 🔧 ShaderDefVal::Bool("IS_RED", true) 注入 bool 宏——也可用 Int/Uint 类型；',
            "- **CustomMaterialKey 设计**:",
            "  - #[repr(C)] #[derive(Eq, PartialEq, Hash, Copy, Clone)] 快速比较和哈希；",
            "  - impl From<&CustomMaterial> for CustomMaterialKey 从材质数据提取 key——最小化特化维度；",
            "  - 🔧 key 应尽可能小——每个 unique key 产生独立的管线变体；",
            "- **多变体演示**:",
            "  - 蓝色立方体 is_red=false——使用原始颜色；",
            "  - 红色立方体 is_red=true——着色器强制覆盖为红色（忽略材质颜色）；",
            "  - 🔧 同一材质类型不同变体——展示 specialize 机制的实际效果；",
        ],
        [
            "知：",
            "- ShaderDefVal 条件编译宏；",
            "- specialize() 着色器变体注入；",
            "- BindGroupData 特化 key。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        307,
        "着色器",
        [
            "**意图**：预渲染 Pass——深度/法线/运动矢量纹理的生成和可视化；⭐⭐⭐",
            "- **Prepass 组件**:",
            "  - DepthPrepass / NormalPrepass / MotionVectorPrepass 三个组件控制预渲染输出；",
            "  - ⚠️ 透明材质（AlphaMode::Blend）被预渲染跳过——仅处理不透明和 Mask 材质；",
            "  - 🔧 Msaa::Off 关闭多重采样——⚠️ 预渲染 + MSAA 需要 GPU MULTISAMPLED_SHADING 能力；",
            "- **PrepassOutputMaterial**:",
            "  - struct PrepassOutputMaterial { settings: ShowPrepassSettings } 显示预渲染输出；",
            "  - fn enable_prepass() -> bool 返回 false——⚠️ 显示材质自身不写入预渲染缓冲区，否则自引用；",
            "  - fn alpha_mode() -> AlphaMode::Blend 透明混合——使场景内容穿透显示；",
            "- **ShowPrepassSettings**:",
            "  - struct ShowPrepassSettings { show_depth, show_normals, show_motion_vectors, ... } ShaderType uniform；",
            "  - 按空格键切换显示模式——0=透明/1=深度/2=法线/3=运动矢量；",
            "  - 🔧 PrepassOutputMaterial 使用专用着色器 show_prepass.wgsl——读取预渲染纹理并输出；",
            "- **PbrPlugin 配置**:",
            "  - PbrPlugin { prepass_enabled: true } 默认启用预渲染——StandardMaterial 自动参与；",
            "  - 🔧 预渲染可加速延迟渲染管线——深度/法线信息在主渲染前生成；",
            "- **注意事项**:",
            "  - ⚠️ 运动矢量纹理用于运动模糊/TAA 等后处理——需 Camera 配合后处理 Pass；",
            "  - 🔧 预渲染增加一次几何处理——复杂场景可能影响性能，需权衡收益；",
        ],
        [
            "知：",
            "- DepthPrepass / NormalPrepass / MotionVectorPrepass；",
            "- PrepassOutputMaterial 预渲染显示；",
            "- enable_prepass() 避免自引用。",
        ],
        [
            "例：",
            "- 3D/deferred_rendering.rs(65)。",
        ],
    ),
    (
        308,
        "着色器",
        [
            "**意图**：创建 texture_2d_array 并在着色器中采样——MeshTag 控制每实例选择的纹理层；⭐⭐⭐",
            "- **ImageArrayLayout 纹理数组**:",
            "  - asset_server.load_with_settings(path, |s| s.array_layout = Some(ImageArrayLayout::RowCount{rows:4})) 加载为纹理数组；",
            "  - ⚠️ 纹理图片必须按行排列——每行是一个数组层（本例 4 层）；",
            "  - 🔧 load_with_settings 在加载时配置格式转换——运行时无需额外处理；",
            "- **MeshTag 实例数据**:",
            "  - MeshTag(x as u32 % TEXTURE_COUNT) 为每个实体附加标签——着色器通过 @builtin(instance_index) 访问；",
            "  - 🔧 MeshTag 是轻量级每实例数据——不占用 uniform buffer 空间；",
            "- **update_mesh_tags 动画**:",
            "  - Timer::from_seconds(1.5, TimerMode::Repeating) 定时器驱动纹理层切换；",
            "  - tag.0 = (tag.0 + 1) % TEXTURE_COUNT 循环切换——每 1.5 秒更新一次；",
            "  - 🔧 MeshTag 修改自动触发材质重绑定——GPU 数据同步由引擎处理；",
            "- **着色器数组纹理采样**:",
            '  - #[texture(0, dimension = "2d_array")] 声明为 2D 数组纹理——⚠️ dimension 必须指定；',
            "  - 着色器中 textureSample(array_tex, sampler, uv, layer) 按层索引采样；",
            "  - 🔧 数组纹理比多张独立纹理更高效——单次绑定切换不同纹理；",
        ],
        [
            "知：",
            "- ImageArrayLayout 纹理数组加载；",
            "- MeshTag 每实例数据；",
            "- texture_2d_array 着色器采样。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        309,
        "着色器",
        [
            "**意图**：多实例自动 Instancing——相同 Mesh + 相同 Material 自动合批为单次 draw call；⭐⭐⭐",
            "- **自动 Instancing 机制**:",
            "  - 多个实体共享相同 Mesh3d 和 MeshMaterial3d 句柄——Bevy 自动合并为 GPU Instancing；",
            "  - ⚠️ Mesh/Material 必须完全相同（Handle 相等）——不同材质实例不会合批；",
            "  - 🔧 Instancing 将 N 个 draw call 降为 1 个——性能提升数十倍；",
            "- **MeshTag 实例数据**:",
            "  - MeshTag(index) 为每个实例附加唯一索引——着色器中通过 instance_index 访问；",
            "  - 🔧 MeshTag 可存储任意 u32 数据——如颜色索引/动画帧/特效参数；",
            "- **顶点着色器采样**:",
            "  - fn vertex_shader() -> ShaderRef 返回自定义顶点着色器——在顶点阶段采样纹理；",
            "  - 🔧 顶点阶段采样比片段阶段更高效——每个顶点计算一次而非每个像素；",
            "- **update 动画**:",
            "  - transform.translation.z = sin(time + index * 0.01) 螺旋波浪动画；",
            "  - 🔧 每个实例独立运动——展示 Instancing 下的差异化表现；",
            "- **注意事项**:",
            "  - ⚠️ 图像尺寸硬编码为 256x256——总像素数 = 65536 个实例；",
            "  - 🔧 大量实例时 Instancing 性能远优于逐一 spawn Mesh3d 独立实体；",
        ],
        [
            "知：",
            "- 自动 Instancing 合批机制；",
            "- MeshTag 每实例数据；",
            "- 顶点着色器实例索引。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        310,
        "着色器",
        [
            "**意图**：使用 ExtendedMaterial 扩展 StandardMaterial——在 PBR 着色器基础上添加自定义片段逻辑；⭐⭐⭐",
            "- **ExtendedMaterial 结构**:",
            "  - ExtendedMaterial<StandardMaterial, MyExtension> 组合基础材质和扩展——继承所有 PBR 属性；",
            "  - MaterialExtension trait 实现扩展——fragment_shader() 和 deferred_fragment_shader() 两个入口；",
            "  - 🔧 ExtendedMaterial 同时支持前向和延迟渲染——OpaqueRendererMethod::Auto 自动选择；",
            "- **绑定槽冲突避免**:",
            "  - #[uniform(100)] 从 binding 100 开始——⚠️ StandardMaterial 占用 0-99，扩展必须从 100+ 开始；",
            "  - WebGL2 需要 16 字节对齐——_webgl2_padding 三行填充确保正确布局；",
            "  - 🔧 binding 槽规划是 ExtendedMaterial 最常见的错误来源——必须仔细对照着色器声明；",
            "- **MaterialExtension trait**:",
            "  - fn fragment_shader() -> ShaderRef 返回扩展着色器——在 PBR 输出后追加效果；",
            "  - fn deferred_fragment_shader() -> ShaderRef 延迟模式着色器——修改 GBuffer 数据；",
            "  - 🔧 两个着色器文件可相同——naga_oil 条件编译选择正确路径；",
            "- **渲染模式**:",
            "  - OpaqueRendererMethod::Auto 自动选择前向/延迟——延迟模式下修改 PbrInput；",
            "  - ⚠️ 延迟模式需添加 DeferredPrepass 组件到 Camera——否则自动回退前向；",
            "  - 🔧 quantize_steps 量化步数参数传递到着色器——展示 uniform 传递自定义数据；",
        ],
        [
            "知：",
            "- ExtendedMaterial<Standard, Extension> 组合模式；",
            "- MaterialExtension trait 实现；",
            "- binding 槽冲突避免（0-99 保留）。",
        ],
        [
            "例：",
            "- 3D/pbr.rs(40)；",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        311,
        "着色器",
        [
            "**意图**：Bindless ExtendedMaterial——在扩展材质上使用绑定数组实现多材质合批；⭐⭐⭐",
            "- **扩展 Bindless 配置**:",
            "  - #[data(50, ExampleBindlessExtensionUniform, binding_array(101))] 扩展数据放入绑定数组——binding 101；",
            "  - #[bindless(index_table(range(50..53), binding(100)))] 扩展索引表从 slot 50 开始——⚠️ 必须与 StandardMaterial 索引表（默认 binding 0）分离；",
            "  - 🔧 range(50..53) 分配 3 个 slot——material/modulate_texture/modulate_texture_sampler 三个字段；",
            "- **ExampleBindlessExtension**:",
            "  - modulate_color: Color + #[texture(51)] #[sampler(52)] modulate_texture 混合颜色和纹理；",
            "  - impl From<&Extension> for ExtensionUniform CPU→GPU 数据转换——ShaderType 控制内存布局；",
            "  - 🔧 Vec4 存储颜色——LinearRgba::from(color).to_vec4() 转换为 GPU 友好格式；",
            "- **StandardMaterial 继承**:",
            "  - base: StandardMaterial { base_color: GRAY_600 } 继承所有 PBR 属性——扩展只添加额外效果；",
            "  - ExtendedMaterial<StandardMaterial, ExampleBindlessExtension> 一行代码组合——零样板；",
            "  - 🔧 扩展着色器中可通过 base 绑定访问 StandardMaterial 的所有纹理和属性；",
            "- **注意事项**:",
            "  - ⚠️ binding 编号规划：StandardMaterial 占用 0-99，扩展从 100+ 开始——冲突导致渲染错误；",
            "  - 🔧 index_table 的 binding 必须与着色器声明的 @group/@binding 完全匹配；",
        ],
        [
            "知：",
            "- Bindless ExtendedMaterial 扩展绑定；",
            "- index_table 索引表分离；",
            "- binding_array 扩展数据。",
        ],
        [
            "例：",
            "- shader/extended_material.rs(310)。",
        ],
    ),
    (
        312,
        "着色器",
        [
            "**意图**：自定义材质中使用存储缓冲区（StorageBuffer）——GPU 端动态数据读写；⭐⭐⭐",
            "- **ShaderStorageBuffer**:",
            "  - buffers.add(ShaderStorageBuffer::from(data)) 从 CPU 数据创建存储缓冲区——⚠️ 支持 Vec<[f32;4]> 等数组格式；",
            "  - Handle<ShaderStorageBuffer> 作为材质属性——着色器通过 storage buffer binding 访问；",
            "  - 🔧 StorageBuffer 比 UniformBuffer 容量大得多——适合大量数据（如粒子颜色/顶点偏移）；",
            "- **#[storage(0, read_only)]**:",
            "  - struct CustomMaterial { #[storage(0, read_only)] colors: Handle<ShaderStorageBuffer> } 只读存储绑定；",
            "  - ⚠️ read_only 标记——着色器可读但不可写；去除标记则可读写（需 GPU 计算着色器）；",
            "  - 🔧 Material 的 storage 绑定通常只读——计算着色器场景才需要读写；",
            "- **MeshTag 实例颜色**:",
            "  - MeshTag(current_color_id % 5) 每个实例标记颜色索引——着色器从 storage buffer 按索引取色；",
            "  - 🔧 5 种颜色在 buffer 中循环——MeshTag 索引映射到颜色数组；",
            "- **动态更新 buffer**:",
            "  - buffer.set_data(new_data) 运行时更新存储缓冲区内容——sin/cos 驱动颜色变化；",
            "  - 🔧 ShaderStorageBuffer 修改后自动同步到 GPU——无需手动 flush；",
            "- **注意事项**:",
            "  - ⚠️ 频繁更新大 buffer 有 CPU→GPU 传输开销——批量更新优于逐帧小量更新；",
            "  - 🔧 read_only storage buffer 在顶点和片段着色器都可访问——共享数据的理想方式；",
        ],
        [
            "知：",
            "- ShaderStorageBuffer 存储缓冲区；",
            "- #[storage] 绑定属性；",
            "- MeshTag 实例索引。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        313,
        "着色器",
        [
            "**意图**：测试所有纹理维度的 FallbackImage 初始化——确保 Optional 纹理绑定不 panic；⭐⭐",
            "- **FallbackImage 概念**:",
            "  - 当 Option<Handle<Image>> 为 None 时，Bevy 使用 FallbackImage 作为占位纹理；",
            "  - ⚠️ FallbackImage 必须覆盖所有纹理维度——1d/2d/2d_array/cube/cube_array/3d；",
            "  - 🔧 FallbackImage 是默认的 1x1 白色像素——确保着色器绑定有效但不显示内容；",
            "- **六种纹理维度**:",
            '  - #[texture(0, dimension = "1d")] 一维纹理——用于 1D 渐变/查找表；',
            '  - #[texture(2, dimension = "2d")] 二维纹理——最常用的标准纹理；',
            '  - #[texture(4, dimension = "2d_array")] 二维数组纹理——纹理图集；',
            '  - #[texture(6, dimension = "cube")] 立方体贴图——环境映射/天空盒；',
            '  - #[texture(8, dimension = "cube_array")] 立方体贴图数组——多层环境映射；',
            '  - #[texture(10, dimension = "3d")] 三维纹理——体积雾/医学影像；',
            "- **FallbackTestMaterial**:",
            "  - 所有 Handle<Image> 设为 None——测试 FallbackImage 在所有维度上的初始化；",
            "  - 🔧 着色器不着色任何几何——仅验证绑定组初始化不 panic——属于引擎内测用例；",
            "- **注意事项**:",
            "  - ⚠️ 窗口仅显示 clear color——此示例无可见输出，仅测试绑定稳定性；",
            "  - 🔧 添加新纹理维度时需确保 FallbackImage 覆盖——否则 Material 绑定失败；",
        ],
        [
            "知：",
            "- FallbackImage 纹理占位符；",
            "- texture dimension 纹理维度声明。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        314,
        "着色器",
        [
            "**意图**：从 GPU 读回数据——Readback 组件异步读取 StorageBuffer 和 Texture 数据；⭐⭐⭐",
            "- **Readback 组件**:",
            "  - Readback::buffer(handle) 创建缓冲区读回——异步触发 ReadbackComplete 事件；",
            "  - Readback::buffer_range(handle, offset, size) 读回缓冲区范围——可跳过前 N 个元素；",
            "  - Readback::texture(handle) 读回纹理数据——⚠️ 纹理格式决定数据解释方式；",
            "  - 🔧 Readback 实体每帧自动读回—— despawn 实体停止读回；",
            "- **ReadbackComplete 事件**:",
            "  - .observe(|event: On<ReadbackComplete>| { let data: Vec<u32> = event.to_shader_type(); }) 按 ShaderType 解析；",
            "  - event.to_shader_type::<T>() 将原始字节转为具体类型——⚠️ 类型必须与 GPU 数据布局匹配；",
            "  - 🔧 observe 模式异步回调——Readback 在渲染管线完成后触发，不在主线程；",
            "- **GPU 计算管线**:",
            "  - ComputePipeline 手动创建 bind group 和 compute pipeline——RenderApp 侧系统；",
            "  - PassDescriptor + dispatch_workgroups(BUFFER_LEN, 1, 1) 调度计算着色器；",
            "  - 🔧 GPU 计算在 Readback 之前执行——先写入数据再读回；",
            "- **存储缓冲区配置**:",
            "  - buffer.buffer_description.usage |= BufferUsages::COPY_SRC 添加 COPY_SRC 用途——⚠️ 默认无此用途；",
            "  - image.texture_descriptor.usage |= COPY_SRC | STORAGE_BINDING 纹理同时需要拷贝和存储用途；",
            "  - 🔧 Image::new_uninit 创建未初始化纹理——CPU 端无需存储数据；",
            "- **RenderGraph 节点**:",
            "  - ComputeNode 注册为顶层渲染图节点——每帧执行一次；",
            "  - 🔧 添加到顶层（非 CameraDriver 后）确保不被视图裁剪——全局执行；",
        ],
        [
            "知：",
            "- Readback 异步 GPU 读回；",
            "- ReadbackComplete 事件与 to_shader_type()；",
            "- ComputePipeline GPU 计算管线。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
    (
        315,
        "着色器",
        [
            "**意图**：计算着色器模拟康威生命游戏——RenderApp 侧完整计算管线 + 双缓冲 Ping-Pong；⭐⭐⭐",
            "- **计算管线架构**:",
            "  - GameOfLifeComputePlugin 注册 ExtractResourcePlugin + RenderApp 系统——主世界和渲染世界分离；",
            "  - RenderStartup 初始化管线——Render 阶段 prepare_bind_group 准备绑定组；",
            "  - 🔧 RenderApp 是独立的 ECS World——与主 World 通过 ExtractResource 同步数据；",
            "- **双缓冲 Ping-Pong**:",
            "  - GameOfLifeImages { texture_a, texture_b } 两张纹理交替读写——⚠️ GPU 不能同时读写同一纹理；",
            "  - bind_group_0 从 A 读 → 写入 B；bind_group_1 从 B 读 → 写入 A——每帧切换；",
            "  - switch_textures 系统每帧切换 Sprite 显示的纹理——显示最近写入的结果；",
            "- **RenderGraph 节点状态机**:",
            "  - GameOfLifeState::Loading → Init → Update(0) → Update(1) → 循环——⚠️ 管线编译异步；",
            "  - update() 方法检查 PipelineCache 状态——Ok 则切换到下一阶段，Err(ShaderNotLoaded) 则等待；",
            "  - 🔧 状态机确保着色器编译完成后才开始计算——避免未就绪管线的 GPU 错误；",
            "- **UniformBuffer 配置**:",
            "  - GameOfLifeUniforms { alive_color: LinearRgba } 控制存活细胞颜色；",
            "  - UniformBuffer::from(data).write_buffer(&device, &queue) 手动写入 GPU——⚠️ 非自动同步；",
            "  - 🔧 UniformBuffer 适合少量全局参数——大量数据应用 StorageBuffer；",
            "- **ComputePass 调度**:",
            "  - pass.set_bind_group(0, &bind_groups[index], &[]) 设置绑定组——index 控制 Ping-Pong 方向；",
            "  - pass.dispatch_workgroups(SIZE.x / WORKGROUP_SIZE, SIZE.y / WORKGROUP_SIZE, 1) 调度工作组；",
            "  - 🔧 WORKGROUP_SIZE=8 时工作组为 8x8 像素——GPU 线程组大小需匹配着色器声明；",
            "- **纹理配置**:",
            "  - Image::new_target_texture + RenderAssetUsages::RENDER_WORLD 仅 GPU 端纹理——⚠️ CPU 不保留副本；",
            "  - COPY_DST | STORAGE_BINDING | TEXTURE_BINDING 三种用途——拷贝/存储写入/着色器采样；",
        ],
        [
            "知：",
            "- 计算着色器与 RenderApp；",
            "- 双缓冲 Ping-Pong 纹理模式；",
            "- RenderGraph 节点状态机。",
        ],
        [
            "例：",
            "- shader/shader_material.rs(299)。",
        ],
    ),
]


def build_row(seq, cat, intent, knowledge, examples):
    """Build a single catalog table row."""
    intent_text = "<br>".join(intent)
    knowledge_text = "<br>".join(knowledge)
    examples_text = "<br>".join(examples)
    return (
        f"| {seq} | {cat} | `{get_filename(seq)}` | "
        f"{intent_text}<br>{knowledge_text}<br>{examples_text} |"
    )


def get_filename(seq):
    """Map seq to filename."""
    FILENAMES = {
        152: "dynamic.rs",
        158: "asset_loading.rs",
        260: "ui_texture_slice.rs",
        282: "generic_reflection.rs",
        283: "custom_attributes.rs",
        284: "function_reflection.rs",
        285: "dynamic_types.rs",
        286: "serialization.rs",
        287: "type_data.rs",
        288: "auto_register_static/src/lib.rs",
        289: "auto_register_static/src/bin/main.rs",
        290: "load_gltf.rs",
        291: "update_gltf_scene.rs",
        292: "edit_material_on_gltf.rs",
        293: "load_gltf_extras.rs",
        294: "query_gltf_primitives.rs",
        295: "gltf_skinned_mesh.rs",
        296: "custom_gltf_vertex_attribute.rs",
        297: "gltf_extension_animation_graph.rs",
        298: "gltf_extension_mesh_2d.rs",
        299: "shader_material.rs",
        300: "shader_material_2d.rs",
        301: "shader_material_glsl.rs",
        302: "shader_material_wesl.rs",
        303: "shader_material_bindless.rs",
        304: "shader_material_screenspace_texture.rs",
        305: "animate_shader.rs",
        306: "shader_defs.rs",
        307: "shader_prepass.rs",
        308: "array_texture.rs",
        309: "automatic_instancing.rs",
        310: "extended_material.rs",
        311: "extended_material_bindless.rs",
        312: "storage_buffer.rs",
        313: "fallback_image.rs",
        314: "gpu_readback.rs",
        315: "compute_shader_game_of_life.rs",
    }
    return FILENAMES[seq]


def main():
    with open(CATALOG, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")

    # Build replacement map: seq -> new row line
    replacements = {}
    for seq, cat, intent, knowledge, examples in DATA:
        new_row = build_row(seq, cat, intent, knowledge, examples)
        replacements[seq] = new_row

    # Process line by line
    new_lines = []
    i = 0
    while i < len(lines):
        line = lines[i]
        # Check if this line starts a table row with a sequence number we need to replace
        matched = False
        for seq in replacements:
            prefix = f"| {seq} "
            if line.startswith(prefix):
                new_lines.append(replacements[seq])
                matched = True
                break
        if not matched:
            new_lines.append(line)
        i += 1

    with open(CATALOG, "w", encoding="utf-8") as f:
        f.write("\n".join(new_lines))

    print(f"Done. Replaced {len(replacements)} entries: {sorted(replacements.keys())}")


if __name__ == "__main__":
    main()
