#!/usr/bin/env python3
"""Replace catalog entries 316-345 with detailed content from source files.
Matches entries by sequence number and replaces with comprehensive technical details."""

import re

CATALOG_PATH = "/Users/lf380/Code/Bevy/a1/bevy_examples_catalog.md"

DATA = [
    # ── shader_advanced (316-325) ──────────────────────────────
    (
        316,
        "着色器高级",
        [
            "**意图**：自定义后处理 Pass——在主渲染管线之后运行色差(Chromatic Aberration)着色器，演示完整的后处理管线搭建；⭐⭐⭐",
            "- **PostProcessPlugin 插件架构**:",
            "  - ExtractComponentPlugin 将 PostProcessSettings 从主世界提取到渲染世界——组件同步机制；",
            "  - UniformComponentPlugin 将设置数据写入 GPU Uniform Buffer——每帧自动更新；",
            "  - 🔧 后处理效果封装为 Plugin 是 Bevy 的推荐做法——插件化便于复用和组合；",
            "- **RenderGraph 节点插入**:",
            "  - ViewNodeRunner 包装 PostProcessNode——自动为每个视图运行节点；",
            "  - add_render_graph_node 注册到 Core3d 图——指定渲染阶段；",
            "  - add_render_graph_edges 定义执行顺序：Tonemapping → PostProcess → EndMainPassPostProcessing；",
            "  - ⚠️ 节点顺序至关重要——后处理必须在色调映射之后、结束之前执行；",
            "- **ViewTarget 双缓冲机制**:",
            "  - view_target.post_process_write() 获取 source 和 destination 两个纹理视图；",
            "  - 从 source 读取主渲染结果，写入 destination——调用后自动翻转；",
            "  - 🔧 必须写入 destination——否则当前帧信息丢失，下一帧读到空白；",
            "- **BindGroup 动态创建**:",
            "  - 每帧创建 BindGroup——因为 post_process_write 交替切换 source/destination；",
            "  - BindGroupEntries::sequential 绑定纹理+采样器+设置缓冲区；",
            "  - DynamicUniformIndex 处理多相机的设置索引——每个相机独立参数；",
            "- **全屏三角形绘制**:",
            "  - render_pass.draw(0..3, 0..1) 绘制 3 个顶点——覆盖全屏的三角形；",
            "  - FullscreenShader.to_vertex_state() 生成顶点状态——避免手动编写顶点着色器；",
            "  - 🔧 全屏三角形比全屏四边形更高效——无对角线上的重复片段；",
            "- **注意事项**:",
            "  - ⚠️ RenderStartup 在插件构建后运行一次——适合初始化管线资源；",
            "  - 🔧 WebGL2 需要 16 字节对齐——PostProcessSettings 添加 Vec3 padding；",
        ],
        [
            "知：<br>- RenderGraph 自定义节点；<br>- ViewTarget 双缓冲后处理；<br>- UniformComponentPlugin 数据同步。",
            "例：<br>- shader/shader_material.rs(300)；<br>- 3D/post_processing.rs(46)。",
        ],
    ),
    (
        317,
        "着色器高级",
        [
            "**意图**：FullscreenMaterial 简化全屏后处理——比手动搭建 RenderGraph 更简洁的全屏效果实现方式；⭐⭐",
            "- **FullscreenMaterialPlugin**:",
            "  - FullscreenMaterialPlugin::<FullscreenEffect>::default() 注册全屏材质插件——自动处理 RenderGraph 节点；",
            "  - ⚠️ 目前仅支持 3D——2D 等效实现正在开发中；",
            "  - 🔧 比手动实现 ViewNode 更简洁——适合快速原型；",
            "- **FullscreenMaterial trait**:",
            "  - fragment_shader() 返回 ShaderRef——指定片段着色器路径；",
            "  - node_edges() 定义渲染图边——控制效果执行顺序；",
            "  - Self::node_label().intern() 自动生成节点标签——基于结构体名称；",
            "  - 🔧 node_edges 返回的边列表决定效果在管线中的位置；",
            "- **ExtractComponent 数据传递**:",
            "  - FullscreenEffect 组件 derive ExtractComponent——自动提取到渲染世界；",
            "  - intensity: f32 传递参数到着色器——运行时可修改；",
            "  - ShaderType derive 支持 GPU 数据布局——自动处理对齐；",
            "- **注意事项**:",
            "  - ⚠️ 当前不支持 AsBindGroup——只能传递简单结构体；",
            "  - 🔧 2D 场景需要使用 Node2d 替代 Node3d；",
        ],
        [
            "知：<br>- FullscreenMaterialPlugin 全屏材质；<br>- FullscreenMaterial trait；<br>- node_edges 渲染顺序。",
            "例：<br>- shader_advanced/custom_post_processing.rs(316)。",
        ],
    ),
    (
        318,
        "着色器高级",
        [
            "**意图**：深度纹理相机——仅渲染深度缓冲到纹理，实现深度图可视化和球坐标轨道控制；⭐⭐⭐",
            "- **深度相机配置**:",
            "  - Camera3d + RenderTarget::None 禁用颜色输出——仅渲染深度；",
            "  - DepthPrepass 启用深度预渲染——必须添加否则无深度数据；",
            "  - Camera { order: -1 } 确保在主相机之前渲染——深度数据就绪；",
            "  - Msaa::Off 禁用多重采样——简化深度纹理处理；",
            "  - 🔧 RenderTarget::None 必须指定 size——否则 Bevy 不知道深度缓冲尺寸；",
            "- **CopyDepthTextureNode 渲染节点**:",
            "  - ViewNode 实现——仅对 order < 0 的相机执行（深度相机）；",
            "  - copy_texture_to_texture 将 ViewDepthTexture 复制到目标纹理；",
            "  - add_command_buffer_generation_task 异步执行 GPU 命令——不阻塞渲染；",
            "  - ⚠️ wgpu 不允许同时渲染和采样同一深度纹理——必须复制；",
            "- **球坐标轨道控制**:",
            "  - SphericalCoordinates { radius, inclination, azimuth } 球坐标系；",
            "  - WASD 键控制 inclination/azimuth——实现轨道旋转；",
            "  - clamp(0.01, PI-0.01) 防止极点翻转——数学约定而非物理约定；",
            "  - 🔧 球坐标到笛卡尔坐标的转换——sin/cos 组合计算；",
            "- **Depth32Float 纹理**:",
            "  - Image::new_uninit 创建未初始化深度纹理——Depth32Float 格式；",
            "  - ImageSamplerDescriptor::compare 设置比较函数——深度纹理必需；",
            "  - ExtractResourcePlugin 资源提取到渲染世界——跨世界共享纹理；",
            "- **注意事项**:",
            "  - ⚠️ 纹理尺寸 256×256——生产环境可调整为更高分辨率；",
            "  - 🔧 Gizmos 绘制相机锥体——可视化深度相机位置和朝向；",
        ],
        [
            "知：<br>- 深度相机 RenderTarget::None；<br>- ViewDepthTexture 复制；<br>- 球坐标轨道控制。",
            "例：<br>- shader/shader_prepass.rs(307)；<br>- camera/camera_orbit.rs(200)。",
        ],
    ),
    (
        319,
        "着色器高级",
        [
            "**意图**：自定义 Phase Item——在 BinnedRenderPhase 中入队自定义绘制命令，演示低级渲染 API 的使用；⭐⭐⭐",
            "- **CustomRenderedEntity 组件**:",
            "  - derive ExtractComponent 自动提取到渲染世界；",
            "  - #[require(VisibilityClass)] 声明式依赖——自动添加可见性类；",
            "  - on_add hook 调用 add_visibility_class——确保 check_visibility 系统检测；",
            "  - 🔧 可见性系统需要 VisibilityClass 才能正确判断实体可见性；",
            "- **DrawCustomPhaseItem 渲染命令**:",
            "  - impl RenderCommand<P> for DrawCustomPhaseItem——泛型阶段项实现；",
            "  - set_vertex_buffer + set_index_buffer 绑定 GPU 缓冲区；",
            "  - draw_indexed(0..3, 0, 0..1) 绘制单个三角形——3 个索引；",
            "  - 🔧 RawBufferVec 最简单的 GPU 缓冲区类型——适合静态数据；",
            "- **CustomPhasePipeline 资源**:",
            "  - Variants<RenderPipeline, CustomPhaseSpecializer> 管线变体管理；",
            "  - FromWorld 实现——在渲染世界启动时初始化；",
            "  - Specializer trait 处理 MSAA 样本数——按视图特化管线；",
            "  - 🔧 基础描述符包含顶点/片段/深度模板状态——一次创建多次复用；",
            "- **queue_custom_phase_item 入队系统**:",
            "  - ViewBinnedRenderPhases<Opaque3d> 获取不透明渲染阶段；",
            "  - BinnedRenderPhaseType::NonMesh 跳过网格特殊处理——自定义绘制；",
            "  - Opaque3dBatchSetKey + Opaque3dBinKey 构建阶段项键——管线+资产 ID；",
            "  - ⚠️ change_tick 递增强制重建 bin——确保新实体被正确渲染；",
            "- **Vertex 数据布局**:",
            "  - #[repr(C)] + Pod + Zeroable 确保内存布局匹配 GPU；",
            "  - position(Vec3) + pad0(u32) + color(Vec3) + pad1(u32) = 32 字节；",
            "  - VertexBufferLayout 定义步进模式和属性偏移——必须与 Vertex 结构对齐；",
        ],
        [
            "知：<br>- BinnedRenderPhase 入队；<br>- RenderCommand 自定义绘制；<br>- Variants 管线变体。",
            "例：<br>- shader/shader_material.rs(300)；<br>- 3D/3d_shapes.rs(33)。",
        ],
    ),
    (
        320,
        "着色器高级",
        [
            "**意图**：自定义渲染阶段——实现完整的 SortedRenderPhase 用于模板(Stencil)渲染，演示阶段项的完整生命周期；⭐⭐⭐",
            "- **MeshStencilPhasePlugin 插件**:",
            "  - SortedRenderPhasePlugin::<Stencil3d, MeshPipeline> 注册排序渲染阶段；",
            "  - ExtractComponentPlugin 提取 DrawStencil 标记组件；",
            "  - RenderStartup 初始化管线——RenderApp 子应用专用系统；",
            "  - 🔧 RenderStartup 在渲染世界启动时运行一次——比 Startup 更适合渲染初始化；",
            "- **Stencil3d 阶段项**:",
            "  - impl PhaseItem + SortedPhaseItem + CachedRenderPipelinePhaseItem 三个 trait；",
            "  - sort_key: FloatOrd 基于距离排序——实现画家算法；",
            "  - entity: (Entity, MainEntity) 主世界和渲染世界实体映射；",
            "  - batch_range + extra_index 管理批次范围——渲染阶段内部数据；",
            "  - ⚠️ SortedPhaseItem 比 BinnedRenderPhase 更简单——但性能略低；",
            "- **StencilPipeline 管线**:",
            "  - SpecializedMeshPipeline trait 实现——基于 MeshPipelineKey 特化；",
            "  - 复用 MeshPipeline 的 bind group 布局——view/mesh 绑定组；",
            "  - 自定义着色器仅使用 POSITION 属性——简化顶点布局；",
            "  - 🔧 复用 Bevy 内置管线数据比从零搭建更高效；",
            "- **DrawMesh3dStencil 绘制命令**:",
            "  - 元组组合多个渲染命令——SetItemPipeline + SetMeshViewBindGroup + DrawMesh；",
            "  - SetMeshViewEmptyBindGroup<1> 空绑定组 1——占位保持绑定组顺序；",
            "  - 🔧 Bevy 的渲染命令组合模式——像函数组合一样拼装绘制逻辑；",
            "- **GetBatchData/GetFullBatchData**:",
            "  - 从 RenderMeshInstances 提取 MeshUniform 数据；",
            "  - mesh_allocator 获取顶点/索引缓冲区位置——GPU 内存管理；",
            "  - write_batch_indirect_parameters_metadata 写入间接绘制参数；",
            "  - 🔧 CPU 构建和 GPU 构建两种模式——通过 CpuBuilding/GpuBuilding 区分；",
            "- **CustomDrawNode 渲染节点**:",
            "  - ViewNode 实现——在 MainOpaquePass 之后执行；",
            "  - stencil_phase.render 执行阶段的所有绘制命令；",
            "  - Viewport::from_viewport_and_override 处理视口覆盖——支持子视口渲染；",
            "  - ⚠️ 无深度附件——模板渲染不需要深度测试；",
            "- **注意事项**:",
            "  - ⚠️ extract_camera_phases 需要维护 live_entities——清理已销毁的视图；",
            "  - 🔧 使用 radsort（稳定基数排序）获得最佳排序性能；",
        ],
        [
            "知：<br>- SortedRenderPhase 自定义阶段；<br>- PhaseItem + SortedPhaseItem trait；<br>- GetBatchData 批次数据。",
            "例：<br>- shader_advanced/custom_phase_item.rs(319)；<br>- shader/shader_material.rs(300)。",
        ],
    ),
    (
        321,
        "着色器高级",
        [
            "**意图**：SpecializedMeshPipeline 专用网格管线——基于 MeshPipelineKey 特化渲染管线，支持批量和多绘制间接；⭐⭐⭐",
            "- **SpecializedMeshPipeline trait**:",
            "  - specialize(key, layout) 返回 RenderPipelineDescriptor——基于键值特化；",
            "  - Key 类型决定特化维度——本例使用 MeshPipelineKey；",
            "  - 🔧 管线缓存自动避免重复创建——相同键返回缓存的管线；",
            "- **顶点属性动态选择**:",
            "  - layout.0.contains(Mesh::ATTRIBUTE_POSITION) 检查属性存在性；",
            "  - layout.0.get_layout(&attributes) 自动生成 VertexBufferLayout；",
            "  - 🔧 按需选择顶点属性——避免未使用属性的内存开销；",
            "- **HDR/MSAA 特化**:",
            "  - MeshPipelineKey::from_hdr(view.hdr) 根据视图 HDR 状态特化；",
            "  - mesh_key.msaa_samples() 根据 MSAA 样本数特化；",
            "  - ViewTarget::TEXTURE_FORMAT_HDR vs TextureFormat::bevy_default() 输出格式；",
            "  - ⚠️ 不同 HDR 状态需要不同的管线——否则渲染错误；",
            "- **queue_custom_mesh_pipeline 入队**:",
            "  - SpecializedMeshPipelines::specialize 获取特化管线 ID；",
            "  - ViewBinnedRenderPhases<Opaque3d> 入队到不透明阶段；",
            "  - BinnedRenderPhaseType::mesh 根据 should_batch() 选择批次模式；",
            "  - 🔧 支持 Batching 和 Multi Draw Indirect——大量同材质网格自动合批；",
            "- **DrawSpecializedPipelineCommands**:",
            "  - 元组组合：SetItemPipeline + SetMeshViewBindGroup<0> + SetMeshViewEmptyBindGroup<1> + SetMeshBindGroup<2> + DrawMesh；",
            "  - 复用 Bevy 内置的 DrawMesh 命令——标准网格绘制；",
            "  - 🔧 自定义管线只需替换着色器——绘制逻辑完全复用；",
            "- **注意事项**:",
            "  - ⚠️ DepthStencilState 必须与视图深度格式匹配——CORE_3D_DEPTH_FORMAT；",
            "  - 🔧 PrimitiveState 设置背面剔除——Face::Back 提升性能；",
        ],
        [
            "知：<br>- SpecializedMeshPipeline 特化管线；<br>- MeshPipelineKey 管线键；<br>- Batching 批量渲染。",
            "例：<br>- shader_advanced/custom_phase_item.rs(319)；<br>- shader/automatic_instancing.rs(309)。",
        ],
    ),
    (
        322,
        "着色器高级",
        [
            "**意图**：完全手动管理材质管道——不使用 Material trait，直接实现 ErasedRenderAsset + BindGroup 分配；⭐⭐⭐",
            "- **ErasedRenderAsset trait**:",
            "  - prepare_asset 将主世界资产转换为 GPU 准备数据；",
            "  - Output = PreparedMaterial——Bevy 内部材质表示；",
            "  - Param 系统参数——访问 DrawFunctions、AssetServer、RenderDevice 等；",
            "  - 🔧 ErasedRenderAsset 是材质系统的核心 trait——所有材质最终都走这条路；",
            "- **MaterialBindGroupAllocator**:",
            "  - 手动分配 BindGroup——不使用 AsBindGroup 自动分配；",
            "  - allocate_unprepared 将 UnpreparedBindGroup 分配到分配器；",
            "  - free 释放已分配的 BindGroup——支持材质热重载；",
            "  - ⚠️ 必须在 TypeId 上注册分配器——否则材质系统找不到；",
            "- **RenderMaterialInstances 提取**:",
            "  - extract_image_materials 手动提取材质实例到渲染世界；",
            "  - Changed<ViewVisibility> 过滤仅更新可见实体——避免不必要的提取；",
            "  - 🔧 手动提取比 ExtractComponentPlugin 更灵活——可自定义过滤逻辑；",
            "- **实体特化管理**:",
            "  - check_entities_needing_specialization 检测网格/材质变更；",
            "  - EntitySpecializationTickPair 追踪系统 tick 和材质实例 tick；",
            "  - sweep 清理已移除实体的特化缓存——防止内存泄漏；",
            "  - 🔧 特化缓存按视图存储——不同视图可能有不同管线；",
            "- **ImageMaterial 资产**:",
            "  - #[derive(Asset, TypePath, AsBindGroup)] 定义资产类型；",
            "  - AsBindGroup 手动实现——texture_2d + sampler 绑定；",
            "  - 🔧 手动实现 AsBindGroup 可精确控制绑定组布局和资源管理；",
            "- **注意事项**:",
            "  - ⚠️ 手动材质管理比 Material trait 复杂得多——仅在需要完全控制时使用；",
            "  - 🔧 适合需要精细 GPU 资源管理的场景——如大量不同材质的场景；",
        ],
        [
            "知：<br>- ErasedRenderAsset 手动材质；<br>- MaterialBindGroupAllocator 分配；<br>- 手动提取管线。",
            "例：<br>- shader/shader_material.rs(300)；<br>- shader_advanced/custom_phase_item.rs(319)。",
        ],
    ),
    (
        323,
        "着色器高级",
        [
            "**意图**：高级自定义实例化——使用低级渲染 API 实现手动实例化，一次绘制调用渲染多个立方体；⭐⭐⭐",
            "- **InstanceMaterialData 组件**:",
            "  - Deref Vec<InstanceData> 包装实例数据数组；",
            "  - 实现 ExtractComponent——自定义提取逻辑（clone 数据）；",
            "  - 🔧 实例数据存储在组件中——每个实体独立的实例集合；",
            "- **InstanceData 结构**:",
            "  - position(Vec3) + scale(f32) + color([f32;4]) = 32 字节；",
            "  - #[repr(C)] + Pod + Zeroable 确保 GPU 兼容；",
            "  - 🔧 颜色使用 LinearRgba::from(Color::hsla(...)) 确保线性空间；",
            "- **InstanceBuffer GPU 缓冲区**:",
            "  - prepare_instance_buffers 创建 GPU 缓冲区——BufferUsages::VERTEX；",
            "  - bytemuck::cast_slice 零拷贝转换——Pod 类型的高效序列化；",
            "  - 🔧 每帧重新创建缓冲区——适合动态实例数据；",
            "- **CustomPipeline 特化**:",
            "  - extends MeshPipeline 基础管线——添加额外顶点缓冲区；",
            "  - descriptor.vertex.buffers.push 添加实例缓冲区布局；",
            "  - VertexStepMode::Instance 步进模式——每实例更新一次；",
            "  - shader_location 3/4 避开 Bevy 内置属性（0/1/2）；",
            "  - 🔧 实例属性 location 必须避开 Mesh 的 POSITION/NORMAL/UV；",
            "- **DrawMeshInstanced 渲染命令**:",
            "  - set_vertex_buffer(0, mesh_vertices) 网格顶点缓冲区；",
            "  - set_vertex_buffer(1, instance_buffer) 实例数据缓冲区；",
            "  - draw_indexed(0..count, 0, 0..instance_count) 批量绘制；",
            "  - 🔧 两个顶点缓冲区槽位——槽位 0 网格，槽位 1 实例；",
            "- **NoFrustumCulling**:",
            "  - 禁用视锥体剔除——实例位置不在网格 Aabb 范围内；",
            "  - ⚠️ 不禁用会导致所有实例被错误剔除——Aabb 仅覆盖原始网格；",
            "  - 🔧 自定义实例化必须手动处理剔除——或完全禁用；",
            "- **注意事项**:",
            "  - ⚠️ NoIndirectDrawing 禁用间接绘制——使用传统 draw_indexed；",
            "  - 🔧 10×10=100 个实例通过单次绘制调用渲染——性能远优于逐实体绘制；",
        ],
        [
            "知：<br>- 手动实例化 VertexStepMode::Instance；<br>- 双顶点缓冲区布局；<br>- NoFrustumCulling 禁用剔除。",
            "例：<br>- shader/automatic_instancing.rs(309)；<br>- shader_advanced/custom_phase_item.rs(319)。",
        ],
    ),
    (
        324,
        "着色器高级",
        [
            "**意图**：自定义顶点属性——MeshVertexAttribute 定义高随机 ID 属性，着色器中读取并使用自定义颜色；⭐⭐",
            "- **MeshVertexAttribute 常量**:",
            '  - MeshVertexAttribute::new("BlendColor", 988540917, VertexFormat::Float32x4)；',
            "  - 高随机 ID(988540917) 避免与其他属性冲突——⚠️ 必须全局唯一；",
            "  - Float32x4 格式——4 个 32 位浮点数（RGBA）；",
            "  - 🔧 属性名称在着色器中通过 @location(N) 访问；",
            "- **Mesh 自定义属性**:",
            "  - mesh.with_inserted_attribute(ATTRIBUTE_BLEND_COLOR, vec![[1,0,0,1]; 24])；",
            "  - Cuboid 有 24 个顶点（6 面 × 4 顶点）——每个顶点独立颜色；",
            "  - 🔧 自定义属性数据与网格顶点数必须匹配——否则渲染错误；",
            "- **Material specialize 实现**:",
            "  - Material::specialize 重写管线特化——自定义顶点布局；",
            "  - layout.0.get_layout(&[POSITION, BLEND_COLOR]) 仅声明使用的属性；",
            "  - descriptor.vertex.buffers = vec![vertex_layout] 替换默认缓冲区布局；",
            "  - ⚠️ 必须在 specialize 中声明自定义属性——否则着色器无法读取；",
            "- **着色器访问**:",
            "  - @location(0) 位置 + @location(1) 自定义颜色——与 Rust 端对应；",
            "  - 顶点和片段着色器都使用同一文件——SHADER_ASSET_PATH 常量；",
            "  - 🔧 自定义属性在顶点着色器中插值后传递给片段着色器；",
            "- **注意事项**:",
            "  - ⚠️ 属性 ID 必须大于 1000——避免与 Bevy 内置属性冲突；",
            "  - 🔧 适合实现：逐顶点风力、UV 动画、顶点动画等效果；",
        ],
        [
            "知：<br>- MeshVertexAttribute 自定义属性；<br>- specialize 顶点布局；<br>- 高随机 ID 避免冲突。",
            "例：<br>- shader/shader_material.rs(300)；<br>- shader/automatic_instancing.rs(309)。",
        ],
    ),
    (
        325,
        "着色器高级",
        [
            "**意图**：纹理绑定数组——多纹理非均匀采样(Bindless Textures)，16 张纹理绑定到单个 binding_array 槽位；⭐⭐⭐",
            "- **AsBindGroup 手动实现**:",
            "  - as_bind_group 直接构建 BindGroup——不使用 derive 自动生成；",
            "  - UnpreparedBindGroup 包含纹理视图和采样器绑定；",
            "  - 🔧 Bindless 纹理不能被 owned——必须手动管理生命周期；",
            "- **binding_array 纹理布局**:",
            "  - texture_2d().count(16) 声明 16 个纹理的绑定数组；",
            "  - sampler(SamplerBindingType::Filtering) 共享采样器——所有纹理使用同一采样器；",
            "  - 🔧 采样器也可以是数组——但本例使用共享采样器节省绑定槽位；",
            "- **FallbackImage 填充**:",
            "  - fallback_image.d2 获取 2D 回退图像——未加载完成的纹理槽位；",
            "  - vec![&fallback_image.texture_view; 16] 初始化全部槽位；",
            "  - 替换为实际纹理视图——images[id] = &image.texture_view；",
            "  - ⚠️ 必须填满所有槽位——未填充的槽位会导致 GPU 错误；",
            "- **GPU 特性检查**:",
            "  - WgpuFeatures::SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING；",
            "  - render_device.features().contains() 检查特性支持；",
            "  - 不支持则 exit(1) 退出——生产环境应有降级方案；",
            "  - 🔧 Bindless 纹理需要特定 GPU 特性——不是所有设备都支持；",
            "- **非均匀索引**:",
            "  - 着色器中使用 nonuniform 修饰符——不同片段可采样不同纹理；",
            "  - 适合：地形纹理混合/粒子系统/纹理图集选择；",
            "  - 🔧 比每个纹理一个绑定组更高效——减少 Draw Call 和绑定切换；",
            "- **注意事项**:",
            "  - ⚠️ MAX_TEXTURE_COUNT = 16 是硬件限制——实际最大值因设备而异；",
            "  - 🔧 bind_group_layout_entries 手动定义——精确控制布局和索引；",
        ],
        [
            "知：<br>- binding_array 绑定数组；<br>- FallbackImage 回退填充；<br>- 非均匀纹理采样。",
            "例：<br>- shader/shader_material_bindless.rs(303)；<br>- shader/shader_material.rs(300)。",
        ],
    ),
    # ── async_tasks (326-328) ──────────────────────────────────
    (
        326,
        "异步任务",
        [
            "**意图**：异步通道模式——AsyncComputeTaskPool 派生任务 + crossbeam 通道通信，任务完成后动态生成实体；⭐⭐⭐",
            "- **CubeChannel Resource**:",
            "  - crossbeam::unbounded() 创建无界通道——Sender/Receiver 配对存储在 Resource 中；",
            "  - CubeFinished { transform } 消息结构体——包含完成任务的 Transform 数据；",
            "  - 🔧 无界通道适合突发任务——不会阻塞发送方；",
            "- **AsyncComputeTaskPool::get().spawn().detach()**:",
            "  - spawn 在计算线程池派生任务——不阻塞主线程；",
            "  - detach 使任务独立运行——无需每帧轮询；",
            "  - 🔧 detach 后无法取消任务——适合确定性完成的任务；",
            "- **通道通信**:",
            "  - sender.send(CubeFinished { transform }) 从异步任务发送结果；",
            "  - receiver.try_iter() 非阻塞接收——每帧检查一次；",
            "  - 🔧 try_iter() 返回迭代器——一次处理所有已到达的消息；",
            "- **动态实体生成**:",
            "  - 从通道接收 Transform 后 spawn 新实体——异步任务驱动 ECS；",
            "  - 共享 MeshMaterial3d Handle——避免重复创建资源；",
            "  - 🔧 异步计算 + 通道是 Bevy 中处理耗时任务的标准模式；",
            "- **注意事项**:",
            "  - ⚠️ 无界通道可能消耗大量内存——生产环境考虑有界通道；",
            "  - 🔧 适合：AI 路径计算/网络数据处理/文件加载回调；",
        ],
        [
            "知：<br>- AsyncComputeTaskPool 异步计算；<br>- crossbeam 通道通信；<br>- detach 派生任务。",
            "例：<br>- ecs/ecs_guide.rs(124)。",
        ],
    ),
    (
        327,
        "异步任务",
        [
            "**意图**：异步计算轮询——Task<CommandQueue> 组件追踪任务状态，每帧 check_ready 轮询，完成后应用延迟命令；⭐⭐⭐",
            "- **ComputeTransform 组件**:",
            "  - Task<CommandQueue> 包装异步任务——可作为 ECS 组件存储；",
            "  - 🔧 将异步任务作为组件——利用 ECS 生命周期自动管理；",
            "- **check_ready 轮询**:",
            "  - task.0.check_ready(&mut context) 检查任务完成状态——非阻塞；",
            "  - ⚠️ 不要使用 future::block_on——会阻塞主线程；",
            "  - 🔧 check_ready 返回 Option<T>——Some 表示完成，None 表示继续等待；",
            "- **CommandQueue 延迟命令**:",
            "  - CommandQueue::apply(&mut world) 应用异步任务产生的命令；",
            "  - 异步任务中通过 SystemState 访问 World——生成延迟命令；",
            "  - 🔧 CommandQueue 允许异步任务修改 ECS——突破异步任务不能直接访问 World 的限制；",
            "- **3D 网格任务**:",
            "  - 每个任务计算一个 3D 位置——在异步线程中执行；",
            "  - Task 完成后移除 ComputeTransform 组件——清理标记；",
            "  - 🔧 多个任务并行执行——利用多核 CPU 计算密集型任务；",
            "- **注意事项**:",
            "  - ⚠️ CommandQueue 必须在主线程 apply——不能在异步任务中直接修改 World；",
            "  - 🔧 适合：程序化网格生成/物理模拟/AI 计算等耗时操作；",
        ],
        [
            "知：<br>- Task<CommandQueue> 组件轮询；<br>- check_ready 非阻塞检查；<br>- CommandQueue 延迟命令。",
            "例：<br>- async_tasks/async_channel_pattern.rs(326)。",
        ],
    ),
    (
        328,
        "异步任务",
        [
            "**意图**：外部线程通信——跨线程通道 + Message API 将外部数据注入 ECS，FixedUpdate 控制读取频率；⭐⭐⭐",
            "- **外部线程创建**:",
            "  - std::thread::spawn 创建独立线程——与 Bevy 主循环并行运行；",
            "  - crossbeam::bounded(1) 有界通道——仅容纳 1 条消息，实现背压；",
            "  - 🔧 有界通道防止数据堆积——发送方在接收方消费前阻塞；",
            "- **Message API**:",
            "  - #[derive(Message)] 定义 ECS 消息类型——替代旧的 Event 系统；",
            "  - add_message::<StreamMessage>() 注册消息类型——系统级注册；",
            "  - MessageWriter 发送消息，MessageReader 接收消息——类型安全的通信；",
            "  - 🔧 Message 比 Event 更轻量——专为跨线程/异步通信设计；",
            "- **FixedUpdate 频率控制**:",
            "  - 从外部线程的 Update 读取改为 FixedUpdate 读取——固定频率消费；",
            "  - Time::<Fixed>::from_seconds(0.5) 每 0.5 秒读取一次；",
            "  - 🔧 固定频率读取避免帧率波动影响数据消费速度；",
            "- **Text2d 动态生成**:",
            "  - 从消息数据生成 Text2d 实体——外部数据驱动 UI；",
            "  - move_text 系统每帧下移文本——超出窗口时 despawn；",
            "  - 🔧 外部数据 → 消息 → ECS 实体的标准流程；",
            "- **确定性随机数**:",
            "  - ChaCha8Rng::seed_from_u64(42) 确定性 RNG——每次运行结果相同；",
            "  - 🔧 确定性随机数对回归测试和调试至关重要；",
            "- **注意事项**:",
            "  - ⚠️ 有界通道在接收方未消费时会阻塞发送方——注意线程死锁风险；",
            "  - 🔧 适合：网络数据接收/文件系统监控/外部传感器数据；",
        ],
        [
            "知：<br>- 跨线程通道通信；<br>- Message API ECS 消息；<br>- FixedUpdate 频率控制。",
            "例：<br>- async_tasks/async_channel_pattern.rs(326)。",
        ],
    ),
    # ── math (329-334) ─────────────────────────────────────────
    (
        329,
        "数学",
        [
            "**意图**：2D 包围体相交检测——Aabb2d/BoundingCircle 的交集测试、射线投射和扫掠测试完整演示；⭐⭐⭐",
            "- **包围体类型**:",
            "  - Aabb2d 轴对齐包围盒——基于 center + half_extents；",
            "  - BoundingCircle 包围圆——基于 center + radius；",
            "  - aabb_2d(isometry) / bounding_circle(isometry) 从图元生成包围体；",
            "  - 🔧 包围体是碰撞检测的第一阶段——快速排除不相交的对；",
            "- **相交测试**:",
            "  - aabb.intersects(&other_aabb) AABB vs AABB；",
            "  - circle.intersects(&aabb) 圆 vs AABB；",
            "  - aabb.intersects(&circle) AABB vs 圆；",
            "  - 🔧 所有包围体类型支持双向相交测试——任意组合；",
            "- **射线投射**:",
            "  - ray.aabb_intersection_at() 返回 Option<f32>——命中时间(TOI)；",
            "  - ray.circle_intersection_at() 圆射线投射；",
            "  - ray.aabb_cast_at() 扫掠投射——带尺寸的 AABB 移动检测；",
            "  - 🔧 TOI 为 0.0 表示起始即命中——需要额外处理；",
            "- **Gizmos 可视化**:",
            "  - Gizmos::primitive_2d 绘制原始形状——旋转动画展示；",
            "  - Gizmos::rect_2d / circle_2d 绘制包围体轮廓；",
            "  - 红色=相交，白色=未相交——实时视觉反馈；",
            "  - 🔧 Gizmos 调试工具在碰撞检测开发中不可或缺；",
            "- **状态驱动测试**:",
            "  - Test 枚举状态：AabbSweep/CircleSweep/RayCast/AabbCast/CircleCast；",
            "  - Space 键循环切换测试模式——同一场景不同测试；",
            "  - run_if(in_state(Test::RayCast)) 条件系统——仅在对应状态运行；",
            "  - 🔧 状态系统让一个示例覆盖多种测试场景；",
            "- **注意事项**:",
            "  - ⚠️ 包围体是近似检测——可能产生误报（AABB 重叠但形状未接触）；",
            "  - 🔧 实际碰撞检测需要包围体粗检测 + 精确几何检测两阶段；",
        ],
        [
            "知：<br>- Aabb2d/BoundingCircle 包围体；<br>- 射线投射 TOI；<br>- 扫掠测试 sweep。",
            "例：<br>- 2D/move_sprite.rs(3)。",
        ],
    ),
    (
        330,
        "数学",
        [
            "**意图**：三次贝塞尔曲线交互编辑——Hermite/Cardinal/B-spline 三种插值模式 + 循环曲线 + 鼠标拖拽控制点；⭐⭐⭐",
            "- **CubicHermite/CubicCardinalSpline/CubicBSpline**:",
            "  - Hermite: 需要控制点+切线——完全控制曲线形状；",
            "  - Cardinal (Catmull-Rom): 仅需控制点——切线自动计算，tension 参数控制张力；",
            "  - B-spline: 平滑逼近控制点——曲线不经过控制点（仅在循环模式下经过）；",
            "  - 🔧 三种模式适合不同场景：Hermite 精确控制，Cardinal 平滑路径，B-spline 有机形状；",
            "- **to_curve() / to_curve_cyclic()**:",
            "  - to_curve() 将构建器转换为 CubicCurve<Vec2>——需要足够控制点；",
            "  - to_curve_cyclic() 创建循环曲线——首尾相接；",
            "  - 🔧 CubicCurve 支持 sample(t) 采样——t 在 [0, length] 范围内；",
            "- **Gizmos 曲线渲染**:",
            "  - gizmos.linestrip_2d(points) 绘制曲线——采样 50+ 个点；",
            "  - gizmos.arrow_2d(origin, origin + tangent) 绘制切线箭头；",
            "  - gizmos.circle_2d(control_point, 5.0, RED) 绘制控制点；",
            "  - 🔧 Gizmos 调试可视化帮助理解曲线数学特性；",
            "- **鼠标交互编辑**:",
            "  - camera.viewport_to_world_2d() 屏幕坐标→世界坐标转换；",
            "  - 鼠标左键拖拽放置控制点——同时设置切线方向；",
            "  - S 键切换模式，C 键切换循环，R 键移除最后一个点；",
            "  - 🔧 交互式编辑器是理解曲线数学的最佳方式；",
            "- **注意事项**:",
            "  - ⚠️ B-spline 在非循环模式下曲线不经过控制点——这是设计如此；",
            "  - 🔧 Cardnal 的 tension 参数：0.0=尖角，0.5=Catmull-Rom，1.0=线性；",
        ],
        [
            "知：<br>- CubicHermite/CardinalSpline/BSpline 三种插值；<br>- to_curve 曲线构建；<br>- 鼠标交互编辑。",
            "例：<br>- transforms/transform.rs(30)。",
        ],
    ),
    (
        331,
        "数学",
        [
            "**意图**：所有 Bevy 数学图元的 2D/3D Mesh 和 Gizmo 可视化——20 种图元的完整渲染对比；⭐⭐⭐",
            "- **图元类型全覆盖**:",
            "  - 2D: Rectangle, Circle, Ellipse, Triangle2d, Capsule2d, RegularPolygon, Polygon, Arc2d, CircularSector, CircularSegment, Annulus, Plane2d, Line2d, Segment2d, Polyline2d；",
            "  - 3D: Cuboid, Sphere, Capsule3d, Cylinder, Cone, ConicalFrustum, Torus, Tetrahedron, Triangle3d, Plane3d, Line3d, Segment3d, Polyline3d, Extrusion；",
            "  - 🔧 每种图元都有 primitive.mesh().build() 方法生成 Mesh——无需手动构建顶点；",
            "- **双渲染对比**:",
            "  - Mesh 渲染（Mesh3d/Mesh2d + Material）——完整光照/纹理效果；",
            "  - Gizmo 渲染（Gizmos::primitive_2d/3d）——线框/轮廓调试；",
            "  - 🔧 对比两种渲染方式帮助理解图元的数学定义和视觉表现；",
            "- **CameraActive 状态**:",
            "  - Dim2/Dim3 状态切换 2D/3D 相机——C 键切换；",
            "  - Camera { is_active } 控制相机激活状态——同时只能有一个活跃相机；",
            "  - 🔧 UiTargetCamera 在切换时重新绑定——确保 UI 跟随正确的相机；",
            "- **PrimitiveSelected 状态**:",
            "  - 20 种图元状态——Tab 键循环切换；",
            "  - 每种图元独立的 Mesh 和 Gizmo 实体——Visibility 控制显隐；",
            "  - 🔧 状态系统让一个示例展示所有图元——避免 20 个独立示例；",
            "- **Gizmo 旋转动画**:",
            "  - gizmos.primitive_2d(&shape, isometry, color) 带旋转的图元绘制；",
            "  - Rot2::radians(time) / Quat::from_rotation_y(time) 连续旋转；",
            "  - 🔧 旋转动画让 3D 图元的形状更易辨识；",
            "- **注意事项**:",
            "  - ⚠️ Mesh::try_from(primitive) 可能失败——某些图元不支持 Mesh 生成；",
            "  - 🔧 非 wasm 平台支持线框模式——WireframePlugin 调试用途；",
        ],
        [
            "知：<br>- 20 种 Bevy 数学图元；<br>- Mesh/Gizmo 双渲染；<br>- 状态驱动相机切换。",
            "例：<br>- 2D/2d_shapes.rs(12)；<br>- 3D/3d_shapes.rs(33)。",
        ],
    ),
    (
        332,
        "数学",
        [
            "**意图**：从 3D 图元随机采样点——Cuboid/Sphere/Capsule/Cylinder/Tetrahedron/Triangle 六种形状的内部/边界采样；⭐⭐⭐",
            "- **ShapeSample trait**:",
            "  - sample_interior(rng) 在形状内部均匀采样——连续分布；",
            "  - sample_boundary(rng) 在形状边界采样——表面分布；",
            "  - 🔧 Bevy 为所有内置图元实现了 ShapeSample——开箱即用；",
            "- **自定义 Shape 枚举**:",
            "  - Cuboid/Sphere/Capsule3d/Cylinder/Tetrahedron/Triangle3d 六种变体；",
            "  - impl ShapeSample for Shape 委托给具体类型——match 分发；",
            "  - 🔧 枚举包装允许运行时选择采样形状——比泛型更灵活；",
            "- **采样点可视化**:",
            "  - 小球 Mesh 渲染采样点——Mesh3d + MeshMaterial3d；",
            "  - ChaCha8Rng 确定性随机数——可复现的采样结果；",
            "  - 🔧 透明材质(AlphaMode::Blend)允许观察重叠的采样点；",
            "- **交互控制**:",
            "  - S 键采样一个点，D 键采样 100 个点，R 键重置；",
            "  - M 键切换 Interior/Boundary 模式——对比两种采样方式；",
            "  - 鼠标拖拽旋转相机——AccumulatedMouseMotion 平滑输入；",
            "  - 🔧 单次和批量采样对比——展示分布特性；",
            "- **注意事项**:",
            "  - ⚠️ 边界采样在角落/边缘可能产生聚集——这是均匀采样的数学特性；",
            "  - 🔧 采样算法对性能有影响——Sphere 最快，Tetrahedron 需要额外计算；",
        ],
        [
            "知：<br>- ShapeSample trait 随机采样；<br>- sample_interior/sample_boundary；<br>- 确定性随机数。",
            "例：<br>- math/random_sampling.rs(332)。",
        ],
    ),
    (
        333,
        "数学",
        [
            "**意图**：所有数学图元的采样演示——自动/手动模式切换，粒子生成+消失动画，Bloom 泛光效果；⭐⭐⭐",
            "- **自定义 ShapeSample**:",
            "  - Shape 枚举实现 ShapeSample——委托给具体类型；",
            "  - impl Meshable for Shape 生成 Mesh——自定义 MeshBuilder；",
            "  - 🔧 自定义图元需要同时实现 ShapeSample 和 Meshable 才能完整使用；",
            "- **自动/手动采样**:",
            "  - SpawningMode::Manual: 按键触发采样；",
            "  - SpawningMode::Automatic: 每帧自动生成，最多 1000 个/帧；",
            "  - SpawnQueue Resource 追踪待生成数量——帧预算控制；",
            "  - 🔧 帧预算避免卡顿——每帧最多处理固定数量的生成/销毁；",
            "- **粒子生命周期动画**:",
            "  - SpawningPoint: 缩放动画从 0→1——渐显效果；",
            "  - DespawningPoint: 缩放动画从 1→0——渐隐效果；",
            "  - 两阶段动画：生成 → 可见 → 销毁动画 → 实际销毁；",
            "  - 🔧 分离动画组件便于系统独立处理——符合 ECS 最佳实践；",
            "- **Bloom 泛光**:",
            "  - Bloom::NATURAL 启用自然泛光；",
            "  - Tonemapping::TonyMcMapface 色调映射；",
            "  - FireflyLights 组件根据粒子数量调整光源强度——动态光照；",
            "  - 🔧 泛光让采样点呈现萤火虫般的效果——视觉增强；",
            "- **CameraRig 组件**:",
            "  - yaw/pitch/distance/target 存储轨道相机参数；",
            "  - 鼠标拖拽控制 yaw/pitch，滚轮控制 distance；",
            "  - 🔧 自定义相机控制器比内置更灵活——可精确控制轨道行为；",
            "- **注意事项**:",
            "  - ⚠️ MAX_POINTS 限制最大粒子数——超过时随机销毁旧粒子；",
            "  - 🔧 children![] 宏简化子实体创建——每个粒子带光源子实体；",
        ],
        [
            "知：<br>- 自定义 ShapeSample/Meshable；<br>- 粒子生命周期动画；<br>- Bloom 泛光效果。",
            "例：<br>- math/random_sampling.rs(332)；<br>- 3D/bloom_3d.rs(18)。",
        ],
    ),
    (
        334,
        "数学",
        [
            "**意图**：自定义图元完整指南——Heart 心形图元的 Primitive2d/Measured2d/Bounded2d/Meshable 全套 trait 实现；⭐⭐⭐",
            "- **Primitive2d trait**:",
            "  - impl Primitive2d for Heart {} 最小实现——空 trait body；",
            "  - 🔧 Primitive2d 标记类型为 2D 图元——启用 Bevy 图元系统集成；",
            "- **Measured2d trait**:",
            "  - perimeter() 计算周长——基于半径的近似公式；",
            "  - area() 计算面积——心形面积公式；",
            "  - 🔧 周长和面积用于碰撞检测和物理模拟——精度要求不高时可用近似值；",
            "- **Bounded2d trait**:",
            "  - bounding_rectangle 计算 AABB——基于半径的矩形包围；",
            "  - bounding_circle 计算包围圆——心形的最小包围圆；",
            "  - 🔧 包围体用于快速碰撞检测——精确检测才使用原始形状；",
            "- **Meshable trait + HeartMeshBuilder**:",
            "  - resolution 控制网格精度——顶点数 = resolution × 2；",
            "  - mesh() 方法生成顶点/法线/UV/索引——心形参数方程；",
            "  - PerimeterSegment::Smooth 生成平滑侧面——用于 Extrusion；",
            "  - 🔧 MeshBuilder 是 Bevy 的网格构建接口——自定义形状的核心；",
            "- **Extrusion 3D 挤压**:",
            "  - Extrusion<Heart> 将 2D 心形挤压为 3D——depth 控制厚度；",
            "  - Ring<Heart> 从心形生成环形——inner_radius 控制内径；",
            "  - 🔧 Extrusion/Ring 是通用容器——任何 2D 图元都支持；",
            "- **BoundingShape 状态**:",
            "  - None/BoundingSphere/BoundingBox 三种包围体可视化；",
            "  - Gizmos 绘制包围体——调试碰撞检测；",
            "  - 🔧 可视化包围体帮助验证碰撞检测的准确性；",
            "- **注意事项**:",
            "  - ⚠️ with_inner() 配置嵌套 MeshBuilder——Ring 需要内部图元的 MeshBuilder；",
            '  - 🔧 平台条件编译 #[cfg(not(target_family = "wasm"))] 仅原生支持线框模式；',
        ],
        [
            "知：<br>- Primitive2d 自定义图元；<br>- Meshable 网格生成；<br>- Extrusion 挤压/Ring 环形。",
            "例：<br>- math/render_primitives.rs(331)；<br>- 3D/3d_shapes.rs(33)。",
        ],
    ),
    # ── movement (335-336) ─────────────────────────────────────
    (
        335,
        "移动",
        [
            "**意图**：固定时间步长物理——分离物理状态(PhysicalTranslation)和渲染状态(Transform)，通过插值实现平滑视觉效果；⭐⭐⭐",
            "- **物理/渲染状态分离**:",
            "  - PhysicalTranslation 物理位置——仅在 FixedUpdate 中更新；",
            "  - PreviousPhysicalTranslation 上一帧物理位置——用于插值；",
            "  - Transform 视觉位置——每帧通过插值计算，驱动实际渲染；",
            "  - 🔧 分离物理和渲染是 Fixed Timestep 模式的核心——确保确定性物理；",
            "- **FixedUpdate 调度**:",
            "  - RunFixedMainLoop::BeforeFixedMainLoop: 输入累积→物理更新→清除输入；",
            "  - RunFixedMainLoop::AfterFixedMainLoop: 插值计算→相机同步；",
            "  - 🔧 固定频率物理更新——不受帧率波动影响，60fps 和 30fps 物理行为一致；",
            "- **overstep_fraction() 插值**:",
            "  - time.overstep_fraction() 获取固定步长之间的插值因子 [0,1)；",
            "  - Vec3::lerp(prev, current, fraction) 线性插值——平滑过渡；",
            "  - 🔧 插值消除固定步长的视觉卡顿——每帧都更新渲染位置；",
            "- **输入累积**:",
            "  - AccumulatedInput 存储 WASD 输入——旋转后累加到 Velocity；",
            "  - clear_input 系统在固定步长后清除——防止重复累积；",
            "  - 🔧 输入在固定步长之前累积——确保物理步长使用正确的输入；",
            "- **相机跟随**:",
            "  - translate_camera 将相机同步到玩家插值位置；",
            "  - 移动设备：AccumulatedMouseMotion 控制相机旋转；",
            "  - Pitch clamp 防止万向锁——(-FRAC_PI_2, FRAC_PI_2) 范围限制；",
            "  - 🔧 相机跟随使用插值位置而非物理位置——视觉更平滑；",
            "- **注意事项**:",
            "  - ⚠️ DidFixedTimestepRunThisFrame 标记防止每帧多次插值；",
            "  - 🔧 clamp_length_max(1.0) 标准化模拟输入——防止对角线超速；",
        ],
        [
            "知：<br>- 物理/渲染状态分离；<br>- overstep_fraction 插值；<br>- RunFixedMainLoop 调度顺序。",
            "例：<br>- ecs/fixed_timestep.rs(140)；<br>- transforms/transform.rs(30)。",
        ],
    ),
    (
        336,
        "移动",
        [
            "**意图**：平滑跟随——Transform::smooth_nudge 指数衰减插值实现目标跟踪，配合随机目标生成；⭐⭐",
            "- **Transform::smooth_nudge()**:",
            "  - smooth_nudge(target, decay_rate, delta_time) 指数衰减趋近目标；",
            "  - decay_rate 控制跟踪速度——越大越快到达目标；",
            "  - 🔧 smooth_nudge 比 lerp 更自然——接近目标时自动减速，无过冲；",
            "- **Dir3::new() 到达检测**:",
            "  - Dir3::new(direction) 返回 Result——方向向量接近零时返回 Err；",
            "  - Err 表示到达目标——触发新目标生成；",
            "  - 🔧 利用 Dir3 的零向量检测作为到达判断——简洁高效；",
            "- **随机目标生成**:",
            "  - Cuboid::sample_interior(rng) 在边界框内随机采样——生成新目标位置；",
            "  - ChaCha8Rng 确定性随机数——可复现的移动路径；",
            "  - 🔧 采样边界框比全空间采样更可控——限制目标范围；",
            "- **Single<> 查询**:",
            "  - Single<&mut Transform, With<FollowingSphere>> 单一实体查询；",
            "  - Single<&Transform, With<TargetSphere>> 单一目标查询；",
            "  - 🔧 Single 在确定只有一个实体时使用——比 Query 更简洁；",
            "- **速度控制**:",
            "  - f32::min(speed * delta, distance) 限制最大步长——防止超调；",
            "  - TargetSphereSpeed Resource 存储速度参数——运行时可调；",
            "  - 🔧 速度限制确保即使大时间步长也不会跳过目标；",
            "- **注意事项**:",
            "  - ⚠️ smooth_nudge 是指数衰减——永远不会完全到达目标（渐近线）；",
            "  - 🔧 Dir3::new 的 Err 检测提供了自然的到达阈值——避免手动计算距离；",
        ],
        [
            "知：<br>- smooth_nudge 指数衰减跟随；<br>- Dir3::new 零向量检测；<br>- 随机目标生成。",
            "例：<br>- movement/physics_in_fixed_timestep.rs(335)；<br>- camera/2d_top_down_camera.rs(198)。",
        ],
    ),
    # ── remote (337-338) ───────────────────────────────────────
    (
        337,
        "远程控制",
        [
            "**意图**：BRP 服务器——RemotePlugin + RemoteHttpPlugin 暴露 Bevy 应用的 ECS 世界，支持远程查询和编辑；⭐⭐",
            "- **RemotePlugin 配置**:",
            "  - RemotePlugin::default() 启用 BRP 服务器——默认监听 HTTP；",
            "  - RemoteHttpPlugin::default() HTTP 传输层——JSON-RPC 2.0 协议；",
            "  - 🔧 BRP 是 Bevy 的远程调试协议——允许外部工具检查和修改 ECS 状态；",
            "- **Reflect 派生**:",
            "  - #[reflect(Resource, Serialize, Deserialize)] 标记可远程访问的资源；",
            "  - #[reflect(Component, Serialize, Deserialize)] 标记可远程访问的组件；",
            "  - ⚠️ 没有 Reflect 派生的组件/资源无法被 BRP 查询；",
            "  - 🔧 Serialize + Deserialize 确保 JSON 序列化兼容——BRP 使用 JSON-RPC；",
            "- **TestResource 示例**:",
            "  - foo: Vec2 + bar: bool 演示复合类型远程访问；",
            "  - 🔧 Resource 和 Component 都可以被远程读取和修改；",
            "- **Cube 组件**:",
            "  - f32 值字段——演示组件属性的远程编辑；",
            "  - move_cube 系统每帧移动——远程可观察到位置变化；",
            "  - 🔧 远程编辑组件后，本地系统会立即使用新值——实时生效；",
            "- **注意事项**:",
            "  - ⚠️ 默认监听 localhost:127.0.0.1:15702——生产环境需配置安全策略；",
            "  - 🔧 配合 client.rs 使用——命令行客户端发送查询请求；",
        ],
        [
            "知：<br>- RemotePlugin BRP 服务器；<br>- Reflect 远程可访问；<br>- JSON-RPC 2.0 协议。",
            "例：<br>- app/empty_defaults.rs(108)。",
        ],
    ),
    (
        338,
        "远程控制",
        [
            "**意图**：BRP 命令行客户端——通过 HTTP POST 向运行中的 Bevy 应用发送 JSON-RPC 查询，获取 ECS 世界数据；⭐⭐",
            "- **BrpRequest JSON-RPC**:",
            "  - BrpQuery { filter, components } 构建查询请求；",
            "  - BrpQueryFilter { without: [...] } 排除过滤——不返回包含指定组件的实体；",
            "  - BrpQueryFilter { with: [...] } 包含过滤——仅返回包含指定组件的实体；",
            "  - 🔧 JSON-RPC 2.0 格式——标准远程过程调用协议；",
            "- **三种查询模式**:",
            "  - run_transform_only_query: 查询所有带 Transform 的实体；",
            "  - run_query_root_entities: 查询根实体（无 ChildOf 组件）；",
            "  - run_query_all_components_and_entities: 查询整个 ECS 世界；",
            "  - 🔧 渐进式查询复杂度——从特定组件到完整世界；",
            "- **ureq HTTP 客户端**:",
            "  - ureq::post(url).send_json(&request) 发送请求；",
            "  - response.into_json::<Value>() 解析 JSON 响应；",
            "  - 🔧 ureq 是同步 HTTP 客户端——命令行工具的理想选择；",
            "- **BrpQueryParams 参数**:",
            "  - components: ComponentSelector::All 查询所有组件；",
            "  - 或指定具体组件列表——精确查询；",
            "  - 🔧 ComponentSelector::All 适合调试——生产环境建议指定组件；",
            "- **注意事项**:",
            "  - ⚠️ 客户端假设服务器在 localhost:15702 运行——需先启动 server.rs；",
            "  - 🔧 响应数据是 serde_json::Value——动态类型，可进一步处理/过滤；",
        ],
        [
            "知：<br>- BrpRequest 查询请求；<br>- BrpQueryFilter 过滤；<br>- ureq HTTP 客户端。",
            "例：<br>- remote/server.rs(337)。",
        ],
    ),
    # ── games (339-345) ────────────────────────────────────────
    (
        339,
        "游戏示例",
        [
            "**意图**：经典打砖块游戏——完整的 Breakout 实现，包含挡板控制、球反弹物理、砖块碰撞、计分系统和音效；⭐⭐⭐",
            "- **碰撞检测系统**:",
            "  - BoundingCircle(Ball) vs Aabb2d(Wall/Brick) 包围体相交测试；",
            "  - Collision 枚举标识碰撞方向(Left/Right/Top/Bottom)——决定反弹方向；",
            "  - 🔧 AABB-Circle 碰撞需要计算最近点——circle.center 到 aabb 的最近点距离；",
            "- **球反弹物理**:",
            "  - velocity.x/y 根据碰撞方向取反——Left/Right 反转 X，Top/Bottom 反转 Y；",
            "  - BallCollided Event 触发音效——Observer 模式处理；",
            "  - 🔧 64Hz FixedUpdate 确保高速球不会穿透薄砖块；",
            "- **挡板控制**:",
            "  - ArrowLeft/Right 键盘控制——velocity.x = ±PLAYER_SPEED；",
            "  - 窗口边界钳制——防止挡板移出视野；",
            "  - 🔧 挡板仅水平移动——经典的 Breakout 操作方式；",
            "- **砖块系统**:",
            "  - Brick 组件标记可破坏砖块；",
            "  - 碰撞后 despawn 砖块实体——Score += 1；",
            "  - 🔧 砖块排列使用嵌套循环——计算行列位置；",
            "- **音效系统**:",
            "  - AudioPlayer(sound.clone()) 播放碰撞音效；",
            "  - PlaybackSettings::DESPAWN 自动清理播放完成的音频实体；",
            "  - 🔧 Observer 监听 BallCollided 事件——事件驱动音效播放；",
            "- **计分板 UI**:",
            "  - TextUiWriter 动态更新分数显示；",
            "  - TextFont 设置字号——ScoreboardUi 组件标记文本实体；",
            "  - 🔧 计分系统与游戏逻辑解耦——通过 Score Resource 访问；",
            "- **注意事项**:",
            "  - ⚠️ Wall 使用 #[require(Sprite, Transform, Collider)] 声明式组件依赖；",
            "  - 🔧 Sprite::from_color() 创建纯色精灵——无需加载纹理；",
        ],
        [
            "知：<br>- AABB-Circle 碰撞检测；<br>- Observer 事件音效；<br>- FixedUpdate 物理。",
            "例：<br>- 2D/2d_shapes.rs(12)；<br>- math/bounding_2d.rs(329)。",
        ],
    ),
    (
        340,
        "游戏示例",
        [
            "**意图**：贡献者展示——从 git log 读取真实贡献者数据，弹跳球体展示，定时轮播选中效果；⭐⭐",
            "- **Git 数据加载**:",
            "  - std::process::Command 执行 git log 解析贡献者；",
            "  - LoadContributorsError thiserror 错误类型——优雅处理 git 不可用的情况；",
            "  - 🔧 CI 环境可能没有 git——fallback 默认数据确保测试通过；",
            "- **Contributor 组件**:",
            "  - name/num_commits/hue 存储贡献者信息；",
            "  - hue 从名字哈希计算——Hsla 颜色确保每个贡献者独特颜色；",
            "  - 🔧 确定性哈希→色相映射——同一贡献者每次运行颜色相同；",
            "- **弹跳物理**:",
            "  - Aabb2d::new(center, half_size) 窗口边界碰撞检测；",
            "  - velocity.translation.y -= gravity 模拟重力；",
            "  - 边界反弹时随机调整高度——增加视觉趣味性；",
            "  - 🔧 简化物理——无球体间碰撞，仅窗口边界反弹；",
            "- **选中轮播**:",
            "  - SelectionTimer 重复定时器——每 3 秒切换选中贡献者；",
            "  - select()/deselect() 函数——z 轴偏移 + 精灵翻转标记选中状态；",
            "  - ContributorDisplay TextUiWriter 更新显示文本；",
            "  - 🔧 选中效果：z+0.1 提升层级 + flip_x 水平翻转；",
            "- **注意事项**:",
            "  - ⚠️ git 命令失败时使用 fallback 数据——保证任何环境都能运行；",
            "  - 🔧 SharedRng ChaCha8Rng 确定性随机数——可复现的弹跳轨迹；",
        ],
        [
            "知：<br>- Git 进程数据加载；<br>- 弹跳物理模拟；<br>- 定时轮播展示。",
            "例：<br>- 2D/sprite.rs(2)。",
        ],
    ),
    (
        341,
        "游戏示例",
        [
            "**意图**：多屏游戏菜单——Splash→Menu→Settings→Game 完整状态机，嵌套状态管理 + 按钮交互 + 设置选择；⭐⭐⭐",
            "- **嵌套状态机**:",
            "  - GameState: Splash/Menu/Game 管理游戏级状态；",
            "  - MenuState: Main/Settings/SettingsDisplay/SettingsSound/Disabled 管理菜单级状态；",
            "  - 🔧 嵌套状态允许独立导航——菜单状态不影响游戏状态；",
            "- **DespawnOnExit(T)**:",
            "  - 状态退出时自动 despawn 关联实体——状态作用域清理；",
            "  - OnSplashScreen/OnGameScreen/OnMainMenuScreen 等标记组件；",
            "  - 🔧 DespawnOnExit 比手动清理更安全——避免遗漏清理导致幽灵实体；",
            "- **generic setting_button<T>**:",
            "  - setting_button<T: Resource + Component + PartialEq + Copy> 泛型设置选择系统；",
            "  - DisplayQuality/Volume 不同类型复用同一选择逻辑；",
            "  - SelectedOption 标记当前选中项——视觉反馈；",
            "  - 🔧 泛型系统避免重复代码——一套逻辑处理所有设置类型；",
            "- **按钮颜色状态**:",
            "  - 正常: 深灰色；悬停: 浅灰色；悬停+选中: 白色；按下: 深蓝色；",
            "  - Interaction 枚举驱动颜色变化——None/Hovered/Pressed；",
            "  - 🔧 四种颜色状态覆盖所有交互组合——清晰的视觉反馈；",
            "- **SpawnIter 动态 UI**:",
            "  - SpawnIter(iterator) 从迭代器批量生成子实体；",
            "  - SpawnWith(closure) 闭包生成——可访问外部状态；",
            "  - 🔧 动态 UI 生成比静态 children![] 更灵活——适合列表/网格布局；",
            "- **注意事项**:",
            "  - ⚠️ AppState(AppExit::Success) 退出应用——不是 std::process::exit；",
            "  - 🔧 SettingsResource<T> 泛型包装设置值——统一访问模式；",
        ],
        [
            "知：<br>- 嵌套状态机(GameState+MenuState)；<br>- DespawnOnExit 状态清理；<br>- 泛型 setting_button。",
            "例：<br>- state/states.rs(155)；<br>- ui/button.rs(231)。",
        ],
    ),
    (
        342,
        "游戏示例",
        [
            "**意图**：加载屏幕——同时追踪资产加载和 GPU 管线编译状态，确认帧防止闪烁，SystemId 动态关卡切换；⭐⭐⭐",
            "- **双状态追踪**:",
            "  - AssetServer::get_recursive_dependency_load_state() 检查资产加载；",
            "  - RenderApp + PipelineCache::waiting_pipelines() 检查 GPU 管线编译；",
            "  - ⚠️ 资产加载完成≠渲染就绪——管线编译可能延迟；",
            "  - 🔧 同时追踪两种加载状态才能准确判断「真正就绪」；",
            "- **确认帧机制**:",
            "  - LoadingData::confirmation_frames 追踪连续确认帧数；",
            "  - 连续 3 帧确认才切换到就绪状态——防止快速加载/卸载时的闪烁；",
            "  - 🔧 确认帧是 UI 稳定性的常用技巧——避免 loading→ready→loading 抖动；",
            "- **SystemId 动态关卡**:",
            "  - commands.register_system() 注册关卡加载/卸载系统为 SystemId；",
            "  - commands.run_system(id) 运行时动态执行——运行时选择关卡；",
            "  - 🔧 SystemId 比枚举匹配更灵活——支持动态注册新关卡；",
            "- **UntypedHandle 类型擦除**:",
            "  - loading_assets: Vec<UntypedHandle> 跟踪所有加载中的资产；",
            "  - UntypedHandle 脱离泛型——统一处理不同类型的资产句柄；",
            "  - 🔧 类型擦除允许异构资产列表——Mesh/Scene/Texture 混合追踪；",
            "- **加载屏幕 UI**:",
            "  - Camera { order: 1 } 覆盖相机——加载屏幕渲染在游戏之上；",
            "  - LoadingScreen 标记组件——控制加载屏幕显隐；",
            "  - 🔧 覆盖相机不影响游戏相机——两层独立渲染；",
            "- **注意事项**:",
            "  - ⚠️ RenderApp 子应用通过 ExtractSchedule 跨世界通信——管线状态需提取；",
            "  - 🔧 适合：大型关卡加载/远程资产下载/着色器热重载场景；",
        ],
        [
            "知：<br>- 资产加载+管线编译双追踪；<br>- SystemId 动态系统；<br>- 确认帧防闪烁。",
            "例：<br>- asset/asset_loading.rs(159)；<br>- state/states.rs(155)。",
        ],
    ),
    (
        343,
        "游戏示例",
        [
            "**意图**：完整 3D 小游戏——外星人吃蛋糕，网格移动+GLTF 模型加载+计分系统+游戏结束+相机跟踪；⭐⭐⭐",
            "- **GameState 状态机**:",
            "  - Playing/GameOver 两种状态——DespawnOnExit(Playing) 自动清理；",
            "  - OnEnter(Playing) 初始化游戏——重置分数/棋盘/玩家；",
            "  - OnEnter(GameOver) 显示结算画面——最终分数+重新开始提示；",
            "  - 🔧 状态驱动的游戏生命周期——清晰的状态转换逻辑；",
            "- **Game Resource**:",
            "  - board: Vec<Vec<Cell>> 棋盘数据——存储高度信息；",
            "  - player/bonus 结构体追踪实体和网格位置；",
            "  - score/cake_eaten 全局状态——驱动游戏逻辑和 UI；",
            "  - 🔧 单一 Resource 存储所有游戏状态——集中管理便于序列化；",
            "- **网格移动**:",
            "  - Arrow 键控制网格位置(i,j)——非连续移动；",
            "  - move_cooldown: Timer 防止过快移动——0.15 秒冷却；",
            "  - let-else + let-chains 组合条件——优雅处理 Option 嵌套；",
            "  - 🔧 网格移动比连续移动更适合棋盘游戏——精确的格子控制；",
            "- **GLTF 场景加载**:",
            "  - GltfAssetLabel::Scene(0).from_asset() 加载 GLTF 场景；",
            "  - SceneRoot(scene) 生成场景实体——包含动画/材质/网格；",
            "  - 🔧 GLTF 是游戏资产的标准格式——支持动画/材质/骨骼；",
            "- **相机平滑跟踪**:",
            "  - focus_camera 系统在 player 和 bonus 之间平滑切换焦点；",
            "  - Vec3::new() + Lerp 插值——相机跟随游戏焦点变化；",
            "  - 🔧 相机焦点随游戏事件变化——增强游戏体验；",
            "- **ParamSet 多查询**:",
            "  - 同时查询 Camera3d 和普通 Transform——ParamSet 解决查询冲突；",
            "  - 🔧 ParamSet 允许同一系统访问多个冲突查询——ECS 灵活性的体现；",
            "- **注意事项**:",
            "  - ⚠️ CI 环境使用 fallback 数据（GITHUB_ACTIONS 环境变量检测）；",
            "  - 🔧 children![] 宏创建 bonus 光源子实体——灯光跟随蛋糕移动；",
        ],
        [
            "知：<br>- 游戏状态机；<br>- GLTF 场景加载；<br>- 网格移动+冷却。",
            "例：<br>- 3D/3d_scene.rs(32)；<br>- gltf/load_gltf.rs(290)。",
        ],
    ),
    (
        344,
        "游戏示例",
        [
            "**意图**：透明窗口桌面玩具——Bevy Logo + 物理驱动的 Googly Eyes，拖拽交互+点击穿透+窗口透明；⭐⭐⭐",
            "- **透明窗口**:",
            "  - Window { transparent: true, decorations: false } 无边框透明窗口；",
            "  - ClearColor(Color::NONE) 透明背景——alpha=0；",
            "  - WindowLevel::AlwaysOnTop 始终置顶——桌面玩具标准行为；",
            "  - 🔧 透明窗口需要平台支持——macOS 需要 PostMultiplied alpha；",
            "- **hit_test 点击穿透**:",
            "  - CursorOptions { hit_test } 控制鼠标事件穿透；",
            "  - 仅在 Logo 附近启用 hit_test——远离时鼠标穿透到下层窗口；",
            "  - 🔧 动态 hit_test 实现「智能穿透」——交互区域响应，空白区域穿透；",
            "- **拖拽交互**:",
            "  - DragOperation Resource 存储拖拽偏移——按下时记录，释放时清除；",
            "  - camera.viewport_to_world_2d() 屏幕→世界坐标转换；",
            "  - 🔧 拖拽偏移防止 Logo 跳到鼠标位置——平滑的拖拽体验；",
            "- **Googly Eyes 物理**:",
            "  - Pupil 组件存储 eye_radius/pupil_radius/velocity；",
            "  - 速度衰减：velocity *= powf(0.04, dt) 指数衰减；",
            "  - 边界反弹：velocity *= -0.5 反转+衰减；",
            "  - 🔧 物理驱动的瞳孔运动——拖拽时眼球跟随，释放后惯性晃动；",
            "- **层级实体结构**:",
            "  - BevyLogo → Eye → Sclera → Pupil → Highlight 四层嵌套；",
            "  - 每层独立的 Mesh2d + MeshMaterial2d 渲染；",
            "  - 🔧 层级结构便于独立控制每层的位置/缩放/颜色；",
            "- **注意事项**:",
            "  - ⚠️ 退出应用：Escape 键或右键点击——非标准退出方式；",
            "  - 🔧 Space 键切换透明模式——桌面模式 vs 窗口模式；",
        ],
        [
            "知：<br>- 透明窗口+hit_test 点击穿透；<br>- 物理驱动瞳孔运动；<br>- 层级实体结构。",
            "例：<br>- window/transparent_window.rs(217)；<br>- ecs/hierarchy.rs(128)。",
        ],
    ),
    (
        345,
        "游戏示例",
        [
            "**意图**：步进调度调试——SteppingPlugin 实现逐系统/逐帧步进，列出所有系统并可视化当前位置；⭐⭐",
            "- **SteppingPlugin 配置**:",
            "  - .add_schedule(ScheduleLabel) 添加需要步进的调度——可配置多个；",
            "  - .at(UiRect::LEFT) 设置 UI 位置——调试面板定位；",
            "  - 🔧 SteppingPlugin 是 Bevy 内置的调试工具——feature-gated；",
            "- **DebugSchedule 独立调度**:",
            "  - MainScheduleOrder::insert_after(Update, DebugSchedule) 插入在 Update 之后；",
            "  - 🔧 独立调度避免步进 UI 干扰游戏逻辑——UI 更新与游戏解耦；",
            "- **步进控制**:",
            "  - Backquote(`) 键切换步进模式——启用/禁用；",
            "  - S 键步进单个系统——仅执行光标所在的系统；",
            "  - Space 键步进整帧——执行所有系统到下一帧；",
            "  - 🔧 步进调试是排查系统执行顺序问题的利器；",
            "- **UI 列表显示**:",
            "  - schedule.systems() 遍历调度中的所有系统——获取 NodeId；",
            "  - build_ui 从 Schedules 元数据构建系统列表——动态生成；",
            "  - cursor() 获取当前步进位置——高亮显示；",
            "  - 🔧 懒构建 UI——可能在数据就绪前多次运行；",
            "- **InternedScheduleLabel**:",
            "  - 调度标签的内存高效表示——避免字符串比较开销；",
            "  - 🔧 Interned 类型在 Bevy 中广泛使用——性能关键路径的优化；",
            "- **注意事项**:",
            '  - ⚠️ cfg!(feature = "bevy_debug_stepping") 运行时特性检查；',
            "  - 🔧 步进调试会严重影响性能——仅在调试时启用；",
        ],
        [
            "知：<br>- SteppingPlugin 逐步调试；<br>- DebugSchedule 独立调度；<br>- InternedScheduleLabel。",
            "例：<br>- ecs/system_stepping.rs(153)。",
        ],
    ),
]


def build_entry_line(seq, cat, intent_lines, knowledge_lines):
    intent = "<br>".join(intent_lines)
    knowledge = "<br>".join(knowledge_lines)
    return f"| {seq} | {cat} | `{get_filename(seq)}` | {intent} | {knowledge} |"


def get_filename(seq):
    """Map sequence number to filename."""
    filenames = {
        316: "custom_post_processing.rs",
        317: "fullscreen_material.rs",
        318: "render_depth_to_texture.rs",
        319: "custom_phase_item.rs",
        320: "custom_render_phase.rs",
        321: "specialized_mesh_pipeline.rs",
        322: "manual_material.rs",
        323: "custom_shader_instancing.rs",
        324: "custom_vertex_attribute.rs",
        325: "texture_binding_array.rs",
        326: "async_channel_pattern.rs",
        327: "async_compute.rs",
        328: "external_source_external_thread.rs",
        329: "bounding_2d.rs",
        330: "cubic_splines.rs",
        331: "render_primitives.rs",
        332: "random_sampling.rs",
        333: "sampling_primitives.rs",
        334: "custom_primitives.rs",
        335: "physics_in_fixed_timestep.rs",
        336: "smooth_follow.rs",
        337: "server.rs",
        338: "client.rs",
        339: "breakout.rs",
        340: "contributors.rs",
        341: "game_menu.rs",
        342: "loading_screen.rs",
        343: "alien_cake_addict.rs",
        344: "desk_toy.rs",
        345: "stepping.rs",
    }
    return filenames.get(seq, "unknown.rs")


def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []
    replaced = set()

    for line in lines:
        matched = False
        for seq, cat, intent, knowledge in DATA:
            pattern = rf"^\| {seq} \|"
            if re.match(pattern, line.strip()):
                entry_line = build_entry_line(seq, cat, intent, knowledge)
                new_lines.append(entry_line + "\n")
                replaced.add(seq)
                matched = True
                break
        if not matched:
            new_lines.append(line)

    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        f.writelines(new_lines)

    print(f"Replaced {len(replaced)} entries:")
    for seq in sorted(replaced):
        print(f"  seq {seq:3d}: {get_filename(seq)}")


if __name__ == "__main__":
    main()
