#!/usr/bin/env python3
"""Replace catalog entries 177-206 (input/audio/camera/gizmos) with detailed content.
Matches entries by seq number and replaces the entire table row."""

import re
import sys

CATALOG_PATH = "/Users/lf380/Code/Bevy/a1/bevy_examples_catalog.md"

DATA = [
    (
        177,
        "输入处理",
        [
            "**意图**：使用 ButtonInput<KeyCode> 和 ButtonInput<Key> 两种资源检测按键的按下/释放状态，理解 KeyCode（位置相关）与 Key（逻辑按键）的区别。⭐⭐",
            "- **ButtonInput<KeyCode> 按键位置检测**:",
            "  - keyboard_input.pressed(KeyCode::KeyA) 持续按住时每帧返回 true；",
            "  - keyboard_input.just_pressed(KeyCode::KeyA) 仅在按下瞬间那一帧返回 true；",
            "  - keyboard_input.just_released(KeyCode::KeyA) 仅在释放瞬间那一帧返回 true；",
            "  - ⚠️ KeyCode 对应键盘物理位置（QWERTY 布局），不同键盘布局下同一 KeyCode 可能对应不同字符；",
            "- **ButtonInput<Key> 逻辑按键检测**:",
            '  - Key::Character("?".into()) 创建逻辑字符按键——不关心物理位置；',
            "  - key_input.pressed(key.clone()) 检测逻辑按键状态；",
            "  - 🔧 Key 适合绑定操作（如 +/- 缩放、? 帮助菜单），KeyCode 适合 WASD 移动等位置敏感操作；",
            "- **两种资源的对比**:",
            "  - Res<ButtonInput<T>> 是资源（Resource），系统参数直接注入，无需事件注册；",
            "  - KeyCode 按物理位置匹配（跨布局一致），Key 按逻辑字符匹配（跨布局不一致）；",
            "  - 🧩 两者可同时使用——KeyCode 处理方向控制，Key 处理符号快捷键；",
            "- **注意事项**:",
            "  - ⚠️ pressed/just_pressed/just_released 是查询方法，不需要 EventReader；",
            "  - 🔧 just_pressed 适合触发类操作（跳跃/攻击），pressed 适合持续类操作（移动/瞄准）；",
        ],
        [
            "知：<br>- ButtonInput&lt;KeyCode&gt; 按位置检测；<br>- ButtonInput&lt;Key&gt; 按逻辑按键检测；<br>- pressed/just_pressed/just_released 三态。",
            "例：<br>- hello_world(1)；<br>- input/keyboard_input_events.rs(178)。",
        ],
    ),
    (
        178,
        "输入处理",
        [
            "**意图**：使用 MessageReader<KeyboardInput> 消费键盘事件流，每次按键/释放产生一个 KeyboardInput 事件，包含完整的按键元数据。⭐⭐",
            "- **KeyboardInput 事件结构**:",
            "  - key_code: KeyCode 物理按键位置；",
            "  - logical_key: Key 逻辑按键（含字符信息）；",
            "  - state: ButtonState Pressed/Released 按键状态；",
            "  - text: Option<String> 按键产生的文本（仅部分按键有值）；",
            "  - window: Entity 触发事件的窗口实体；",
            "- **MessageReader 消费模式**:",
            "  - mut reader: MessageReader<KeyboardInput> 系统参数注入事件读取器；",
            "  - reader.read() 返回本次系统执行期间所有新事件的迭代器；",
            "  - ⚠️ MessageReader 每帧只读取一次——事件在被读后自动标记为已消费；",
            "- **与 ButtonInput 的区别**:",
            "  - ButtonInput 聚合状态（pressed/just_pressed），适合轮询；",
            "  - MessageReader 保留完整事件流，适合日志/回放/精确时序分析；",
            "  - 🔧 MessageReader 能获取 text 字段（实际输入的字符），ButtonInput 不能；",
            "- **注意事项**:",
            "  - ⚠️ 事件仅在产生后的一帧内可读——错过则永久丢失；",
            "  - 🔧 高频输入（如打字）事件量大，日志时建议过滤或采样；",
        ],
        [
            "知：<br>- KeyboardInput 事件结构（key_code/logical_key/state/text）；<br>- MessageReader&lt;T&gt; 消费事件流；<br>- 与 ButtonInput 的区别。",
            "例：<br>- input/keyboard_input.rs(177)；<br>- input/char_input_events.rs(180)。",
        ],
    ),
    (
        179,
        "输入处理",
        [
            "**意图**：使用 Res<ButtonInput<KeyCode>> 检测修饰键（Shift/Ctrl/Alt）的组合状态，实现多键组合触发。⭐",
            "- **修饰键检测**:",
            "  - input.any_pressed([KeyCode::ShiftLeft, KeyCode::ShiftRight]) 任一 Shift 按下即为 true；",
            "  - input.any_pressed([KeyCode::ControlLeft, KeyCode::ControlRight]) 任一 Ctrl 按下即为 true；",
            "  - 🔧 any_pressed 接受数组参数，一次检测多个等价按键（左右修饰键）；",
            "- **组合键判断**:",
            "  - ctrl && shift && input.just_pressed(KeyCode::KeyA) 三键组合条件；",
            "  - ⚠️ 条件顺序：先检测修饰键状态（持续），再检测目标键瞬间状态（just_pressed）；",
            "  - 🧩 此模式适用于快捷键绑定（Ctrl+S 保存、Ctrl+Shift+Z 重做）；",
            "- **注意事项**:",
            "  - ⚠️ 仅检测键盘修饰键——鼠标修饰键（Ctrl+Click 等）需要单独处理；",
            "  - 🔧 实际项目中建议将快捷键配置提取为 Resource，避免硬编码；",
        ],
        [
            "知：<br>- any_pressed 多键检测；<br>- 修饰键组合模式；<br>- just_pressed 瞬间触发。",
            "例：<br>- input/keyboard_input.rs(177)。",
        ],
    ),
    (
        180,
        "输入处理",
        [
            "**意图**：从 KeyboardInput 事件中提取 Key::Character 字符数据，仅处理字符输入（过滤非字符按键）。⭐",
            "- **字符提取逻辑**:",
            "  - if let Key::Character(character) = &event.logical_key 匹配字符类型；",
            "  - event.state.is_pressed() 过滤释放事件——仅处理按下时的字符；",
            "  - 🔧 event.text 字段也包含字符信息，但 logical_key 的 Character 变体更可靠；",
            "- **事件过滤**:",
            "  - ⚠️ 键盘事件包含所有按键（方向键/功能键/修饰键），大部分不产生字符——需要过滤；",
            "  - is_pressed() 检查确保每个按键只处理一次（按下时），避免重复输入；",
            "- **与 text_input.rs 的区别**:",
            "  - char_input_events 仅打印字符（调试/日志用途）；",
            "  - text_input 支持 IME 输入法和文本编辑（实际文本输入用途）；",
            "  - 🔧 选择取决于需求：原始字符流用 char_input，完整文本编辑用 text_input；",
            "- **注意事项**:",
            "  - ⚠️ 非字符键（Shift/Ctrl/方向键）的 logical_key 不是 Character 变体——自动被跳过；",
        ],
        [
            "知：<br>- Key::Character 字符提取；<br>- 事件状态过滤；<br>- 与 text_input 的区别。",
            "例：<br>- input/keyboard_input.rs(177)；<br>- input/text_input.rs(181)。",
        ],
    ),
    (
        181,
        "输入处理",
        [
            "**意图**：完整的文本输入系统——支持 IME 输入法、回车换行、退格删除、鼠标点击切换 IME，以及气泡动画文本输出。⭐⭐⭐",
            "- **IME 输入法支持**:",
            "  - window.ime_enabled = !window.ime_enabled 切换 IME 启用状态；",
            "  - MessageReader<Ime> 消费 IME 事件（Preedit/Commit/Enabled/Disabled）；",
            "  - Ime::Preedit { value, cursor } 输入法预编辑文本（候选词显示）；",
            "  - Ime::Commit { value } 输入法确认提交最终字符；",
            "  - ⚠️ IME 仅在 window.ime_enabled = true 时激活——点击窗口切换；",
            "- **Text2d 文本编辑**:",
            '  - Text2d::new("") 创建可编辑的 2D 文本实体；',
            "  - Key::Enter 触发换行——将当前文本移入气泡实体并清空；",
            "  - Key::Backspace 触发删除——text.pop() 移除最后一个字符；",
            "  - (_, Some(inserted_text)) 追加普通字符——过滤控制字符后 push_str；",
            "  - 🔧 is_printable_char 过滤私有使用区和 ASCII 控制字符——防止异常输入；",
            "- **TextUiWriter 精确更新**:",
            "  - TextUiWriter 按 Entity + span 索引精确修改文本片段；",
            "  - ui_writer.text(entity, 3) 更新第 4 个 span（索引 3）的文本内容；",
            "  - 🔧 比直接修改 Text 组件更高效——仅重建变更的文本片段；",
            "- **气泡动画**:",
            "  - Bubble { timer: Timer } 组件标记临时文本——5 秒后自动 despawn；",
            "  - transform.translation.y += 100.0 * delta_secs 向上飘动；",
            "  - 🔧 Timer::Once 模式：到期后 just_finished() 触发 despawn；",
        ],
        [
            "知：<br>- IME 输入法事件（Preedit/Commit/Enabled/Disabled）；<br>- TextUiWriter 按索引更新；<br>- window.ime_enabled 切换。",
            "例：<br>- input/keyboard_input_events.rs(178)；<br>- ui/text.rs(231)。",
        ],
    ),
    (
        182,
        "输入处理",
        [
            "**意图**：使用 ButtonInput<MouseButton> 检测鼠标按键状态，配合 AccumulatedMouseMotion 和 AccumulatedMouseScroll 获取累积的鼠标移动/滚轮数据。⭐⭐",
            "- **鼠标按键检测**:",
            "  - mouse_button_input.pressed(MouseButton::Left) 左键持续按住；",
            "  - mouse_button_input.just_pressed(MouseButton::Left) 左键按下瞬间；",
            "  - mouse_button_input.just_released(MouseButton::Left) 左键释放瞬间；",
            "  - 🔧 MouseButton 支持 Left/Right/Middle/Other(按钮编号)；",
            "- **AccumulatedMouseMotion 累积移动**:",
            "  - accumulated_mouse_motion.delta: Vec2 本帧累积的鼠标像素位移；",
            "  - ⚠️ delta 在每帧结束后重置——获取的是自上一帧以来的总移动量；",
            "  - Vec2::ZERO 表示鼠标未移动——避免不必要的日志输出；",
            "- **AccumulatedMouseScroll 累积滚轮**:",
            "  - accumulated_mouse_scroll.delta: Vec2 水平(x)/垂直(y)滚轮累积量；",
            "  - 🔧 y > 0 滚轮向上（放大），y < 0 滚轮向下（缩小）——与平台约定一致；",
            "- **注意事项**:",
            "  - ⚠️ AccumulatedMouseMotion 是资源（Resource）不是事件——直接 Res 注入；",
            "  - 🔧 鼠标移动不乘 delta_time——delta 本身已是帧间总位移；",
        ],
        [
            "知：<br>- ButtonInput&lt;MouseButton&gt; 按键检测；<br>- AccumulatedMouseMotion 累积位移；<br>- AccumulatedMouseScroll 累积滚轮。",
            "例：<br>- input/keyboard_input.rs(177)；<br>- 2D/rotate_to_cursor.rs(19)。",
        ],
    ),
    (
        183,
        "输入处理",
        [
            "**意图**：使用多种 MessageReader 同时消费所有鼠标相关事件——按键/移动/光标/滚轮/手势（捏合/旋转/双击），全面了解鼠标事件体系。⭐⭐",
            "- **七种鼠标事件**:",
            "  - MouseButtonInput: 鼠标按键按下/释放（含按钮标识和状态）；",
            "  - MouseMotion: 鼠标移动位移（与 AccumulatedMouseMotion 不同，这是原始事件）；",
            "  - CursorMoved: 光标在窗口中的位置变化（含物理和逻辑坐标）；",
            "  - MouseWheel: 滚轮事件（含方向 LineIdent/PixelIdent 和单位）；",
            "  - PinchGesture: 触控板捏合手势（仅 macOS）；",
            "  - RotationGesture: 触控板旋转手势（仅 macOS）；",
            "  - DoubleTapGesture: 触控板双击手势（仅 macOS）；",
            "- **MessageReader 并行消费**:",
            "  - 同一系统中注入多个 MessageReader——各自独立读取对应事件类型；",
            "  - 🔧 每个 reader.read() 仅返回对应类型的事件，不会交叉；",
            "- **与 button_input/motion 资源的区别**:",
            "  - 事件（Event）保留完整的每帧原始数据——适合日志/回放；",
            "  - 资源（Resource）聚合状态——适合轮询/游戏逻辑；",
            "  - 🧩 调试时用事件记录，游戏中用资源查询；",
            "- **平台差异**:",
            "  - ⚠️ 手势事件（Pinch/Rotation/DoubleTap）仅在 macOS 触控板上触发；",
            "  - 🔧 其他平台不会报错——事件读取器为空迭代器；",
        ],
        [
            "知：<br>- 七种鼠标事件类型；<br>- MessageReader 并行消费多事件；<br>- 事件 vs 资源的区别。",
            "例：<br>- input/mouse_input.rs(182)；<br>- input/keyboard_input_events.rs(178)。",
        ],
    ),
    (
        184,
        "输入处理",
        [
            "**意图**：使用 CursorOptions 组件控制鼠标光标的可见性和抓取模式——左键锁定光标，Escape 释放。⭐",
            "- **CursorOptions 组件**:",
            "  - cursor_options.visible: bool 控制光标可见性；",
            "  - cursor_options.grab_mode: CursorGrabMode 控制抓取模式；",
            "  - Single<&mut CursorOptions> 精确获取唯一窗口的光标选项——高效查询；",
            "- **CursorGrabMode 三种模式**:",
            "  - CursorGrabMode::None: 不抓取——光标自由移动（默认）；",
            "  - CursorGrabMode::Locked: 锁定模式——光标隐藏但可报告相对移动（FPS 游戏常用）；",
            "  - CursorGrabMode::Confined: 困住模式——光标限制在窗口范围内（策略游戏常用）；",
            "  - ⚠️ Locked 模式在 Web 平台需要用户交互后才能启用（浏览器安全策略）；",
            "- **交互逻辑**:",
            "  - mouse.just_pressed(Left) → 隐藏 + 锁定：进入沉浸模式；",
            "  - key.just_pressed(Escape) → 显示 + 释放：退出沉浸模式；",
            "  - 🔧 Escape 是通用的退出键——用户期望按 Escape 释放鼠标；",
            "- **注意事项**:",
            "  - ⚠️ visible=false 且 grab_mode=None 时鼠标完全不可见且无法操作——确保有退出机制；",
            "  - 🔧 FPS/TPS 游戏标配：左键锁定，Escape 释放，Tab 切换 UI 时临时释放；",
        ],
        [
            "知：<br>- CursorOptions 光标选项；<br>- CursorGrabMode::Locked/Confined 抓取模式；<br>- Single 精确查询。",
            "例：<br>- input/mouse_input.rs(182)；<br>- camera/free_camera_controller.rs(201)。",
        ],
    ),
    (
        185,
        "输入处理",
        [
            "**意图**：使用 Query<(Entity, &Gamepad)> 遍历已连接手柄，检测按钮按下/释放和轴值（摇杆/扳机）。⭐⭐",
            "- **Gamepad 组件查询**:",
            "  - Query<(Entity, &Gamepad)> 获取所有手柄实体和 Gamepad 组件；",
            "  - gamepad.just_pressed(GamepadButton::South) 按钮瞬间按下；",
            "  - gamepad.just_released(GamepadButton::South) 按钮瞬间释放；",
            "  - 🔧 GamepadButton 支持 South/East/North/West（四面键）+ LeftStick/RightStick + Trigger 等；",
            "- **轴值读取**:",
            "  - gamepad.get(GamepadButton::RightTrigger2) 返回 Option<f32>（0.0~1.0 扳机值）；",
            "  - gamepad.get(GamepadAxis::LeftStickX) 返回 Option<f32>（-1.0~1.0 摇杆值）；",
            "  - ⚠️ get 返回 Option——手柄未连接或轴不存在时为 None；",
            "  - 🔧 abs() > 0.01 死区过滤——防止摇杆漂移产生噪声输入；",
            "- **按钮布局映射**:",
            "  - South = A/X（底部），East = B/○（右部），North = Y/△（顶部），West = X/□（左部）；",
            "  - ⚠️ 不同手柄平台的物理按钮不同——用 South/East/North/West 抽象避免硬编码；",
            "- **注意事项**:",
            "  - ⚠️ 手柄连接/断开是动态的——Query 每帧重新评估；",
            "  - 🔧 死区阈值 0.01 适合大多数手柄，精确模拟摇杆可提高到 0.05；",
        ],
        [
            "知：<br>- Gamepad 组件与 Query 遍历；<br>- GamepadButton/GamepadAxis 轴值读取；<br>- 死区过滤。",
            "例：<br>- input/gamepad_input_events.rs(186)；<br>- input/keyboard_input.rs(177)。",
        ],
    ),
    (
        186,
        "输入处理",
        [
            "**意图**：使用多种 MessageReader 消费手柄底层事件——连接/断开、轴值变化、按钮状态变化，以及通过 GamepadEvent 统一事件流获取帧内排序。⭐⭐",
            "- **四种手柄事件**:",
            "  - GamepadConnectionEvent: 手柄连接/断开事件（含手柄名称和连接状态）；",
            "  - GamepadAxisChangedEvent: 轴值变化事件（含轴类型和新值）；",
            "  - GamepadButtonChangedEvent: 按钮模拟值变化（0.0~1.0 连续值）；",
            "  - GamepadButtonStateChangedEvent: 按钮布尔状态变化（Pressed/Released，受阈值控制）；",
            "  - 🔧 Changed 事件按阈值触发——按钮从未按到按下超过阈值才产生事件；",
            "- **GamepadEvent 统一事件流**:",
            "  - MessageReader<GamepadEvent> 消费所有手柄事件的统一流；",
            "  - GamepadEvent::Connection/Axis/Button 三种变体——匹配后分别处理；",
            "  - 🔧 统一流保持帧内事件顺序——需要精确时序分析时使用；",
            "- **事件 vs 资源的选择**:",
            "  - 事件：连接/断开通知、调试日志、回放系统——需要每帧原始数据；",
            "  - 资源（ButtonInput/Axis）：游戏逻辑——轮询当前状态更简单；",
            "  - 🧩 连接事件适合动态手柄管理（UI 提示/按键重映射）；",
            "- **注意事项**:",
            "  - ⚠️ 手柄断开后轴值可能停留在最后值——需要检测连接状态；",
        ],
        [
            "知：<br>- 四种手柄事件类型；<br>- GamepadEvent 统一事件流；<br>- 连接/断开事件。",
            "例：<br>- input/gamepad_input.rs(185)。",
        ],
    ),
    (
        187,
        "输入处理",
        [
            "**意图**：使用 GamepadRumbleRequest 消息请求手柄力反馈——支持强/弱电机独立控制、持续时间、中断停止。⭐⭐",
            "- **GamepadRumbleRequest::Add 请求**:",
            "  - gamepad: Entity 目标手柄实体；",
            "  - intensity: GamepadRumbleIntensity 力反馈强度；",
            "  - duration: Duration 持续时间——到期自动停止；",
            "  - 🔧 MessageWriter<GamepadRumbleRequest> 发送请求——异步执行不阻塞系统；",
            "- **GamepadRumbleIntensity 三种预设**:",
            "  - strong_motor(0.1): 低频电机（左手柄侧）——低强度持续震动；",
            "  - weak_motor(0.25): 高频电机（右手柄侧）——高频细微震动；",
            "  - MAX: 两个电机全速——最大震动效果；",
            "  - 🔧 自定义 { strong_motor: 0.5, weak_motor: 0.25 } 混合强度——精细控制体验；",
            "- **GamepadRumbleRequest::Stop 停止**:",
            "  - rumble_requests.write(GamepadRumbleRequest::Stop { gamepad: entity }) 立即中断当前震动；",
            "  - ⚠️ Stop 仅停止由 Add 启动的震动——不影响其他请求；",
            "- **按钮映射**:",
            "  - North/East/South/West 四个面键分别触发不同强度/电机组合；",
            "  - Start 键中断震动——测试 Stop 功能；",
            "- **注意事项**:",
            "  - ⚠️ 多次 Add 请求会叠加——当前震动结束后新请求才生效（或被 Stop 中断）；",
            "  - 🔧 强度值范围 0.0~1.0——超出范围会被 clamp；",
        ],
        [
            "知：<br>- GamepadRumbleRequest 消息力反馈；<br>- strong_motor/weak_motor 双电机；<br>- Add/Stop 请求。",
            "例：<br>- input/gamepad_input.rs(185)。",
        ],
    ),
    (
        188,
        "输入处理",
        [
            "**意图**：使用 Res<Touches> 资源查询多点触控输入——遍历按下/释放/取消事件，以及查询当前活跃触控点状态。⭐⭐",
            "- **Touches 资源查询**:",
            "  - touches.iter_just_pressed() 遍历本帧新按下的触控点——含 id 和 position；",
            "  - touches.iter_just_released() 遍历本帧释放的触控点；",
            "  - touches.iter_just_canceled() 遍历本帧取消的触控点（系统中断）；",
            "  - touches.iter() 遍历所有当前活跃的触控点；",
            "  - 🔧 每个 Touch 对象提供 id()/position()/phase() 等方法；",
            "- **触控点状态查询**:",
            "  - touches.just_pressed(touch.id()) 查询特定触控点是否本帧按下；",
            "  - ⚠️ 触控 id 在按下到释放之间保持不变——可用于跟踪多指手势；",
            "- **与 TouchInput 事件的区别**:",
            "  - Res<Touches> 是聚合状态——查询当前帧的触控点集合；",
            "  - MessageReader<TouchInput> 是事件流——逐个处理每个触控事件；",
            "  - 🧩 多指手势（缩放/旋转）用 Touches 资源更方便——可同时访问所有触控点；",
            "- **注意事项**:",
            "  - ⚠️ 触控输入仅在支持触摸的设备上可用——桌面/Web 无触摸时不产生事件；",
            "  - 🔧 每个触控点有唯一 id——多指手势需按 id 分组处理；",
        ],
        [
            "知：<br>- Res&lt;Touches&gt; 多点触控资源；<br>- iter_just_pressed/released/canceled 遍历；<br>- Touch id 跟踪。",
            "例：<br>- input/touch_input_events.rs(189)。",
        ],
    ),
    (
        189,
        "输入处理",
        [
            "**意图**：使用 MessageReader<TouchInput> 消费底层触控事件流，获取每次触控操作的完整元数据。⭐",
            "- **TouchInput 事件结构**:",
            "  - id: u64 触控点唯一标识；",
            "  - position: Vec2 触控位置（逻辑像素坐标）；",
            "  - phase: TouchPhase 枚举（Started/Moved/Ended/Cancelled）；",
            "  - window: Entity 触控发生的窗口实体；",
            "  - force: Option<f64> 触控压力（部分设备支持）；",
            "- **MessageReader 消费**:",
            "  - mut reader: MessageReader<TouchInput> 注入事件读取器；",
            "  - reader.read() 遍历本帧所有触控事件——每个手指的每次移动都产生事件；",
            "  - 🔧 事件量可能很大（多指+高采样率）——日志时建议采样或过滤；",
            "- **与 Res<Touches> 的区别**:",
            "  - TouchInput 事件保留原始时序——适合回放/精确手势识别；",
            "  - Res<Touches> 聚合当前帧状态——适合简单查询；",
            "  - 🧩 手势识别引擎通常基于事件流——可精确计算速度/方向/加速度；",
            "- **注意事项**:",
            "  - ⚠️ 触控事件在桌面平台上不产生——仅移动端/Web 触摸设备；",
        ],
        [
            "知：<br>- TouchInput 事件结构（id/position/phase/force）；<br>- TouchPhase 四种状态；<br>- 与 Touches 资源的区别。",
            "例：<br>- input/touch_input.rs(188)。",
        ],
    ),
    (
        190,
        "音频",
        [
            "**意图**：最简音频播放——使用 AudioPlayer 组件加载并播放 OGG 音频文件，展示 Bevy 音频系统的基本用法。⭐",
            "- **AudioPlayer 组件**:",
            "  - AudioPlayer::new(handle) 创建音频播放器组件——绑定 AudioSource 句柄；",
            "  - commands.spawn(AudioPlayer::new(asset_server.load(path))) 一行完成加载+播放；",
            "  - ⚠️ AudioPlayer 是组件（Component）——需要 spawn 到实体上才能播放；",
            "- **音频加载**:",
            '  - asset_server.load("sounds/Windless Slopes.ogg") 加载 OGG 音频文件；',
            "  - 🔧 支持格式取决于启用的 feature：ogg（默认）/mp3/wav/flac；",
            "  - 路径相对于 assets/ 目录——与其他资产加载一致；",
            "- **默认行为**:",
            "  - 默认音量 100%——通过 AudioPlugin::global_volume 控制；",
            "  - 默认播放一次——PlaybackSettings::DESPAWN 播放完自动清理；",
            "  - 🔧 无需手动管理生命周期——AudioPlayer 实体播放完自动 despawn（默认设置）；",
            "- **注意事项**:",
            "  - ⚠️ 无 DefaultPlugins 时无音频系统——音频依赖 Bevy 的音频插件；",
            "  - 🔧 音频文件建议使用 OGG 格式——体积小、压缩率高、免费；",
        ],
        [
            "知：<br>- AudioPlayer 组件播放音频；<br>- AssetServer 加载音频文件；<br>- 默认播放行为。",
            "例：<br>- asset/asset_loading.rs(159)；<br>- audio/audio_control.rs(191)。",
        ],
    ),
    (
        191,
        "音频",
        [
            "**意图**：完整的音频播放控制——播放/暂停、音量调节（百分比增减）、速度控制（正弦波调制）、静音切换，以及播放进度实时显示。⭐⭐⭐",
            "- **AudioSink 播放控制**:",
            "  - Single<&AudioSink, With<MyMusic>> 精确获取目标音频控制器；",
            "  - sink.toggle_playback() 切换播放/暂停——Space 键交互；",
            "  - sink.toggle_mute() 切换静音——M 键交互；",
            "  - sink.position() 获取当前播放位置（Duration）——用于进度显示；",
            "- **音量控制**:",
            "  - sink.set_volume(current_volume.increase_by_percentage(10.0)) 增加 10% 音量；",
            "  - sink.set_volume(current_volume.increase_by_percentage(-10.0)) 减少 10% 音量；",
            "  - ⚠️ = 键增音量，- 键减音量——符合直觉的 +/- 映射；",
            "  - 🔧 Volume 类型支持 increase_by_percentage/decrease_by_percentage 等便捷方法；",
            "- **速度控制（正弦波调制）**:",
            "  - sink.set_speed((ops::sin(time.elapsed_secs() / 5.0) + 1.0).max(0.1)) 速度随时间波动；",
            "  - sin 输出 [-1, 1]，+1 后范围 [0, 2]，max(0.1) 防止负速度；",
            "  - 🔧 此模式模拟磁带机变速效果——适合特殊音效/环境音；",
            "- **播放进度 UI**:",
            '  - Text::new("") + PositionType::Absolute 固定位置文本；',
            '  - format!("Progress: {}s", position.as_secs_f32()) 实时更新播放秒数；',
            "- **注意事项**:",
            "  - ⚠️ AudioSink 操作需要可变借用——Query<&mut AudioSink> 与 Query<&AudioSink> 互斥；",
            "  - 🔧 分离只读系统（进度/速度）和可写系统（暂停/音量）避免查询冲突；",
        ],
        [
            "知：<br>- AudioSink 播放控制（toggle_playback/toggle_mute/set_volume/set_speed）；<br>- Volume 百分比调节；<br>- position() 进度查询。",
            "例：<br>- audio/audio.rs(190)。",
        ],
    ),
    (
        192,
        "音频",
        [
            "**意图**：使用 Pitch 资产类型播放程序化生成的单频音调——键盘上下键按半音阶调整频率，Space 触发播放。⭐⭐",
            "- **Pitch 资产类型**:",
            "  - Pitch::new(frequency, Duration) 创建指定频率和持续时间的音调；",
            "  - frequency 单位 Hz——220Hz = A3，440Hz = A4（标准音高）；",
            "  - Duration::new(1, 0) 播放 1 秒；",
            "  - 🔧 Pitch 是 Bevy 内置的 Decodable 类型——无需外部音频文件；",
            "- **Assets<Pitch> 资产管理**:",
            "  - pitch_assets.add(Pitch::new(freq, duration)) 将音调加入资产存储；",
            "  - AudioPlayer(pitch_assets.add(...)) 直接从 add 结果创建播放器——无需文件加载；",
            "  - 🔧 pitch_assets.len() 查询当前音调资产数量——调试用途；",
            "- **半音阶频率调整**:",
            "  - frequency *= ops::powf(2.0, 1.0 / 12.0) 上调一个半音（乘以 2^(1/12)）；",
            "  - frequency /= ops::powf(2.0, 1.0 / 12.0) 下调一个半音；",
            "  - 🔧 2^(1/12) 是十二平均律的频率比——音乐理论中的标准半音间距；",
            "- **PlaybackSettings::DESPAWN**:",
            "  - 播放完成后自动销毁 AudioPlayer 实体——防止内存泄漏；",
            "  - 🔧 短音效（如按键反馈）应使用 DESPAWN 模式；",
            "- **注意事项**:",
            "  - ⚠️ 高频（>20000Hz）超出人耳范围但仍有性能开销；",
        ],
        [
            "知：<br>- Pitch 资产程序化音调；<br>- 半音阶频率计算 2^(1/12)；<br>- PlaybackSettings::DESPAWN 自动清理。",
            "例：<br>- audio/audio.rs(190)。",
        ],
    ),
    (
        193,
        "音频",
        [
            "**意图**：实现自定义 Decodable 类型——定义 SineAudio 资产结构体和 SineDecoder 迭代器，通过 Source + Decodable trait 桥接到 Bevy 音频管线。⭐⭐⭐",
            "- **Asset 结构体**:",
            "  - #[derive(Asset, TypePath)] 标记为 Bevy 资产类型——可存入 Assets<T>；",
            "  - SineAudio { frequency: f32 } 存储音频参数（频率）——实际音频数据由 Decoder 生成；",
            "  - 🔧 Asset 结构体存储「如何生成音频」的参数，而非音频数据本身；",
            "- **SineDecoder 迭代器**:",
            "  - current_progress: f32 当前相位（0.0~1.0）；",
            "  - progress_per_frame: f32 每样本步进量 = frequency / sample_rate；",
            "  - Iterator::next() 返回当前相位的 sin 值——逐样本生成正弦波；",
            "  - ⚠️ current_progress %= 1.0 防止浮点累积误差——回到起点重新计算；",
            "- **Source trait 实现**:",
            "  - channels() -> 1 单声道；",
            "  - sample_rate() -> 44100 标准采样率；",
            "  - current_frame_len() -> None 无限长度（实时生成）；",
            "  - total_duration() -> None 无固定时长；",
            "  - 🔧 Source trait 提供音频元数据——Bevy 音频管线据此配置播放参数；",
            "- **Decodable trait 桥接**:",
            "  - type Decoder = SineDecoder 指定解码器类型；",
            "  - fn decoder(&self) -> SineDecoder::new(self.frequency) 从资产参数创建解码器；",
            "  - 🔧 Decodable 是 Asset → Decoder 的工厂模式——每次播放创建新迭代器；",
            "- **注册与播放**:",
            "  - .add_audio_source::<SineAudio>() 注册自定义音频源类型；",
            "  - assets.add(SineAudio { frequency: 440.0 }) 创建 A4 标准音高；",
            "  - AudioPlugin { global_volume: Volume::Linear(0.2) } 降低全局音量——防止刺耳；",
        ],
        [
            "知：<br>- Decodable trait 自定义音频解码；<br>- Source trait 音频元数据；<br>- add_audio_source 注册。",
            "例：<br>- audio/audio.rs(190)；<br>- asset/custom_asset.rs(167)。",
        ],
    ),
    (
        194,
        "音频",
        [
            "**意图**：基于 GameState 资源变化自动切换音轨——和平/战斗两种状态对应不同音乐，配合 FadeIn/FadeOut 组件实现渐入渐出过渡。⭐⭐⭐",
            "- **GameState 资源驱动切换**:",
            "  - enum GameState { Peaceful, Battle } 自定义状态枚举；",
            "  - game_state.is_changed() 检测状态变化——仅在切换时执行 change_track 系统；",
            "  - 🔧 Res<GameState> 变化检测比轮询更高效——状态不变时不执行；",
            "- **SoundtrackPlayer 资源**:",
            "  - track_list: Vec<Handle<AudioSource>> 存储音轨句柄列表；",
            "  - 按 GameState 索引选择音轨——Peaceful → track_list[0]，Battle → track_list[1]；",
            "  - 🔧 资源存储音轨引用——setup 时预加载，运行时按索引切换；",
            "- **FadeIn/FadeOut 渐变系统**:",
            "  - FadeIn 组件标记需渐入的实体——fade_in 系统每帧增加音量；",
            "  - FadeOut 组件标记需渐出的实体——fade_out 系统每帧减少音量；",
            "  - Volume::SILENT.fade_towards(Volume::Linear(1.0), t) 线性插值音量；",
            "  - ⚠️ FADE_TIME = 2.0 秒——渐变时长由计时器控制；",
            "- **播放模式**:",
            "  - PlaybackSettings { mode: Loop, volume: SILENT } 循环播放+初始静音；",
            "  - 🔧 初始 SILENT 由 FadeIn 系统接管——避免切换时音量突变；",
            "- **清理逻辑**:",
            "  - fade_out 完成后 commands.entity(entity).despawn() 销毁旧音轨实体；",
            "  - 🔧 每次切换先 FadeOut 旧的再 Spawn 新的——平滑过渡无断音；",
        ],
        [
            "知：<br>- GameState 资源变化驱动音轨切换；<br>- FadeIn/FadeOut 组件渐变系统；<br>- Volume::SILENT.fade_towards 渐变。",
            "例：<br>- audio/audio.rs(190)；<br>- state/states.rs(155)。",
        ],
    ),
    (
        195,
        "音频",
        [
            "**意图**：2D 空间音频——声音源随距离衰减，SpatialListener 双耳模型根据听者与声源的相对位置产生立体声效果。⭐⭐",
            "- **SpatialScale 空间缩放**:",
            "  - AUDIO_SCALE = 1.0/100.0 将像素距离映射为音频距离单位；",
            "  - AudioPlugin { default_spatial_scale: SpatialScale::new_2d(AUDIO_SCALE) } 全局配置；",
            "  - ⚠️ 2D 中默认 1 像素 = 1 距离单位——声音衰减过快，需要缩放；",
            "  - 🔧 100 像素 = 1 音频单位——合理的 2D 游戏空间音频衰减比例；",
            "- **SpatialListener 双耳模型**:",
            "  - SpatialListener::new(gap) 创建双耳间距为 gap 的听者组件；",
            "  - left_ear_offset / right_ear_offset 左右耳偏移量——可视化用；",
            "  - 🧩 左右耳两个 Sprite 可视化——帮助理解空间音频的双耳分离；",
            "- **空间音频播放**:",
            "  - PlaybackSettings::LOOP.with_spatial(true) 循环+空间音频模式；",
            "  - Emitter 组件标记声源实体——AudioPlayer 自动参与空间计算；",
            "  - 🔧 spatial: true 是空间音频的开关——false 时为普通 2D 音频；",
            "- **声源移动**:",
            "  - Stopwatch 控制移动计时——Space 键暂停/恢复；",
            "  - sin(elapsed) * 500.0 声源左右往复运动——演示距离衰减和方向变化；",
            "- **听者移动**:",
            "  - 方向键控制 SpatialListener 移动——听者靠近声源时声音变大；",
            "  - 🔧 SpatialListener 继承 Transform——移动它即移动双耳位置；",
        ],
        [
            "知：<br>- SpatialScale 2D 空间缩放；<br>- SpatialListener 双耳模型；<br>- PlaybackSettings::with_spatial(true)。",
            "例：<br>- audio/audio.rs(190)；<br>- audio/spatial_audio_3d.rs(196)。",
        ],
    ),
    (
        196,
        "音频",
        [
            "**意图**：3D 空间音频——声源在三维空间中定位，SpatialListener 双耳根据距离和方向产生 3D 立体声效果，支持 M 键全局静音。⭐⭐",
            "- **3D 空间音频设置**:",
            "  - AudioPlayer::new(handle) + PlaybackSettings::LOOP.with_spatial(true) 启用空间模式；",
            "  - Emitter 组件标记声源——在 3D 空间中定位；",
            "  - 🔧 3D 空间音频自动根据 Transform 计算距离衰减和方向偏移——无需手动配置；",
            "- **SpatialListener 3D 双耳**:",
            "  - SpatialListener::new(gap=4.0) 双耳间距 4 个世界单位；",
            "  - left_ear_offset/right_ear_offset 可视化为红/绿色立方体；",
            "  - 🔧 双耳间距影响空间感知——间距越大方向感越强；",
            "- **声源运动**:",
            "  - sin(elapsed)*3.0 / cos(elapsed)*3.0 圆周运动——3D 空间中声源环绕听者；",
            "  - Stopwatch 控制运动启停——Space 键切换；",
            "  - 🔧 圆周运动比直线运动更直观展示 3D 空间音频的方向变化；",
            "- **SpatialAudioSink 静音**:",
            "  - Query<&mut SpatialAudioSink> 获取空间音频控制器；",
            "  - sink.toggle_mute() 全局静音所有空间音频源；",
            "  - 🔧 SpatialAudioSink 与普通 AudioSink 不同——前者管理空间音频实例；",
            "- **与 2D 空间音频的区别**:",
            "  - 2D: 声源在 XY 平面，听者在 Z=0——声音仅左右方向变化；",
            "  - 3D: 声源在 XYZ 空间，听者可全方位移动——声音有完整 3D 方向感；",
        ],
        [
            "知：<br>- 3D SpatialListener 双耳模型；<br>- Emitter 3D 声源定位；<br>- SpatialAudioSink 静音控制。",
            "例：<br>- audio/spatial_audio_2d.rs(195)；<br>- 3D/3d_scene.rs(32)。",
        ],
    ),
    (
        197,
        "相机",
        [
            "**意图**：使用 PanCamera 插件为 2D 相机添加键盘/鼠标平移和缩放控制——最简的交互式 2D 相机方案。⭐",
            "- **PanCameraPlugin 插件**:",
            "  - .add_plugins(PanCameraPlugin) 注册平移相机插件——自动添加输入处理系统；",
            "  - PanCamera::default() 组件附加到 Camera2d 实体——激活控制；",
            "  - 🔧 插件封装了所有输入逻辑——无需手动编写 WASD/滚轮系统；",
            "- **默认控制**:",
            "  - 方向键/WASD：平移相机；",
            "  - 鼠标滚轮/+/- 键：缩放；",
            "  - ⚠️ PanCamera 默认行为可配置——通过修改 PanCamera 组件字段调整；",
            "- **场景搭建**:",
            "  - Camera2d + PanCamera::default() 最简相机配置；",
            "  - Sprite::from_image(handle) 显示图像——作为相机内容参照物；",
            "  - Text UI 显示当前 PanCamera 参数——调试/教学用途；",
            "- **应用场景**:",
            "  - 🔧 2D 策略游戏/地图编辑器/图片查看器的标配相机方案；",
            "  - 🧩 后续相机示例（top_down/shake/orbit）在此基础上增加特定功能；",
        ],
        [
            "知：<br>- PanCameraPlugin 平移相机插件；<br>- PanCamera 组件配置；<br>- 2D 相机控制。",
            "例：<br>- 2D/move_sprite.rs(3)；<br>- camera/2d_top_down_camera.rs(198)。",
        ],
    ),
    (
        198,
        "相机",
        [
            "**意图**：2D 俯视相机平滑跟随玩家——使用 smooth_nudge 指数衰减插值实现相机跟踪，配合 Bloom 泛光效果。⭐⭐",
            "- **smooth_nudge 平滑跟踪**:",
            "  - camera.translation.smooth_nudge(&direction, CAMERA_DECAY_RATE, delta_secs) 指数衰减趋近；",
            "  - CAMERA_DECAY_RATE = 2.0 控制跟踪速度——越大越快到达目标；",
            "  - ⚠️ smooth_nudge 比 lerp 更自然——接近目标时自动减速，避免过冲；",
            "  - 🔧 保留 camera.translation.z 不变——2D 相机 Z 轴控制深度排序；",
            "- **玩家移动**:",
            "  - WASD 四方向移动 + direction.normalize_or_zero() 防止对角线超速；",
            "  - PLAYER_SPEED = 100.0 像素/秒——帧率无关速度；",
            "  - 🔧 仅 X/Y 轴移动——2D 游戏中 Z 轴留给深度排序；",
            "- **Bloom 泛光**:",
            "  - Bloom::NATURAL 加到 Camera2d——启用自然风格泛光；",
            "  - 玩家颜色 RGB 超过 1.0（Color::srgb(6.25, 9.4, 9.1)）——HDR 超亮产生辉光；",
            "  - 🔧 高于 1.0 的颜色值在 Bloom 模式下产生光晕——视觉上像自发光；",
            "- **Single + Without 过滤**:",
            "  - Single<&mut Transform, (With<Camera2d>, Without<Player>)> 相机排除玩家；",
            "  - Single<&Transform, (With<Player>, Without<Camera2d>)> 玩家排除相机；",
            "  - 🔧 双向 Without 避免同时获取两个实体的 Transform——防止冲突；",
        ],
        [
            "知：<br>- smooth_nudge 指数衰减跟踪；<br>- Bloom::NATURAL 泛光；<br>- Single + Without 过滤。",
            "例：<br>- camera/pan_camera_controller.rs(197)；<br>- 2D/bloom_2d.rs(20)。",
        ],
    ),
    (
        199,
        "相机",
        [
            "**意图**：基于创伤值（trauma）和 Perlin 噪声实现 2D 屏幕震动——创伤自动衰减、指数级强度映射、噪声驱动平滑位移。⭐⭐⭐",
            "- **创伤值系统**:",
            "  - trauma: f32 范围 [0.0, 1.0]——越大震动越强；",
            "  - TRAUMA_PER_PRESS = 0.4 每次按键增加创伤值；",
            "  - TRAUMA_DECAY_PER_SECOND = 0.5 创伤每秒衰减 0.5——2 秒恢复平静；",
            "  - 🔧 trauma 超过 1.0 会被 clamp——防止极端震动；",
            "- **指数级强度映射**:",
            "  - shake = powf(trauma, TRAUMA_EXPONENT) 指数映射——低创伤几乎无感，高创伤急剧增强；",
            "  - TRAUMA_EXPONENT = 2.0 二次方——符合人眼对震动的非线性感知；",
            "  - ⚠️ trauma ∈ [0,1] 时 exponent 越大，shake 越小——0.5 trauma + exp2 = 0.25 shake；",
            "- **Perlin 噪声位移**:",
            "  - perlin_noise::generate(t + offset) 1D Perlin 噪声——输出 [-1, 1]；",
            "  - 三个独立噪声通道（rotation/x/y）使用不同偏移——避免同步；",
            "  - offset × noise_speed 控制噪声变化速度——值越大震动越快；",
            "  - 🔧 Perlin 噪声的连续性保证相机不会突跳——比随机数更自然；",
            "- **帧首重置 + 帧尾施加**:",
            "  - PreUpdate: reset_transform 恢复原始 Transform——游戏逻辑不受影响；",
            "  - PostUpdate: shake_camera 施加震动偏移——仅影响渲染；",
            "  - ⚠️ .before(TransformSystems::Propagate) 确保震动偏移传播到 GlobalTransform；",
            "  - 🔧 此模式下游戏逻辑（碰撞/移动）使用无震动坐标——仅视觉效果；",
            "- **CameraShakeConfig 组件**:",
            "  - trauma_decay_per_second/exponent/max_angle/max_translation/noise_speed 五参数配置；",
            "  - #[require(CameraShakeState)] 自动附加状态组件——声明式依赖；",
        ],
        [
            "知：<br>- 创伤值 trauma 指数衰减；<br>- Perlin 噪声平滑位移；<br>- PreUpdate 重置 + PostUpdate 施加。",
            "例：<br>- camera/2d_top_down_camera.rs(198)；<br>- time/time.rs(174)。",
        ],
    ),
    (
        200,
        "相机",
        [
            "**意图**：使用 Pitch/Yaw/Roll 欧拉角实现 3D 轨道相机——鼠标拖拽控制旋转方向，相机始终围绕目标点环绕。⭐⭐",
            "- **CameraSettings Resource**:",
            "  - orbit_distance: f32 轨道半径（相机到目标距离）；",
            "  - pitch_speed/yaw_speed: f32 鼠标灵敏度；",
            "  - pitch_range: Range<f32> pitch 限制范围——防止翻转；",
            "  - roll_speed: f32 滚转速度——鼠标按键控制；",
            "  - 🔧 所有参数存储在 Resource 中——运行时可调整；",
            "- **欧拉角旋转**:",
            "  - (yaw, pitch, roll) = camera.rotation.to_euler(EulerRot::YXZ) 提取当前旋转；",
            "  - pitch += delta_pitch，yaw += delta_yaw，roll += delta_roll 增量更新；",
            "  - camera.rotation = Quat::from_euler(EulerRot::YXZ, yaw, pitch, roll) 应用旋转；",
            "  - ⚠️ pitch 必须 clamp 在 (-FRAC_PI_2+0.01, FRAC_PI_2-0.01)——防止万向锁；",
            "- **鼠标输入处理**:",
            "  - AccumulatedMouseMotion.delta 获取鼠标位移——不乘 delta_time；",
            "  - ⚠️ 鼠标位移已经是帧间总增量——再乘 delta_time 会导致速度依赖帧率；",
            "  - 鼠标按键（Left/Right）控制 roll——需要乘 time.delta_secs()（离散输入）；",
            "- **轨道位置计算**:",
            "  - camera.translation = target - camera.forward() * orbit_distance；",
            "  - 🔧 forward() 返回旋转后的前方向量——自动跟随旋转更新位置；",
            "  - target = Vec3::ZERO 围绕原点——可替换为任意目标点；",
        ],
        [
            "知：<br>- Pitch/Yaw/Roll 欧拉角轨道控制；<br>- AccumulatedMouseMotion 鼠标位移；<br>- forward() 前方向量。",
            "例：<br>- 3D/3d_scene.rs(32)；<br>- input/mouse_input_events.rs(183)。",
        ],
    ),
    (
        201,
        "相机",
        [
            "**意图**：FreeCamera 自由相机控制器——6 轴自由移动 + 鼠标环顾 + 冲刺/慢走 + 速度调节，适合 3D 场景探索和调试。⭐⭐⭐",
            "- **FreeCamera 组件**:",
            "  - sensitivity: f32 鼠标灵敏度（可运行时调节）；",
            "  - friction: f32 摩擦力——停止按键后减速快慢；",
            "  - walk_speed / run_speed: f32 行走/冲刺速度；",
            "  - scroll_factor: f32 滚轮速度调节倍率；",
            "  - 🔧 FreeCameraState 存储运行时状态（velocity 等）——组件分离数据和状态；",
            "- **FreeCameraPlugin 插件**:",
            "  - .add_plugins(FreeCameraPlugin) 注册所有控制系统；",
            "  - 自动处理鼠标捕获/释放——M 键切换，左键按住捕获；",
            "  - 🔧 插件封装完整输入逻辑——添加组件即可获得自由相机；",
            "- **默认控制**:",
            "  - WASD：水平移动；QE：垂直移动；鼠标：环顾；",
            "  - Left Shift：冲刺（speed × 3）；滚轮：调节速度；",
            "  - M：切换鼠标捕获模式；左键按住：临时捕获；",
            "- **运行时参数调节**:",
            "  - Z/X：增减灵敏度；C/V：增减摩擦力；F/G：增减滚轮倍率；",
            "  - B：启用/禁用控制器——禁用后 FreeCamera 不处理输入；",
            "  - 🔧 右上角实时显示所有参数——方便调试时观察；",
            "- **场景搭建**:",
            "  - 多个 PointLight 不同颜色——验证空间感知；",
            "  - 地板双面渲染（cull_mode: None）——俯视时也能看到地板底面；",
            "  - 🔧 场景包含隐藏物体（地板下/墙后）——验证自由相机的探索能力；",
        ],
        [
            "知：<br>- FreeCamera 组件参数（sensitivity/friction/speed）；<br>- FreeCameraPlugin 自动输入处理；<br>- 6 轴自由移动。",
            "例：<br>- camera/camera_orbit.rs(200)；<br>- 3D/3d_scene.rs(32)。",
        ],
    ),
    (
        202,
        "相机",
        [
            "**意图**：第一人称相机 ViewModel/WorldModel 分离——两个 Camera3d 使用不同 RenderLayers 和 FOV，实现手臂（视图模型）与场景（世界模型）独立渲染。⭐⭐⭐",
            "- **ViewModel/WorldModel 分离**:",
            "  - WorldModelCamera: Camera3d 默认 layer(0)，fov=90°——渲染场景；",
            "  - View Model Camera: Camera3d layer(1)，order=1，fov=70°——渲染手臂；",
            "  - 🔧 不同 FOV 让手臂比例不受场景 FOV 调整影响——FPS 游戏标准做法；",
            "- **RenderLayers 分层渲染**:",
            "  - DEFAULT_RENDER_LAYER = 0：场景物体 + 世界模型相机；",
            "  - VIEW_MODEL_RENDER_LAYER = 1：玩家手臂 + 视图模型相机；",
            "  - 光源 RenderLayers::from_layers(&[0, 1])——照亮两个层的物体；",
            "  - ⚠️ 不在 RenderLayers 中的实体对该相机不可见——精确控制渲染范围；",
            "- **鼠标环顾**:",
            "  - CameraSensitivity(Vec2) 组件存储水平/垂直灵敏度；",
            "  - AccumulatedMouseMotion 获取鼠标位移——不乘 delta_time；",
            "  - EulerRot::YXZ 提取 yaw/pitch/roll——pitch clamp 防止翻转；",
            "  - 🔧 水平灵敏度 0.003 > 垂直 0.002——符合 FPS 游戏惯例；",
            "- **FOV 动态调节**:",
            "  - ArrowUp/Down 调整世界模型相机 FOV——20°~160° 范围；",
            "  - Perspective { fov } 直接修改投影参数——即时生效；",
            "  - 🔧 FOV 调节仅影响世界模型——手臂比例保持不变；",
            "- **NotShadowCaster**:",
            "  - 玩家手臂添加 NotShadowCaster——防止手臂投射不合理的阴影；",
            "  - 🔧 自由浮动的视图模型不应投射阴影——视觉上更正确；",
        ],
        [
            "知：<br>- RenderLayers 分层渲染（layer 0/1）；<br>- ViewModel/WorldModel 双相机分离；<br>- 不同 FOV 独立控制。",
            "例：<br>- camera/camera_orbit.rs(200)；<br>- 3D/two_passes.rs(50)。",
        ],
    ),
    (
        203,
        "相机",
        [
            "**意图**：实现自定义 CameraProjection——定义 ObliquePerspectiveProjection 偏斜透视投影，通过修改投影矩阵的第 3 列实现非对称消失点。⭐⭐⭐",
            "- **CameraProjection trait**:",
            "  - fn get_clip_from_view(&self) -> Mat4 返回裁剪空间矩阵——核心方法；",
            "  - fn get_clip_from_view_for_sub(&self, sub_view) -> Mat4 子视口适配；",
            "  - fn update(&mut self, width, height) 窗口尺寸变化时更新内部状态；",
            "  - fn far(&self) -> f32 返回远裁剪面距离；",
            "  - 🔧 仅 get_clip_from_view 是必须重写的——其余方法有默认实现；",
            "- **偏斜透视实现**:",
            "  - PerspectiveProjection::default() 基础透视投影；",
            "  - mat.col_mut(2)[0] = horizontal_obliqueness 修改第 3 列第 1 行——水平偏移；",
            "  - mat.col_mut(2)[1] = vertical_obliqueness 修改第 3 列第 2 行——垂直偏移；",
            "  - ⚠️ 修改投影矩阵的第 3 列是偏斜变换的标准做法——改变裁剪空间的对称性；",
            "- **Projection::custom()**:",
            "  - Projection::custom(ObliquePerspectiveProjection { ... }) 使用自定义投影；",
            "  - 🔧 Projection 枚举支持 Perspective/Orthographic/Custom 三种变体；",
            "- **场景效果**:",
            "  - 偏斜 0.2/0.6——消失点偏移到画面右上方；",
            "  - 地面圆盘 + 立方体展示偏斜效果——物体看起来向右上方倾斜；",
            "  - 🔧 此效果常用于风格化渲染/斜 45° 视角/等距投影变体；",
            "- **注意事项**:",
            "  - ⚠️ get_frustum_corners 直接委托给内部 PerspectiveProjection——视锥体计算不受偏斜影响；",
        ],
        [
            "知：<br>- CameraProjection trait 自定义投影；<br>- 投影矩阵第 3 列偏斜变换；<br>- Projection::custom()。",
            "例：<br>- 3D/orthographic.rs(53)；<br>- camera/projection_zoom.rs(204)。",
        ],
    ),
    (
        204,
        "相机",
        [
            "**意图**：正交/透视投影相机的鼠标滚轮缩放——正交投影通过 scale 参数缩放，透视投影通过 FOV 调整，Space 键切换投影类型。⭐⭐⭐",
            "- **正交投影缩放**:",
            "  - OrthographicProjection { scale, .. } 控制缩放倍数——scale 越小视野越窄（放大）；",
            "  - ScalingMode::FixedVertical { viewport_height } 固定视口高度——宽高比变化时保持高度；",
            "  - 🔧 对数缩放：multiplicative_zoom = 1 + delta——正负 delta 产生对称的缩放感；",
            "- **透视投影缩放**:",
            "  - PerspectiveProjection { fov } 控制视场角——fov 越小视野越窄（放大）；",
            "  - ⚠️ fov 范围 (PI/5)..(PI-0.2)——约 36°~172°——防止极端值导致视觉异常；",
            "  - perspective.fov += delta_zoom 线性调整——比正交的对数缩放更直观；",
            "- **投影类型切换**:",
            "  - **camera = match **camera { Orthographic → Perspective, Perspective → Orthographic }；",
            "  - ⚠️ 切换时重置投影参数到初始值——避免保留上次的缩放状态；",
            "  - 🔧 Space 键切换——同一场景两种投影效果对比；",
            "- **AccumulatedMouseScroll**:",
            "  - mouse_wheel_input.delta.y 滚轮垂直方向——正值向上（放大），负值向下（缩小）；",
            "  - ⚠️ 取反（-delta）是因为正交投影中 scale 减小 = 放大——需要与用户直觉一致；",
            "- **CameraSettings Resource**:",
            "  - orthographic_zoom_range/speed + perspective_zoom_range/speed 四组参数；",
            "  - 🔧 所有参数存储在 Resource 中——运行时可通过 UI 调节；",
        ],
        [
            "知：<br>- OrthographicProjection scale 缩放；<br>- PerspectiveProjection fov 缩放；<br>- 投影类型运行时切换。",
            "例：<br>- 3D/orthographic.rs(53)；<br>- camera/custom_projection.rs(203)。",
        ],
    ),
    (
        205,
        "相机",
        [
            "**意图**：使用双 Camera2d + RenderLayers 在 UI 上层渲染 2D 物体——默认相机渲染 UI，高 order 相机渲染精灵，实现 UI 与游戏内容分层。⭐⭐",
            "- **双 Camera2d 分层**:",
            "  - Camera 1：Camera2d + IsDefaultUiCamera——默认 UI 渲染相机（order=0）；",
            "  - Camera 2：Camera2d + Camera { order: 1, clear_color: None }——2D 物体渲染相机；",
            "  - ⚠️ Camera 2 的 clear_color 设为 None——不清除 Camera 1 的渲染结果；",
            "  - 🔧 Camera 2 的 order=1 确保在 UI 之上渲染——2D 物体遮挡 UI 元素；",
            "- **RenderLayers 分层**:",
            "  - Camera 2 使用 RenderLayers::layer(1)——仅渲染 layer 1 的实体；",
            "  - Sprite 添加 RenderLayers::layer(1)——被 Camera 2 渲染；",
            "  - UI 节点不加 RenderLayers——默认 layer(0)，仅被 Camera 1 渲染；",
            "  - 🔧 RenderLayers 是精确控制「谁看到什么」的利器——比 Camera order 更灵活；",
            "- **IsDefaultUiCamera**:",
            "  - IsDefaultUiCamera 标记默认 UI 相机——UI 节点自动绑定到此相机；",
            "  - 🔧 替代方案：UiTargetCamera(camera_entity) 显式绑定——更精确但更繁琐；",
            "- **Sprite 旋转动画**:",
            "  - sprite.rotation *= Quat::from_rotation_z(dt * 0.5) * Quat::from_rotation_y(dt)；",
            "  - 🔧 双轴旋转产生复杂运动——验证 Camera 2 正确渲染 2D 物体；",
            "- **应用场景**:",
            "  - 🧩 3D 场景上的 2D HUD/准星/伤害数字——需要在 UI 层之上渲染；",
            "  - 🧩 地图编辑器：UI 面板 + 2D 网格/标记物分层显示；",
        ],
        [
            "知：<br>- 双 Camera2d + Camera::order 分层；<br>- RenderLayers 控制可见性；<br>- IsDefaultUiCamera 默认 UI 相机。",
            "例：<br>- 2D/sprite.rs(2)；<br>- ui/button.rs(230)。",
        ],
    ),
    (
        206,
        "调试绘图",
        [
            "**意图**：2D Gizmos 即时模式绘图完整演示——线段/射线/网格/三角形/矩形/十字/曲线/圆/椭圆/弧/箭头，以及自定义 GizmoConfigGroup 和线宽/样式/连接控制。⭐⭐⭐",
            "- **Gizmos 基本图元**:",
            "  - gizmos.line_2d(start, end, color) 2D 线段；",
            "  - gizmos.ray_2d(origin, direction, color) 2D 射线（从原点沿方向）；",
            "  - gizmos.grid_2d(isometry, cells, spacing, color) 2D 网格；",
            "  - gizmos.rect_2d(isometry, size, color) 2D 矩形；",
            "  - gizmos.cross_2d(position, size, color) 2D 十字标记；",
            "  - gizmos.arrow_2d(start, end, color) 2D 箭头——支持 with_double_end() 双头；",
            "  - 🔧 所有 2D gizmos 使用 Isometry2d 定位——IDENTITY = 原点无旋转；",
            "- **曲线与渐变**:",
            "  - gizmos.curve_gradient_2d(curve, times_and_colors) 沿曲线渐变色绘制；",
            "  - FunctionCurve::new(domain, |t| Vec2) 定义参数曲线——t 为参数；",
            "  - gizmos.linestrip_gradient_2d([(pos, color), ...]) 渐变色折线——三角形示例；",
            "  - 🔧 渐变色使用 mix() 混合——TEAL.mix(&HOT_PINK, t) 线性插值；",
            "- **圆/椭圆/弧**:",
            "  - gizmos.circle_2d(isometry, radius, color).resolution(64) 指定分辨率的圆；",
            "  - gizmos.ellipse_2d(rotation, radii, color) 椭圆——Rot2 控制旋转；",
            "  - gizmos.arc_2d(direction, angle, radius, color) 弧形——角度和半径控制；",
            "  - gizmos.rounded_rect_2d(isometry, size, color).corner_radius(r) 圆角矩形；",
            "  - 🔧 圆形默认 32 线段——大圆需要提高 resolution 避免锯齿；",
            "- **自定义 GizmoConfigGroup**:",
            "  - #[derive(Default, Reflect, GizmoConfigGroup)] struct MyRoundGizmos {}；",
            "  - init_gizmo_group::<MyRoundGizmos>() 注册自定义组；",
            "  - Gizmos<MyRoundGizmos> 独立配置——与默认组互不干扰；",
            "  - 🔧 多组 gizmos 可独立控制可见性/线宽/样式——调试时选择性显示；",
            "- **运行时配置调节**:",
            "  - GizmoConfigStore 资源存储所有组的配置；",
            "  - config.line.width 线宽（0~50）；config.line.style 线样式（Solid/Dotted/Dashed）；",
            "  - config.line.joints 线连接（None/Bevel/Miter/Round）；",
            "  - Space 暂停 Virtual 时间——验证 gizmos 在暂停时仍可绘制；",
        ],
        [
            "知：<br>- Gizmos 2D 图元（line/grid/rect/circle/arc/arrow）；<br>- GizmoConfigGroup 自定义组；<br>- GizmoConfigStore 运行时配置。",
            "例：<br>- 2D/move_sprite.rs(3)；<br>- gizmos/3d_gizmos.rs(207)。",
        ],
    ),
]

# Build filename→entry map
ENTRY_MAP = {}
for seq, cat, intent, knowledge in DATA:
    ENTRY_MAP[seq] = (cat, intent, knowledge)


def build_row(seq, cat, filename, intent_lines, knowledge_lines):
    """Build a single catalog table row."""
    intent_text = "<br>".join(intent_lines)
    knowledge_text = "<br>".join(knowledge_lines)
    return f"| {seq} | {cat} | {filename} | {intent_text} | {knowledge_text} |"


def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    new_lines = []
    replaced = set()

    for line in lines:
        # Match table rows like: | 177 | 输入处理 | `keyboard_input.rs` | ...
        m = re.match(r"^\|\s*(\d+)\s*\|", line)
        if m:
            seq = int(m.group(1))
            if seq in ENTRY_MAP:
                # Extract filename from the line
                fm = re.search(r"\|\s*`([^`]+)`\s*\|", line)
                if fm:
                    filename = f"`{fm.group(1)}`"
                else:
                    # Fallback
                    parts = line.split("|")
                    filename = parts[3].strip() if len(parts) > 3 else "`unknown.rs`"

                cat, intent, knowledge = ENTRY_MAP[seq]
                new_line = build_row(seq, cat, filename, intent, knowledge)
                new_lines.append(new_line)
                replaced.add(seq)
                continue

        new_lines.append(line)

    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(new_lines))

    print(f"Replaced {len(replaced)} entries: {sorted(replaced)}")
    missing = set(ENTRY_MAP.keys()) - replaced
    if missing:
        print(f"WARNING: Not found in catalog: {sorted(missing)}")


if __name__ == "__main__":
    main()
