#!/usr/bin/env python3
"""Replace catalog entries 346-375 with detailed content from source files."""

import re

CATALOG_PATH = "/Users/lf380/Code/Bevy/a1/bevy_examples_catalog.md"

# DATA = [(seq, "分类", [intent_lines], [knowledge_lines], [example_lines])]
DATA = [
    # ── Stress Tests ──────────────────────────────────────────────
    (
        346,
        "压力测试",
        [
            "**意图**：大量 3D 立方体/形状的渲染性能基准测试，支持球面/立方体/密集三种布局；⭐⭐⭐",
            "- **布局模式**:",
            "  - Sphere 布局：Fibonacci 螺旋球面均匀分布（WIDTH×HEIGHT×4=160000 个实体），确保不同视角可见数量一致；",
            "  - Cube 布局：四面立方体阵列，每 10 格间隔插入空隙防摩尔纹，测试视锥剔除效果；",
            "  - Dense 布局：密集立方体堆叠（cbrt 计算网格），所有实体始终在视锥内——测试无剔除场景；",
            "- **渲染优化开关**:",
            "  - --no-frustum-culling: NoFrustumCulling 禁用视锥剔除，所有 MeshMaterial 实体始终绘制；",
            "  - --no-automatic-batching: NoAutomaticBatching 禁用自动合批，压力测试绘制命令编码；",
            "  - --no-indirect-drawing: NoIndirectDrawing 禁用间接绘制；",
            "  - --no-cpu-culling: NoCpuCulling 禁用 CPU 剔除；",
            "- **多 Mesh 变体**:",
            "  - 15 种图元随机选择：Cuboid/Capsule3d/Circle/Triangle2d/Rectangle/RegularPolygon(5-8边)/Cylinder/Ellipse/Plane3d/Sphere/Torus/Capsule2d；",
            "  - ChaCha8Rng 种子化随机确保结果确定性——可复现；",
            "- **材质变体**:",
            "  - --vary-material-data-per-instance 每实例独立材质（大量不同 Material Handle）；",
            "  - --material-texture-count N 随机纹理采样；",
            "  - --animate-materials 每帧 CPU 更新材质颜色（fast_hue_to_rgb 优化）；",
            "- **其他功能**:",
            "  - --rotate-cubes: par_iter_mut 并行旋转立方体；",
            "  - --shadows: 方向光级联阴影；",
            "  - --benchmark 固定帧步长保证跨运行一致性；",
            "  - WinitSettings continuous 模式消除输入等待——纯渲染压力；",
            "  - 🔬 默认关闭 VSync（PresentMode::AutoNoVsync）+ 1920×1080 无缩放——最大帧率；",
        ],
        [
            "知：<br>- Mesh3d/MeshMaterial3d 3D渲染组件；<br>- NoFrustumCulling/NoAutomaticBatching 渲染控制；<br>- Fibonacci 球面分布算法。",
            "例：<br>- 3D/3d_scene.rs(32)。",
        ],
    ),
    (
        347,
        "压力测试",
        [
            "**意图**：大量 2D Sprite 渲染性能测试，随机大小/旋转/缩放，相机旋转移动测试视锥剔除；⭐⭐",
            "- **Sprite 生成**:",
            "  - 地图尺寸 320×320，tile 64px，half_x/half_y = ±160，生成 102400 个 Sprite 实体；",
            "  - 每个 Sprite：随机 translation.z、随机 Quat::from_rotation_z、随机 scale(0~2)；",
            '  - assets.load("branding/icon.png") 共享同一纹理 Handle——测试合批性能；',
            "- **--colored 模式**:",
            "  - 三种颜色随机着色（BLUE/WHITE/RED），破坏合批——测试多批次渲染性能下降；",
            "  - 颜色着色通过 Sprite.color 字段实现——每个实例独立颜色；",
            "- **相机运动**:",
            "  - 相机绕 Z 轴旋转 + 沿 X 轴匀速移动（CAMERA_SPEED=1000）；",
            "  - 移动过程中大量 Sprite 进出视锥——测试剔除效率；",
            "- **诊断输出**:",
            "  - FrameTimeDiagnosticsPlugin + LogDiagnosticsPlugin 每秒打印 FPS 和 Sprite 数量；",
            "  - WinitSettings::continuous() + AutoNoVsync 最大帧率压力；",
        ],
        [
            "知：<br>- Sprite 组件与 Transform 随机变换；<br>- Camera2d 视锥剔除。",
            "例：<br>- 2D/sprite.rs(2)。",
        ],
    ),
    (
        348,
        "压力测试",
        [
            "**意图**：大规模 ECS 世界压力测试——动态注册 Component、动态生成 System、大量实体查询；⭐⭐⭐",
            "- **动态组件注册**:",
            "  - ComponentDescriptor::new_with_layout 创建 u8 布局的动态组件——⚠️ 需要 unsafe；",
            "  - ComponentCloneBehavior::Default + StorageType::Table——标准表存储；",
            "  - 默认 1000 个组件（Component1~Component1000）；",
            "- **动态 System 生成**:",
            "  - QueryParamBuilder 动态构建 Query——随机选择 1~10 个组件的读/写访问；",
            "  - base_system 使用 FilteredEntityMut + get_by_id/get_mut_by_id 动态访问组件值；",
            "  - Faulhaber 公式 mod 256 计算——确保不同 System 有不同执行时间；",
            "  - 默认 800 个 System；",
            "- **实体生成**:",
            "  - 每个实体随机 1~10 个组件 + 随机 u8 值；",
            "  - ManuallyDrop<u8> + OwningPtr 传递所有权到 World——⚠️ 避免 drop 双重释放；",
            "  - insert_by_ids 批量插入——unsafe 但高效；",
            "  - 默认 50000 个实体；",
            "- **命令行参数**:",
            "  - num_entities / num_components(≥10) / num_systems 均可自定义；",
            "  - MinimalPlugins（无渲染）+ DiagnosticsPlugin + FrameTimeDiagnosticsPlugin；",
            "  - 🔬 纯 ECS 查询压力——不涉及渲染，测试调度器和查询匹配性能；",
        ],
        [
            "知：<br>- 动态 ComponentDescriptor 注册；<br>- FilteredEntityMut 动态访问；<br>- QueryParamBuilder 动态查询构建。",
            "例：<br>- ecs/ecs_guide.rs(124)。",
        ],
    ),
    (
        349,
        "压力测试",
        [
            "**意图**：大量 UI 按钮压力测试——布局/文本/交互/渲染综合性能基准；⭐⭐",
            "- **Flex/Grid 布局**:",
            "  - 默认 110×110=12100 个按钮网格；",
            "  - --grid 使用 Display::Grid + RepeatedGridTrack::flex 布局——对比 Flex 布局性能；",
            "  - 默认 Flex 布局：嵌套 Node（Column→Row→Button）；",
            "- **按钮样式**:",
            "  - 每个按钮：Button + Node（vw/vh 百分比尺寸）+ BackgroundColor（彩虹色 HSL）+ BorderColor；",
            "  - --text 模式添加 Text + TextSpan 文本标签——压测文本布局；",
            "  - --image-freq N 每 N 个按钮添加 ImageNode 图标；",
            "- **交互系统**:",
            "  - button_system: Interaction::Hovered 切换 ORANGE_RED 背景色；",
            "  - Changed<Interaction> 仅在交互变化时触发——Bevy 内置优化；",
            "- **压力变体**:",
            "  - --relayout: 每帧对所有 Node 调用 set_changed() 强制重新布局；",
            "  - --recompute-text: 每帧强制文本重新计算；",
            "  - --respawn: 每帧 despawn 整棵 UI 树并重新创建——最极端的压力测试；",
            "  - --display-none: Display::None 移除所有节点布局——测试隐藏性能；",
            "  - --many-cameras: 每个按钮一个 Camera2d——极端多相机压力；",
            "  - 🔬 Display::None 但仍渲染——测试跳过布局但保留渲染的成本；",
        ],
        [
            "知：<br>- Button 交互组件；<br>- Display::Grid/Flex 布局；<br>- Changed&lt;T&gt; 变更检测过滤。",
            "例：<br>- ui/button.rs(232)。",
        ],
    ),
    (
        350,
        "压力测试",
        [
            "**意图**：大量不同材质的 3D 渲染压力测试——每帧 CPU 更新所有材质颜色；⭐⭐",
            "- **材质网格**:",
            "  - 默认 10×10=100 个 Cuboid 立方体（-n N 自定义网格大小）；",
            "  - 每个立方体独立 StandardMaterial——测试多材质实例渲染性能；",
            "- **材质动画**:",
            "  - animate_materials 系统每帧遍历所有 MeshMaterial3d Handle；",
            "  - Color::hsl(hue, 1.0, 0.5) 动态计算彩虹色——基于索引和时间的偏移；",
            "  - materials.get_mut(handle) 直接修改材质数据——触发 GPU 上传；",
            "- **场景设置**:",
            "  - Camera3d 从高角度俯视网格；",
            "  - DirectionalLight + shadows_enabled 阴影渲染压力；",
            "  - WinitSettings continuous + AutoNoVsync 最大帧率；",
            "  - 🔬 每帧修改所有材质 base_color——测试材质脏标记和 GPU 重传性能；",
        ],
        [
            "知：<br>- StandardMaterial 基础材质；<br>- Color::hsl 动态颜色；<br>- ResMut&lt;Assets&lt;StandardMaterial&gt;&gt; 材质修改。",
            "例：<br>- 3D/3d_shapes.rs(33)。",
        ],
    ),
    (
        351,
        "压力测试",
        [
            "**意图**：大量点光源渲染压力测试——100000 个 PointLight 的聚类和渲染性能；⭐⭐⭐",
            "- **光源分布**:",
            "  - 100000 个 PointLight 通过 Fibonacci 螺旋球面均匀分布——确保各视角可见数量一致；",
            "  - 每个光源：range=0.3（极小范围）+ intensity=1000——仅照亮周围小区域；",
            "  - DEEP_PINK 颜色——测试多光源颜色混合；",
            "- **聚类渲染**:",
            "  - 🔬 Bevy 内置聚类前向渲染器——将光源分配到屏幕空间簇；",
            "  - ExtractedPointLight / GlobalClusterableObjectMeta 聚类元数据追踪；",
            "  - RenderApp + RenderSystems hook 用于提取聚类统计；",
            "- **反向球体**:",
            "  - 反向缩放 Sphere（scale=-ONE）作为光源载体——所有光源在球体内侧；",
            "  - Fibonacci 球面分布保证可见光源数量恒定——排除视角影响；",
            "- **交互功能**:",
            "  - 相机绕球面旋转观察不同角度的光照效果；",
            "  - 每秒打印可见光源数量（LogVisibleLights 自定义插件）；",
            "  - ⚠️ WGPU_SETTINGS_PRIO=webgl2 可限制为 uniform buffer + 最大 256 光源——测试降级路径；",
            "  - 🔬 100K 光源在高端 GPU 可达 60fps，低端设备可能严重掉帧；",
        ],
        [
            "知：<br>- PointLight 聚类前向渲染；<br>- Fibonacci 球面分布；<br>- RenderApp 渲染管线 hook。",
            "例：<br>- 3D/lighting.rs(35)。",
        ],
    ),
    (
        352,
        "压力测试",
        [
            "**意图**：大量骨骼动画狐狸的渲染和动画性能测试——glTF 蒙皮网格 + AnimationPlayer；⭐⭐⭐",
            "- **狐狸生成**:",
            "  - 默认 1000 只狐狸（--count N 自定义）——从 Fox.glb 加载 Scene(0)；",
            "  - 同心环分布：RING_SPACING=2m 间隔，FOX_SPACING=2m 间距——交替顺时针/逆时针运动；",
            "  - Scale::splat(0.01) 缩放狐狸模型——防止环间重叠；",
            "- **动画系统**:",
            "  - AnimationGraph 同时加载 3 个动画剪辑（Animation 0/1/2）；",
            "  - setup_scene_once_loaded Observer：SceneInstanceReady 时自动播放动画；",
            "  - ⚠️ 非同步模式：seek_to(entity.index / 10.0) 错开起始帧——避免所有狐狸同步；",
            "  - --sync 模式：所有狐狸同步播放——测试同步动画合批效果；",
            "- **动画控制**:",
            "  - Space: 暂停/恢复全部动画；",
            "  - ArrowUp/Down: 调整播放速度（×1.25/×0.8）；",
            "  - ArrowLeft/Right: seek 前后 0.1 秒；",
            "  - Enter: AnimationTransitions::play 切换动画剪辑（250ms 过渡）；",
            "- **渲染特性**:",
            "  - CascadeShadowConfigBuilder 配置级联阴影——first_cascade_far_bound 和 maximum_distance 按狐狸环半径动态设置；",
            "  - StaticTransformOptimizations::disabled() 禁用静态变换优化——狐狸持续运动；",
            "  - 🔬 蒙皮网格 + 骨骼动画是 GPU 开销最大的场景之一；",
        ],
        [
            "知：<br>- glTF 蒙皮动画加载；<br>- AnimationGraph/AnimationPlayer；<br>- SceneInstanceReady Observer。",
            "例：<br>- animation/animated_mesh.rs(102)。",
        ],
    ),
    (
        353,
        "压力测试",
        [
            "**意图**：大量 Gizmo 调试线绘制的性能测试——10 个系统并行绘制 50000 条线；⭐⭐",
            "- **线绘制**:",
            "  - 默认 50000 条线，分配到 10 个 system（SYSTEM_COUNT=10），每个系统绘制 5000 条；",
            "  - 普通模式：gizmos.line(NEG_Y, Y, BLACK)——简单直线；",
            "  - Fancy 模式：gizmos.line_gradient——渐变色线，sin/cos 计算颜色，更复杂的片段着色器路径；",
            "- **交互控制**:",
            "  - ArrowUp/Down: 增减 10000 条线（saturating_sub 防下溢）；",
            "  - Space: 切换普通/Fancy 模式；",
            "  - 实时 FPS 显示在左上角 Text 节点；",
            "- **注意事项**:",
            "  - Gizmo 每帧重新绘制（不持久化）——每次 Update 调用都完整重绘；",
            "  - 🔬 Gizmo 绘制走即时模式管线——大量调用会压测命令缓冲区编码；",
            "  - 🔧 10 个独立 system 测试多 System 间 Gizmo 缓冲区隔离性能；",
        ],
        [
            "知：<br>- Gizmos 调试绘制 API；<br>- line/line_gradient 线绘制。",
            "例：<br>- gizmos/2d_gizmos.rs(206)。",
        ],
    ),
    (
        354,
        "压力测试",
        [
            "**意图**：大量字形文本渲染性能测试——100000 个字符的 UI Text 和 Text2d；⭐⭐",
            "- **文本内容**:",
            '  - 100000 个字符："0123456789" 重复 10000 次——包含数字和标点的密集字形集；',
            "  - --many-glyphs: 从 5 个 Unicode 范围随机选取 4 个字符——增加字体图集纹理数量；",
            "  - --many-font-sizes: 6 种字号随机选择——增加字体图集变体；",
            "- **双通道渲染**:",
            "  - UI Text：居中 Flex 布局 + 白色文本——测试 UI 文本管线；",
            "  - Text2d：红色文本 + TextBounds 水平宽度 1000px——测试 2D 文本管线；",
            "  - --no-ui / --no-text2d 分别禁用——隔离单管线性能；",
            "- **文本配置**:",
            "  - font_size=4（极小字号）——最大化字形密度；",
            "  - TextLayout + LineBreak::AnyCharacter——任意字符换行；",
            "  - --center: Justify::Center 居中对齐——对比 Left 性能差异；",
            "- **压力变体**:",
            "  - --recompute: 每帧对所有 TextLayout 调用 set_changed() 强制重算；",
            "  - --no-frustum-culling: NoFrustumCulling 禁用剔除——所有 Text2d 始终渲染；",
            "  - FontAtlasSet 追踪字体图集纹理数量——监控图集增长；",
            "  - 🔬 小字号 + 大量字形 = 最大化字体图集纹理切换和字形缓存压力；",
        ],
        [
            "知：<br>- Text2d/Text 文本组件；<br>- FontAtlasSet 字体图集；<br>- TextBounds 文本约束。",
            "例：<br>- ui/text.rs(233)。",
        ],
    ),
    (
        355,
        "压力测试",
        [
            "**意图**：大量 UI 渐变（LinearGradient）渲染性能测试——CPU 预转换颜色空间优化；⭐⭐",
            "- **渐变网格**:",
            "  - 默认 900 个渐变节点（--gradient-count N 自定义）——Display::Grid 布局；",
            "  - 每个渐变：7 个 ColorStop（RED/BLUE/GREEN/YELLOW/ORANGE/LIME/DARK_CYAN）；",
            "  - 角度按索引递增（i×10°%360°）——测试不同方向渐变性能；",
            "- **颜色空间**:",
            "  - 默认 OkLab 空间——感知均匀的颜色插值；",
            "  - --srgb: InterpolationColorSpace::Srgba——传统 sRGB 插值；",
            "  - --hsl: InterpolationColorSpace::Hsla——色相环插值；",
            "  - 🔧 OkLab 是性能和视觉质量的最佳平衡——大多数场景推荐；",
            "- **动画模式**:",
            "  - --animate: 每帧更新所有渐变的 ColorStop 颜色（sin 偏移）；",
            "  - 触发渐变脏标记 → 重新计算渐变纹理 → GPU 上传；",
            "  - 🔬 动画模式下每帧重算 900 个渐变——测试 CPU 颜色转换瓶颈；",
            "- **注意事项**:",
            "  - BackgroundGradient(vec![Gradient::Linear(gradient)]) 组件；",
            "  - InterpolationColorSpace 影响渐变纹理的生成方式——不同空间性能特征不同；",
            "  - 🔬 非动画模式下渐变纹理仅生成一次——测试首次渲染和缓存命中；",
        ],
        [
            "知：<br>- BackgroundGradient/LinearGradient 渐变组件；<br>- InterpolationColorSpace 颜色空间；<br>- ColorStop 渐变停点。",
            "例：<br>- ui/gradients.rs(245)。",
        ],
    ),
    (
        356,
        "压力测试",
        [
            "**意图**：多相机多光源 3D 渲染压力测试——4×4=16 个视口 + 5 个彩色点光源；⭐⭐",
            "- **多相机系统**:",
            "  - CAMERA_ROWS=4 × CAMERA_COLS=4 = 16 个 Camera3d；",
            "  - 每个相机独立 Viewport：physical_position 按行列计算，physical_size = 窗口尺寸/4；",
            "  - Camera.order 按索引递增——控制渲染优先级和视口叠加顺序；",
            "- **多光源**:",
            "  - NUM_LIGHTS=5 个 PointLight 环形分布——HSV 颜色均匀分配；",
            "  - intensity = 2000000/5 = 400000 每个——总亮度恒定；",
            "  - shadows_enabled: 每个光源独立阴影贴图——⚠️ 5 个阴影贴图是主要开销；",
            "- **相机旋转**:",
            "  - 所有相机绕原点 rotate_around——持续旋转观察场景；",
            "  - Quat::from_rotation_y(delta) 每帧递增旋转；",
            "- **场景元素**:",
            "  - Circle(4.0) 平面 + Cuboid(1,1,1) 立方体——简单几何体；",
            "  - 🔬 16 个视口 × 5 光源 = 80 次渲染遍历——测试多视口和阴影贴图性能；",
            "  - 🔧 返回 Result 类型——Bevy 0.18+ 系统错误处理新模式；",
        ],
        [
            "知：<br>- Camera Viewport 分屏；<br>- 多 Camera3d 渲染顺序；<br>- PointLight 阴影贴图。",
            "例：<br>- 3D/3d_scene.rs(32)。",
        ],
    ),
    (
        357,
        "压力测试",
        [
            "**意图**：大量帧动画 Sprite 渲染性能测试——TextureAtlas 帧切换 + 视锥剔除；⭐⭐",
            "- **动画 Sprite 生成**:",
            "  - 地图 320×320，tile 64px，生成 102400 个动画 Sprite；",
            "  - TextureAtlasLayout::from_grid(UVec2::splat(24), 7, 1)——24×24 像素 7 帧精灵表；",
            "  - 每个 Sprite：随机位置/旋转/缩放 + AnimationTimer（TimerMode::Repeating, 0.1s）；",
            "- **动画系统**:",
            "  - animate_sprite 系统：timer.tick() → just_finished() → atlas.index = (index+1) % len；",
            "  - TextureAtlas.index 帧推进——7 帧循环播放；",
            "  - ⚠️ 每个 Sprite 独立 Timer——不同步，避免所有 Sprite 同帧切换；",
            "- **相机运动**:",
            "  - 相机绕 Z 轴旋转 + X 轴匀速移动（CAMERA_SPEED=1000）；",
            "  - 移动中大量 Sprite 进出视锥——测试动态剔除；",
            "- **诊断输出**:",
            "  - 每秒打印存活 Sprite 数量；",
            "  - FrameTimeDiagnosticsPlugin 实时 FPS；",
            "  - 🔬 比静态 Sprite 多了帧动画开销——每帧遍历所有 Timer + 更新 Atlas Index；",
        ],
        [
            "知：<br>- TextureAtlasLayout 帧动画；<br>- AnimationTimer 组件驱动；<br>- TimerMode::Repeating 循环。",
            "例：<br>- 2D/sprite_sheet.rs(10)。",
        ],
    ),
    (
        358,
        "压力测试",
        [
            "**意图**：大量 Text2d 实体渲染性能测试——随机字形/字号/颜色/变换；⭐⭐",
            "- **Text2d 生成**:",
            "  - 地图 640×640，tile 64px，生成 25600 个 Text2d 实体；",
            "  - 每个：随机位置/旋转/缩放 + 随机 HSL 颜色——视觉上可区分；",
            "  - ChaCha8Rng 种子化随机——确定性结果；",
            "- **字形变体**:",
            '  - 默认模式：所有 Text2d 显示 "Bevy"——单一字形集；',
            "  - --many-glyphs: 从 5 个 Unicode 范围随机选取 4 字符——增加字体图集纹理；",
            "  - CODE_POINT_RANGES 覆盖拉丁/西里尔/希腊等多文字范围；",
            "- **字号变体**:",
            "  - --many-font-sizes: 6 种字号（10/20/30/40/50/60）随机——增加字体图集变体；",
            "  - 默认固定 60px——最小化图集变体；",
            "- **压力变体**:",
            "  - --recompute: 每帧 set_changed() 强制文本重算；",
            "  - --no-frustum-culling: NoFrustumCulling 禁用剔除；",
            "  - --center: Justify::Center 居中对齐；",
            "- **诊断追踪**:",
            "  - FontAtlasSet 追踪字形图集纹理数量——监控图集增长；",
            "  - 每秒打印 Texts/Visible/Atlases 三项指标；",
            "  - 🔬 字体图集是文本渲染的关键瓶颈——每种字号+字形组合可能生成新纹理；",
        ],
        [
            "知：<br>- Text2d 2D 文本；<br>- FontAtlasSet 字体图集缓存；<br>- CODE_POINT_RANGES 字形范围。",
            "例：<br>- 2D/text2d.rs(11)。",
        ],
    ),
    (
        359,
        "压力测试",
        [
            "**意图**：交互式 2D Sprite 生成/销毁基准测试——鼠标拖动生成 Bird 实体 + 物理碰撞；⭐⭐⭐",
            "- **生成模式**:",
            "  - 鼠标按住持续生成：BIRDS_PER_SECOND=10000 只/秒；",
            "  - 每次释放鼠标：随机切换 Bird 颜色（Counter.color）；",
            "  - --benchmark: 固定帧步长（FIXED_TIMESTEP=0.2s）保证跨运行一致；",
            "  - --per-wave / --waves: 分批预生成——测试批量 spawn 性能；",
            "- **渲染模式**:",
            "  - Mode::Sprite: 标准 Sprite 组件 + Bevy icon 纹理；",
            "  - Mode::Mesh2d: Mesh2d + MeshMaterial2d + Rectangle 网格——测试 2D Mesh 路径；",
            "  - --material-texture-count N: 程序化生成纹理——Image::new_fill + Rgba8UnormSrgb；",
            "- **物理模拟**:",
            "  - GRAVITY=-980 重力 + 速度碰撞反弹——每帧遍历所有 Bird；",
            "  - handle_collision: 检测窗口边界反弹——测试大量实体碰撞检测；",
            "  - --ordered-z: 按生成顺序递增 Z 值——测试排序渲染性能；",
            "- **材质变体**:",
            "  - --vary-per-instance: 每实例独立 ColorMaterial——破坏合批；",
            "  - --alpha-mode: Opaque/Blend/AlphaMask 三种 AlphaMode2d 切换；",
            "  - 🔬 Blend 模式需画家算法排序——性能最差但视觉正确；",
            "- **诊断 UI**:",
            "  - 实时显示 Bird Count / FPS(raw) / FPS(SMA) / FPS(EMA)；",
            "  - StaticTransformOptimizations::disabled() 禁用静态优化——Bird 持续运动；",
            "  - 🔬 最经典的 Bevy 性能基准——混合 spawn/destroy + 物理 + 渲染；",
        ],
        [
            "知：<br>- Sprite/Mesh2d 2D 渲染；<br>- spawn_batch 批量生成；<br>- FrameTimeDiagnosticsPlugin 帧诊断。",
            "例：<br>- 2D/sprite.rs(2)。",
        ],
    ),
    (
        360,
        "压力测试",
        [
            "**意图**：文本管线压力测试——100 个 TextSpan 持续重算布局和渲染；⭐⭐",
            "- **文本结构**:",
            '  - 49 组 × 2 个 TextSpan = 98 个子 span——每组包含 "text"×i 和 "pipeline"×i；',
            "  - 两种字体交替：FiraMono-Medium.ttf（蓝色）和 FiraSans-Bold.ttf（黄色）；",
            "  - 字号动态变化：(4+i%10) 和 (4+i%11)——最大化字体图集变体；",
            "- **持续重算**:",
            "  - update_text_bounds 系统：每帧修改 TextBounds.width = (1+sin(t))×600；",
            "  - 宽度周期性变化触发文本重新排版——每帧重算所有 TextSpan 的换行和布局；",
            "  - ⚠️ TextBounds 变化是变更检测触发器——不需要手动 set_changed()；",
            "- **渲染配置**:",
            "  - Text2d 根节点 + Justify::Center 居中 + LineBreak::AnyCharacter；",
            "  - TextBounds::default() 初始无约束——宽度由系统动态设置；",
            "- **注意事项**:",
            "  - 🔬 每帧重排 98 个 span 的文本——压测布局引擎和字形缓存；",
            "  - 🔧 多字体+多字号+动态宽度 = 字体图集纹理切换最大化的极端场景；",
        ],
        [
            "知：<br>- TextSpan 富文本子节点；<br>- TextBounds 文本约束驱动换行；<br>- TextLayout 排版配置。",
            "例：<br>- ui/text.rs(233)。",
        ],
    ),
    (
        361,
        "压力测试",
        [
            "**意图**：Transform 层级传播性能测试——9 种预配置的树结构/人形骨骼；⭐⭐⭐",
            "- **测试配置**:",
            "  - large_tree: 深度 18、分支 8 的非均匀树——宽深平衡；",
            "  - wide_tree: 深度 3、分支 500 的浅宽树——测试宽层级传播；",
            "  - deep_tree: 深度 25、分支 2 的深窄链——测试深度传播；",
            "  - chain: 深度 2500 的纯链——极端深度测试；",
            "  - update_leaves: 仅更新叶子节点——测试叶节点变更传播；",
            "  - update_shallow: 仅更新前 8 层——测试浅层变更传播；",
            "- **人形骨骼配置**:",
            "  - humanoids_active: 4000 个活跃人形骨骼（67 个节点/mixamo 骨架）——每帧更新；",
            "  - humanoids_inactive: 10 活跃 + 3990 非活跃——测试静止层级开销；",
            "  - humanoids_mixed: 2000 活跃 + 2000 非活跃——混合场景；",
            "- **UpdateFilter 系统**:",
            "  - probability: 0~1 控制节点更新概率——评估增量更新性能；",
            "  - min_depth/max_depth: 深度过滤——仅更新特定层级范围；",
            "  - ⚠️ UpdateValue 组件标记需更新的节点——无此组件的节点不参与 Update 系统；",
            "- **Transform 传播**:",
            "  - update 系统修改 translation（cos/sin）——触发子节点 Transform 重新计算；",
            "  - ⚠️ 更新必须在 PostUpdate 之前——否则层级临时处于无效状态；",
            "  - 🔬 HUMANOID_RIG 67 节点骨架模拟真实骨骼动画场景——深度 6 层；",
            "  - 🔧 ExitCondition::DontExit + 无窗口——纯后台计算压力测试；",
        ],
        [
            "知：<br>- Transform 层级传播；<br>- Children/ChildOf 父子关系；<br>- HUMANOID_RIG 人形骨骼结构。",
            "例：<br>- ecs/hierarchy.rs(128)。",
        ],
    ),
    # ── Testbed ───────────────────────────────────────────────────
    (
        362,
        "测试床",
        [
            "**意图**：2D 渲染测试床——空格键循环切换 Shapes/Bloom/Text/Sprite/SpriteSlicing/Gizmos 六个场景；⭐⭐",
            "- **场景状态机**:",
            "  - Scene 枚举 derive(States) + impl Next trait——定义循环切换顺序；",
            "  - switch_scene 系统：空格键 → next_scene.set(scene.next())；",
            "  - DespawnOnExit(Scene::X) 组件——离开场景时自动 despawn 所有实体；",
            "- **Shapes 场景**:",
            "  - 10 种 2D 图元（Circle/CircularSector/CircularSegment/Ellipse/Annulus/Capsule2d/Rhombus/Rectangle/RegularPolygon/Triangle2d）；",
            "  - 彩虹色均匀分布——每种形状独立颜色；",
            "- **Bloom 场景**:",
            "  - HDR 颜色（7.5, 0, 7.5）+ Bloom::default()——测试 2D 泛光；",
            "  - Circle + RegularPolygon 六边形——高亮度发光体；",
            "- **Text 场景**:",
            "  - 4 种 Justify（Left/Right/Center/Justified）× 4 种 Anchor——16 种文本布局组合；",
            "  - TextBounds 约束测试——150×60 包围盒；",
            "  - 10 层旋转缩放 Text2d——测试 Z 排序和缩放渲染；",
            "- **Sprite/SpriteSlicing/Gizmos 场景**:",
            "  - Sprite: 4 种 Anchor + flip_x/flip_y 组合——测试翻转渲染；",
            "  - SpriteSlicing: 九宫格切片对比——原始 vs Sliced(TextureSlicer)；",
            "  - Gizmos: 2D 矩形/圆形 + grid 网格（outer_edges_x/y 变体）；",
            "  - 🔧 bevy_ci_testing feature 自动截图——CI 中遍历所有场景后退出；",
        ],
        [
            "知：<br>- States 状态机；<br>- DespawnOnExit 场景清理；<br>- Next trait 循环切换。",
            "例：<br>- 2D/2d_shapes.rs(12)。",
        ],
    ),
    (
        363,
        "测试床",
        [
            "**意图**：3D 渲染测试床——循环切换 Light/Bloom/Gltf/Animation/Gizmos/GltfCoordinateConversion 六个场景；⭐⭐",
            "- **场景状态机**:",
            "  - 与 2d.rs 相同模式：Scene 枚举 + Next trait + DespawnOnExit + 空格键切换；",
            "  - bevy_ci_testing 自动截图遍历；",
            "- **Light 场景**:",
            "  - 三种光源同屏：PointLight(RED) + SpotLight(LIME, inner/outer_angle) + DirectionalLight；",
            "  - Plane3d 平面 + Cuboid 立方体——展示光照效果；",
            "- **Bloom 场景**:",
            "  - Bloom::NATURAL 模式——5 个球体排列；",
            "  - 交替 emissive 材质（红/绿）——测试 HDR 泛光；",
            "- **Gltf 场景**:",
            "  - FlightHelmet glTF 模型 + EnvironmentMapLight 环境光；",
            "  - DirectionalLight 补光——标准 3D 模型查看配置；",
            "- **Animation 场景**:",
            "  - Fox.glb 动画——AnimationGraph + AnimationTransitions；",
            "  - pause_animation_frame: 暂停在 0.5 帧——展示静态姿态；",
            "- **Gizmos/GltfCoordinateConversion 场景**:",
            "  - 3D Gizmos：cube/sphere + 3D grid（outer_edges_x/y/z 8 种变体）；",
            "  - GltfConvertCoordinates：rotate_scene_entity + rotate_meshes——glTF 坐标系转换演示；",
            "  - ShowAabbGizmo 可视化网格包围盒；",
        ],
        [
            "知：<br>- 3D 光源类型；<br>- Bloom::NATURAL 泛光；<br>- GltfConvertCoordinates 坐标转换。",
            "例：<br>- 3D/3d_scene.rs(32)。",
        ],
    ),
    (
        364,
        "测试床",
        [
            "**意图**：UI 测试床——13 个场景循环测试 Image/Text/Grid/Borders/BoxShadow/TextWrap/Overflow/Slice/LayoutRounding/LinearGradient/RadialGradient/Transformations/ViewportCoords；⭐⭐⭐",
            "- **场景覆盖**:",
            "  - Image: 最简 ImageNode 显示 Bevy Logo；",
            "  - Text: 多种 TextSpan 组合——白/红/绿/蓝/黑+背景色+TextBackgroundColor；",
            "  - Grid: 顶层 Grid + 子 Grid 嵌套——测试 grid_column span 和 row/column 定义；",
            "  - Borders: 9 种 UiRect 边框组合 × 2 种圆角——测试 BorderColor + Outline；",
            "- **高级 UI 测试**:",
            "  - BoxShadow: 6 种阴影配置——不同 size/offset/spread/blur/border_radius 组合；",
            "  - TextWrap: 4 种 LineBreak 策略（AnyCharacter/WordBoundary/WordOrCharacter/NoWrap）× 2 段文本；",
            "  - Overflow: 4 种 Overflow 模式（visible/clip_x/clip_y/clip）——测试内容溢出行为；",
            "  - Slice: TextureSlicer 九宫格按钮——Stretch/Tile 两种 center_scale_mode 对比；",
            "- **渐变测试**:",
            "  - LinearGradient: 多种 InterpolationColorSpace（OkLab/sRGB/HSL）+ 网格布局对比；",
            "  - RadialGradient: 径向渐变 + 多种形状/大小配置；",
            "- **布局测试**:",
            "  - LayoutRounding: 10 行 Grid 布局——测试小数像素舍入精度；",
            "  - Transformations: UI 节点变换——测试 rotate/translate/scale 对布局的影响；",
            "  - ViewportCoords: 视口坐标系统测试——固定 1280×720 窗口；",
            "  - 🔧 DebugOutlines feature 场景——测试 bevy_ui_debug 调试轮廓渲染；",
        ],
        [
            "知：<br>- DespawnOnExit 场景清理；<br>- Display::Grid/Flex 布局；<br>- BorderColor/Outline/BoxShadow。",
            "例：<br>- ui/button.rs(232)。",
        ],
    ),
    (
        365,
        "测试床",
        [
            "**意图**：完整 UI 组件测试场景——展示 Bevy UI 几乎所有组件和布局特性；⭐⭐⭐",
            "- **布局结构**:",
            "  - 左侧边栏(200px) + 中间滚动内容 + 右侧固定面板——经典三栏布局；",
            "  - Flex 布局 + Node::default() 嵌套——测试各种布局属性组合；",
            "- **UI 组件覆盖**:",
            "  - Text + TextSpan 富文本——多颜色/多字体文本段落；",
            "  - ImageNode 图片节点——bevy_logo + icon 纹理；",
            "  - Button 交互按钮——Interaction::Hovered/Pressed 状态切换；",
            "  - Scrollbar 滚动条组件——MouseWheel 滚动事件处理；",
            "- **视觉效果**:",
            "  - BackgroundColor 背景色——多种颜色/透明度；",
            "  - BorderColor 边框——各方向独立颜色和宽度；",
            "  - BoxShadow 投影——多层阴影效果；",
            "  - Outline 轮廓——额外的描边效果；",
            "- **无障碍支持**:",
            "  - AccessibilityNode + accesskit::Role——UI 无障碍树构建；",
            "  - Pickable::IGNORE 标记不可交互节点——优化拾取性能；",
            "  - HoverMap 悬停映射——追踪鼠标悬停状态；",
            "- **调试功能**:",
            "  - bevy_ui_debug feature: toggle_debug_overlay 系统——切换调试叠加层；",
            "  - BoxShadowSamples(6) 阴影采样数——平衡质量和性能；",
            "  - IsDefaultUiCamera 标记默认 UI 相机；",
        ],
        [
            "知：<br>- Scrollbar 滚动组件；<br>- AccessibilityNode 无障碍；<br>- Pickable 拾取控制。",
            "例：<br>- ui/standard_widgets.rs(271)。",
        ],
    ),
    (
        366,
        "测试床",
        [
            "**意图**：测试床辅助模块——CI 测试场景自动切换 + Next trait 定义；⭐",
            "- **Next trait**:",
            "  - pub trait Next { fn next(&self) -> Self; }——定义场景循环切换接口；",
            "  - 各测试床（2d/3d/ui）实现此 trait 定义自定义切换顺序；",
            "- **CI 测试支持**:",
            '  - #[cfg(feature = "bevy_ci_testing")] 条件编译——仅 CI 构建启用；',
            "  - switch_scene_in_ci 泛型系统：",
            "    - CiTestingConfig 注册截图事件——切换场景后 100 帧截图；",
            "    - scenes_visited: Local&lt;HashSet&lt;Scene&gt;&gt; 跟踪已访问场景；",
            "    - 所有场景截图完成后触发 AppExit——CI 自动退出；",
            "  - FrameCount 帧计数——精确控制截图时机；",
            "  - RemovedComponents&lt;Captured&gt; 监听截图完成事件——触发下一次切换；",
            "- **注意事项**:",
            "  - 🔧 FreelyMutableState 约束——Scene 必须是可变状态；",
            "  - 🔧 每个测试床共享同一套 CI 逻辑——模块复用设计；",
        ],
        [
            "知：<br>- CiTestingConfig CI 测试配置；<br>- Next trait 场景切换；<br>- FreelyMutableState 状态约束。",
            "例：<br>- testbed/ui.rs(365)。",
        ],
    ),
    # ── Tools ─────────────────────────────────────────────────────
    (
        367,
        "工具",
        [
            "**意图**：游戏手柄调试可视化工具——实时显示所有按钮/摇杆/扳机的状态和数值；⭐⭐",
            "- **按钮可视化**:",
            "  - 4 个方向按钮（North/South/West/East）：圆形 Mesh + 集群布局（BUTTON_CLUSTER_RADIUS=50）；",
            "  - Start/Select 按钮：矩形 Mesh——按压时切换紫色；",
            "  - D-Pad：三角形 Mesh + 旋转（PI/2 步进）——四方向指示；",
            "  - ReactTo&lt;GamepadButton&gt; 组件——按钮按下/释放时切换 NORMAL/ACTIVE 颜色材质；",
            "- **摇杆可视化**:",
            "  - 左右两个摇杆：dead zone（DEAD_COLOR）+ live zone（LIVE_COLOR）可视化；",
            "  - MoveWithAxes 组件——轴值驱动圆点位移（scale=STICK_BOUNDS_SIZE）；",
            "  - TextWithAxes 实时显示 X/Y 轴数值（格式化到 3 位小数）；",
            "- **扳机显示**:",
            "  - LeftTrigger/RightTrigger（模拟扳机）+ LeftTrigger2/RightTrigger2（数字扳机）；",
            "  - TextWithButtonValue 实时显示扳机按压值（0.000~1.000）；",
            "- **事件驱动更新**:",
            "  - GamepadButtonChangedEvent: MessageReader 读取按钮状态变化；",
            "  - GamepadAxisChangedEvent: MessageReader 读取轴值变化；",
            "  - GamepadConnectionEvent: 追踪手柄连接/断开；",
            "- **连接状态**:",
            "  - ConnectedGamepadsText UI 节点——显示所有已连接手柄的 Entity + Name；",
            "  - 🔧 ButtonMaterials/ButtonMeshes Resource 缓存——避免每帧重新创建材质/网格；",
        ],
        [
            "知：<br>- Gamepad 按钮/轴事件；<br>- Mesh2d/MeshMaterial2d 2D 渲染；<br>- MessageReader 事件读取。",
            "例：<br>- input/gamepad_input.rs(185)。",
        ],
    ),
    (
        368,
        "工具",
        [
            "**意图**：场景查看器动画控制插件——自动检测 glTF 动画并绑定 AnimationPlayer；⭐⭐",
            "- **动画自动分配**:",
            "  - assign_clips 系统：场景加载后遍历所有 AnimationClip；",
            "  - 通过 AnimationTargetId → Entity 映射找到每个 clip 的目标实体；",
            "  - 向上遍历 ChildOf 链找到最近的 AnimationPlayer 祖先——clip 归属判断；",
            "  - ⚠️ 一个 clip 的所有 target 必须属于同一 player——否则跳过；",
            "- **AnimationGraph 构建**:",
            "  - 为每个 player 构建独立 AnimationGraph——添加所有归属 clip；",
            "  - Clips 组件存储 AnimationNodeIndex 列表——支持动画切换；",
            "  - AnimationGraphHandle 插入到 player 实体——绑定图到播放器；",
            "- **键盘控制**:",
            "  - Space: 暂停/恢复（player.pause_all/resume_all）；",
            "  - Enter: Clips::advance_to_next() 循环切换下一个动画——stop_all → play(新 clip)；",
            "  - ⚠️ 切换时保持暂停状态——如果之前暂停，切换后仍暂停；",
            "- **注意事项**:",
            "  - 🔧 SceneHandle Resource 提供 gltf_handle 和 is_loaded 状态——触发一次初始化；",
            "  - 🔧 Display 实体名或 Entity ID——调试输出友好；",
        ],
        [
            "知：<br>- AnimationClip/AnimationGraph 动画图；<br>- AnimationPlayer 动画播放；<br>- SceneInstanceReady 触发时机。",
            "例：<br>- animation/animated_mesh.rs(102)。",
        ],
    ),
    (
        369,
        "工具",
        [
            "**意图**：场景查看器 Morph Target 控件——检测并交互控制 glTF 变形目标权重；⭐⭐",
            "- **Morph 检测**:",
            "  - detect_morphs 系统：遍历所有 MorphWeights 组件——收集实体/权重/名称信息；",
            "  - weights.first_mesh() → meshes.get() → morph_target_names() 读取变形目标名称；",
            "  - Target 结构体：entity_name + entity + name + index + weight + change_dir；",
            "- **键盘控制**:",
            "  - 56 个 MorphKey：字母(r/t/z/i/o/p/...) + Shift+组合——最多控制 56 个变形目标；",
            "  - WeightChange::change_weight：权重在 0.0~1.0 间自动反弹（increase↔decrease）；",
            "  - WEIGHT_PER_SECOND=0.8 控制变化速率——按住按键持续变形；",
            "- **UI 显示**:",
            "  - Text 节点实时显示所有变形目标的当前权重值；",
            "  - update_text 系统：读取实际 MorphWeights.weights() 同步显示值；",
            "  - ⚠️ weights_mut() 获取可变切片——直接修改底层权重数据；",
            "- **注意事项**:",
            "  - 🔧 MorphKey.active() 检查修饰键状态——ShiftLeft/ControlLeft/AltLeft 互斥组合；",
            "  - 🔧 EntityHashMap 加速目标查找——大量变形目标时性能关键；",
        ],
        [
            "知：<br>- MorphWeights 变形权重；<br>- weights_mut() 直接修改；<br>- AnimationTargetId 目标映射。",
            "例：<br>- animation/morph_targets.rs(105)。",
        ],
    ),
    (
        370,
        "工具",
        [
            "**意图**：场景查看器核心插件——glTF 场景加载/光源控制/相机追踪；⭐⭐⭐",
            "- **SceneHandle 资源**:",
            "  - gltf_handle + scene_index + instance_id + is_loaded + has_light；",
            "  - scene_load_check 系统：三阶段状态机（None → Some(!loaded) → Some(loaded)）；",
            "  - SceneSpawner::spawn 触发场景实例化——instance_is_ready 检测完成；",
            "- **光源控制**:",
            "  - L 键：animate_directional_light 开关——DirectionalLight 旋转动画；",
            "  - U 键：切换 shadows_enabled——实时开关阴影；",
            "  - EulerRot::ZYX 欧拉角旋转——稳定的光源方向控制；",
            "- **相机追踪**:",
            "  - CameraTracker Resource：active_index + cameras Vec——管理多个相机；",
            "  - track_camera: 新相机注册时自动设为活跃——场景相机优先于 FreeCamera；",
            "  - C 键：循环切换相机——当前相机 deactivate → 下一个 activate；",
            "  - ⚠️ ParamSet 三元组查询：scene cameras / free cameras / all cameras——避免查询冲突；",
            "- **包围盒调试**:",
            "  - B 键：toggle AabbGizmoConfigGroup.draw_all——显示/隐藏所有包围盒；",
            "- **注意事项**:",
            "  - 🔧 INSTRUCTIONS 文本区分 gltf_animation feature——有/无动画时显示不同控件说明；",
            "  - 🔧 SceneHandle::new(gltf_handle, scene_index)——支持 #SceneN 后缀选择子场景；",
        ],
        [
            "知：<br>- SceneSpawner 场景实例化；<br>- CameraTracker 相机管理；<br>- DirectionalLight 光源控制。",
            "例：<br>- gltf/load_gltf.rs(291)。",
        ],
    ),
    (
        371,
        "工具",
        [
            "**意图**：glTF 场景查看器主入口——命令行加载任意 glTF 模型并提供交互控制；⭐⭐⭐",
            "- **命令行参数**:",
            "  - positional: scene_path——默认 assets/models/FlightHelmet/FlightHelmet.gltf；",
            "  - --depth-prepass: DepthPrepass 深度预渲染——用于更高精度遮挡；",
            "  - --occlusion-culling: OcclusionCulling 遮挡剔除——⚠️ 需要 DepthPrepass；",
            "  - --deferred: DeferredPrepass + Msaa::Off 延迟渲染——测试延迟着色路径；",
            "  - --add-light: 强制添加默认方向光——即使场景已有光源；",
            "  - --convert-scene-coordinates / --convert-mesh-coordinates: GltfConvertCoordinates 坐标转换；",
            "- **场景加载流程**:",
            "  - parse_scene: 解析 #SceneN 后缀——提取路径和场景索引；",
            "  - AssetPlugin unapproved_path_mode: Allow——允许加载任意磁盘路径；",
            "  - GltfPlugin convert_coordinates: 全局坐标转换配置；",
            "- **相机自动定位**:",
            "  - 遍历所有 Mesh3d 的 GlobalTransform + Aabb——计算场景包围盒；",
            "  - Sphere → Aabb 转换确保旋转后仍获得保守包围盒；",
            "  - FreeCamera: walk_speed = size×3，far = size×10——自动适配场景尺度；",
            "  - EnvironmentMapLight 环境光（pisa_diffuse/specular）——默认 HDR 环境；",
            "- **渲染选项**:",
            "  - DefaultOpaqueRendererMethod::deferred() 全局延迟渲染；",
            "  - OcclusionCulling + DepthPrepass 组合——完整遮挡剔除管线；",
            "  - 🔧 FreeCameraPlugin 提供 WASD+鼠标自由相机——无需场景相机；",
            "  - 🔧 FileWatcher feature 热重载——修改 glTF 文件后自动刷新；",
        ],
        [
            "知：<br>- argh 命令行解析；<br>- FreeCamera 自由相机；<br>- GltfPlugin glTF 加载配置。",
            "例：<br>- tools/scene_viewer/scene_viewer_plugin.rs(370)。",
        ],
    ),
    # ── Helpers ───────────────────────────────────────────────────
    (
        372,
        "辅助工具",
        [
            "**意图**：示例 UI 用的单选按钮 Widget 插件库——提供可复用的 radio button 组件和交互处理；⭐⭐",
            "- **核心组件**:",
            "  - WidgetClickEvent&lt;T&gt;: Message 泛型事件——点击时发送值为 T 的事件；",
            "  - WidgetClickSender&lt;T&gt;: Component 标记——绑定按钮到事件类型 T；",
            "  - RadioButton: Component 标记——标识所有 radio button；",
            "  - RadioButtonText: Component 标记——标识按钮内的文本；",
            "- **按钮构建**:",
            "  - option_button&lt;T&gt;(value, name, is_selected, is_first, is_last)→Bundle：",
            "    - Button + Node（边框/内边距/对齐）+ BackgroundColor（选中白/未选黑）+ WidgetClickSender；",
            "    - ⚠️ is_first/is_last 控制圆角——首尾按钮有 BorderRadius，中间无圆角；",
            "  - option_buttons&lt;T&gt;(title, options)→Bundle：标题 + 按钮行——Flex 横向排列；",
            "- **交互处理**:",
            "  - handle_ui_interactions&lt;T&gt;: Query 过滤 Interaction::Pressed + RadioButton；",
            "  - MessageWriter&lt;WidgetClickEvent&lt;T&gt;&gt; 发送点击事件——消费者订阅处理；",
            "  - update_ui_radio_button: 更新 BackgroundColor 反映选中状态；",
            "  - update_ui_radio_button_text: 更新所有子文本颜色——选中黑/未选白；",
            "- **样式常量**:",
            "  - BUTTON_BORDER: UiRect::all(1px)——统一按钮边框；",
            "  - BUTTON_BORDER_COLOR: Color::WHITE 四边白色；",
            "  - BUTTON_PADDING: UiRect::axes(12px, 6px)——水平/垂直内边距；",
            "  - BUTTON_BORDER_RADIUS_SIZE: 6px——圆角半径；",
            "  - main_ui_node(): 左下角绝对定位 Column 布局——示例标准 UI 位置；",
        ],
        [
            "知：<br>- WidgetClickEvent Message 泛型事件；<br>- RadioButton 组件标记；<br>- option_buttons 构建函数。",
            "例：<br>- ui/button.rs(232)。",
        ],
    ),
    # ── Mobile ────────────────────────────────────────────────────
    (
        373,
        "移动端",
        [
            "**意图**：移动端（iOS/Android）Bevy 应用入口库——3D 场景 + 触摸相机 + 音频 + 生命周期管理；⭐⭐",
            "- **窗口配置**:",
            "  - WindowMode::BorderlessFullscreen(MonitorSelection::Primary)——全屏无边框；",
            "  - resizable: false 禁止调整大小——移动端固定全屏；",
            "  - recognize_rotation_gesture: true——iOS 旋转手势识别；",
            "  - prefers_home_indicator_hidden / prefers_status_bar_hidden——iOS 状态栏隐藏；",
            "  - preferred_screen_edges_deferring_system_gestures: ScreenEdge::Bottom——底部手势延迟；",
            "- **触摸相机控制**:",
            "  - TouchInput 事件：TouchPhase::Started 重置 last_position；",
            "  - 滑动位移 → 相机平移（除以窗口尺寸归一化 × 5.0）；",
            "  - RotationGesture：iOS 旋转手势 → rotate_axis(forward)——绕前方向旋转；",
            "  - 🔧 last_position: Local&lt;Option&lt;Vec2&gt;&gt;——追踪触摸起始位置；",
            "- **3D 场景**:",
            "  - Plane3d + Cuboid + Sphere 三个基础几何体；",
            "  - PointLight(1000000)——⚠️ Android 阴影可能导致 segfault（#8214）；",
            "  - Camera3d——⚠️ Android MSAA 可能 panic（#8229），条件编译 Msaa::Off；",
            "- **音频管理**:",
            "  - AudioPlayer + PlaybackSettings::LOOP——背景音乐循环；",
            "  - handle_lifetime: AppLifecycle 事件驱动——Suspended 暂停/Running 恢复；",
            "  - run_if(any_with_component&lt;AudioSink&gt;)——仅音频初始化后运行；",
            "- **WinitSettings**:",
            "  - WinitSettings::mobile()——移动端优化循环：无输入时降低更新频率省电；",
            "  - #[bevy_main] proc_macro——Android 必需的入口点样板代码；",
        ],
        [
            "知：<br>- TouchInput 触摸事件；<br>- AppLifecycle 生命周期；<br>- WinitSettings::mobile() 移动端优化。",
            "例：<br>- app/empty_defaults.rs(109)。",
        ],
    ),
    (
        374,
        "移动端",
        [
            "**意图**：移动端主入口——iOS 应用入口点，委托给 lib.rs 的 main 函数；⭐",
            "- **入口点**:",
            "  - use bevy_mobile_example::main;——引用 lib.rs 的 pub fn main()；",
            "  - iOS 应用需要独立的 main.rs 作为编译入口——iOS 链接器要求；",
            "- **架构设计**:",
            "  - lib.rs 包含实际逻辑（pub fn main）——iOS/Android 共享；",
            "  - main.rs 仅一行委托——iOS 特定入口；",
            "  - 🔧 Android 通过 #[bevy_main] proc_macro 自动生成入口——不需要 main.rs；",
            "  - 🔧 lib pub 可见性——允许 main.rs 访问 lib 中的 main 函数；",
        ],
        [
            "知：<br>- iOS 应用入口点要求；<br>- lib/pub 函数可见性。",
            "例：<br>- mobile/src/lib.rs(373)。",
        ],
    ),
    # ── no_std ────────────────────────────────────────────────────
    (
        375,
        "无标准库",
        [
            "**意图**：Bevy no_std 兼容库示例——展示如何编写可在标准库和 no_std 环境下运行的 Bevy 插件；⭐⭐",
            "- **no_std 基础配置**:",
            "  - #![no_std] 禁用标准库——自动切换到 core::prelude；",
            '  - #[cfg(feature = "std")] extern crate std;——条件引入标准库；',
            "  - extern crate alloc;——无条件引入 alloc（Vec/String/Box 等堆分配类型）；",
            "- **平台兼容层**:",
            "  - bevy::platform::collections::{HashMap, HashSet}——跨平台集合类型；",
            "  - bevy::platform::sync::{Arc, Mutex, RwLock, AtomicBool, ...}——跨平台同步原语；",
            "  - ⚠️ 部分平台不支持原子操作——portable-atomic 回退由 Bevy 自动处理；",
            "  - bevy::platform::time::Instant——跨平台时间点；",
            "- **DelayedComponentPlugin 实现**:",
            "  - insert_delayed&lt;B&gt;(bundle, delay)：延迟插入 Bundle——Timer 倒计时后触发；",
            "  - DelayedComponentTimer(Timer) + DelayedComponent&lt;B&gt;(B) 组件对；",
            "  - #[component(immutable)]——DelayedComponent 不可变——防止外部修改；",
            "- **EntityEvent 机制**:",
            "  - Unwrap EntityEvent 在 Timer 完成时触发——Observer 回调执行实际插入；",
            "  - unwrap&lt;B&gt; 函数：world.get_entity_mut → take::&lt;DelayedComponent&lt;B&gt;&gt; → insert；",
            "  - ⚠️ world.despawn(event.observer())——清理 Observer 实体避免泄漏；",
            "- **注意事项**:",
            "  - 🔧 core::time::Duration 替代 std::time::Duration——相同类型不同导入路径；",
            "  - 🔧 Reflect + #[reflect(Component)]——no_std 下仍支持反射；",
            "  - 🔬 no_std 限制：无 I/O/线程/文件系统——但 Bevy ECS 核心功能完整可用；",
        ],
        [
            "知：<br>- #![no_std] 禁用标准库；<br>- extern crate alloc 堆分配；<br>- bevy::platform 跨平台抽象。",
            "例：<br>- app/empty_defaults.rs(109)。",
        ],
    ),
]


def build_intent_text(intent_lines):
    """Join intent lines with <br> separator."""
    return "<br>".join(intent_lines)


def build_knowledge_text(knowledge_lines):
    """Join knowledge lines with <br> separator."""
    return "<br>".join(knowledge_lines)


def build_entry_line(entry):
    """Build a catalog table row from entry tuple."""
    if len(entry) == 5:
        seq, cat, intent_lines, knowledge_lines, example_lines = entry
    else:
        seq, cat, intent_lines, knowledge_lines = entry
        example_lines = []
    intent = build_intent_text(intent_lines)
    knowledge = build_knowledge_text(knowledge_lines + example_lines)
    filename_map = {
        346: "many_cubes.rs",
        347: "many_sprites.rs",
        348: "many_components.rs",
        349: "many_buttons.rs",
        350: "many_materials.rs",
        351: "many_lights.rs",
        352: "many_foxes.rs",
        353: "many_gizmos.rs",
        354: "many_glyphs.rs",
        355: "many_gradients.rs",
        356: "many_cameras_lights.rs",
        357: "many_animated_sprites.rs",
        358: "many_text2d.rs",
        359: "bevymark.rs",
        360: "text_pipeline.rs",
        361: "transform_hierarchy.rs",
        362: "2d.rs",
        363: "3d.rs",
        364: "ui.rs",
        365: "full_ui.rs",
        366: "helpers.rs",
        367: "gamepad_viewer.rs",
        368: "scene_viewer/animation_plugin.rs",
        369: "scene_viewer/morph_viewer_plugin.rs",
        370: "scene_viewer/scene_viewer_plugin.rs",
        371: "scene_viewer/main.rs",
        372: "widgets.rs",
        373: "src/lib.rs",
        374: "src/main.rs",
        375: "library/src/lib.rs",
    }
    fname = filename_map.get(seq, f"unknown_{seq}.rs")
    return f"| {seq} | {cat} | `{fname}` | {intent} | {knowledge} |"


def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []
    replaced = set()

    for line in lines:
        matched = False
        for entry in DATA:
            seq = entry[0]
            pattern = rf"^\| {seq} \|"
            if re.match(pattern, line.strip()):
                new_line = build_entry_line(entry) + "\n"
                new_lines.append(new_line)
                replaced.add(seq)
                matched = True
                break
        if not matched:
            new_lines.append(line)

    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        f.writelines(new_lines)

    print(f"Replaced {len(replaced)} entries:")
    for seq in sorted(replaced):
        print(f"  seq {seq:3d}")


if __name__ == "__main__":
    main()
