### Tutorial hints — en-US
### Prefix: tutorial

-tutorial-move = [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
-tutorial-select = [XXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
-tutorial-attack = [XXXXXXXXXXXXXXXXXXXXXXXXX]
-tutorial-use-skill = [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
-tutorial-end-turn = [XXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
-tutorial-defeat = [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
-tutorial-victory = [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
