#!/usr/bin/env python3
"""
批量重命名测试函数为中文
用法: python rename_tests.py
"""

import os
import re
from pathlib import Path

# 测试函数名映射表（英文 -> 中文）
# 保留AI、UI等专用术语
TEST_NAME_MAP = {
    # Stacking 模块
    "stacking_rule_max_stacks": "叠层规则_最大层数",
    "stacking_rule_allows_stacking": "叠层规则_允许叠加",
    "stacking_rule_is_replace": "叠层规则_是否替换",
    "stacking_rule_is_refresh": "叠层规则_是否刷新",
    "stacking_rule_def_conversion": "叠层规则定义_转换",
    "stacking_rule_def_zero_max_becomes_one": "叠层规则定义_零上限变为一",
    "resolve_no_existing_returns_newly_applied": "解析_无已有效果_返回新施加",
    "resolve_replace_returns_replaced": "解析_替换策略_返回已替换",
    "resolve_refresh_returns_refreshed": "解析_刷新策略_返回已刷新",
    "resolve_stack_add_increments": "解析_叠加策略_层数递增",
    "resolve_stack_max_below_limit": "解析_上限叠加_低于上限",
    "resolve_stack_max_at_limit_ignores": "解析_上限叠加_达到上限忽略",
    "resolve_stack_max_above_limit_ignores": "解析_上限叠加_超过上限忽略",
    "stacking_plugin_registers_types": "叠层插件_注册类型",
    "full_stack_scenario": "完整叠层场景",
    "replace_scenario": "替换场景",
    "refresh_scenario": "刷新场景",

    # Execution 模块
    "execution_registry_default_has_3_executors": "执行器注册表_默认有3个执行器",
    "execution_registry_unknown_returns_none": "执行器注册表_未知返回None",
    "execution_plugin_registers_resource": "执行器插件_注册资源",
    "damage_calculation_basic": "伤害计算_基础",
    "damage_calculation_with_multiplier": "伤害计算_带倍率",
    "damage_calculation_minimum_1": "伤害计算_最低为1",
    "heal_calculation_basic": "治疗计算_基础",
    "heal_calculation_with_bonus": "治疗计算_带加成",
    "shield_calculation_basic": "护盾计算_基础",
    "shield_calculation_with_bonus": "护盾计算_带加成",

    # Cue 模块
    "cue_damage_construction": "Cue伤害_构造",
    "cue_death_construction": "Cue死亡_构造",
    "cue_heal_construction": "Cue治疗_构造",
    "cue_emitter_emit_damage": "Cue发射器_发射伤害",
    "cue_emitter_has_pending": "Cue发射器_有待发送事件",
    "cue_emitter_clear": "Cue发射器_清空",
    "cue_plugin_registers_events": "Cue插件_注册事件",
    "full_cue_scenario": "完整Cue场景",

    # Effect 模块
    "伤害计算_基础": "伤害计算_基础",
    "伤害计算_森林地形": "伤害计算_森林地形",
    "伤害计算_最低为1": "伤害计算_最低为1",
    "伤害计算_技能倍率": "伤害计算_技能倍率",
    "伤害计算_无视防御": "伤害计算_无视防御",
    "伤害计算_100百分比无视防御": "伤害计算_100百分比无视防御",
    "伤害计算_山地地形无防御加成": "伤害计算_山地地形无防御加成",
    "伤害计算_水域地形无防御加成": "伤害计算_水域地形无防御加成",
    "伤害计算_高倍率技能": "伤害计算_高倍率技能",
    "效果队列_push和drain": "效果队列_push和drain",
    "效果队列_clear": "效果队列_clear",
    "effect_def_type_name": "效果定义_类型名",
    "pending_effect_data_type_name": "待处理效果数据_类型名",

    # Tag 模块
    "标签_位掩码查询": "标签_位掩码查询",
    "标签_多标签组合": "标签_多标签组合",
    "标签_has_any": "标签_has_any",
    "标签_has_all": "标签_has_all",
    "tag_name_转换": "tag_name_转换",
    "标签_from_tags空数组": "标签_from_tags空数组",
    "标签_from_tags多个标签": "标签_from_tags多个标签",
    "标签_has_any都不匹配": "标签_has_any都不匹配",
    "标签_has_all空集": "标签_has_all空集",
    "标签_add重复幂等": "标签_add重复幂等",
    "ron_反序列化_标签定义": "ron_反序列化_标签定义",
    "tag_registry_查询": "标签注册表_查询",
    "tag_registry_按分类查询": "标签注册表_按分类查询",
    "tag_registry_显示名称回退": "标签注册表_显示名称回退",
    "tag_registry_from_enum_defaults_覆盖所有标签": "标签注册表_from_enum_defaults_覆盖所有标签",
    "tag_registry_new_categories": "标签注册表_新分类",
    "ron_coverage_all_tags": "ron_覆盖所有标签",
    "tag_category_coverage_all_tags": "标签分类_覆盖所有标签",
    "tag_category_default_for": "标签分类_默认值",

    # Modifier 模块
    "ron_反序列化_修饰规则": "ron_反序列化_修饰规则",
    "修饰规则_兜底默认值": "修饰规则_兜底默认值",
    "修饰规则_固定加成": "修饰规则_固定加成",
    "修饰规则_多规则叠加": "修饰规则_多规则叠加",
    "修饰规则_无匹配规则不变": "修饰规则_无匹配规则不变",
    "修饰规则_最低治疗为0": "修饰规则_最低治疗为0",
    "修饰规则_最低伤害为1": "修饰规则_最低伤害为1",
    "修饰规则_治疗倍率": "修饰规则_治疗倍率",
    "修饰规则_治疗固定加成": "修饰规则_治疗固定加成",
    "修饰规则_治疗无匹配不变": "修饰规则_治疗无匹配不变",
    "修饰规则_火焰增伤": "修饰规则_火焰增伤",

    # Attribute 模块
    "核心属性_基础值": "核心属性_基础值",
    "加法修饰符_核心属性": "加法修饰符_核心属性",
    "加法修饰符_衍生属性": "加法修饰符_衍生属性",
    "乘法修饰符_衍生属性": "乘法修饰符_衍生属性",
    "不能设置衍生属性基础值": "不能设置衍生属性基础值",
    "生命资源_初始化为最大值": "生命资源_初始化为最大值",
    "生命资源_战斗中变化": "生命资源_战斗中变化",
    "set_vital_不影响最大值": "set_vital_不影响最大值",
    "set_vital_设置hp当前值": "set_vital_设置hp当前值",
    "set_vital_设置mp当前值": "set_vital_设置mp当前值",
    "set_vital_设置stamina当前值": "set_vital_设置stamina当前值",
    "set_vital_非生命资源不生效": "set_vital_非生命资源不生效",
    "移除减益修饰符": "移除减益修饰符",
    "移除指定源修饰符": "移除指定源修饰符",
    "add_modifiers_from_def_批量添加": "add_modifiers_from_def_批量添加",
    "哥布林模板": "哥布林模板",
    "法师模板": "法师模板",
    "衍生属性_弓手模板": "衍生属性_弓手模板",
    "衍生属性_战士模板": "衍生属性_战士模板",
    "属性中文名_核心属性": "属性中文名_核心属性",
    "属性中文名_衍生属性": "属性中文名_衍生属性",
    "属性中文名_资源属性": "属性中文名_资源属性",
    "属性分类_三类互斥": "属性分类_三类互斥",
    "属性分类_核心属性返回true": "属性分类_核心属性返回true",
    "属性分类_衍生属性返回false": "属性分类_衍生属性返回false",
    "属性分类_衍生属性返回true": "属性分类_衍生属性返回true",
    "属性分类_资源属性返回false": "属性分类_资源属性返回false",
    "属性分类_资源属性返回true": "属性分类_资源属性返回true",
    "属性分类_非资源属性返回false": "属性分类_非资源属性返回false",
    "属性分类_非衍生属性返回false": "属性分类_非衍生属性返回false",
    "属性缩写_核心属性返回三字母缩写": "属性缩写_核心属性返回三字母缩写",
    "属性缩写_非核心属性回退到label": "属性缩写_非核心属性回退到label",
    "attribute_registry_defaults_总数为24": "属性注册表_默认总数为24",
    "attribute_registry_显示名称_已注册": "属性注册表_显示名称_已注册",
    "attribute_registry_显示名称回退": "属性注册表_显示名称回退",
    "attribute_registry_查询": "属性注册表_查询",
    "attribute_registry_查询所有默认属性": "属性注册表_查询所有默认属性",
    "attribute_registry_defaults_包含所有属性": "属性注册表_默认包含所有属性",
    "ron_反序列化_属性定义": "ron_反序列化_属性定义",

    # Buff 模块
    "apply_buff_添加修饰符和标签": "施加buff_添加修饰符和标签",
    "remove_buff_清理修饰符和标签": "移除buff_清理修饰符和标签",
    "remove_buff_共享标签不被误删": "移除buff_共享标签不被误删",
    "apply_buff_cleanse_驱散所有debuff": "施加buff_驱散所有debuff",
    "remove_all_debuffs_只移除debuff保留buff": "移除所有debuff_只移除debuff保留buff",
    "apply_buff_同源刷新不重复添加修饰符": "施加buff_同源刷新不重复添加修饰符",
    "apply_buff_不同源同id可共存": "施加buff_不同源同id可共存",
    "stack_nostack_不同源同id刷新不新增": "叠层_nostack_不同源同id刷新不新增",
    "stack_nostack_不同源同id也刷新": "叠层_nostack_不同源同id也刷新",
    "stack_stackable_在上限内可叠多层": "叠层_stackable_在上限内可叠多层",
    "stack_stackable_达到上限移除最旧": "叠层_stackable_达到上限移除最旧",
    "stack_stackable_no_refresh_达到上限跳过": "叠层_stackable_no_refresh_达到上限跳过",
    "buff_def_转换为_buff_data": "buff定义_转换为buff数据",
    "buff_registry_查询已注册buff": "buff注册表_查询已注册buff",
    "buff_registry_查询未注册返回none": "buff注册表_查询未注册返回none",
    "buff_registry_默认buff包含新字段": "buff注册表_默认buff包含新字段",
    "buff_registry_默认注册": "buff注册表_默认注册",
    "is_debuff_减益返回true": "is_debuff_减益返回true",
    "is_debuff_增益返回false": "is_debuff_增益返回false",
    "ron_反序列化_带duration和stack字段": "ron_反序列化_带duration和stack字段",
    "ron_反序列化_旧配置无version字段": "ron_反序列化_旧配置无version字段",
    "活跃buff_dot_hot汇总": "活跃buff_dot_hot汇总",
    "活跃buff_tick_递减后过期": "活跃buff_tick_递减后过期",
    "活跃buff_tick_递减持续时间": "活跃buff_tick_递减持续时间",
    "活跃buff_tick_非turns策略不递减": "活跃buff_tick_非turns策略不递减",
    "活跃buff_不同源同id不刷新": "活跃buff_不同源同id不刷新",
    "活跃buff_同源同id刷新持续时间": "活跃buff_同源同id刷新持续时间",
    "活跃buff_晕眩检查": "活跃buff_晕眩检查",
    "活跃buff_消耗晕眩": "活跃buff_消耗晕眩",
    "活跃buff_移除不存在的返回none": "活跃buff_移除不存在的返回none",
    "活跃buff_添加和查询": "活跃buff_添加和查询",
    "活跃buff_移除": "活跃buff_移除",
    "活跃buff_移除所有debuff": "活跃buff_移除所有debuff",
    "rebuild_tags_从活跃buff重建标签": "rebuild_tags_从活跃buff重建标签",
    "rebuild_tags_多buff多标签合并": "rebuild_tags_多buff多标签合并",
    "rebuild_tags_空buff空trait": "rebuild_tags_空buff空trait",
    "rebuild_tags_保留trait授予的标签": "rebuild_tags_保留trait授予的标签",
    "rebuild_tags_清除非trait非buff标签": "rebuild_tags_清除非trait非buff标签",
    "tick_buffs_空buff列表": "tick_buffs_空buff列表",
    "tick_buffs_未过期buff持续时间递减": "tick_buffs_未过期buff持续时间递减",
    "tick_buffs_清理过期buff的修饰符": "tick_buffs_清理过期buff的修饰符",
    "tick_buffs_过期buff标签被清除": "tick_buffs_过期buff标签被清除",
    "tick_buffs_过期buff清理修饰符": "tick_buffs_过期buff清理修饰符",
    "tick_buffs_保留多个buff中未过期的": "tick_buffs_保留多个buff中未过期的",
    "tick_buffs_permanent_buff不递减": "tick_buffs_permanent_buff不递减",
    "dispatch_empty_registry": "分发_空注册表",
    "dispatch_wrong_trigger_type": "分发_错误触发器类型",
    "handlers_sorted_by_priority_descending": "处理器_按优先级降序排序",
    "register_and_dispatch_single_handler": "注册并分发单个处理器",
    "registry_default_is_empty": "注册表_默认为空",

    # Battle 模块
    "曼哈顿距离_同一位置": "曼哈顿距离_同一位置",
    "曼哈顿距离_对角线": "曼哈顿距离_对角线",
    "曼哈顿距离_相邻格子": "曼哈顿距离_相邻格子",
    "曼哈顿距离_负坐标": "曼哈顿距离_负坐标",
    "battle_error_相等性": "战斗错误_相等性",
    "empty_effect_queue_包含上下文": "空效果队列_包含上下文",
    "battle_result_类型可用": "战斗结果_类型可用",
    "skill_not_found_包含错误码和技能id": "技能未找到_包含错误码和技能id",
    "invalid_combat_intent_包含双方单位": "无效战斗意图_包含双方单位",
    "target_not_found_包含unit_id": "目标未找到_包含unit_id",
    "character_died_消息字段": "角色死亡_消息字段",
    "damage_applied_消息字段": "伤害应用_消息字段",
    "dot_applied_消息字段": "dot应用_消息字段",
    "heal_applied_消息字段": "治疗应用_消息字段",
    "hot_applied_消息字段": "hot应用_消息字段",
    "stun_applied_消息字段": "晕眩应用_消息字段",
    "战斗日志_刚好等于最大条数不截断": "战斗日志_刚好等于最大条数不截断",
    "战斗日志_多条日志": "战斗日志_多条日志",
    "战斗日志_多片段拼接": "战斗日志_多片段拼接",
    "战斗日志_添加一条": "战斗日志_添加一条",
    "战斗日志_超过最大条数截断最旧": "战斗日志_超过最大条数截断最旧",
    "apply_buff_effect_未知buff静默跳过": "施加buff效果_未知buff静默跳过",
    "apply_buff_effect_正常施加": "施加buff效果_正常施加",
    "on_attack_触发apply_buff": "on_attack_触发apply_buff",
    "on_hit_触发apply_buff": "on_hit_触发apply_buff",
    "passive_trait_不触发": "passive_trait_不触发",
    "多个on_attack_trait_全部触发": "多个on_attack_trait_全部触发",
    "伤害分解_多修饰符叠加": "伤害分解_多修饰符叠加",
    "伤害分解_基础构建": "伤害分解_基础构建",
    "伤害分解_实际伤害低于修饰值": "伤害分解_实际伤害低于修饰值",
    "伤害分解_无修饰符": "伤害分解_无修饰符",
    "战斗记录_伤害分解": "战斗记录_伤害分解",
    "战斗记录_回合开始更新回合数": "战斗记录_回合开始更新回合数",
    "战斗记录_实体统计": "战斗记录_实体统计",
    "伤害分解_序列化反序列化": "伤害分解_序列化反序列化",
    "战斗记录_按回合查询": "战斗记录_按回合查询",
    "战斗记录_清空": "战斗记录_清空",
    "战斗记录_最近N条记录": "战斗记录_最近N条记录",
    "战斗记录_序列化反序列化": "战斗记录_序列化反序列化",
    "战斗记录_按实体查询": "战斗记录_按实体查询",
    "战斗记录_记录伤害": "战斗记录_记录伤害",
    "on_character_died_队列中无死亡单位则不触发": "on_character_died_队列中无死亡单位则不触发",
    "on_character_died_多次死亡消息按序移除": "on_character_died_多次死亡消息按序移除",
    "on_character_died_从行动队列移除": "on_character_died_从行动队列移除",
    "apply_heal_effect_回血": "施加治疗效果_回血",
    "apply_heal_effect_不超过maxhp": "施加治疗效果_不超过maxhp",
    "apply_damage_effect_扣血": "施加伤害效果_扣血",
    "apply_damage_effect_致死添加dead标记": "施加伤害效果_致死添加dead标记",

    # Character 模块
    "unit_id_basic_property": "unit_id_基本属性",
    "unit_id_equality_and_hash": "unit_id_相等性和哈希",
    "unit_id_mount_and_read": "unit_id_挂载和读取",
    "unit_auto_inserts_required_components": "unit_自动插入必需组件",
    "dead_hook_no_selected_does_not_panic": "dead_hook_无选中不panic",
    "dead_hook_marks_unit_as_acted": "dead_hook_标记单位已行动",
    "dead_hook_removes_selected": "dead_hook_移除选中",
    "moving_unit_is_finished_completed": "移动单位_已完成",
    "moving_unit_is_finished_not_yet": "移动单位_未完成",
    "moving_unit_is_finished_just_arrived": "移动单位_刚到达",
    "moving_unit_is_finished_empty_path": "移动单位_空路径",
    "moving_unit_target_coord_index_out_of_bounds": "移动单位_目标坐标索引越界",
    "moving_unit_target_coord_empty_path": "移动单位_目标坐标空路径",
    "moving_unit_target_coord_within_path": "移动单位_目标坐标在路径内",
    "faction_def_enemy_converts": "阵营定义_敌方转换",
    "faction_def_player_converts": "阵营定义_玩家转换",
    "unit_template_def_converts_to_unit_template": "单位模板定义_转换为单位模板",
    "unit_template_registry_default_templates": "单位模板注册表_默认模板",
    "ron_deserialize_unit_template": "ron_反序列化_单位模板",
    "unit_template_registry_query": "单位模板注册表_查询",
    "unit_template_registry_query_unregistered_returns_none": "单位模板注册表_查询未注册返回none",
    "ron_deserialize_old_config_without_version": "ron_反序列化_旧配置无version字段",
    "trait_collection_query": "trait集合_查询",
    "trait_def_转换为_trait_data": "trait定义_转换为trait数据",
    "ron_deserialize_trait_definition": "ron_反序列化_trait定义",
    "ron_deserialize_trait_with_trigger": "ron_反序列化_trait带触发器",
    "apply_passive_traits_grants_tags_and_modifiers": "施加passive_traits_授予标签和修饰符",
    "apply_passive_traits_independent_source_id": "施加passive_traits_独立source_id",
    "apply_passive_traits_skips_non_passive_trigger": "施加passive_traits_跳过非passive触发器",
    "apply_buff_handler_no_modifiers": "施加buff处理器_无修饰符",
    "apply_buff_handler_no_tags": "施加buff处理器_无标签",
    "apply_buff_handler_type_name": "施加buff处理器_类型名",
    "grant_tag_handler_grants_tags": "授予标签处理器_授予标签",
    "grant_tag_handler_no_attribute_modifiers": "授予标签处理器_无属性修饰符",
    "grant_tag_handler_returns_empty_for_non_grant_tag": "授予标签处理器_非授予标签返回空",
    "grant_tag_handler_type_name": "授予标签处理器_类型名",
    "modify_attribute_handler_no_tags": "修改属性处理器_无标签",
    "modify_attribute_handler_returns_empty_for_non_modify": "修改属性处理器_非修改返回空",
    "modify_attribute_handler_returns_modifiers": "修改属性处理器_返回修饰符",
    "modify_attribute_handler_type_name": "修改属性处理器_类型名",
    "registry_default_equals_with_defaults": "注册表_默认等于带默认值",
    "registry_default_contains_three_handlers": "注册表_默认包含三个处理器",
    "registry_query_nonexistent_returns_none": "注册表_查询不存在返回none",
    "registry_register_custom_handler": "注册表_注册自定义处理器",

    # Equipment 模块
    "ron_反序列化_带需求的装备": "ron_反序列化_带需求的装备",
    "装备槽位_label": "装备槽位_label",
    "稀有度_label": "稀有度_label",
    "装备注册表_幂等": "装备注册表_幂等",
    "装备注册表_查询": "装备注册表_查询",
    "装备注册表_默认装备": "装备注册表_默认装备",
    "穿戴装备_属性修饰符生效": "穿戴装备_属性修饰符生效",
    "穿戴装备_trait添加到集合": "穿戴装备_trait添加到集合",
    "脱卸装备_属性恢复": "脱卸装备_属性恢复",
    "穿戴装备_标签添加到persistent": "穿戴装备_标签添加到persistent",
    "多个需求_部分不满足": "多个需求_部分不满足",
    "属性需求_不满足": "属性需求_不满足",
    "无需求_总是满足": "无需求_总是满足",
    "属性需求_满足": "属性需求_满足",
    "标签需求_满足": "标签需求_满足",
    "标签需求_不满足": "标签需求_不满足",
    "装备槽_卸下空槽位": "装备槽_卸下空槽位",
    "装备槽_多槽位": "装备槽_多槽位",
    "装备槽_实例id自增": "装备槽_实例id自增",
    "装备槽_替换旧装备": "装备槽_替换旧装备",
    "装备槽_装备和卸下": "装备槽_装备和卸下",
    "背包_容量限制": "背包_容量限制",
    "背包_添加和移除": "背包_添加和移除",
    "背包_查找": "背包_查找",
    "背包_移除不存在的返回none": "背包_移除不存在的返回none",
    "战场背包_创建": "战场背包_创建",
    "战场背包_容量限制": "战场背包_容量限制",
    "战场背包_创建时复制物品": "战场背包_创建时复制物品",

    # Inventory 模块
    "容器_不可合并装备": "容器_不可合并装备",
    "容器_容量上限": "容器_容量上限",
    "容器_减少堆叠": "容器_减少堆叠",
    "容器_创建背包": "容器_创建背包",
    "容器_查找物品": "容器_查找物品",
    "容器_按类型筛选": "容器_按类型筛选",
    "容器_减少堆叠至零自动移除": "容器_减少堆叠至零自动移除",
    "容器_添加物品": "容器_添加物品",
    "容器_移除物品": "容器_移除物品",
    "容器_添加物品_堆叠超重也拒绝": "容器_添加物品_堆叠超重也拒绝",
    "容器_添加物品_超重拒绝": "容器_添加物品_超重拒绝",
    "容器_自动合并": "容器_自动合并",
    "容器_超重检查": "容器_超重检查",
    "容器_添加物品_部分成功返回已添加数量": "容器_添加物品_部分成功返回已添加数量",
    "堆叠_不可合并_绑定物品": "堆叠_不可合并_绑定物品",
    "堆叠_不可合并_超出堆叠上限": "堆叠_不可合并_超出堆叠上限",
    "堆叠_不可合并_不同定义": "堆叠_不可合并_不同定义",
    "堆叠_可合并": "堆叠_可合并",
    "堆叠_从定义创建": "堆叠_从定义创建",
    "堆叠_总重量": "堆叠_总重量",
    "堆叠_拆分": "堆叠_拆分",
    "堆叠_拆分_数量不足返回none": "堆叠_拆分_数量不足返回none",
    "实例_从消耗品定义创建": "实例_从消耗品定义创建",
    "实例_从装备定义创建": "实例_从装备定义创建",
    "实例id计数器": "实例id计数器",
    "资源_查询不存在的资源": "资源_查询不存在的资源",
    "资源_消费不足": "资源_消费不足",
    "资源_多种资源": "资源_多种资源",
    "资源_消费成功": "资源_消费成功",
    "资源_添加": "资源_添加",
    "资源_累加": "资源_累加",
    "转移_全部转移": "转移_全部转移",
    "转移_成功": "转移_成功",
    "转移_源容器不存在": "转移_源容器不存在",
    "转移_目标容器满": "转移_目标容器满",
    "consumable_apply_buff_effect": "消耗品_施加buff效果",
    "consumable_apply_restore_effect": "消耗品_施加恢复效果",
    "consumable_cast_skill_returns_pending_effect": "消耗品_施放技能返回待处理效果",
    "consumable_grant_temp_trait_returns_pending_effect": "消耗品_授予临时trait返回待处理效果",
    "consumable_non_consumable_skipped": "消耗品_非消耗品跳过",
    "物品类型_label": "物品类型_label",
    "物品注册表_查询": "物品注册表_查询",
    "物品注册表_按类型筛选": "物品注册表_按类型筛选",
    "bag_full_包含错误码": "bag_full_包含错误码",
    "inventory_result_类型可用": "inventory_result_类型可用",
    "item_not_found_包含item_id": "item_not_found_包含item_id",
    "ron_反序列化_弹药": "ron_反序列化_弹药",
    "ron_反序列化_消耗品": "ron_反序列化_消耗品",
    "ron_反序列化_装备物品": "ron_反序列化_装备物品",
    "ron_反序列化_兼容旧装备格式": "ron_反序列化_兼容旧装备格式",

    # Map 模块
    "level_config_def_转换为level_config": "level_config_def_转换为level_config",
    "level_config_地形网格解析": "level_config_地形网格解析",
    "level_config_自定义char_map覆盖默认": "level_config_自定义char_map覆盖默认",
    "level_registry_first": "level_registry_first",
    "level_registry_first_空返回none": "level_registry_first_空返回none",
    "level_registry_查询关卡": "level_registry_查询关卡",
    "level_registry_查询未注册返回none": "level_registry_查询未注册返回none",
    "ron_反序列化_不可通行地形": "ron_反序列化_不可通行地形",
    "terrain_def_ron_可通行地形move_cost": "terrain_def_ron_可通行地形move_cost",
    "ron_反序列化_关卡配置": "ron_反序列化_关卡配置",
    "terrain_registry_兜底默认值": "terrain_registry_兜底默认值",
    "terrain_registry_char_map": "terrain_registry_char_map",
    "ron_反序列化_地形定义": "ron_反序列化_地形定义",
    "坐标转世界_地图中心": "坐标转世界_地图中心",
    "世界转坐标_往返一致": "世界转坐标_往返一致",
    "game_map_从关卡配置创建": "game_map_从关卡配置创建",
    "坐标转世界_左下角原点": "坐标转世界_左下角原点",
    "边界_内部坐标合法": "边界_内部坐标合法",
    "边界_超出宽高非法": "边界_超出宽高非法",
    "边界_负坐标非法": "边界_负坐标非法",
    "ground_unit_cannot_traverse_mountain_or_water": "地面单位_不能穿越山地或水域",
    "flying_unit_traverses_mountain_water_cost_1": "飞行单位_穿越山地水域消耗1",
    "ground_unit_mp_0_no_reachable_tiles": "地面单位_mp_0_无可到达格子",
    "ground_unit_forest_costs_2_mp": "地面单位_森林消耗2mp",
    "ground_unit_mp_1_adjacent_4_tiles_only": "地面单位_mp_1_仅相邻4格",
    "ground_unit_occupied_tile_unreachable": "地面单位_被占格子不可达",
    "ground_unit_corner_position_mp_limited": "地面单位_角落位置mp受限",
    "mounted_unit_cannot_traverse_mountain_or_water": "骑兵单位_不能穿越山地或水域",
    "ground_unit_self_position_not_counted_as_occupied": "地面单位_自身位置不计为被占",
    "ground_unit_reachability_with_mp_3_on_plains": "地面单位_mp_3平原可达性",
    "reconstruct_path_l_shape": "重建路径_L形",
    "reconstruct_path_same_start_end_returns_self": "重建路径_起点终点相同返回自身",
    "swimming_priority_over_flying": "游泳优先于飞行",
    "mounted_unit_plains_cost_1_forest_cost_3": "骑兵单位_平原消耗1森林消耗3",
    "terrain_cost_registry_resolves_from_tags": "地形消耗注册表_从标签解析",
    "swimming_unit_cannot_traverse_mountain": "游泳单位_不能穿越山地",
    "swimming_unit_water_cost_1": "游泳单位_水域消耗1",
    "terrain_cost_registry_contains_four_calculators_by_default": "地形消耗注册表_默认包含四个计算器",
    "排除自身检查占用": "排除自身检查占用",
    "设置和查询占用": "设置和查询占用",
    "重建占用网格": "重建占用网格",
    "移除占用": "移除占用",
    "设置地形": "设置地形",
    "从地形map构建": "从地形map构建",
    "边界检查": "边界检查",
    "迭代所有格子": "迭代所有格子",

    # Turn 模块
    "force_end_turn_消息可创建": "force_end_turn_消息可创建",
    "turn_ended_消息字段": "turn_ended_消息字段",
    "turn_started_消息字段": "turn_started_消息字段",
    "行动队列_按initiative降序排列": "行动队列_按initiative降序排列",
    "行动队列_相同initiative稳定排序": "行动队列_相同initiative稳定排序",
    "行动队列_空队列": "行动队列_空队列",
    "行动队列_current_unit和advance": "行动队列_current_unit和advance",
    "回合结束_重建队列并增加回合数": "回合结束_重建队列并增加回合数",
    "回合结束_needs_resolve标记设置": "回合结束_needs_resolve标记设置",
    "回合结束_进入后总是切换到_select_unit": "回合结束_进入后总是切换到_select_unit",
    "回合结束_重置单位行动状态": "回合结束_重置单位行动状态",
    "force_end_turn_消费消息不报错": "force_end_turn_消费消息不报错",
    "game_over_state_default_is_playing": "game_over_state_默认是playing",
    "game_over_state_variants_are_distinct": "game_over_state_变体是不同的",
    "check_survive_turns_达到目标": "check_survive_turns_达到目标",
    "check_turn_limit_exceeded_超过上限": "check_turn_limit_exceeded_超过上限",
    "check_survive_turns_未达目标": "check_survive_turns_未达目标",
    "check_turn_limit_exceeded_未超过上限": "check_turn_limit_exceeded_未超过上限",
    "ecs_仍有存活敌人继续战斗": "ecs_仍有存活敌人继续战斗",
    "ecs_DefeatBoss_Boss已死亡判定胜利": "ecs_DefeatBoss_Boss已死亡判定胜利",
    "ecs_SurviveTurns_达到目标回合判定胜利": "ecs_SurviveTurns_达到目标回合判定胜利",
    "ecs_兜底_全灭玩家即失败": "ecs_兜底_全灭玩家即失败",
    "ecs_全灭敌人判定胜利": "ecs_全灭敌人判定胜利",
    "game_over_state_终态不可逆": "game_over_state_终态不可逆",
    "ecs_TurnLimitExceeded_超时判定失败": "ecs_TurnLimitExceeded_超时判定失败",
    "ecs_兜底_终态后不重复触发": "ecs_兜底_终态后不重复触发",
    "ecs_DefeatBoss_Boss存活继续战斗": "ecs_DefeatBoss_Boss存活继续战斗",
    "ecs_多胜利条件OR_任一满足即胜利": "ecs_多胜利条件OR_任一满足即胜利",
    "ecs_兜底_有存活玩家不触发": "ecs_兜底_有存活玩家不触发",
    "ecs_失败优先_超时且全灭敌人判定失败": "ecs_失败优先_超时且全灭敌人判定失败",
    "ecs_全灭玩家判定失败": "ecs_全灭玩家判定失败",
    "边界值_存活与超时的不对称判断": "边界值_存活与超时的不对称判断",
    "ecs_无配置时全灭即失败": "ecs_无配置时全灭即失败",
    "ecs_胜利时发送LevelCompleted消息": "ecs_胜利时发送LevelCompleted消息",
    "ecs_默认全灭条件不可移除": "ecs_默认全灭条件不可移除",
    "ecs_终态不可逆_Defeat后保持": "ecs_终态不可逆_Defeat后保持",
    "ecs_空注册表不崩溃": "ecs_空注册表不崩溃",
    "ecs_终态不可逆_Victory后保持": "ecs_终态不可逆_Victory后保持",
    "victory_condition_default_is_empty": "victory_condition_默认为空",
    "ron_胜负条件配置反序列化": "ron_胜负条件配置反序列化",
    "win_condition_kill_all_type": "win_condition_kill_all_类型",
    "win_condition_survive_turns_params": "win_condition_survive_turns_参数",
    "lose_condition_turn_limit_params": "lose_condition_turn_limit_参数",
    "current_stage_needs_manual_update_after_victory": "当前关卡_胜利后需手动更新",
    "defeat_keeps_current_stage_unlocked": "失败_保持当前关卡解锁",
    "defeat_preserves_current_stage_pointer": "失败_保留当前关卡指针",
    "double_victory_same_stage_does_not_double_unlock": "同一关卡双胜利_不双重解锁",
    "sequential_victories_unlock_all_stages": "连续胜利_解锁所有关卡",
    "playing_state_is_ignored": "playing状态_被忽略",
    "victory_after_defeat_unlocks_next": "失败后胜利_解锁下一关",
    "victory_completes_current_stage_unlocks_next": "胜利_完成当前关卡解锁下一关",
    "victory_on_last_stage_does_not_panic": "最后一关胜利_不panic",
    "victory_with_no_current_stage_does_nothing": "无当前关卡时胜利_无操作",
    "complete_current_stage_no_current_does_nothing": "完成当前关卡_无当前关卡无操作",
    "complete_current_stage_preserves_other_stages": "完成当前关卡_保留其他关卡",
    "complete_current_stage_unlocks_next": "完成当前关卡_解锁下一关",
    "complete_last_stage_does_not_panic": "完成最后一关_不panic",
    "complete_multiple_stages_sequentially": "连续完成多个关卡",
    "initialize_first_stage_unlocked_rest_locked": "初始化_第一关解锁其余锁定",
    "initialize_single_stage": "初始化_单关卡",
    "initialize_empty_registry_returns_default": "初始化_空注册表返回默认",
    "stage_status_clone": "stage_status_clone",
    "stage_status_equality": "stage_status_相等性",
    "stage_status_nonexistent_returns_none": "stage_status_不存在返回none",
    "stage_status_labels": "stage_status_标签",
    "get_nonexistent_campaign_returns_none": "get_nonexistent_campaign_returns_none",
    "first_returns_none_when_empty": "first_空时返回none",
    "stage_def_clone": "stage_def_clone",
    "get_campaign_has_correct_stages": "get_campaign_有正确关卡",
    "get_existing_campaign": "get_existing_campaign",
    "campaign_def_clone": "campaign_def_clone",
    "first_returns_some_when_not_empty": "first_非空时返回some",
    "first_returns_only_campaign": "first_只返回一个战役",

    # Campaign 模块
    "save_full_snapshot_空world_返回some": "save_full_snapshot_空world_返回some",
    "save_snapshot_空列表_返回some": "save_snapshot_空列表_返回some",
    "save_snapshot_指定entity_返回some": "save_snapshot_指定entity_返回some",
    "save_full_snapshot_多个entity_返回some": "save_full_snapshot_多个entity_返回some",

    # AI 模块
    "ai_behavior_registry_默认行为": "AI行为注册表_默认行为",
    "ai_behavior_def_转换为_ai_behavior": "AI行为定义_转换为AI行为",
    "ron_反序列化_ai行为": "ron_反序列化_AI行为",
    "ron_反序列化_带技能优先级": "ron_反序列化_带技能优先级",
    "移动策略_激进_贪心靠近目标": "移动策略_激进_贪心靠近目标",
    "移动策略_空可移动范围返回自身": "移动策略_空可移动范围返回自身",
    "移动策略_谨慎_无范围内位置时靠近": "移动策略_谨慎_无范围内位置时靠近",
    "移动策略_谨慎_保持攻击距离": "移动策略_谨慎_保持攻击距离",
    "移动策略_通过注册表分发": "移动策略_通过注册表分发",
    "技能策略_优先基础": "技能策略_优先基础",
    "技能策略_优先特殊_全冷却回退基础攻击": "技能策略_优先特殊_全冷却回退基础攻击",
    "技能策略_按优先级": "技能策略_按优先级",
    "技能策略_优先特殊_跳过冷却": "技能策略_优先特殊_跳过冷却",
    "技能策略_按优先级_首选冷却时选次选": "技能策略_按优先级_首选冷却时选次选",
    "技能策略_通过注册表分发": "技能策略_通过注册表分发",
    "技能策略_按优先级_空回退特殊": "技能策略_按优先级_空回退特殊",
    "策略注册表_未知名称回退默认": "策略注册表_未知名称回退默认",
    "策略注册表_默认注册所有策略": "策略注册表_默认注册所有策略",
    "策略注册表_按名称查询": "策略注册表_按名称查询",
    "目标策略_无玩家时返回自身位置": "目标策略_无玩家时返回自身位置",
    "目标策略_最低血量百分比": "目标策略_最低血量百分比",
    "目标策略_最危险": "目标策略_最危险",
    "目标策略_最近": "目标策略_最近",
    "目标策略_最远": "目标策略_最远",
    "目标策略_通过注册表分发": "目标策略_通过注册表分发",

    # Trigger 模块
    "trigger枚举所有变体": "trigger枚举所有变体",
    "注册表_handler按priority排序": "注册表_handler按priority排序",
    "注册表_分发返回effects": "注册表_分发返回effects",
    "注册表_多个handler聚合effects": "注册表_多个handler聚合effects",
    "注册表_无handler返回空": "注册表_无handler返回空",
    "注册表_注册后存在": "注册表_注册后存在",
    "注册表_默认为空": "注册表_默认为空",
    "cancel_top_取消栈顶可取消_保留下层不可取消": "cancel_top_取消栈顶可取消_保留下层不可取消",
    "cancel_top_可取消条目_成功取消": "cancel_top_可取消条目_成功取消",
    "cancel_top_不可取消条目_返回false": "cancel_top_不可取消条目_返回false",
    "cancel_top_栈顶不可取消_跳过": "cancel_top_栈顶不可取消_跳过",
    "cancel_top_空栈返回false": "cancel_top_空栈返回false",
    "cancel_top_连续取消": "cancel_top_连续取消",
    "clear_压入5条目后清空": "clear_压入5条目后清空",
    "clear_满栈清空后可再压入": "clear_满栈清空后可再压入",
    "clear_空栈清空无影响": "clear_空栈清空无影响",
    "lifo_交替push_pop": "lifo_交替push_pop",
    "lifo_三个条目_弹出顺序正确": "lifo_三个条目_弹出顺序正确",
    "lifo_单条目_push_pop": "lifo_单条目_push_pop",
    "max_depth_弹出后可再压入": "max_depth_弹出后可再压入",
    "max_depth_拒绝后栈内容不变": "max_depth_拒绝后栈内容不变",
    "max_depth_拒绝后深度不变": "max_depth_拒绝后深度不变",
    "max_depth_第3条目被拒绝": "max_depth_第3条目被拒绝",
    "peek_不改变深度": "peek_不改变深度",
    "peek_连续查看返回相同结果": "peek_连续查看返回相同结果",
    "stack_overflow_error_clone": "stack_overflow_error_clone",
    "stack_overflow_error_display": "stack_overflow_error_display",
    "深度追踪_cancel后递减": "深度追踪_cancel后递减",
    "深度追踪_逐条目递增": "深度追踪_逐条目递增",
    "深度追踪_push_pop交替": "深度追踪_push_pop交替",
    "深度追踪_弹出后递减": "深度追踪_弹出后递减",
    "max_depth_压入32条目成功": "max_depth_压入32条目成功",
    "确定性_不同priority_仍为lifo": "确定性_不同priority_仍为lifo",
    "确定性_大量条目_顺序一致": "确定性_大量条目_顺序一致",
    "空栈_depth为0": "空栈_depth为0",
    "确定性_相同输入序列_相同输出序列": "确定性_相同输入序列_相同输出序列",
    "空栈_cancel_top返回false": "空栈_cancel_top返回false",
    "空栈_is_empty为true": "空栈_is_empty为true",
    "空栈_peek返回none": "空栈_peek返回none",
    "空栈_pop返回none": "空栈_pop返回none",

    # Targeting 模块
    "targeting_label": "targeting_label",
    "targeting_requires_target_selection": "targeting_需要目标选择",
    "默认验证器_已死亡目标_非施法者_报错": "默认验证器_已死亡目标_非施法者_报错",
    "默认验证器_已死亡目标_施法者自身_通过": "默认验证器_已死亡目标_施法者自身_通过",
    "默认验证器_敌对阵营_不同阵营通过": "默认验证器_敌对阵营_不同阵营通过",
    "默认验证器_敌对阵营_同阵营报错": "默认验证器_敌对阵营_同阵营报错",
    "默认验证器_自身_他人报错": "默认验证器_自身_他人报错",
    "默认验证器_自身_施法者通过": "默认验证器_自身_施法者通过",

    # Ability 模块
    "skill_not_found_包含错误码": "skill_not_found_包含错误码",
    "skill_not_ready_包含原因": "skill_not_ready_包含原因",
    "skill_result_类型可用": "skill_result_类型可用",
    "skill_def_转换为_skill_data": "skill_def_转换为skill_data",
    "ron_反序列化_技能定义": "ron_反序列化_技能定义",
    "内置技能_重复注册幂等": "内置技能_重复注册幂等",
    "条件_hp低于阈值": "条件_hp低于阈值",
    "条件_hp高于阈值": "条件_hp高于阈值",
    "内置技能_注册表包含6个技能": "内置技能_注册表包含6个技能",
    "条件_mp不足不可使用": "条件_mp不足不可使用",
    "条件_冷却中不可使用": "条件_冷却中不可使用",
    "条件_多个条件全部满足": "条件_多个条件全部满足",
    "条件_目标缺少标签": "条件_目标缺少标签",
    "条件_空条件列表可使用": "条件_空条件列表可使用",
    "条件_满足条件可使用": "条件_满足条件可使用",
    "条件_缺少标签不可使用": "条件_缺少标签不可使用",
    "目标类型_label": "目标类型_label",
    "目标类型_需要选择目标": "目标类型_需要选择目标",
    "can_use_hp不高于阈值返回错误": "can_use_hp_不高于阈值返回错误",
    "can_use_hp低于阈值成功": "can_use_hp_低于阈值成功",
    "can_use_hp不低于阈值返回错误": "can_use_hp_不低于阈值返回错误",
    "can_use_hp高于阈值成功": "can_use_hp_高于阈值成功",
    "can_use_mp不足返回错误": "can_use_mp_不足返回错误",
    "can_use_mp足够成功": "can_use_mp_足够成功",
    "can_use_冷却中返回错误": "can_use_冷却中返回错误",
    "can_use_冷却结束成功": "can_use_冷却结束成功",
    "can_use_多条件全部满足": "can_use_多条件全部满足",
    "can_use_拥有标签成功": "can_use_拥有标签成功",
    "can_use_多条件之一不满足": "can_use_多条件之一不满足",
    "can_use_目标缺少标签返回错误": "can_use_目标缺少标签返回错误",
    "can_use_无目标标签检查跳过": "can_use_无目标标签检查跳过",
    "can_use_目标拥有标签成功": "can_use_目标拥有标签成功",
    "can_use_缺少标签返回错误": "can_use_缺少标签返回错误",
    "targeting_label": "targeting_label",
    "targeting_requires_target_selection": "targeting_需要目标选择",
    "ron_反序列化_旧配置无version字段": "ron_反序列化_旧配置无version字段",
    "apply_costs_mp不足不减到负数": "apply_costs_mp_不足不减到负数",
    "apply_costs_冷却结束不设置": "apply_costs_冷却结束不设置",
    "apply_costs_扣mp和冷却": "apply_costs_扣mp和冷却",
    "prepare_execution_验证通过": "prepare_execution_验证通过",
    "prepare_execution_mp不足失败": "prepare_execution_mp_不足失败",
    "prepare_execution_冷却中失败": "prepare_execution_冷却中失败",
    "is_alive_存活检查": "is_alive_存活检查",
    "冷却_初始值": "冷却_初始值",
    "冷却_clear清空": "冷却_clear_清空",
    "冷却_设置和查询": "冷却_设置和查询",
    "冷却_tick递减": "冷却_tick_递减",
    "技能槽_特殊技能": "技能槽_特殊技能",
    "技能槽_特殊技能_空列表": "技能槽_特殊技能_空列表",
    "技能槽_特殊技能_只有一个技能": "技能槽_特殊技能_只有一个技能",
    "技能槽_迭代器": "技能槽_迭代器",
    "技能槽_默认攻击": "技能槽_默认攻击",
    "技能槽_默认攻击_空列表回退": "技能槽_默认攻击_空列表回退",
    "技能范围_使用单位基础范围": "技能范围_使用单位基础范围",
    "技能范围_技能自带范围": "技能范围_技能自带范围",
    "预览_伤害预览": "预览_伤害预览",
    "预览_治疗不超过最大hp": "预览_治疗不超过最大hp",
    "预览_治疗预览": "预览_治疗预览",
    "预览_致死伤害标记": "预览_致死伤害标记",

    # Snapshot 模块
    "save_full_snapshot_空world_返回some": "save_full_snapshot_空world_返回some",
    "save_snapshot_空列表_返回some": "save_snapshot_空列表_返回some",
    "save_snapshot_指定entity_返回some": "save_snapshot_指定entity_返回some",
    "save_full_snapshot_多个entity_返回some": "save_full_snapshot_多个entity_返回some",

    # Registry Loader 模块
    "registry_loader_空注册表": "registry_loader_空注册表",
    "registry_loader_默认注册_幂等": "registry_loader_默认注册_幂等",
    "registry_loader_注册表": "registry_loader_注册表",
    "registry_loader_目录不存在时使用默认": "registry_loader_目录不存在时使用默认",
    "registry_loader_文件不存在时使用默认": "registry_loader_文件不存在时使用默认",
    "registry_loader_默认注册_空时填充": "registry_loader_默认注册_空时填充",
    "registry_loader_默认注册_非空时不覆盖": "registry_loader_默认注册_非空时不覆盖",

    # Debug 模块
    "debug_overlay_default_all_off": "debug_overlay_默认全部关闭",
    "f3_toggle_all_off_to_all_on": "F3_全部关闭到全部开启",
    "f3_toggle_all_on_to_all_off": "F3_全部开启到全部关闭",
    "f3_toggle_partial_on_to_all_on": "F3_部分开启到全部开启",
    "debug_view_all_returns_correct_count": "debug_view_all_返回正确数量",
    "debug_view_default_is_battle": "debug_view_默认是battle",
    "debug_panel_state_default_all_off": "debug_panel_state_默认全部关闭",
    "debug_view_equality": "debug_view_相等性",
    "debug_view_hash_consistency": "debug_view_哈希一致性",
    "grid_viewer_state_default_values": "grid_viewer_state_默认值",
    "pagination_first_page": "分页_第一页",
    "pagination_last_page": "分页_最后一页",
    "pagination_last_page_map_smaller_than_page": "分页_最后一页地图小于页",
    "pagination_next_page": "分页_下一页",
    "pagination_next_page_clamped_to_last": "分页_下一页限制到最后",
    "pagination_prev_page": "分页_上一页",
    "pagination_prev_page_at_first_page": "分页_上一页在第一页",
    "viewport_range_calculation": "视口范围计算",
    "viewport_range_last_page_partial": "视口范围_最后一页部分",

    # Infrastructure 模块
    "白名单_entries_返回完整列表": "白名单_entries_返回完整列表",
    "白名单_战斗事件通过校验": "白名单_战斗事件通过校验",
    "白名单_未注册事件被拒绝": "白名单_未注册事件被拒绝",
    "白名单_注册新事件": "白名单_注册新事件",
    "cache_args_hash_different": "cache_args_hash_different",
    "cache_clear": "cache_clear",
    "cache_insert_and_get": "cache_insert_and_get",
    "cache_lru_access_refreshes_order": "cache_lru_access_refreshes_order",
    "cache_miss": "cache_miss",
    "cache_lru_eviction": "cache_lru_eviction",
    "localized_text_new": "localized_text_new",
    "localized_text_with_args": "localized_text_with_args",
    "locale_all_count": "locale_all_count",
    "locale_default_is_zh_cn": "locale_默认是zh_cn",
    "locale_as_str": "locale_as_str",
    "locale_display_name": "locale_display_name",
    "locale_from_str": "locale_from_str",
    "has_key": "has_key",
    "load_ftl_error": "load_ftl_error",
    "merge_multiple_ftl_loads": "merge_multiple_ftl_loads",
    "resolve_basic_key": "resolve_basic_key",
    "resolve_with_args": "resolve_with_args",
    "resolve_missing_key_returns_placeholder": "resolve_missing_key_返回占位符",
    "clear_cache": "clear_cache",
    "resolve_fallback_to_default": "resolve_fallback_to_default",
    "loaded_locales": "loaded_locales",
    "resolve_with_args_actual_parameters": "resolve_with_args_实际参数",
    "discover_ftl_files_nonexistent_dir": "discover_ftl_files_不存在目录",
    "load_ftl_file_nonexistent": "load_ftl_file_不存在",
    "plugin_registers_resources": "plugin_registers_resources",

    # Shared 模块
    "infrastructure_error_with_context": "infrastructure_error_带上下文",
    "ok_with_context_passthrough": "ok_with_context_透传",
    "string_error_with_context": "string_error_带上下文",
    "chaining_with_unwrap_or_default": "chaining_with_unwrap_or_default",
    "err_returns_none": "err_returns_none",
    "ok_returns_some": "ok_returns_some",
    "works_with_different_error_types": "works_with_different_error_types",
    "game_result_err_可转换": "game_result_err_可转换",
    "game_result_类型可用": "game_result_类型可用",
    "infrastructure_error_消息格式": "infrastructure_error_消息格式",
    "unit_id_创建与相等性": "unit_id_创建与相等性",
    "unit_id_display_格式": "unit_id_display_格式",
    "unit_id_from_str": "unit_id_from_str",
    "unit_id_hash_一致性": "unit_id_hash_一致性",
    "skill_id_创建与相等性": "skill_id_创建与相等性",
    "skill_id_display_格式": "skill_id_display_格式",
    "skill_id_与unit_id_类型安全": "skill_id_与unit_id_类型安全",
    "buff_id_创建与相等性": "buff_id_创建与相等性",
    "buff_id_display_格式": "buff_id_display_格式",
    "buff_id_from_str": "buff_id_from_str",
    "item_id_创建与相等性": "item_id_创建与相等性",
    "item_id_display_格式": "item_id_display_格式",
    "item_id_from_string": "item_id_from_string",
    "resettable_resource_重置为默认值": "resettable_resource_重置为默认值",

    # UI 模块
    "相机目标_默认值无目标位置": "相机目标_默认值无目标位置",
    "相机平滑移动_插值公式正确": "相机平滑移动_插值公式正确",
    "相机目标_可设置目标位置": "相机目标_可设置目标位置",
    "相机缩放_钳制到有效范围": "相机缩放_钳制到有效范围",
    "ui命令_各变体可构造": "ui命令_各变体可构造",
    "ui命令_技能携带skill_id": "ui命令_技能携带skill_id",
    "ui命令_移动单位携带坐标": "ui命令_移动单位携带坐标",
    "ui命令_选择单位携带entity": "ui命令_选择单位携带entity",
    "ui焦点状态_可恢复阻止输入": "ui焦点状态_可恢复阻止输入",
    "ui焦点状态_可阻止输入": "ui焦点状态_可阻止输入",
    "ui焦点状态_默认不阻止输入": "ui焦点状态_默认不阻止输入",
    "色盲模式_所有枚举值序列化反序列化": "色盲模式_所有枚举值序列化反序列化",
    "设置_默认值合理": "设置_默认值合理",
    "设置_ron序列化往返保持一致": "设置_ron序列化往返保持一致",
    "主题_默认值完整性": "主题_默认值完整性",
    "阵营颜色_区分玩家和敌人": "阵营颜色_区分玩家和敌人",
    "阵营颜色_敌方为红色系": "阵营颜色_敌方为红色系",
    "阵营颜色_玩家为蓝色系": "阵营颜色_玩家为蓝色系",
    "伤害弹窗_淡出比例完成": "伤害弹窗_淡出比例完成",
    "伤害弹窗_淡出比例边界": "伤害弹窗_淡出比例边界",
    "伤害弹窗_淡出比例计算": "伤害弹窗_淡出比例计算",
    "伤害弹窗_配置默认值合理": "伤害弹窗_配置默认值合理",
    "回合信息视图_默认值为空": "回合信息视图_默认值为空",
    "选中单位视图_默认值为空": "选中单位视图_默认值为空",
    "战斗预览视图_默认不可见": "战斗预览视图_默认不可见",
    "悬停实体_默认值为none": "悬停实体_默认值为none",
    "悬停实体_可设置entity": "悬停实体_可设置entity",
    "label_返回正确组件": "label_返回正确组件",
    "divider_返回水平分隔线": "divider_返回水平分隔线",
    "hbox_返回横向布局": "hbox_返回横向布局",
    "panel_返回带内边距布局": "panel_返回带内边距布局",
    "vbox_返回纵向布局": "vbox_返回纵向布局",

    # App 模块
    "error_type_label_对应分类": "error_type_label_对应分类",
    "game_error_message_可构造": "game_error_message_可构造",
    "game_error_message_可附加上下文": "game_error_message_可附加上下文",
    "game_error_message_是bevy_message": "game_error_message_是bevy_message",
    "monitor_消费空上下文消息": "monitor_消费空上下文消息",
    "monitor_消费带上下文消息": "monitor_消费带上下文消息",
    "monitor_消费批量消息": "monitor_消费批量消息",

    # GAS 集成测试
    "stacking_rule_complete_scenarios": "叠层规则_完整场景",
    "execution_registry_complete": "执行器注册表_完整流程",
    "execution_calculation_complete": "执行器计算_完整流程",
    "cue_emission_complete": "Cue发射_完整流程",
    "effect_def_duration_complete": "效果定义_持续时间完整",
    "gas_phase_complete": "GAS阶段_完整流程",
    "replay_complete": "回放_完整流程",
    "asset_registry_complete": "资产注册表_完整流程",
}


def rename_tests_in_file(filepath):
    """重命名文件中的测试函数"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    original_content = content
    changes = 0

    for old_name, new_name in TEST_NAME_MAP.items():
        # 匹配 fn old_name() 模式
        pattern = f'fn {old_name}('
        replacement = f'fn {new_name}('
        if pattern in content:
            content = content.replace(pattern, replacement)
            changes += 1

    if changes > 0:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  修改了 {changes} 个测试函数: {filepath}")

    return changes


def main():
    """主函数"""
    src_dir = Path("D:/Code/Bevy/Fre/src")
    total_changes = 0

    # 遍历所有 .rs 文件
    for filepath in src_dir.rglob("*.rs"):
        changes = rename_tests_in_file(filepath)
        total_changes += changes

    print(f"\n总共修改了 {total_changes} 个测试函数")


if __name__ == "__main__":
    main()
